from pathlib import Path
from playwright.sync_api import sync_playwright
import json,time,sys,tempfile
REPO=Path(__file__).resolve().parents[1]
ROOT=Path(tempfile.mkdtemp(prefix='tauceti-browser-'))
url=sys.argv[1] if len(sys.argv)>1 else (REPO/'index.html').as_uri()
results=[];errors=[];requests=[]
def record(name,value=True):
 assert value,name
 results.append(name)
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True)
 context=browser.new_context(viewport={'width':1600,'height':1000},accept_downloads=True)
 page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
 if url.startswith('file:'):
  page.route('http://**/*',lambda route:(requests.append(route.request.url),route.abort()))
  page.route('https://**/*',lambda route:(requests.append(route.request.url),route.abort()))
 page.goto(url,wait_until='load');page.wait_for_function('!!window.TauExplorer',timeout=15000)
 record('Native offline mathematics renders',page.evaluate("() => {const d=TauMarkdown.render('$x^2$');return !!d.querySelector('math')}"))
 record('180 roadmap and 1604 stage records',page.evaluate('TauExplorer.data.roadmaps.length===180 && TauExplorer.data.stages.length===1604'))
 page.screenshot(path=str(ROOT/'preview-overview.png'))
 page.evaluate("TauExplorer.navigate({view:'subjects',id:null,selected:null,origin:'all'})")
 page.locator('[data-node-id="classical"]').click()
 record('Click subject opens its description',page.locator('#inspector').is_visible())
 page.get_by_role('button',name='Open roadmaps →').click()
 page.locator('[data-node-id="AnalyticNumberTheory"]').click()
 record('Click roadmap shows meaningful summary',len(page.locator('.detail-summary').inner_text())>50)
 page.get_by_role('button',name='Open stage layers →').click()
 record('Open stages displays exact stage nodes',page.evaluate("TauExplorer.graph.debugState().nodes===TauExplorer.data.roadmaps.find(r=>r.id==='AnalyticNumberTheory').stages.length"))
 page.locator('[data-node-id="AnalyticNumberTheory:AN.0"]').click()
 page.get_by_label('Layer status',exact=True).select_option('complete');page.get_by_label('Progress note',exact=True).fill('Browser test evidence')
 page.get_by_role('button',name='Save status',exact=True).click()
 record('Local update persists and makes stage green',page.evaluate("TauExplorer.progress.stage('AnalyticNumberTheory:AN.0').manual && TauExplorer.progress.stage('AnalyticNumberTheory:AN.0').status==='complete'"))
 record('Node progress colour updates',page.locator('[data-node-id="AnalyticNumberTheory:AN.0"]').get_attribute('data-progress')=='100')
 page.reload(wait_until='load');page.wait_for_function('!!window.TauExplorer')
 record('Progress survives reload',page.evaluate("TauExplorer.progress.stage('AnalyticNumberTheory:AN.0').status==='complete'"))
 page.screenshot(path=str(ROOT/'preview-stage.png'))
 record('Export/reset/import round trip',page.evaluate("""() => {const x=TauExplorer.progress.export();TauExplorer.progress.resetStage('AnalyticNumberTheory:AN.0');const reverted=TauExplorer.progress.stage('AnalyticNumberTheory:AN.0').status!=='complete';TauExplorer.progress.import(x);return reverted&&TauExplorer.progress.stage('AnalyticNumberTheory:AN.0').status==='complete'}"""))
 record('Malformed import is atomic',page.evaluate("""() => {const a=JSON.stringify(TauExplorer.progress.export());try{TauExplorer.progress.import({version:1,stages:{bad:{status:'complete'}}});return false}catch{}return a===JSON.stringify(TauExplorer.progress.export())}"""))
 page.evaluate("TauExplorer.progress.resetStage('AnalyticNumberTheory:AN.0')")
 page.get_by_role('button',name='Read full roadmap',exact=True).click()
 record('Full document readable offline',page.locator('#reader[open]').is_visible() and len(page.locator('#reader-body').inner_text())>3000)
 page.locator('#close-reader').click()
 page.locator('#search').fill('Perron')
 record('Search reaches mathematical roadmap text',page.locator('.search-hit').count()>0)
 page.locator('#search').fill('')
 page.locator('#source-filter').select_option('tauceti')
 record('Tau Ceti collection filter',page.evaluate("TauExplorer.getState().origin==='tauceti'"))
 page.evaluate("TauExplorer.openItem('tauceti:Completed/EffectiveBounds')")
 record('Maintainer completed area is green',page.evaluate("TauExplorer.progress.roadmap('tauceti:Completed/EffectiveBounds').percent===100"))
 page.evaluate("TauExplorer.openItem('tauceti:TauCetiRoadmap/RepresentationTheory')")
 record('Nested roadmap collection opens 11 children',page.evaluate("TauExplorer.getState().view==='collection' && TauExplorer.graph.debugState().nodes===11"))
 page.evaluate("TauExplorer.navigate({view:'all',id:null,selected:null,origin:'all'})")
 record('All nodes and all roadmap edges available',page.evaluate('TauExplorer.graph.debugState().nodes===180 && TauExplorer.graph.debugState().edges===1011'))
 record('All graph positions finite',page.evaluate('TauExplorer.graph.debugState().positions.every(n=>Number.isFinite(n.x)&&Number.isFinite(n.y))'))
 page.screenshot(path=str(ROOT/'preview-all.png'))
 record('Vascular overview has 13 subject branches',page.evaluate("TauExplorer.graph.debugState().layout==='vessels' && TauExplorer.graph.debugState().vesselSubjects===13"))
 page.locator('#stats-button').click()
 record('Mission status uses unique leaf totals',page.locator('#stats-scope').inner_text().endswith('1,543 tracked leaf layers'))
 record('Mission status distinguishes 4 states',page.locator('#stats-summary .metric.complete strong').inner_text()=='36' and page.locator('#stats-summary .metric.active strong').inner_text()=='49' and page.locator('#stats-summary .metric.unknown strong').inner_text()=='1,352')
 record('All 13 mathematical areas have progress ledgers',page.locator('#area-progress .area-stat').count()==13)
 page.screenshot(path=str(ROOT/'preview-stats.png'));page.locator('#close-stats').click()
 page.locator('#activity-filter').select_option('active')
 record('Activity filter shows only active roadmaps',page.evaluate("TauExplorer.getGraph().nodes.length>0 && TauExplorer.getGraph().nodes.length<180 && TauExplorer.getGraph().nodes.every(n=>TauExplorer.progress.roadmap(n.id).active>0)"))
 page.locator('#activity-filter').select_option('all')
 page.evaluate("TauExplorer.openItem('AnalyticNumberTheory')")
 page.locator('.pin-button').click()
 record('Roadmap can be pinned',page.locator('#pinned-list .pin-item').count()==1)
 page.reload(wait_until='load');page.wait_for_function('!!window.TauExplorer')
 record('Pinned roadmap persists',page.locator('.pin-button').get_attribute('aria-pressed')=='true')
 page.locator('#activity-filter').select_option('pinned')
 record('Pinned filter returns saved roadmap',page.evaluate("TauExplorer.getGraph().nodes.length===1 && TauExplorer.getGraph().nodes[0].id==='AnalyticNumberTheory'"))
 page.locator('#activity-filter').select_option('all')
 page.evaluate("TauExplorer.openReader('tauceti:TauCetiRoadmap/ModularForms')")
 internal=page.locator('#reader-body [data-doc-link]').all()
 linked=False
 for link in internal:
  raw=link.get_attribute('data-doc-link')
  if raw and 'README.md' in raw and not raw.startswith(('http','file','#')):
   before=page.locator('#reader-title').inner_text();link.click()
   if page.locator('#reader-title').inner_text()!=before:linked=True;break
 record('Embedded roadmap document links resolve',linked)
 page.locator('#close-reader').click()
 if page.evaluate('(TauExplorer.data.documents||[]).length'):
  page.evaluate("TauExplorer.openReader('AnalyticNumberTheory')")
  page.locator('#reader-body [data-doc-link]').filter(has_text='campaign execution protocol').click()
  record('Campaign execution guide is embedded and linked', 'execution' in page.locator('#reader-title').inner_text().lower())
  page.locator('#close-reader').click()
 page.locator('#progress-button').click()
 with page.expect_download() as dl:page.locator('#download-offline').click()
 artifact=ROOT/'verified-offline.html';dl.value.save_as(str(artifact));page.locator('#close-progress').click()
 offline=browser.new_context();op=offline.new_page();op.goto(artifact.as_uri());op.wait_for_function('!!window.TauExplorer')
 record('Downloaded atlas starts independently',op.evaluate('TauExplorer.data.roadmaps.length===180') and op.locator('#pinned-list .pin-item').count()==0)
 offline.close()
 page.set_viewport_size({'width':390,'height':844})
 page.locator('#catalogue-button').click()
 record('Phone view has working browse/search',page.locator('#search').is_visible())
 page.locator('#search').fill('Perron');record('Phone search returns topics',page.locator('.search-hit').count()>0)
 page.locator('.search-hit').first.click();record('Phone selection dismisses index',not page.locator('#search').is_visible())
 page.screenshot(path=str(ROOT/'preview-phone.png'))
 page.set_viewport_size({'width':1600,'height':1000})
 page.evaluate("TauExplorer.openItem('AnalyticNumberTheory')")
 page.set_viewport_size({'width':900,'height':800});page.screenshot(path=str(ROOT/'preview-narrow.png'))
 record('Narrow view usable',page.locator('#inspector').is_visible())
 record('Markdown rejects unsafe HTML and schemes',page.evaluate("""() => {const f=TauMarkdown.render('<img src=x onerror=alert(1)>\\n\\n[x](javascript:alert(1))');const d=document.createElement('div');d.append(f);return !d.querySelector('img,script,iframe')&&!Array.from(d.querySelectorAll('a')).some(a=>a.href.startsWith('javascript:'))}"""))
 record('No application exceptions',not errors)
 if url.startswith('file:'):record('No network requests needed',not requests)
 browser.close()
report={'url':url,'checks':results,'pageErrors':errors,'externalRequests':requests,'result':'PASS'}
(ROOT/'BROWSER_VALIDATION.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report,indent=2))
print('Screenshots and report:',ROOT)
