/-
This file is not the roadmap and is not exhaustive. The roadmap document is
 definitive. These statements suggest Lean forms so that contributors and
reviewers converge on names and signatures. Proof placeholders claim no
implementation. The accepted parent file supplies the retained R01.5 targets;
this file supplies their trace-field/image-algebra refinements and the
Boston–Lenstra–Ribet input. No polynomial-law or generic Brauer theory is rebuilt.

The algebraic interface accepts the full-span conclusion of Burnside explicitly.
For an absolutely irreducible representation over an algebraic closure that
conclusion comes from R01.1/absolutely-irreducible. This stronger-looking matrix
interface works over any ambient field whenever the full-span condition holds.
-/
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.FieldTheory.Galois.Infinite
import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.LinearAlgebra.Matrix.Charpoly.Coeff
import Mathlib.LinearAlgebra.Matrix.ToLin
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.LinearAlgebra.TensorProduct.Basic
import Mathlib.Algebra.MonoidAlgebra.Module
import Mathlib.RingTheory.TwoSidedIdeal.Operations
import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import Mathlib.RingTheory.RootsOfUnity.PrimitiveRoots
import TauCeti.Algebra.BrauerGroup.BaseChange
import TauCeti.Algebra.BrauerGroup.Splitting
import TauCeti.Algebra.BrauerGroup.Quaternion
import TauCeti.Algebra.CentralSimple.Index

noncomputable section
open scoped TensorProduct Quaternion
universe u v
namespace TauCeti.GaloisRep

variable (k : Type u) [Field k] {Ω : Type u} [Field Ω] [Algebra k Ω]
variable {Γ : Type v} [Group Γ] {n : ℕ}
variable (ρ : Γ →* (Matrix (Fin n) (Fin n) Ω)ˣ)

/-- The intermediate field generated by the traces, with no characteristic restriction. -/
def traceField : IntermediateField k Ω :=
  IntermediateField.adjoin k
    (Set.range fun g ↦ Matrix.trace (ρ g : Matrix (Fin n) (Fin n) Ω))

lemma traceField_mem (g : Γ) :
    Matrix.trace (ρ g : Matrix (Fin n) (Fin n) Ω) ∈ traceField k ρ := by sorry

lemma traceField_le_iff (L : IntermediateField k Ω) :
    traceField k ρ ≤ L ↔
      ∀ g, Matrix.trace (ρ g : Matrix (Fin n) (Fin n) Ω) ∈ L := by sorry

lemma traceField_conjugate (ρ' : Γ →* (Matrix (Fin n) (Fin n) Ω)ˣ)
    (P : (Matrix (Fin n) (Fin n) Ω)ˣ)
    (hconj : ∀ g, (ρ' g : Matrix (Fin n) (Fin n) Ω) =
      (P : Matrix (Fin n) (Fin n) Ω) * (ρ g : Matrix (Fin n) (Fin n) Ω) *
        (↑(P⁻¹) : Matrix (Fin n) (Fin n) Ω)) :
    traceField k ρ = traceField k ρ' := by sorry

/-- Closure as an algebra agrees with the linear span because the generators form a group. -/
def imageAlgebra : Subalgebra (traceField k ρ) (Matrix (Fin n) (Fin n) Ω) :=
  Algebra.adjoin (traceField k ρ)
    (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω))

lemma imageAlgebra_mem (g : Γ) :
    (ρ g : Matrix (Fin n) (Fin n) Ω) ∈ imageAlgebra k ρ := by sorry

lemma imageAlgebra_le_iff (S : Subalgebra (traceField k ρ)
    (Matrix (Fin n) (Fin n) Ω)) :
    imageAlgebra k ρ ≤ S ↔
      ∀ g, (ρ g : Matrix (Fin n) (Fin n) Ω) ∈ S := by sorry

lemma imageAlgebra_span :
    (imageAlgebra k ρ).toSubmodule = Submodule.span (traceField k ρ)
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) := by sorry

lemma imageAlgebra_trace_mem (b : imageAlgebra k ρ) :
    Matrix.trace (b : Matrix (Fin n) (Fin n) Ω) ∈ traceField k ρ := by sorry

/-- A matrix basis can be chosen among the group elements. -/
lemma imageAlgebra_image_basis
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    ∃ (g : Fin (n * n) → Γ)
      (b : Module.Basis (Fin (n * n)) Ω (Matrix (Fin n) (Fin n) Ω)),
      ∀ i, b i = (ρ (g i) : Matrix (Fin n) (Fin n) Ω) := by sorry

/-- The trace-dual argument descends coordinates, not just traces. -/
lemma imageAlgebra_traceDualBasis
    (g : Fin (n * n) → Γ)
    (b : Module.Basis (Fin (n * n)) Ω (Matrix (Fin n) (Fin n) Ω))
    (hb : ∀ i, b i = (ρ (g i) : Matrix (Fin n) (Fin n) Ω)) :
    (imageAlgebra k ρ).toSubmodule =
      Submodule.span (traceField k ρ) (Set.range b) := by sorry

lemma imageAlgebra_finiteDimensional
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    FiniteDimensional (traceField k ρ) (imageAlgebra k ρ) := by sorry

lemma imageAlgebra_finrank
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    Module.finrank (traceField k ρ) (imageAlgebra k ρ) = n * n := by sorry

/-- The equivalence is pinned to the canonical multiplication map. -/
theorem imageAlgebra_baseChange
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    ∃ e : (Ω ⊗[traceField k ρ] (imageAlgebra k ρ)) ≃ₐ[Ω]
      Matrix (Fin n) (Fin n) Ω,
      ∀ (x : Ω) (b : imageAlgebra k ρ),
        e (x ⊗ₜ[traceField k ρ] b) = x • (b : Matrix (Fin n) (Fin n) Ω) := by sorry

lemma imageAlgebra_isCentral
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    Algebra.IsCentral (traceField k ρ) (imageAlgebra k ρ) := by sorry

lemma imageAlgebra_isSimple [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    IsSimpleRing (imageAlgebra k ρ) := by sorry

/-- Automorphisms of a splitting field change a splitting only by inner
conjugacy, so the attached characteristic polynomial is invariant. -/
lemma imageAlgebra_split_charpoly_invariant [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤)
    {L : Type u} [Field L] [Algebra (traceField k ρ) L]
    (e : (L ⊗[traceField k ρ] imageAlgebra k ρ) ≃ₐ[L]
      Matrix (Fin n) (Fin n) L)
    (b : imageAlgebra k ρ) (σ : L ≃ₐ[traceField k ρ] L) :
    (e (1 ⊗ₜ[traceField k ρ] b)).charpoly.map σ.toRingHom =
      (e (1 ⊗ₜ[traceField k ρ] b)).charpoly := by sorry

/-- Attached coefficient descent via a separable splitting and fixed fields.
No generic reduced-characteristic-polynomial definition is duplicated here. -/
lemma imageAlgebra_charpoly_mem [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤)
    (b : imageAlgebra k ρ) (j : ℕ) :
    (b : Matrix (Fin n) (Fin n) Ω).charpoly.coeff j ∈ traceField k ρ := by sorry

/-- Absolute irreducibility/full span is essential to this field equality. -/
lemma traceField_eq_polynomialField [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    traceField k ρ = IntermediateField.adjoin k
      (Set.range fun p : Γ × ℕ ↦
        (ρ p.1 : Matrix (Fin n) (Fin n) Ω).charpoly.coeff p.2) := by sorry

/-- The group-algebra map is onto, and its kernel is detected by the
matrix determinant law. The universal polynomial-law interpretation is
imported from IHG.1, rather than redefined here. -/
theorem imageAlgebra_faithfulDeterminantQuotient [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤)
    (r : MonoidAlgebra (traceField k ρ) Γ →ₐ[traceField k ρ] imageAlgebra k ρ)
    (hr : ∀ g, (r (MonoidAlgebra.of (traceField k ρ) Γ g) :
      Matrix (Fin n) (Fin n) Ω) = (ρ g : Matrix (Fin n) (Fin n) Ω)) :
    Function.Surjective r ∧ ∀ x, r x = 0 ↔
      ∀ b : imageAlgebra k ρ,
        ((b : Matrix (Fin n) (Fin n) Ω) *
          (r x : Matrix (Fin n) (Fin n) Ω)).charpoly = Polynomial.X ^ n := by sorry

/-- Use Tau Ceti's actual central-simple constructor and class map. -/
def brauerClass [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    BrauerGroup.{u,u} (traceField k ρ) := by
  letI := imageAlgebra_finiteDimensional k ρ hspan
  letI := imageAlgebra_isCentral k ρ hspan
  letI := imageAlgebra_isSimple k ρ hspan
  exact BrauerGroup.mk (CSA.of (traceField k ρ) (imageAlgebra k ρ))

lemma brauerClass_eq_mk [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    letI := imageAlgebra_finiteDimensional k ρ hspan
    letI := imageAlgebra_isCentral k ρ hspan
    letI := imageAlgebra_isSimple k ρ hspan
    brauerClass k ρ hspan = BrauerGroup.mk (CSA.of (traceField k ρ) (imageAlgebra k ρ)) := by sorry

/-- HEq expresses equality after the equality of intermediate fields from
traceField_conjugate; it does not choose a noncanonical field isomorphism. -/
lemma brauerClass_congr [NeZero n]
    (ρ' : Γ →* (Matrix (Fin n) (Fin n) Ω)ˣ)
    (P : (Matrix (Fin n) (Fin n) Ω)ˣ)
    (hconj : ∀ g, (ρ' g : Matrix (Fin n) (Fin n) Ω) =
      (P : Matrix (Fin n) (Fin n) Ω) * (ρ g : Matrix (Fin n) (Fin n) Ω) *
        (↑(P⁻¹) : Matrix (Fin n) (Fin n) Ω))
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤)
    (hspan' : Submodule.span Ω
      (Set.range fun g ↦ (ρ' g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    HEq (brauerClass k ρ hspan) (brauerClass k ρ' hspan') := by sorry

lemma brauerClass_baseChange [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤)
    (L : Type u) [Field L] [Algebra (traceField k ρ) L] :
    letI := imageAlgebra_finiteDimensional k ρ hspan
    letI := imageAlgebra_isCentral k ρ hspan
    letI := imageAlgebra_isSimple k ρ hspan
    BrauerGroup.baseChange (traceField k ρ) L (brauerClass k ρ hspan) =
      BrauerGroup.mk (CSA.baseChange L (CSA.of (traceField k ρ) (imageAlgebra k ρ))) := by sorry

/-- Splitting is the hypothesis that permits a trace field to be a field of definition. -/
theorem brauerClass_eq_one_iff [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    brauerClass k ρ hspan = 1 ↔
      ∃ P : (Matrix (Fin n) (Fin n) Ω)ˣ, ∀ g i j,
        ((P : Matrix (Fin n) (Fin n) Ω) * (ρ g : Matrix (Fin n) (Fin n) Ω) *
          (↑(P⁻¹) : Matrix (Fin n) (Fin n) Ω)) i j ∈ traceField k ρ := by sorry

theorem brauerClass_baseChange_eq_one_iff [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤)
    (L : IntermediateField (traceField k ρ) Ω) :
    BrauerGroup.baseChange (traceField k ρ) L (brauerClass k ρ hspan) = 1 ↔
      ∃ P : (Matrix (Fin n) (Fin n) Ω)ˣ, ∀ g i j,
        ((P : Matrix (Fin n) (Fin n) Ω) * (ρ g : Matrix (Fin n) (Fin n) Ω) *
          (↑(P⁻¹) : Matrix (Fin n) (Fin n) Ω)) i j ∈ L := by sorry

/-- Use the presentation-independent index already defined in Tau Ceti. -/
def schurIndex [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤) : ℕ := by
  letI := imageAlgebra_finiteDimensional k ρ hspan
  letI := imageAlgebra_isCentral k ρ hspan
  letI := imageAlgebra_isSimple k ρ hspan
  exact Algebra.index (traceField k ρ) (imageAlgebra k ρ)

lemma schurIndex_pos [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    0 < schurIndex k ρ hspan := by sorry

lemma schurIndex_dvd [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    schurIndex k ρ hspan ∣ n := by sorry

lemma schurIndex_eq_one_iff [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    schurIndex k ρ hspan = 1 ↔ brauerClass k ρ hspan = 1 := by sorry

lemma schurIndex_of_matrix [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤)
    {a : ℕ} [NeZero a] (D : Type u) [DivisionRing D]
    [Algebra (traceField k ρ) D] [Algebra.IsCentral (traceField k ρ) D]
    [FiniteDimensional (traceField k ρ) D]
    (e : imageAlgebra k ρ ≃ₐ[traceField k ρ] Matrix (Fin a) (Fin a) D) :
    schurIndex k ρ hspan = Algebra.deg (traceField k ρ) D ∧
      n = a * schurIndex k ρ hspan := by sorry

lemma schurIndex_congr [NeZero n]
    (ρ' : Γ →* (Matrix (Fin n) (Fin n) Ω)ˣ)
    (P : (Matrix (Fin n) (Fin n) Ω)ˣ)
    (hconj : ∀ g, (ρ' g : Matrix (Fin n) (Fin n) Ω) =
      (P : Matrix (Fin n) (Fin n) Ω) * (ρ g : Matrix (Fin n) (Fin n) Ω) *
        (↑(P⁻¹) : Matrix (Fin n) (Fin n) Ω))
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤)
    (hspan' : Submodule.span Ω
      (Set.range fun g ↦ (ρ' g : Matrix (Fin n) (Fin n) Ω)) = ⊤) :
    schurIndex k ρ hspan = schurIndex k ρ' hspan' := by sorry

/-! Concrete tests. The quaternion hypotheses specify exactly the eight matrices
of Q₈; no unrelated field or group property is hidden behind a placeholder. -/
private def quaternionI : Matrix (Fin 2) (Fin 2) ℂ := !![Complex.I, 0; 0, -Complex.I]
private def quaternionJ : Matrix (Fin 2) (Fin 2) ℂ := !![0, 1; -1, 0]
private def quaternionMatrices : Set (Matrix (Fin 2) (Fin 2) ℂ) :=
  {1, -1, quaternionI, -quaternionI, quaternionJ, -quaternionJ,
    quaternionI * quaternionJ, -(quaternionI * quaternionJ)}

-- TauCeti.GaloisRep.traceField_trivial
example : traceField k (1 : Γ →* (Matrix (Fin 1) (Fin 1) Ω)ˣ) = ⊥ := by sorry

-- TauCeti.GaloisRep.traceField_cubic_character
example (χ : Γ →* (Matrix (Fin 1) (Fin 1) ℂ)ˣ) (ζ : ℂ)
    (hζ : IsPrimitiveRoot ζ 3)
    (himage : Set.range (fun g ↦ (χ g : Matrix (Fin 1) (Fin 1) ℂ) 0 0) = {1, ζ, ζ ^ 2}) :
    traceField ℚ χ = IntermediateField.adjoin ℚ {ζ} ∧ traceField ℚ χ ≠ ⊥ := by sorry

-- TauCeti.GaloisRep.traceField_quaternion_real
example (r : Γ →* (Matrix (Fin 2) (Fin 2) ℂ)ˣ)
    (himage : Set.range (fun g ↦ (r g : Matrix (Fin 2) (Fin 2) ℂ)) = quaternionMatrices) :
    traceField ℝ r = ⊥ ∧
      ∃ g, (r g : Matrix (Fin 2) (Fin 2) ℂ) 0 0 ∉ (⊥ : IntermediateField ℝ ℂ) := by sorry

-- TauCeti.GaloisRep.imageAlgebra_trivial_rank_two
example : imageAlgebra k (1 : Γ →* (Matrix (Fin 2) (Fin 2) Ω)ˣ) = ⊥ := by sorry

-- TauCeti.GaloisRep.imageAlgebra_one_dim
example (χ : Γ →* (Matrix (Fin 1) (Fin 1) Ω)ˣ) :
    Nonempty (imageAlgebra k χ ≃ₐ[traceField k χ] traceField k χ) := by sorry

-- TauCeti.GaloisRep.imageAlgebra_cubic_not_base_span
example (χ : Γ →* (Matrix (Fin 1) (Fin 1) ℂ)ˣ) (ζ : ℂ)
    (hζ : IsPrimitiveRoot ζ 3)
    (himage : Set.range (fun g ↦ (χ g : Matrix (Fin 1) (Fin 1) ℂ) 0 0) = {1, ζ, ζ ^ 2}) :
    Module.finrank ℚ (Submodule.span ℚ
      (Set.range fun g ↦ (χ g : Matrix (Fin 1) (Fin 1) ℂ))) = 2 ∧
    Module.finrank (traceField ℚ χ) (imageAlgebra ℚ χ) = 1 := by sorry

-- TauCeti.GaloisRep.brauerClass_one_dim
example (χ : Γ →* (Matrix (Fin 1) (Fin 1) Ω)ˣ)
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (χ g : Matrix (Fin 1) (Fin 1) Ω)) = ⊤) :
    brauerClass k χ hspan = 1 := by sorry

-- TauCeti.GaloisRep.brauerClass_finite_field
example [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤)
    [Finite (traceField k ρ)] : brauerClass k ρ hspan = 1 := by sorry

-- TauCeti.GaloisRep.brauerClass_quaternion_real
example (r : Γ →* (Matrix (Fin 2) (Fin 2) ℂ)ˣ)
    (himage : Set.range (fun g ↦ (r g : Matrix (Fin 2) (Fin 2) ℂ)) = quaternionMatrices)
    (hspan : Submodule.span ℂ
      (Set.range fun g ↦ (r g : Matrix (Fin 2) (Fin 2) ℂ)) = ⊤) :
    Nonempty ((imageAlgebra ℝ r).restrictScalars ℝ ≃ₐ[ℝ] ℍ[ℝ]) ∧
      brauerClass ℝ r hspan ≠ 1 := by sorry

-- TauCeti.GaloisRep.schurIndex_one_dim
example (χ : Γ →* (Matrix (Fin 1) (Fin 1) Ω)ˣ)
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (χ g : Matrix (Fin 1) (Fin 1) Ω)) = ⊤) :
    schurIndex k χ hspan = 1 := by sorry

-- TauCeti.GaloisRep.schurIndex_finite_field
example [NeZero n]
    (hspan : Submodule.span Ω
      (Set.range fun g ↦ (ρ g : Matrix (Fin n) (Fin n) Ω)) = ⊤)
    [Finite (traceField k ρ)] : schurIndex k ρ hspan = 1 := by sorry

-- TauCeti.GaloisRep.schurIndex_quaternion_real
example (r : Γ →* (Matrix (Fin 2) (Fin 2) ℂ)ˣ)
    (himage : Set.range (fun g ↦ (r g : Matrix (Fin 2) (Fin 2) ℂ)) = quaternionMatrices)
    (hspan : Submodule.span ℂ
      (Set.range fun g ↦ (r g : Matrix (Fin 2) (Fin 2) ℂ)) = ⊤) :
    schurIndex ℝ r hspan = 2 ∧
      Module.finrank ℝ ((imageAlgebra ℝ r).restrictScalars ℝ) = 4 := by sorry

-- Acceptance test: the matrix trace pairing survives characteristic two.
example : Matrix.trace (1 : Matrix (Fin 2) (Fin 2) (ZMod 2)) = 0 ∧
    Matrix.trace ((Matrix.single 0 1 1 : Matrix (Fin 2) (Fin 2) (ZMod 2)) *
      Matrix.single 1 0 1) = 1 := by sorry

/-! Boston–Lenstra–Ribet. Use the group-element ideal explicitly; it is not
silently replaced by the polynomial-law Cayley–Hamilton ideal. -/
section RankTwo
variable {F : Type u} [Field F]
variable (r : MonoidAlgebra F Γ →ₐ[F] Matrix (Fin 2) (Fin 2) F)

/-- Proposition 1, pp.323–324. Polarization is valid even in characteristic two. -/
theorem rankTwo_polarized_relations :
    let J := TwoSidedIdeal.span (Set.range fun g : Γ ↦
      let x := MonoidAlgebra.of F Γ g
      x * x - algebraMap F (MonoidAlgebra F Γ) (Matrix.trace (r x)) * x +
        algebraMap F (MonoidAlgebra F Γ) (Matrix.det (r x)))
    ∃ s : MonoidAlgebra F Γ →ₗ[F] MonoidAlgebra F Γ,
      (∀ g, s (MonoidAlgebra.of F Γ g) =
        Matrix.det (r (MonoidAlgebra.of F Γ g)) • MonoidAlgebra.of F Γ (g⁻¹)) ∧
      (∀ x, s (s x) = x) ∧ (∀ x y, s (x * y) = s y * s x) ∧
      (∀ x, x + s x - algebraMap F (MonoidAlgebra F Γ) (Matrix.trace (r x)) ∈ J) ∧
      (∀ x, x * s x - algebraMap F (MonoidAlgebra F Γ) (Matrix.det (r x)) ∈ J) := by sorry

/-- Proposition 2, p.324: surjectivity is the Burnside conclusion for an
absolutely irreducible rank-two representation. -/
theorem rankTwo_quadratic_relations_kernel (hr : Function.Surjective r) :
    TwoSidedIdeal.span (Set.range fun g : Γ ↦
      let x := MonoidAlgebra.of F Γ g
      x * x - algebraMap F (MonoidAlgebra F Γ) (Matrix.trace (r x)) * x +
        algebraMap F (MonoidAlgebra F Γ) (Matrix.det (r x))) =
      TwoSidedIdeal.ker r := by sorry

/-- Theorem 1, pp.324–325, finite-dimensional form of the isotypic conclusion.
The coefficient field is arbitrary. No semisimplicity assumption on s occurs. -/
theorem rankTwo_annihilation_isotypic (hr : Function.Surjective r)
    {N : ℕ} (s : Γ →* (Matrix (Fin N) (Fin N) F)ˣ)
    (hann : ∀ g, Polynomial.aeval (s g : Matrix (Fin N) (Fin N) F)
      (r (MonoidAlgebra.of F Γ g)).charpoly = 0) :
    ∃ (m : ℕ) (e : (Fin N → F) ≃ₗ[F] ((Fin 2 → F) ⊗[F] (Fin m → F))),
      ∀ g x, e ((s g : Matrix (Fin N) (Fin N) F).mulVec x) =
        TensorProduct.map (Matrix.toLin' (r (MonoidAlgebra.of F Γ g)))
          (LinearMap.id : (Fin m → F) →ₗ[F] (Fin m → F)) (e x) := by sorry
end RankTwo
end TauCeti.GaloisRep
