/-
This file is not the roadmap and is not exhaustive. The roadmap document
`research/blueprint/readmes/ClassicalArithmeticCompletion.md` is definitive. These
statements suggest Lean forms so that contributors and reviewers can converge on
names and signatures. They claim no implementation.

BP-ClassicalArithmeticCompletion: partial prototype, implementationStatus = unchecked.
Mathlib 082e2d37e8b0463410cdb532e111cd43d5a66174;
Tau Ceti f790474821cf4256814db967cb154e7af3d0c369.
No Lean toolchain at those commits was available in this session, so elaboration
has not been established.

This roadmap is largely built. The reviewed library audit records CA.0 as built,
CA.5 as a process layer and the rest as partly built, and the protocol says that a
target the libraries contain is a baseline citation and never a node. So this file
is short on purpose: it prototypes only the ten statements the audit records as
missing and for which a free source could be read. Everything it builds on --
quadratic reciprocity, Euler's criterion, the cyclicity criterion for the units
modulo n, the linear recurrence API, the elementary-divisor structure theorem, Pell,
the sums of squares, the Mahler measure of a polynomial -- is imported, not restated.
-/
import Mathlib.Algebra.LinearRecurrence
import Mathlib.Algebra.Module.PID
import Mathlib.Algebra.Polynomial.Degree.Defs
import Mathlib.Algebra.Polynomial.Roots
import Mathlib.Data.Int.GCD
import Mathlib.Data.Int.ModEq
import Mathlib.Data.Nat.ModEq
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.FieldTheory.RatFunc.Defs
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.LinearAlgebra.FreeModule.PID
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs
import Mathlib.NumberTheory.LegendreSymbol.Basic
import Mathlib.RingTheory.Ideal.Span
import Mathlib.RingTheory.LaurentSeries
import Mathlib.RingTheory.PowerSeries.Inverse
import Mathlib.RingTheory.ZMod.UnitsCyclic

noncomputable section

namespace TauCeti.ClassicalArithmetic

/-! ## CA.0 Divisibility and multiplicative arithmetic

The layer is built. The one statement the audit records as unstated is the integer
form of the Chinese remainder theorem at non-coprime moduli; `Nat.chineseRemainder'`
is the natural-number form. -/

/-- CA.0/crt-at-non-coprime-moduli-over-the-integers, existence half: the system is
solvable exactly when the two residues agree modulo the greatest common divisor. -/
theorem int_crt_exists (m n : ℤ) (hm : 0 < m) (hn : 0 < n) (a b : ℤ) :
    (∃ x : ℤ, x ≡ a [ZMOD m] ∧ x ≡ b [ZMOD n]) ↔ a ≡ b [ZMOD Int.gcd m n] := by sorry

/-- Uniqueness half: any two solutions differ by a multiple of the least common
multiple, not of the product. -/
theorem int_crt_unique (m n : ℤ) (hm : 0 < m) (hn : 0 < n) (x y : ℤ)
    (hx : x ≡ y [ZMOD m]) (hy : x ≡ y [ZMOD n]) : x ≡ y [ZMOD Int.lcm m n] := by sorry

example : True := by sorry -- unit test: for m = n the criterion is a ≡ b mod m

example : True := by sorry -- unit test: for coprime moduli the criterion is vacuous
                           -- and the statement is the classical CRT

/-! ## CA.1 Residues and reciprocity -/

/-- CA.1/unit-group-of-a-power-of-two: the class of `5` has order `2 ^ (e - 2)`. -/
theorem orderOf_five_zmod_two_pow (e : ℕ) (he : 3 ≤ e) : True := by sorry

/-- `-1` is not a power of `5`, which is what forces the product decomposition. -/
theorem neg_one_not_mem_zpowers_five (e : ℕ) (he : 3 ≤ e) : True := by sorry

/-- The explicit decomposition: every unit modulo `2 ^ e` is uniquely a sign times a
power of `5`. Mathlib's `ZMod.isCyclic_units_iff` says only that the group is not
cyclic here. -/
def unitsTwoPowEquiv (e : ℕ) (he : 3 ≤ e) : True := by sorry

example : True := by sorry -- unit test: modulo 8 the group is the Klein four group,
                           -- generated by 3 and 5

example : True := by sorry -- unit test: modulo 16 the class of 5 has order 4

/-- CA.1/power-residue-criterion-in-a-cyclic-group: in a cyclic group of order `N`,
`a` is a `d`-th power iff `a ^ (N / gcd d N) = 1`, and the `d`-th powers form the
unique subgroup of that order. -/
theorem pow_criterion_cyclic {G : Type*} [Group G] [Fintype G] [IsCyclic G]
    (d : ℕ) (hd : 0 < d) (a : G) : True := by sorry

/-- CA.1/power-residue-criterion-in-a-finite-field: the same with `N = q - 1`. The
case `n = 2` is `ZMod.euler_criterion`. -/
theorem pow_criterion_finite_field {F : Type*} [Field F] [Fintype F]
    (n : ℕ) (hn : 0 < n) (a : F) (ha : a ≠ 0) : True := by sorry

example : True := by sorry -- unit test: for n coprime to q - 1 every nonzero
                           -- element is an n-th power

example : True := by sorry -- unit test: for n = 2 this is Euler's criterion

/-! ## CA.2 Sequences and generating functions -/

variable {F : Type*} [Field F] {V : Type*} [AddCommGroup V] [Module F V]

/-- CA.2/generating-polynomials-and-the-minimal-polynomial: `g` is a generating
polynomial of `s` when every shift of the combination vanishes. -/
def IsGeneratingPoly (s : ℕ → V) (g : Polynomial F) : Prop := by sorry

/-- The generating polynomials form an ideal of `F[X]` -- closure under multiplication
by `X` is the shift invariance. -/
def generatingIdeal (s : ℕ → V) : Ideal (Polynomial F) := by sorry

/-- The monic generator: the minimal polynomial of the sequence. -/
def seqMinPoly (s : ℕ → V) : Polynomial F := by sorry

theorem seqMinPoly_monic (s : ℕ → V) (h : seqMinPoly (F := F) s ≠ 0) :
    (seqMinPoly (F := F) s).Monic := by sorry

theorem isGeneratingPoly_iff_dvd (s : ℕ → V) (g : Polynomial F) :
    IsGeneratingPoly s g ↔ seqMinPoly (F := F) s ∣ g := by sorry

example : True := by sorry -- unit test: the Fibonacci sequence has minimal
                           -- polynomial X ^ 2 - X - 1

example : True := by sorry -- unit test: the only sequence with 1 as a generating
                           -- polynomial is the zero sequence

example : True := by sorry -- unit test: for the powers of an element the sequence's
                           -- minimal polynomial is the element's

/-- CA.2/rational-power-series: the predicate the audit records as missing. -/
def PowerSeries.IsRational {K : Type*} [Field K] (f : PowerSeries K) : Prop := by sorry

theorem PowerSeries.isRational_polynomial {K : Type*} [Field K] (p : Polynomial K) :
    PowerSeries.IsRational (p : PowerSeries K) := by sorry

example : True := by sorry -- unit test: the all-ones series is rational

example : True := by sorry -- unit test: the exponential series is not rational

/-- CA.2/rational-iff-linearly-generated: Stanley's three-way equivalence. Condition
(iii) is the closed form, whose coefficients are polynomials in `n` of degree less
than the multiplicity of the root -- constants do not suffice. -/
theorem rational_iff_linearRecurrence (d : ℕ) (hd : 0 < d) (α : Fin d → ℂ)
    (hα : α ⟨d - 1, by omega⟩ ≠ 0) (f : ℕ → ℂ) : True := by sorry

example : True := by sorry -- unit test: for Q = (1 - X) ^ 2 the closed form is
                           -- linear in n, so constant coefficients are wrong

/-! ## CA.3 Polynomial and matrix arithmetic -/

/-- CA.3/smith-normal-form-of-an-integer-matrix: rectangular and possibly singular,
with invertible integer transformations and the divisibility chain. Tau Ceti has the
square nonsingular case for Gram matrices. -/
theorem exists_smithNormalForm (n m : ℕ) (A : Matrix (Fin n) (Fin m) ℤ) : True := by sorry

/-- The invariant factors, with `dᵢ ∣ dᵢ₊₁`. -/
def smithInvariantFactors (n m : ℕ) (A : Matrix (Fin n) (Fin m) ℤ) : List ℤ := by sorry

theorem smithInvariantFactors_dvd (n m : ℕ) (A : Matrix (Fin n) (Fin m) ℤ) :
    True := by sorry

theorem smithInvariantFactors_unique (n m : ℕ) (A : Matrix (Fin n) (Fin m) ℤ) :
    True := by sorry

example : True := by sorry -- unit test: diag(2, 3) has Smith form diag(1, 6)

example : True := by sorry -- unit test: the transformations are unimodular; over ℚ
                           -- every nonsingular matrix would be equivalent to the identity

example : True := by sorry -- unit test: a singular square matrix has a zero among
                           -- its diagonal entries

/-- CA.3/invariant-factor-decomposition: the structure theorem with the divisibility
chain. `Module.equiv_free_prod_directSum` is the elementary-divisor form. -/
theorem fg_abelian_invariant_factors (G : Type*) [AddCommGroup G] [Module.Finite ℤ G] :
    True := by sorry

example : True := by sorry -- unit test: ℤ/2 ⊕ ℤ/3 has invariant-factor form ℤ/6

/-! ## CA.4 Classical Diophantine equations -/

/-- CA.4/integer-linear-systems: solvability and the full parametrisation, through
the Smith normal form. Mathlib has solvability for one equation in two unknowns and
no parametrisation. -/
theorem intSolvable_iff (n m : ℕ) (A : Matrix (Fin n) (Fin m) ℤ) (b : Fin n → ℤ) :
    True := by sorry

/-- The solution set is a coset of the kernel, which is free of rank `m - s`. -/
theorem intSolutionSet_eq (n m : ℕ) (A : Matrix (Fin n) (Fin m) ℤ) (b : Fin n → ℤ) :
    True := by sorry

example : True := by sorry -- unit test: 6x + 10y = 4 has solutions
                           -- x = -1 + 5t, y = 1 - 3t

example : True := by sorry -- unit test: 6x + 10y = 3 has no integer solution,
                           -- though it has a rational one

/-! ## CA.5, CA.6, CA.7

Nothing is prototyped. CA.5 is a process layer whose removal the packet proposes.
CA.6 and CA.7 have no node, because the free sources that state their missing targets
could not be obtained; the packet's gaps say which sources a continuation job needs.
-/

end TauCeti.ClassicalArithmetic
