/-
Suggested signatures for ColemanPowerSeries L0's unramified arithmetic refinement.
The reader document is the specification. These prototypes suggest interfaces,
not an exhaustive implementation checklist. Proof placeholders establish no
formalization claim. The accepted parent packet supplies the base tower.

The pin has no canonical finite-extension structure supplier, unramified-field
Frobenius interface, or native pro-p scalar/completed-action module. The real
local-field structures below are parameters supplied by LocalFieldsRamification;
their arithmetic compatibility is stated explicitly, never replaced by a free
Prop field. Missing current-only interfaces are listed at the end and in gap G1.
-/
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.RingTheory.Polynomial.Cyclotomic.Basic
import Mathlib.RingTheory.Polynomial.Eisenstein.Basic
import Mathlib.FieldTheory.LinearDisjoint
import Mathlib.RingTheory.PowerSeries.Evaluation
import Mathlib.NumberTheory.Padics.LocalField
import Mathlib.NumberTheory.Padics.RingHoms
import Mathlib.RingTheory.RootsOfUnity.PrimitiveRoots
import Mathlib.FieldTheory.Perfect
import Mathlib.RingTheory.Norm.Transitivity
import Mathlib.Algebra.Group.Pi.Units
import Mathlib.Topology.Algebra.Monoid
import Mathlib.NumberTheory.Padics.PadicIntegers
import TauCeti.NumberTheory.LocalField.NormalizedValuation
import TauCeti.NumberTheory.LocalField.Teichmuller
import TauCeti.NumberTheory.LocalField.UnitFiltration.Basic
import TauCeti.Topology.Algebra.Group.Profinite.ProP.Basic

noncomputable section
set_option autoImplicit false
set_option linter.unusedVariables false
open ValuativeRel IsLocalRing

namespace ColemanUnramified

variable {p : ℕ} [Fact p.Prime]
variable (E Ω : Type*) [Field E] [Field Ω] [Algebra (Padic p) E]
  [Algebra E Ω] [Algebra (Padic p) Ω] [IsScalarTower (Padic p) E Ω]
variable (ρ : ℕ → Ω)

/-- The actual intermediate field generated by the chosen root. -/
def coefficientLevel (n : ℕ) : IntermediateField E Ω :=
  IntermediateField.adjoin E {ρ n}

lemma coefficientLevel_eq_adjoin (n : ℕ) :
    coefficientLevel E Ω ρ n = IntermediateField.adjoin E {ρ n} := by sorry
lemma coefficientLevel_le_succ
    (hc : ∀ n, ρ (n+1) ^ p = ρ n) (n : ℕ) :
    coefficientLevel E Ω ρ n ≤ coefficientLevel E Ω ρ (n+1) := by sorry
lemma coefficientLevel_base :
    coefficientLevel (Padic p) Ω ρ = fun n => IntermediateField.adjoin (Padic p) {ρ n} := by sorry

-- Tests: native agreement, trivial dyadic first level, and the first odd degree.
example : coefficientLevel E Ω ρ 0 = IntermediateField.adjoin E {ρ 0} := by sorry
example (hρ : ρ 0 = -1) : coefficientLevel E Ω ρ 0 = ⊥ := by sorry
example (hp : p = 3) (hρ : IsPrimitiveRoot (ρ 0) 3)
    [ValuativeRel E] [TopologicalSpace E] [IsNonarchimedeanLocalField E]
    [Algebra (PadicInt p) 𝒪[E]]
    (hu : Ideal.span ({(p : 𝒪[E])} : Set 𝒪[E]) = maximalIdeal 𝒪[E])
    [FiniteDimensional (Padic p) E] :
    Module.finrank E (coefficientLevel E Ω ρ 0) = 2 := by sorry

abbrev Level (n : ℕ) := coefficientLevel E Ω ρ n

section LocalArithmetic
variable [ValuativeRel E] [TopologicalSpace E] [IsNonarchimedeanLocalField E]
variable [∀ n, ValuativeRel (Level E Ω ρ n)]
  [∀ n, TopologicalSpace (Level E Ω ρ n)]
  [∀ n, IsNonarchimedeanLocalField (Level E Ω ρ n)]
variable [Algebra (PadicInt p) 𝒪[E]]
variable [∀ n, Algebra 𝒪[E] 𝒪[Level E Ω ρ n]]
variable [∀ n, Algebra (Level E Ω ρ n) (Level E Ω ρ (n+1))]
-- The owner supplies these with canonical inclusions into Ω and compatible valuation.
variable (hc : ∀ n, ρ (n+1)^p = ρ n)
  (hr : ∀ n, IsPrimitiveRoot (ρ n) (p^(n+1)))
  (hu : Ideal.span ({(p : 𝒪[E])} : Set 𝒪[E]) = maximalIdeal 𝒪[E])
  [FiniteDimensional (Padic p) E]

/-- Distinguishing root on the native field carrier. -/
def root (n : ℕ) : Level E Ω ρ n := by sorry
lemma root_coe (n : ℕ) : (root E Ω ρ n : Ω) = ρ n := by sorry

-- Supplier compatibility: integer and field inclusions agree.
variable (hO : ∀ n (a : 𝒪[E]),
    ((algebraMap 𝒪[E] 𝒪[Level E Ω ρ n] a : 𝒪[Level E Ω ρ n]) : Level E Ω ρ n) =
      algebraMap E (Level E Ω ρ n) (a : E))
  (hinc : ∀ n (a : Level E Ω ρ n),
    (algebraMap (Level E Ω ρ n) (Level E Ω ρ (n+1)) a : Ω) = (a : Ω))

include hc hr hu hO hinc in
lemma coefficientDegree (n : ℕ) : Module.finrank E (Level E Ω ρ n) = p^n*(p-1) := by sorry
include hu in
lemma shiftedCyclotomic_eisenstein (n : ℕ) :
    (((Polynomial.cyclotomic (p^(n+1)) (PadicInt p)).comp (Polynomial.X+1)).map
      (algebraMap (PadicInt p) 𝒪[E])).IsEisensteinAt (maximalIdeal 𝒪[E]) := by sorry
include hc hr hu in
lemma coefficientDisjoint :
    ∀ n, (IntermediateField.adjoin (Padic p) {ρ n}).LinearDisjoint E := by sorry

/-- Root minus one, corestricted to the canonical integer ring. -/
def integerPi (n : ℕ) : 𝒪[Level E Ω ρ n] := by
  have hprimitive := hr
  sorry
lemma integerPi_coe (n : ℕ) :
    ((integerPi E Ω ρ hr n : 𝒪[Level E Ω ρ n]) : Level E Ω ρ n) = root E Ω ρ n - 1 := by sorry

include hc hr hu hO hinc in
lemma coefficientUniformizer (n : ℕ) : Irreducible (integerPi E Ω ρ hr n) := by sorry
include hc hr hu hO hinc in
lemma coefficientPi_hasEval (n : ℕ) :
    PowerSeries.HasEval (integerPi E Ω ρ hr n) := by sorry
include hc hr hu hO hinc in
lemma coefficientResidueCard (n : ℕ) :
    Nat.card 𝓀[Level E Ω ρ n] = p^(Module.finrank (Padic p) E) := by sorry
include hc hr hu hO hinc in
lemma coefficientValuation_p (n : ℕ) :
    TauCeti.normalizedValuation (Level E Ω ρ n) (Units.mk0 (p : Level E Ω ρ n) (by sorry)) =
      Multiplicative.ofAdd (p^n*(p-1) : ℤ) := by sorry

include hc hr hu hO hinc in
lemma coefficientRelativeDegree (n : ℕ) :
    Module.finrank (Level E Ω ρ n) (Level E Ω ρ (n+1)) = p := by sorry

include hc hr hu hO hinc in
lemma coefficientRelativeMinpoly (n : ℕ) :
    minpoly (Level E Ω ρ n) (root E Ω ρ (n+1)) =
      Polynomial.X ^ p - Polynomial.C (root E Ω ρ n) := by sorry
include hc hr hu hO hinc in
lemma coefficientRelative_isGalois (n : ℕ) :
    IsGalois (Level E Ω ρ n) (Level E Ω ρ (n+1)) := by sorry

/-- The integral power basis is on the actual canonical integer ring. -/
def coefficientIntegralBasis (n : ℕ) : PowerBasis 𝒪[E] 𝒪[Level E Ω ρ n] := by
  have hcompat := hc; have hprimitive := hr; have hunram := hu; have hscalar := hO; have hinclusion := hinc
  sorry
lemma coefficientIntegralBasis_gen (n : ℕ) :
    (coefficientIntegralBasis E Ω ρ hc hr hu hO hinc n).gen = integerPi E Ω ρ hr n := by sorry
lemma coefficientIntegralBasis_dim (n : ℕ) :
    (coefficientIntegralBasis E Ω ρ hc hr hu hO hinc n).dim = p^n*(p-1) := by sorry
lemma coefficientIntegralBasis_repr (n : ℕ) (x : 𝒪[Level E Ω ρ n]) :
    (coefficientIntegralBasis E Ω ρ hc hr hu hO hinc n).basis.repr.symm
      ((coefficientIntegralBasis E Ω ρ hc hr hu hO hinc n).basis.repr x) = x := by sorry
example (n : ℕ) : (coefficientIntegralBasis E Ω ρ hc hr hu hO hinc n).basis ⟨0, by sorry⟩ = 1 := by sorry
example (hp : p = 2) : (coefficientIntegralBasis E Ω ρ hc hr hu hO hinc 0).dim = 1 := by sorry
example (n : ℕ) :
    let pb := coefficientIntegralBasis E Ω ρ hc hr hu hO hinc n
    let F := (Polynomial.cyclotomic (p^(n+1)) 𝒪[E]).comp (Polynomial.X+1)
    ∀ i : Fin pb.dim, pb.basis.repr (integerPi E Ω ρ hr n ^ pb.dim) i = -F.coeff i.val := by sorry

/-- Inverse of the scalar-induced map, rather than an arbitrary finite-field isomorphism. -/
def coefficientResidueEquiv (n : ℕ) : 𝓀[Level E Ω ρ n] ≃+* 𝓀[E] := by
  have hcompat := hc; have hprimitive := hr; have hunram := hu; have hscalar := hO; have hinclusion := hinc
  sorry
abbrev residueAt (n : ℕ) : 𝒪[Level E Ω ρ n] →+* 𝓀[E] :=
  (coefficientResidueEquiv E Ω ρ hc hr hu hO hinc n).toRingHom.comp
    (IsLocalRing.residue 𝒪[Level E Ω ρ n])
lemma coefficientResidueEquiv_scalar (n : ℕ) (a : 𝒪[E]) :
    residueAt E Ω ρ hc hr hu hO hinc n (algebraMap 𝒪[E] 𝒪[Level E Ω ρ n] a) =
      residue 𝒪[E] a := by sorry
lemma coefficientResidueEquiv_root (n : ℕ) :
    residueAt E Ω ρ hc hr hu hO hinc n (integerPi E Ω ρ hr n) = 0 := by sorry
lemma coefficientResidueEquiv_inclusion (n : ℕ)
    (j : 𝒪[Level E Ω ρ n] →+* 𝒪[Level E Ω ρ (n+1)])
    (hj : ∀ a, ((j a : 𝒪[Level E Ω ρ (n+1)]) : Level E Ω ρ (n+1)) =
      algebraMap (Level E Ω ρ n) (Level E Ω ρ (n+1)) (a : Level E Ω ρ n))
    (a : 𝒪[Level E Ω ρ n]) :
    residueAt E Ω ρ hc hr hu hO hinc (n+1) (j a) = residueAt E Ω ρ hc hr hu hO hinc n a := by sorry
example (n : ℕ) (a : 𝒪[E]) :
    residueAt E Ω ρ hc hr hu hO hinc n (algebraMap 𝒪[E] 𝒪[Level E Ω ρ n] a) = residue 𝒪[E] a := by sorry
example (hp : p = 2) : Nat.card 𝓀[Level E Ω ρ 0] = Nat.card 𝓀[E] := by sorry
example (hf : Module.finrank (Padic p) E = 2) (n : ℕ) :
    Nat.card 𝓀[Level E Ω ρ n] = p^2 := by sorry

/-- Field norm corestricted to the actual integer units. -/
def coefficientUnitNorm (n : ℕ) : 𝒪[Level E Ω ρ (n+1)]ˣ →ₜ* 𝒪[Level E Ω ρ n]ˣ := by
  have hcompat := hc; have hprimitive := hr; have hunram := hu; have hscalar := hO; have hinclusion := hinc
  sorry
lemma coefficientUnitNorm_coe (n : ℕ) (u : 𝒪[Level E Ω ρ (n+1)]ˣ) :
    (((coefficientUnitNorm E Ω ρ hc hr hu hO hinc n u : 𝒪[Level E Ω ρ n]ˣ) :
      𝒪[Level E Ω ρ n]) : Level E Ω ρ n) =
    Algebra.norm (Level E Ω ρ n) ((u : 𝒪[Level E Ω ρ (n+1)]) : Level E Ω ρ (n+1)) := by sorry
lemma coefficientUnitNorm_scalar (n : ℕ) (c : 𝒪[Level E Ω ρ n]ˣ)
    (j : 𝒪[Level E Ω ρ n] →+* 𝒪[Level E Ω ρ (n+1)])
    (hj : ∀ a, ((j a : 𝒪[Level E Ω ρ (n+1)]) : Level E Ω ρ (n+1)) =
      algebraMap (Level E Ω ρ n) (Level E Ω ρ (n+1)) (a : Level E Ω ρ n)) :
    coefficientUnitNorm E Ω ρ hc hr hu hO hinc n (Units.map j.toMonoidHom c) = c^p := by sorry
-- Longer norm transitions are the existing Algebra.norm_norm theorem at the actual field tower.
lemma coefficientUnitNorm_trans (n : ℕ)
    [Algebra (Level E Ω ρ n) (Level E Ω ρ (n+2))]
    [IsScalarTower (Level E Ω ρ n) (Level E Ω ρ (n+1)) (Level E Ω ρ (n+2))]
    [FiniteDimensional (Level E Ω ρ n) (Level E Ω ρ (n+1))]
    [FiniteDimensional (Level E Ω ρ (n+1)) (Level E Ω ρ (n+2))]
    (u : 𝒪[Level E Ω ρ (n+2)]ˣ) :
    (((coefficientUnitNorm E Ω ρ hc hr hu hO hinc n
      (coefficientUnitNorm E Ω ρ hc hr hu hO hinc (n+1) u) : 𝒪[Level E Ω ρ n]ˣ) :
      𝒪[Level E Ω ρ n]) : Level E Ω ρ n) =
      Algebra.norm (Level E Ω ρ n) ((u : 𝒪[Level E Ω ρ (n+2)]) : Level E Ω ρ (n+2)) := by sorry
example (n : ℕ) : coefficientUnitNorm E Ω ρ hc hr hu hO hinc n 1 = 1 := by sorry
example (n : ℕ) (c : 𝒪[E]ˣ) :
    coefficientUnitNorm E Ω ρ hc hr hu hO hinc n
      (Units.map (algebraMap 𝒪[E] 𝒪[Level E Ω ρ (n+1)]).toMonoidHom c) =
      (Units.map (algebraMap 𝒪[E] 𝒪[Level E Ω ρ n]).toMonoidHom c)^p := by sorry
example (n : ℕ) (c : 𝒪[E]ˣ) (h : c^p≠c) :
    coefficientUnitNorm E Ω ρ hc hr hu hO hinc n
      (Units.map (algebraMap 𝒪[E] 𝒪[Level E Ω ρ (n+1)]).toMonoidHom c) ≠
      Units.map (algebraMap 𝒪[E] 𝒪[Level E Ω ρ n]).toMonoidHom c := by sorry
include hc hr hu hO hinc in
lemma coefficientRootNorm (n : ℕ) :
    Algebra.norm (Level E Ω ρ n) (root E Ω ρ (n+1)) =
      (-1)^(p+1) * root E Ω ρ n := by sorry
include hc hr hu hO hinc in
lemma coefficientDifferenceNorm (n : ℕ) :
    Algebra.norm (Level E Ω ρ n) (1-root E Ω ρ (n+1)) = 1-root E Ω ρ n := by sorry
example (hp : p = 2) (n : ℕ) :
    Algebra.norm (Level E Ω ρ n) (root E Ω ρ (n+1)) = -root E Ω ρ n := by sorry

lemma coefficientNorm_residue (n : ℕ) (u : 𝒪[Level E Ω ρ (n+1)]ˣ) :
    residueAt E Ω ρ hc hr hu hO hinc n (coefficientUnitNorm E Ω ρ hc hr hu hO hinc n u) =
      (residueAt E Ω ρ hc hr hu hO hinc (n+1) u)^p := by sorry

section AbsoluteValueComparison
variable (n : ℕ) (abv : AbsoluteValue (Level E Ω ρ n) ℝ)
  (hscalar : ∀ a : Padic p, abv (algebraMap (Padic p) (Level E Ω ρ n) a)=‖a‖)
  (hintegers : ∀ x : Level E Ω ρ n, x∈𝒪[Level E Ω ρ n] ↔ abv x≤1)
include hc hr hu hO hinc hscalar hintegers in
lemma coefficientAbsoluteValue (x : Level E Ω ρ n) :
    (TauCeti.normalizedAbsoluteValue (Level E Ω ρ n) x : ℝ) =
      abv x ^ (Module.finrank (Padic p) E * (p^n*(p-1))) := by
  have hcanonicalScalar := hscalar; have hcanonicalIntegers := hintegers
  sorry
include hc hr hu hO hinc in
lemma coefficientAbsoluteValue_scalar (a : E) :
    TauCeti.normalizedAbsoluteValue (Level E Ω ρ n) (algebraMap E (Level E Ω ρ n) a) =
      TauCeti.normalizedAbsoluteValue E a ^ (p^n*(p-1)) := by sorry
end AbsoluteValueComparison

-- Native finite-field Frobenius requires its genuine characteristic hypothesis.
local instance residueTopology : TopologicalSpace 𝓀[E] := ⊥
local instance residueDiscrete : DiscreteTopology 𝓀[E] := ⟨rfl⟩
variable [CharP 𝓀[E] p]
abbrev residueFrobenius : 𝓀[E] ≃+* 𝓀[E] := frobeniusEquiv 𝓀[E] p
abbrev residueUnitsFrobenius : 𝓀[E]ˣ ≃* 𝓀[E]ˣ :=
  Units.mapEquiv (residueFrobenius (p := p) E).toMulEquiv

/-- Transport of the EXISTING native Teichmüller section through the pinned residue map. -/
abbrev omega (n : ℕ) : 𝓀[E]ˣ →* 𝒪[Level E Ω ρ n]ˣ :=
  (TauCeti.teichmuller (Level E Ω ρ n)).comp
    (Units.mapEquiv (coefficientResidueEquiv E Ω ρ hc hr hu hO hinc n).symm.toMulEquiv).toMonoidHom
lemma coefficientNorm_teichmuller (n : ℕ) (r : 𝓀[E]ˣ) :
    coefficientUnitNorm E Ω ρ hc hr hu hO hinc n (omega E Ω ρ hc hr hu hO hinc (n+1) r) =
      omega E Ω ρ hc hr hu hO hinc n (r^p) := by sorry
example (n : ℕ) (r : 𝓀[E]ˣ) (h : r^p ≠ r) :
    coefficientUnitNorm E Ω ρ hc hr hu hO hinc n (omega E Ω ρ hc hr hu hO hinc (n+1) r) ≠
      omega E Ω ρ hc hr hu hO hinc n r := by sorry

/-- Genuine norm equations on genuine integer units. -/
def coefficientUnitLimit : Subgroup (∀ n, 𝒪[Level E Ω ρ n]ˣ) := by
  exact
    { carrier := fun u => ∀ n, coefficientUnitNorm E Ω ρ hc hr hu hO hinc n (u (n+1)) = u n
      one_mem' := by sorry
      mul_mem' := by sorry
      inv_mem' := by sorry }
lemma coefficientUnitLimit_transition (u : coefficientUnitLimit E Ω ρ hc hr hu hO hinc) (n : ℕ) :
    coefficientUnitNorm E Ω ρ hc hr hu hO hinc n (u.1 (n+1)) = u.1 n := by sorry
lemma coefficientUnitLimit_ext (u v : coefficientUnitLimit E Ω ρ hc hr hu hO hinc)
    (h : ∀ n, u.1 n = v.1 n) : u=v := by sorry
/-- Apply at E=ℚ_p with the accepted parent's equalizer and canonical integer-unit maps.
The explicit receiver equation pins the parent carrier to actual field norms. -/
lemma coefficientUnitLimit_base [∀ n, Algebra (PadicInt p) (Level E Ω ρ n)]
    (η : ∀ n, (integralClosure (PadicInt p) (Level E Ω ρ n))ˣ ≃ₜ* 𝒪[Level E Ω ρ n]ˣ)
    (hη : ∀ n u, ((η n u : 𝒪[Level E Ω ρ n]) : Level E Ω ρ n) =
      ((u : integralClosure (PadicInt p) (Level E Ω ρ n)) : Level E Ω ρ n))
    (P : Subgroup (∀ n, (integralClosure (PadicInt p) (Level E Ω ρ n))ˣ))
    (hP : ∀ u, u∈P ↔ ∀ n,
      Algebra.norm (Level E Ω ρ n)
        ((u (n+1) : integralClosure (PadicInt p) (Level E Ω ρ (n+1))) : Level E Ω ρ (n+1)) =
      ((u n : integralClosure (PadicInt p) (Level E Ω ρ n)) : Level E Ω ρ n)) :
    ∃ e : P ≃ₜ* coefficientUnitLimit E Ω ρ hc hr hu hO hinc,
      ∀ u n, (e u).1 n = η n (u.1 n) := by sorry
example : (fun n => (1 : 𝒪[Level E Ω ρ n]ˣ)) ∈
    coefficientUnitLimit E Ω ρ hc hr hu hO hinc := by sorry
example (r : 𝓀[E]ˣ) (h : r^p ≠ r) :
    (fun n => omega E Ω ρ hc hr hu hO hinc n r) ∉ coefficientUnitLimit E Ω ρ hc hr hu hO hinc := by sorry
example (u v : coefficientUnitLimit E Ω ρ hc hr hu hO hinc)
    (n : ℕ) (h : u.1 n ≠ v.1 n) : u ≠ v := by sorry
example (u : ∀ n, 𝒪[Level E Ω ρ n]ˣ) :
    u∈coefficientUnitLimit E Ω ρ hc hr hu hO hinc ↔ ∀ n,
      Algebra.norm (Level E Ω ρ n) ((u (n+1) : 𝒪[Level E Ω ρ (n+1)]) : Level E Ω ρ (n+1)) =
        ((u n : 𝒪[Level E Ω ρ n]) : Level E Ω ρ n) := by sorry
lemma coefficientUnitLimit_compact :
    IsCompact (coefficientUnitLimit E Ω ρ hc hr hu hO hinc : Set (∀ n, 𝒪[Level E Ω ρ n]ˣ)) := by sorry
lemma coefficientUnitLimit_residue (u : coefficientUnitLimit E Ω ρ hc hr hu hO hinc) (n : ℕ) :
    residueAt E Ω ρ hc hr hu hO hinc n (u.1 n) =
      (((residueFrobenius (p := p) E).symm : 𝓀[E] → 𝓀[E])^[n])
        (residueAt E Ω ρ hc hr hu hO hinc 0 (u.1 0)) := by sorry

/-- Principal subgroup: the kernel of level-zero residue. -/
def coefficientPrincipalLimit : Subgroup (coefficientUnitLimit E Ω ρ hc hr hu hO hinc) := by sorry
lemma coefficientPrincipalLimit_iff (u : coefficientUnitLimit E Ω ρ hc hr hu hO hinc) :
    u ∈ coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc ↔
      ∀ n, residueAt E Ω ρ hc hr hu hO hinc n (u.1 n) = 1 := by sorry
lemma coefficientPrincipalLimit_ext (u v : coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc)
    (h : ∀ n, u.1.1 n = v.1.1 n) : u=v := by sorry
lemma coefficientPrincipalLimit_closed :
    IsClosed (coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc :
      Set (coefficientUnitLimit E Ω ρ hc hr hu hO hinc)) := by sorry
example : (1 : coefficientUnitLimit E Ω ρ hc hr hu hO hinc) ∈
    coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc := by sorry
example (u : coefficientUnitLimit E Ω ρ hc hr hu hO hinc) :
    u∈coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc ↔
      ∀ n, (u.1 n : 𝒪[Level E Ω ρ n])-1∈maximalIdeal 𝒪[Level E Ω ρ n] := by sorry
example (u : coefficientUnitLimit E Ω ρ hc hr hu hO hinc)
    (h : residueAt E Ω ρ hc hr hu hO hinc 0 (u.1 0) ≠ 1) :
    u ∉ coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc := by sorry

/-- Inverse Frobenius twists are part of the section, not a convention left implicit. -/
def coefficientTeichSection : 𝓀[E]ˣ →ₜ* coefficientUnitLimit E Ω ρ hc hr hu hO hinc := by sorry
lemma coefficientTeichSection_apply (r : 𝓀[E]ˣ) (n : ℕ) :
    (coefficientTeichSection E Ω ρ hc hr hu hO hinc r).1 n =
      omega E Ω ρ hc hr hu hO hinc n
        (((residueUnitsFrobenius (p := p) E).symm : 𝓀[E]ˣ → 𝓀[E]ˣ)^[n] r) := by sorry
lemma coefficientTeichSection_residue (r : 𝓀[E]ˣ) :
    residueAt E Ω ρ hc hr hu hO hinc 0
      ((coefficientTeichSection E Ω ρ hc hr hu hO hinc r).1 0) = (r : 𝓀[E]) := by sorry
lemma coefficientTeichSection_base (hF : residueUnitsFrobenius (p := p) E = MulEquiv.refl _)
    (r : 𝓀[E]ˣ) (n : ℕ) :
    (coefficientTeichSection E Ω ρ hc hr hu hO hinc r).1 n =
      omega E Ω ρ hc hr hu hO hinc n r := by sorry
example (r : 𝓀[E]ˣ) :
    coefficientTeichSection E Ω ρ hc hr hu hO hinc r ∈
      coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc ↔ r=1 := by sorry
example : coefficientTeichSection E Ω ρ hc hr hu hO hinc 1 = 1 := by sorry
example (hp : p=3) (hf : Nat.card 𝓀[E]=9) (r : 𝓀[E]ˣ) :
    (coefficientTeichSection E Ω ρ hc hr hu hO hinc r).1 1 =
      omega E Ω ρ hc hr hu hO hinc 1 (r^3) := by sorry
example (r : 𝓀[E]ˣ) (h : r^p ≠ r) :
    (coefficientTeichSection E Ω ρ hc hr hu hO hinc r).1 1 ≠
      omega E Ω ρ hc hr hu hO hinc 1 r := by sorry

-- Prototypes of topological group equivalences use ContinuousMulEquiv, not a plain ring map.
def coefficientUnitSplit : coefficientUnitLimit E Ω ρ hc hr hu hO hinc ≃ₜ*
    (𝓀[E]ˣ × coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc) := by sorry
lemma coefficientUnitSplit_fst (u : coefficientUnitLimit E Ω ρ hc hr hu hO hinc) :
    (((coefficientUnitSplit E Ω ρ hc hr hu hO hinc u).1) : 𝓀[E]) =
      residueAt E Ω ρ hc hr hu hO hinc 0 (u.1 0) := by sorry
lemma coefficientUnitSplit_snd (u : coefficientUnitLimit E Ω ρ hc hr hu hO hinc) (n : ℕ) :
    (coefficientUnitSplit E Ω ρ hc hr hu hO hinc u).2.1.1 n =
      ((coefficientTeichSection E Ω ρ hc hr hu hO hinc
        ((coefficientUnitSplit E Ω ρ hc hr hu hO hinc u).1)).1 n)⁻¹ * u.1 n := by sorry
lemma coefficientUnitSplit_symm (r : 𝓀[E]ˣ)
    (v : coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc) :
    (coefficientUnitSplit E Ω ρ hc hr hu hO hinc).symm (r,v) =
      coefficientTeichSection E Ω ρ hc hr hu hO hinc r * v.1 := by sorry
example (r : 𝓀[E]ˣ) : coefficientUnitSplit E Ω ρ hc hr hu hO hinc
    (coefficientTeichSection E Ω ρ hc hr hu hO hinc r) = (r,1) := by sorry
example (v : coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc) :
    coefficientUnitSplit E Ω ρ hc hr hu hO hinc v.1 = (1,v) := by sorry
example (r : 𝓀[E]ˣ) (hres : r≠1) :
    (coefficientUnitSplit E Ω ρ hc hr hu hO hinc
      (coefficientTeichSection E Ω ρ hc hr hu hO hinc r)).1≠1 := by sorry
example (r : 𝓀[E]ˣ) (h : r≠1) : coefficientTeichSection E Ω ρ hc hr hu hO hinc r ∉
    coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc := by sorry

lemma coefficientPrincipal_isProP : TauCeti.IsProP p
    (coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc) := by sorry


/-- Principal integer root used by the norm-compatible Tate coordinates. -/
def signedTateRoot (n : ℕ) : 𝒪[Level E Ω ρ n]ˣ := by
  have hprimitive := hr
  sorry
lemma signedTateRoot_odd (hp : p≠2) (n : ℕ) :
    (((signedTateRoot E Ω ρ hr n : 𝒪[Level E Ω ρ n]) : Level E Ω ρ n) : Ω) = ρ n := by sorry
lemma signedTateRoot_two (hp : p=2) (n : ℕ) :
    (((signedTateRoot E Ω ρ hr n : 𝒪[Level E Ω ρ n]) : Level E Ω ρ n) : Ω) = -ρ n := by sorry
lemma signedTateRoot_order (n : ℕ) (h : p≠2 ∨ n≠0) :
    IsPrimitiveRoot (signedTateRoot E Ω ρ hr n) (p^(n+1)) := by sorry
example (hp : p=2) : signedTateRoot E Ω ρ hr 0 = 1 := by sorry
example (hp : p=2) : IsPrimitiveRoot (signedTateRoot E Ω ρ hr 1) 4 := by sorry
example (hp : p=2) (n : ℕ) :
    let a : Ω := (((signedTateRoot E Ω ρ hr (n+1) : 𝒪[Level E Ω ρ (n+1)]) : Level E Ω ρ (n+1)) : Ω)
    let b : Ω := (((signedTateRoot E Ω ρ hr n : 𝒪[Level E Ω ρ n]) : Level E Ω ρ n) : Ω)
    a^2 = -b := by sorry
lemma signedTateRoot_norm (n : ℕ) :
    coefficientUnitNorm E Ω ρ hc hr hu hO hinc n (signedTateRoot E Ω ρ hr (n+1)) =
      signedTateRoot E Ω ρ hr n := by sorry
example (hp : p=2) :
    ∃ u : coefficientUnitLimit E Ω ρ hc hr hu hO hinc,
      u∈coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc ∧
        (∀ n, u.1 n=signedTateRoot E Ω ρ hr n) ∧ u.1 0=1 := by sorry

/-- Additive form of the continuous signed Tate embedding; scalar API uses the existing owner. -/
def signedTateTower : PadicInt p →ₜ+ Additive (coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc) := by sorry
lemma signedTateTower_coordinate (a : PadicInt p) (n : ℕ) :
    (signedTateTower E Ω ρ hc hr hu hO hinc a).toMul.1.1 n =
      signedTateRoot E Ω ρ hr n ^ (PadicInt.toZModPow (n+1) a).val := by sorry
lemma signedTateTower_injective :
    Function.Injective (signedTateTower E Ω ρ hc hr hu hO hinc) := by sorry
-- signedTateTower_scalar: omitted current-only native Module instance, G1.
example : signedTateTower E Ω ρ hc hr hu hO hinc 0 = 0 := by sorry
example (n : ℕ) :
    (signedTateTower E Ω ρ hc hr hu hO hinc 1).toMul.1.1 n =
      signedTateRoot E Ω ρ hr n := by sorry
example (hp : p=2) :
    (signedTateTower E Ω ρ hc hr hu hO hinc 1).toMul.1.1 0 = 1 := by sorry
example (hp : p=2) :
    ((((signedTateTower E Ω ρ hc hr hu hO hinc 1).toMul.1.1 1 :
      𝒪[Level E Ω ρ 1]) : Level E Ω ρ 1) : Ω) = -ρ 1 := by sorry
example (hp : p=2) :
    (signedTateTower E Ω ρ hc hr hu hO hinc 1).toMul.1.1 1 ≠
      (signedTateTower E Ω ρ hc hr hu hO hinc 0).toMul.1.1 1 := by sorry
example (hp : p=2) : (fun n => signedTateRoot E Ω ρ hr n) ∈
    coefficientUnitLimit E Ω ρ hc hr hu hO hinc := by sorry
example (r : 𝓀[E]ˣ) : coefficientTeichSection E Ω ρ hc hr hu hO hinc r ∈
    coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc ↔ r=1 := by sorry

section FrobeniusAdapter
-- The supplier gives an actual arithmetic field automorphism and its actual integer restriction.
variable (φ : E ≃ₐ[Padic p] E) (φO : 𝒪[E] ≃+* 𝒪[E])
  (hφO : ∀ a : 𝒪[E], (φO a : E) = φ (a : E))
  (hφres : ∀ a : 𝒪[E], residue 𝒪[E] (φO a) = (residue 𝒪[E] a)^p)

def coefficientFrobenius (n : ℕ) : Level E Ω ρ n ≃ₐ[Padic p] Level E Ω ρ n := by
  have hcompat := hc; have hprimitive := hr; have hunram := hu
  have hscalar := hO; have hinclusion := hinc
  have hcoeff := φ; have hcoeffInt := φO; have hcoeffCompat := hφO; have hcoeffResidue := hφres
  sorry
lemma coefficientFrobenius_scalar (n : ℕ) (a : E) :
    coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres n
      (algebraMap E (Level E Ω ρ n) a) = algebraMap E (Level E Ω ρ n) (φ a) := by sorry
lemma coefficientFrobenius_root (n : ℕ) :
    coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres n (root E Ω ρ n) = root E Ω ρ n := by sorry
lemma coefficientFrobenius_residue (n : ℕ) (a : 𝒪[Level E Ω ρ n]) :
    let b : 𝒪[Level E Ω ρ n] := ⟨coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres n a, by sorry⟩
    residueAt E Ω ρ hc hr hu hO hinc n b = (residueAt E Ω ρ hc hr hu hO hinc n a)^p := by sorry
lemma coefficientFrobenius_inclusion (n : ℕ) (a : Level E Ω ρ n) :
    coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres (n+1)
      (algebraMap (Level E Ω ρ n) (Level E Ω ρ (n+1)) a) =
      algebraMap (Level E Ω ρ n) (Level E Ω ρ (n+1))
        (coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres n a) := by sorry
lemma coefficientFrobenius_order (f : ℕ) (hf : orderOf φ=f) (n : ℕ) :
    orderOf (coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres n) = f := by sorry
example (hφ : φ=AlgEquiv.refl) (n : ℕ) :
    coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres n = AlgEquiv.refl := by sorry
example (n : ℕ) (a : 𝒪[E]) (ha : (residue 𝒪[E] a)^p ≠ residue 𝒪[E] a) :
    coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres n
      (algebraMap E (Level E Ω ρ n) a) ≠ algebraMap E (Level E Ω ρ n) a := by sorry
example (n : ℕ) :
    coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres n (root E Ω ρ n) = root E Ω ρ n := by sorry
example (hp : p=2) (hf : Nat.card 𝓀[E]=8) (n : ℕ) (a : 𝒪[E]) :
    let b : 𝒪[Level E Ω ρ n] := ⟨coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres n
      (algebraMap E (Level E Ω ρ n) (a : E)), by sorry⟩
    residueAt E Ω ρ hc hr hu hO hinc n b = (residue 𝒪[E] a)^2 := by sorry
lemma coefficientNorm_equivariant (n : ℕ) (a : Level E Ω ρ (n+1)) :
    Algebra.norm (Level E Ω ρ n)
      (coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres (n+1) a) =
    coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres n
      (Algebra.norm (Level E Ω ρ n) a) := by sorry
end FrobeniusAdapter

/-- The native field automorphisms give the finite cyclotomic action. -/
def coefficientCyclotomicAction (n : ℕ) : (PadicInt p)ˣ →* (Level E Ω ρ n ≃ₐ[E] Level E Ω ρ n) := by
  have hcompat := hc; have hprimitive := hr; have hunram := hu
  have hscalar := hO; have hinclusion := hinc
  sorry
lemma coefficientCyclotomicAction_scalar (n : ℕ) (g : (PadicInt p)ˣ) (a : E) :
    coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc n g
      (algebraMap E (Level E Ω ρ n) a) = algebraMap E (Level E Ω ρ n) a := by sorry
lemma coefficientCyclotomicAction_root (n : ℕ) (g : (PadicInt p)ˣ) :
    coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc n g (root E Ω ρ n) =
      root E Ω ρ n ^ (PadicInt.toZModPow (n+1) (g : PadicInt p)).val := by sorry
lemma coefficientCyclotomicAction_mul (n : ℕ) (g h : (PadicInt p)ˣ) :
    coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc n (g*h) =
      coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc n g *
        coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc n h := by sorry
example (n : ℕ) : coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc n 1 = 1 := by sorry
example (n : ℕ) :
    coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc n (-1) (root E Ω ρ n) = (root E Ω ρ n)⁻¹ := by sorry
example (hp : p=5) (g : (PadicInt p)ˣ) (hg : PadicInt.toZModPow 1 (g : PadicInt p)=2) :
    coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc 0 g (root E Ω ρ 0) =
      root E Ω ρ 0 ^ 2 := by sorry
example (n : ℕ) (g : (PadicInt p)ˣ)
    (hg : PadicInt.toZModPow (n+1) (g : PadicInt p)=1) :
    coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc n g = 1 := by sorry
lemma coefficientNorm_cyclotomic_equivariant (n : ℕ) (g : (PadicInt p)ˣ) (a : Level E Ω ρ (n+1)) :
    Algebra.norm (Level E Ω ρ n) (coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc (n+1) g a) =
      coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc n g (Algebra.norm (Level E Ω ρ n) a) := by sorry

section LimitActions
variable (φ : E ≃ₐ[Padic p] E) (φO : 𝒪[E] ≃+* 𝒪[E])
  (hφO : ∀ a : 𝒪[E], ((φO a : 𝒪[E]) : E) = φ (a : E))
  (hφres : ∀ a : 𝒪[E], residue 𝒪[E] (φO a) = (residue 𝒪[E] a)^p)

lemma coefficientActions_commute (n : ℕ) (g : (PadicInt p)ˣ) (a : Level E Ω ρ n) :
    coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres n
      (coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc n g a) =
    coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc n g
      (coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres n a) := by sorry

/-- Cyclotomic action and coefficient-Frobenius generator on the actual norm limit.
The order theorem factors the second component through the finite coefficient group. -/
def coefficientLimitActions :
    ((PadicInt p)ˣ →* MulAut (coefficientUnitLimit E Ω ρ hc hr hu hO hinc)) ×
      MulAut (coefficientUnitLimit E Ω ρ hc hr hu hO hinc) := by
  have hcyclo := coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc
  have hfrob := coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres
  sorry
lemma coefficientLimitActions_coordinate (g : (PadicInt p)ˣ)
    (u : coefficientUnitLimit E Ω ρ hc hr hu hO hinc) (n : ℕ) :
    ((((coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).1 g u).1 n :
      𝒪[Level E Ω ρ n]) : Level E Ω ρ n) =
    coefficientCyclotomicAction E Ω ρ hc hr hu hO hinc n g
      ((u.1 n : 𝒪[Level E Ω ρ n]) : Level E Ω ρ n) ∧
    ((((coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).2 u).1 n :
      𝒪[Level E Ω ρ n]) : Level E Ω ρ n) =
    coefficientFrobenius E Ω ρ hc hr hu hO hinc φ φO hφO hφres n
      ((u.1 n : 𝒪[Level E Ω ρ n]) : Level E Ω ρ n) := by sorry
lemma coefficientLimitActions_teich (g : (PadicInt p)ˣ) (r : 𝓀[E]ˣ) :
    (coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).1 g
      (coefficientTeichSection E Ω ρ hc hr hu hO hinc r) =
      coefficientTeichSection E Ω ρ hc hr hu hO hinc r ∧
    (coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).2
      (coefficientTeichSection E Ω ρ hc hr hu hO hinc r) =
      coefficientTeichSection E Ω ρ hc hr hu hO hinc (Units.mapEquiv (frobeniusEquiv 𝓀[E] p).toMulEquiv r) := by sorry
lemma coefficientLimitActions_commute (g : (PadicInt p)ˣ) :
    (coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).1 g *
      (coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).2 =
    (coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).2 *
      (coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).1 g := by sorry
example (u : coefficientUnitLimit E Ω ρ hc hr hu hO hinc) :
    (coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).1 1 u = u := by sorry
example (hp : p=5) (g : (PadicInt p)ˣ) (hg : PadicInt.toZModPow 1 (g : PadicInt p)=2) :
    (((((coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).1 g
      (signedTateTower E Ω ρ hc hr hu hO hinc 1).toMul.1).1 0 :
        𝒪[Level E Ω ρ 0]) : Level E Ω ρ 0) : Ω) = (ρ 0)^2 := by sorry
example (r : 𝓀[E]ˣ) (h : Units.mapEquiv (frobeniusEquiv 𝓀[E] p).toMulEquiv r ≠ r) :
    (coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).2
      (coefficientTeichSection E Ω ρ hc hr hu hO hinc r) ≠ coefficientTeichSection E Ω ρ hc hr hu hO hinc r := by sorry
example (g : (PadicInt p)ˣ) (v : coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc) :
    (coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).1 g v.1 ∈
      coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc ∧
    (coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).2 v.1 ∈
      coefficientPrincipalLimit E Ω ρ hc hr hu hO hinc := by sorry
lemma signedTateTower_equivariant (g : (PadicInt p)ˣ) (a : PadicInt p) :
    (coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).1 g
      (Multiplicative.ofAdd (signedTateTower E Ω ρ hc hr hu hO hinc a)).1 =
      (Multiplicative.ofAdd (signedTateTower E Ω ρ hc hr hu hO hinc ((g : PadicInt p)*a))).1 ∧
    (coefficientLimitActions E Ω ρ hc hr hu hO hinc φ φO hφO hφres).2
      (Multiplicative.ofAdd (signedTateTower E Ω ρ hc hr hu hO hinc a)).1 =
      (Multiplicative.ofAdd (signedTateTower E Ω ρ hc hr hu hO hinc a)).1 := by sorry
end LimitActions

end LocalArithmetic

section CanonicalComparison
-- K is the accepted parent’s actual K_n, furnished with the owner’s canonical structures.
variable (K : Type*) [Field K] [Algebra (Padic p) K] [Algebra (PadicInt p) K]
  [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [Algebra (PadicInt p) 𝒪[K]]
  (hint : ∀ x : K, IsIntegral (PadicInt p) x ↔ x∈𝒪[K])
  (hscalar : ∀ a : PadicInt p,
    ((algebraMap (PadicInt p) 𝒪[K] a : 𝒪[K]) : K) = algebraMap (PadicInt p) K a)

def baseIntegerEquiv : integralClosure (PadicInt p) K ≃ₐ[PadicInt p] 𝒪[K] := by
  have hintegers := hint; have hscalars := hscalar
  sorry
lemma baseIntegerEquiv_coe (x : integralClosure (PadicInt p) K) :
    ((baseIntegerEquiv K hint hscalar x : 𝒪[K]) : K) = (x : K) := by sorry
lemma baseIntegerEquiv_continuous : Continuous (baseIntegerEquiv K hint hscalar) := by sorry
lemma baseIntegerEquiv_symm_continuous : Continuous (baseIntegerEquiv K hint hscalar).symm := by sorry
lemma baseIntegerEquiv_scalar (a : PadicInt p) :
    baseIntegerEquiv K hint hscalar (algebraMap (PadicInt p) (integralClosure (PadicInt p) K) a) =
      algebraMap (PadicInt p) 𝒪[K] a := by sorry
example (a : PadicInt p) :
    ((baseIntegerEquiv K hint hscalar (algebraMap (PadicInt p) (integralClosure (PadicInt p) K) a) : 𝒪[K]) : K) =
      algebraMap (PadicInt p) K a := by sorry
example (π : integralClosure (PadicInt p) K) :
    ((baseIntegerEquiv K hint hscalar π : 𝒪[K]) : K) = (π : K) := by sorry
example (hp : (p : 𝒪[K]) ∈ maximalIdeal 𝒪[K]) :
    ¬ IsUnit (baseIntegerEquiv K hint hscalar (algebraMap (PadicInt p) (integralClosure (PadicInt p) K) p)) := by sorry

variable [IsLocalRing (integralClosure (PadicInt p) K)]
lemma baseIntegerEquiv_maximalIdeal (x : integralClosure (PadicInt p) K) :
    x∈maximalIdeal (integralClosure (PadicInt p) K) ↔
      baseIntegerEquiv K hint hscalar x∈maximalIdeal 𝒪[K] := by sorry

-- Parent reduction red has its verified residue equivalence and kernel; it is not an arbitrary reduction.
variable (red : integralClosure (PadicInt p) K →+* ZMod p)
  (hk : RingHom.ker red = maximalIdeal (integralClosure (PadicInt p) K))
  (rEquiv : 𝓀[K] ≃+* ZMod p)
  (hred : ∀ x : integralClosure (PadicInt p) K,
    rEquiv (residue 𝒪[K] (baseIntegerEquiv K hint hscalar x)) = red x)
lemma baseIntegerEquiv_residue (x : integralClosure (PadicInt p) K) :
    rEquiv (residue 𝒪[K] (baseIntegerEquiv K hint hscalar x)) = red x := by sorry

def basePrincipalEquiv : (Units.map red.toMonoidHom).ker ≃ₜ* TauCeti.unitFiltration K 1 := by
  have hintegers := hint; have hscalars := hscalar
  have hkernel := hk; have hresidue := hred
  sorry
lemma basePrincipalEquiv_coe (u : (Units.map red.toMonoidHom).ker) :
    ((basePrincipalEquiv K hint hscalar red hk rEquiv hred u : Kˣ) : K) =
      ((u.1 : integralClosure (PadicInt p) K) : K) := by sorry
lemma basePrincipalEquiv_residue (u : (integralClosure (PadicInt p) K)ˣ) :
    red u=1 ↔ (baseIntegerEquiv K hint hscalar (u : integralClosure (PadicInt p) K))-1∈maximalIdeal 𝒪[K] := by sorry
-- Norm compatibility uses the actual consecutive field norms, prototyped by coefficientUnitNorm_coe.
lemma basePrincipalEquiv_norm (L : Type*) [Field L] [Algebra K L]
    [Algebra (PadicInt p) L]
    (ν : (integralClosure (PadicInt p) L)ˣ →* (integralClosure (PadicInt p) K)ˣ)
    (hν : ∀ u, ((ν u : integralClosure (PadicInt p) K) : K) =
      Algebra.norm K ((u : integralClosure (PadicInt p) L) : L))
    (u : (integralClosure (PadicInt p) L)ˣ) (hprincipal : ν u∈(Units.map red.toMonoidHom).ker) :
    ((basePrincipalEquiv K hint hscalar red hk rEquiv hred ⟨ν u,hprincipal⟩ : Kˣ) : K) =
      Algebra.norm K ((u : integralClosure (PadicInt p) L) : L) := by sorry
example (ζ : (integralClosure (PadicInt p) K)ˣ) (hζ : red ζ=1) : ζ∈(Units.map red.toMonoidHom).ker := by sorry
example (ζ : (integralClosure (PadicInt p) K)ˣ) (hζ : red ζ=1) :
    ((basePrincipalEquiv K hint hscalar red hk rEquiv hred ⟨ζ,by sorry⟩ : Kˣ) : K) =
      ((ζ : integralClosure (PadicInt p) K) : K) := by sorry
example (hp : p≠2) : (-1 : (integralClosure (PadicInt p) K)ˣ) ∉ (Units.map red.toMonoidHom).ker := by sorry
example (hp : p=2) : (-1 : (integralClosure (PadicInt p) K)ˣ) ∈ (Units.map red.toMonoidHom).ker := by sorry

-- Native normalization has value one on π and d_n on p; no abstract valuation replacement.
lemma baseValuation_pi (π : 𝒪[K]) (hπ : Irreducible π) :
    TauCeti.normalizedValuation K (Units.mk0 (π : K) (by sorry)) = Multiplicative.ofAdd 1 := by sorry
lemma baseValuation_p (n : ℕ) (π : 𝒪[K]) (hπ : Irreducible π)
    (u : 𝒪[K]ˣ) (hpow : π^(p^n*(p-1))=(p : 𝒪[K])*u) :
    TauCeti.normalizedValuation K (Units.mk0 (p : K) (by sorry)) = Multiplicative.ofAdd (p^n*(p-1) : ℤ) := by sorry
lemma baseAbsoluteValue (n : ℕ) (abv : AbsoluteValue K ℝ)
    (hscalarAbs : ∀ a : Padic p, abv (algebraMap (Padic p) K a)=‖a‖)
    (hintegersAbs : ∀ x : K, x∈𝒪[K] ↔ abv x≤1)
    (hcard : Nat.card 𝓀[K]=p)
    (hvp : TauCeti.normalizedValuation K (Units.mk0 (p : K) (by sorry)) =
      Multiplicative.ofAdd (p^n*(p-1) : ℤ)) (x : K) :
    (TauCeti.normalizedAbsoluteValue K x : ℝ)=abv x^(p^n*(p-1)) := by sorry
lemma baseTeichmuller_eq (a : 𝓀[K]ˣ) (u : 𝒪[K]ˣ)
    (hpow : u^(Nat.card 𝓀[K]-1)=1) (hres : residue 𝒪[K] u=(a : 𝓀[K])) :
    u=TauCeti.teichmuller K a := by sorry
end CanonicalComparison

/-
Current-only native receiving signatures are omitted at this pin (gap G1):
coefficientTotallyRamified, coefficientRamification, coefficientAbsoluteRamification
and coefficientResidueDegree against native ramification predicates;
coefficientPrincipalScalar_eq, coefficientCompletedAction_eq, signedTateTower_scalar
and semilocalPrincipalScalar_eq against the current native modules. The scalar
and equivariance refinements of semilocalTate_eq use those same receivers.
Their exact mathematical statements, tests and
prerequisite chains remain in the packet and reader. Import the current native
IsProP.module and IsProP.completedGroupAlgebraModule when the suppliers are
adopted; never replace those constructions by assumed arbitrary module fields.
-/

section Semilocal
variable {I : Type*} [Fintype I] [Nonempty I] [DecidableEq I]
variable (Ei : I → Type*) [∀ i, Field (Ei i)] [∀ i, Algebra (Padic p) (Ei i)]
  [∀ i, Algebra (Ei i) Ω] [∀ i, IsScalarTower (Padic p) (Ei i) Ω]
  [∀ i, ValuativeRel (Ei i)] [∀ i, TopologicalSpace (Ei i)]
  [∀ i, IsNonarchimedeanLocalField (Ei i)]
  [∀ i, FiniteDimensional (Padic p) (Ei i)]
  [∀ i, Algebra (PadicInt p) 𝒪[Ei i]]
  [∀ i n, ValuativeRel (Level (Ei i) Ω ρ n)]
  [∀ i n, TopologicalSpace (Level (Ei i) Ω ρ n)]
  [∀ i n, IsNonarchimedeanLocalField (Level (Ei i) Ω ρ n)]
  [∀ i n, Algebra 𝒪[Ei i] 𝒪[Level (Ei i) Ω ρ n]]
  [∀ i n, Algebra (Level (Ei i) Ω ρ n) (Level (Ei i) Ω ρ (n+1))]
variable (hc : ∀ n, ρ (n+1)^p=ρ n)
  (hr : ∀ n, IsPrimitiveRoot (ρ n) (p^(n+1)))
  (hu : ∀ i, Ideal.span ({(p : 𝒪[Ei i])} : Set 𝒪[Ei i]) = maximalIdeal 𝒪[Ei i])
  (hO : ∀ i n (a : 𝒪[Ei i]),
    ((algebraMap 𝒪[Ei i] 𝒪[Level (Ei i) Ω ρ n] a : 𝒪[Level (Ei i) Ω ρ n]) : Level (Ei i) Ω ρ n) =
      algebraMap (Ei i) (Level (Ei i) Ω ρ n) (a : Ei i))
  (hinc : ∀ i n (a : Level (Ei i) Ω ρ n),
    (algebraMap (Level (Ei i) Ω ρ n) (Level (Ei i) Ω ρ (n+1)) a : Ω) = (a : Ω))

/-- Actual finite product of the canonical integer rings. -/
abbrev semilocalLevel (n : ℕ) := ∀ i, 𝒪[Level (Ei i) Ω ρ n]
lemma semilocalLevel_projection (n : ℕ) (i : I) :
    ∃ f : semilocalLevel Ω ρ Ei n →+* 𝒪[Level (Ei i) Ω ρ n], ∀ x, f x = x i := by sorry
lemma semilocalLevel_units (n : ℕ) (u : (semilocalLevel Ω ρ Ei n)ˣ) (i : I) :
    ((MulEquiv.piUnits u i : 𝒪[Level (Ei i) Ω ρ n])) = (u : semilocalLevel Ω ρ Ei n) i := by sorry
/-- The componentwise actual field norm, transferred across native units of a product. -/
def semilocalNorm (n : ℕ) : (semilocalLevel Ω ρ Ei (n+1))ˣ →ₜ* (semilocalLevel Ω ρ Ei n)ˣ := by
  have hnorms := fun i => coefficientUnitNorm (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) n
  sorry
lemma semilocalLevel_norm (n : ℕ) (u : (semilocalLevel Ω ρ Ei (n+1))ˣ) (i : I) :
    MulEquiv.piUnits (semilocalNorm Ω ρ Ei hc hr hu hO hinc n u) i =
      coefficientUnitNorm (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) n (MulEquiv.piUnits u i) := by sorry
lemma semilocalNorm_scalar (n : ℕ)
    (j : ∀ i, 𝒪[Level (Ei i) Ω ρ n] →+* 𝒪[Level (Ei i) Ω ρ (n+1)])
    (hj : ∀ i a, ((j i a : 𝒪[Level (Ei i) Ω ρ (n+1)]) : Level (Ei i) Ω ρ (n+1)) =
      algebraMap (Level (Ei i) Ω ρ n) (Level (Ei i) Ω ρ (n+1)) (a : Level (Ei i) Ω ρ n))
    (u : (semilocalLevel Ω ρ Ei n)ˣ) :
    semilocalNorm Ω ρ Ei hc hr hu hO hinc n
      (MulEquiv.piUnits.symm (fun i => Units.map (j i).toMonoidHom (MulEquiv.piUnits u i)))=u^p := by sorry
lemma semilocalNorm_trans (n : ℕ)
    [∀ i, Algebra (Level (Ei i) Ω ρ n) (Level (Ei i) Ω ρ (n+2))]
    [∀ i, IsScalarTower (Level (Ei i) Ω ρ n) (Level (Ei i) Ω ρ (n+1)) (Level (Ei i) Ω ρ (n+2))]
    [∀ i, FiniteDimensional (Level (Ei i) Ω ρ n) (Level (Ei i) Ω ρ (n+1))]
    [∀ i, FiniteDimensional (Level (Ei i) Ω ρ (n+1)) (Level (Ei i) Ω ρ (n+2))]
    (u : (semilocalLevel Ω ρ Ei (n+2))ˣ) (i : I) :
    ((MulEquiv.piUnits (semilocalNorm Ω ρ Ei hc hr hu hO hinc n
      (semilocalNorm Ω ρ Ei hc hr hu hO hinc (n+1) u)) i : 𝒪[Level (Ei i) Ω ρ n]) :
      Level (Ei i) Ω ρ n) =
      Algebra.norm (Level (Ei i) Ω ρ n) ((MulEquiv.piUnits u i : 𝒪[Level (Ei i) Ω ρ (n+2)]) :
        Level (Ei i) Ω ρ (n+2)) := by sorry
example (n : ℕ) : semilocalNorm Ω ρ Ei hc hr hu hO hinc n 1=1 := by sorry
example (n : ℕ) (i : I) (u : (semilocalLevel Ω ρ Ei (n+1))ˣ)
    (hunit : MulEquiv.piUnits u i=1) :
    MulEquiv.piUnits (semilocalNorm Ω ρ Ei hc hr hu hO hinc n u) i=1 := by sorry
example (hp : p=2) (n : ℕ) (i : I) :
    coefficientUnitNorm (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) n
      (signedTateRoot (Ei i) Ω ρ hr (n+1)) =
    signedTateRoot (Ei i) Ω ρ hr n := by sorry
-- Standard idempotents are the existing function-ring singletons, not new generic ring objects.
lemma semilocalLevel_idempotent (n : ℕ) (i : I) :
    (Pi.single i (1 : 𝒪[Level (Ei i) Ω ρ n]) : semilocalLevel Ω ρ Ei n)^2 =
      (Pi.single i 1 : semilocalLevel Ω ρ Ei n) := by sorry
example (n : ℕ) [Unique I] (u : semilocalLevel Ω ρ Ei n) :
    ∃ e : semilocalLevel Ω ρ Ei n ≃+* 𝒪[Level (Ei (default : I)) Ω ρ n],
      e u = u (default : I) := by sorry
example (n : ℕ) (i j : I) (h : i≠j) :
    (Pi.single i 1 : semilocalLevel Ω ρ Ei n) * Pi.single j 1 = 0 := by sorry
example (n : ℕ) (i j : I) (h : i≠j) (hall : ∀ k : I, k=i ∨ k=j) :
    (Pi.single i 1 : semilocalLevel Ω ρ Ei n) + Pi.single j 1=1 := by sorry
example (n : ℕ) (i j : I) (h : i≠j) :
    ¬ IsUnit (Pi.single i 1 : semilocalLevel Ω ρ Ei n) := by sorry

/-- Equalizers on units of the actual product ring. -/
def semilocalUnitLimit : Subgroup (∀ n, (semilocalLevel Ω ρ Ei n)ˣ) := by
  have hnorms := semilocalNorm Ω ρ Ei hc hr hu hO hinc
  sorry
lemma semilocalUnitLimit_transition (u : semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc) (n : ℕ) :
    semilocalNorm Ω ρ Ei hc hr hu hO hinc n (u.1 (n+1)) = u.1 n := by sorry
lemma semilocalUnitLimit_ext (u v : semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc)
    (h : ∀ n i, MulEquiv.piUnits (u.1 n) i = MulEquiv.piUnits (v.1 n) i) : u=v := by sorry
lemma semilocalUnitLimit_closed :
    IsClosed (semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc : Set (∀ n, (semilocalLevel Ω ρ Ei n)ˣ)) := by sorry
/-- The actual principal kernel in the semilocal norm-compatible units. -/
def semilocalPrincipalLimit : Subgroup (semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc) := by sorry
lemma semilocalUnitLimit_principal (u : semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc) :
    u∈semilocalPrincipalLimit Ω ρ Ei hc hr hu hO hinc ↔
    ∀ i n, residueAt (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) n (MulEquiv.piUnits (u.1 n) i) = 1 := by sorry
lemma semilocalPrincipalLimit_ext (u v : semilocalPrincipalLimit Ω ρ Ei hc hr hu hO hinc)
    (h : ∀ n i, MulEquiv.piUnits (u.1.1 n) i = MulEquiv.piUnits (v.1.1 n) i) : u=v := by sorry
lemma semilocalPrincipalLimit_closed :
    IsClosed (semilocalPrincipalLimit Ω ρ Ei hc hr hu hO hinc :
      Set (semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc)) := by sorry
example : (1 : ∀ n, (semilocalLevel Ω ρ Ei n)ˣ) ∈ semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc := by sorry
example (u : ∀ n, (semilocalLevel Ω ρ Ei n)ˣ) (n : ℕ) (i : I)
    (hfail : coefficientUnitNorm (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) n
      (MulEquiv.piUnits (u (n+1)) i) ≠ MulEquiv.piUnits (u n) i) :
    u∉semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc := by sorry
example : (1 : semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc) ∈
    semilocalPrincipalLimit Ω ρ Ei hc hr hu hO hinc := by sorry
example (u : semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc) (i : I)
    (h : residueAt (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) 0 (MulEquiv.piUnits (u.1 0) i) ≠ 1) :
    u∉semilocalPrincipalLimit Ω ρ Ei hc hr hu hO hinc := by sorry

/-- Reorder genuine norm-compatible coordinates, preserving their actual field norms. -/
def semilocalShuffle : semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc ≃ₜ*
    (∀ i, coefficientUnitLimit (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i)) := by sorry
lemma semilocalShuffle_apply (u : semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc) (i : I) (n : ℕ) :
    (semilocalShuffle Ω ρ Ei hc hr hu hO hinc u i).1 n = MulEquiv.piUnits (u.1 n) i := by sorry
lemma semilocalShuffle_norm (u : semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc) (i : I) (n : ℕ) :
    coefficientUnitNorm (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) n
      ((semilocalShuffle Ω ρ Ei hc hr hu hO hinc u i).1 (n+1)) =
      (semilocalShuffle Ω ρ Ei hc hr hu hO hinc u i).1 n := by sorry
lemma semilocalShuffle_principal (u : semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc) :
    u∈semilocalPrincipalLimit Ω ρ Ei hc hr hu hO hinc ↔
      ∀ i, semilocalShuffle Ω ρ Ei hc hr hu hO hinc u i ∈
        coefficientPrincipalLimit (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) := by sorry
example (u : semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc) :
    u∈semilocalPrincipalLimit Ω ρ Ei hc hr hu hO hinc ↔
      ∀ i, semilocalShuffle Ω ρ Ei hc hr hu hO hinc u i ∈
        coefficientPrincipalLimit (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) := by sorry
example (u : semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc) [Unique I] (n : ℕ) :
    (semilocalShuffle Ω ρ Ei hc hr hu hO hinc u default).1 n = MulEquiv.piUnits (u.1 n) default := by sorry
example (u : ∀ i, coefficientUnitLimit (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i)) (n : ℕ) (i : I) :
    MulEquiv.piUnits (((semilocalShuffle Ω ρ Ei hc hr hu hO hinc).symm u).1 n) i = (u i).1 n := by sorry
example (i j : I) (h : i≠j)
    (u : coefficientUnitLimit (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i)) :
    ∃ v : semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc,
      semilocalShuffle Ω ρ Ei hc hr hu hO hinc v i=u ∧ semilocalShuffle Ω ρ Ei hc hr hu hO hinc v j=1 := by sorry

variable [∀ i, CharP 𝓀[Ei i] p]
local instance semilocalResidueTopology (i : I) : TopologicalSpace 𝓀[Ei i] := ⊥
local instance semilocalResidueDiscrete (i : I) : DiscreteTopology 𝓀[Ei i] := ⟨rfl⟩

section SemilocalActions
variable (φ : ∀ i, Ei i ≃ₐ[Padic p] Ei i) (φO : ∀ i, 𝒪[Ei i] ≃+* 𝒪[Ei i])
  (hφO : ∀ i (a : 𝒪[Ei i]), ((φO i a : 𝒪[Ei i]) : Ei i) = φ i (a : Ei i))
  (hφres : ∀ i (a : 𝒪[Ei i]), residue 𝒪[Ei i] (φO i a) = (residue 𝒪[Ei i] a)^p)

def semilocalFrobenius (n : ℕ) : semilocalLevel Ω ρ Ei n ≃+* semilocalLevel Ω ρ Ei n := by
  have hfrob := fun i => coefficientFrobenius (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i)
    (φ i) (φO i) (hφO i) (hφres i) n
  sorry
lemma semilocalFrobenius_component (n : ℕ) (a : semilocalLevel Ω ρ Ei n) (i : I) :
    ((semilocalFrobenius Ω ρ Ei hc hr hu hO hinc φ φO hφO hφres n a i :
      𝒪[Level (Ei i) Ω ρ n]) : Level (Ei i) Ω ρ n) =
      coefficientFrobenius (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i)
        (φ i) (φO i) (hφO i) (hφres i) n (a i) := by sorry
lemma semilocalFrobenius_idempotent (n : ℕ) (i : I) :
    semilocalFrobenius Ω ρ Ei hc hr hu hO hinc φ φO hφO hφres n
      (Pi.single i 1) = Pi.single i 1 := by sorry
lemma semilocalFrobenius_norm (n : ℕ) (u : (semilocalLevel Ω ρ Ei (n+1))ˣ) :
    semilocalNorm Ω ρ Ei hc hr hu hO hinc n
      (Units.map (semilocalFrobenius Ω ρ Ei hc hr hu hO hinc φ φO hφO hφres (n+1)).toMonoidHom u) =
    Units.map (semilocalFrobenius Ω ρ Ei hc hr hu hO hinc φ φO hφO hφres n).toMonoidHom
      (semilocalNorm Ω ρ Ei hc hr hu hO hinc n u) := by sorry
example (hφ : ∀ i, φ i=AlgEquiv.refl) (n : ℕ) :
    semilocalFrobenius Ω ρ Ei hc hr hu hO hinc φ φO hφO hφres n=RingEquiv.refl _ := by sorry
example (n : ℕ) (i j : I) (hi : orderOf (φ i)=2) (hj : orderOf (φ j)=3)
    (hall : ∀ k, orderOf (φ k)=2 ∨ orderOf (φ k)=3) :
    orderOf (semilocalFrobenius Ω ρ Ei hc hr hu hO hinc φ φO hφO hφres n)=6 := by sorry
example (n : ℕ) (i j : I) (h : i≠j) :
    semilocalFrobenius Ω ρ Ei hc hr hu hO hinc φ φO hφO hφres n
      (Pi.single i 1) ≠ Pi.single j 1 := by sorry
example (hp : p=2) (n : ℕ) (i : I) (hf : Nat.card 𝓀[Ei i]=8)
    (a : semilocalLevel Ω ρ Ei n) :
    residueAt (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) n
      (semilocalFrobenius Ω ρ Ei hc hr hu hO hinc φ φO hφO hφres n a i) =
      (residueAt (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) n (a i))^2 := by sorry
end SemilocalActions

section PermutationActions
variable {H : Type*} [Group H] [Finite H] [MulAction H I]
  (β : ∀ (h : H) (i : I), Ei i ≃ₐ[Padic p] Ei (h•i))
  (hβone : ∀ i, HEq (β 1 i) (AlgEquiv.refl : Ei i ≃ₐ[Padic p] Ei i))
  (hβmul : ∀ g h i, HEq (β (g*h) i) ((β h i).trans (β g (h•i))))

/-- Extend the supplied genuine coefficient isomorphism by fixing the common root. -/
def semilocalCoefficientTransport (h : H) (i : I) (n : ℕ) :
    Level (Ei i) Ω ρ n ≃ₐ[Padic p] Level (Ei (h•i)) Ω ρ n := by
  have hcompat := hc; have hprimitive := hr; have hunram := hu
  have hscalar := hO; have hinclusion := hinc; have hcoeff := β h i
  sorry
lemma semilocalCoefficientTransport_scalar (h : H) (i : I) (n : ℕ) (a : Ei i) :
    semilocalCoefficientTransport Ω ρ Ei hc hr hu hO hinc β h i n
      (algebraMap (Ei i) (Level (Ei i) Ω ρ n) a) =
      algebraMap (Ei (h•i)) (Level (Ei (h•i)) Ω ρ n) (β h i a) := by sorry
lemma semilocalCoefficientTransport_root (h : H) (i : I) (n : ℕ) :
    semilocalCoefficientTransport Ω ρ Ei hc hr hu hO hinc β h i n (root (Ei i) Ω ρ n) =
      root (Ei (h•i)) Ω ρ n := by sorry
lemma semilocalCoefficientTransport_unique (h : H) (i : I) (n : ℕ)
    (γ : Level (Ei i) Ω ρ n ≃ₐ[Padic p] Level (Ei (h•i)) Ω ρ n)
    (hscalar : ∀ a, γ (algebraMap (Ei i) (Level (Ei i) Ω ρ n) a) =
      algebraMap (Ei (h•i)) (Level (Ei (h•i)) Ω ρ n) (β h i a))
    (hroot : γ (root (Ei i) Ω ρ n)=root (Ei (h•i)) Ω ρ n) :
    γ=semilocalCoefficientTransport Ω ρ Ei hc hr hu hO hinc β h i n := by sorry
example (i : I) (n : ℕ) :
    HEq (semilocalCoefficientTransport Ω ρ Ei hc hr hu hO hinc β 1 i n)
      (AlgEquiv.refl : Level (Ei i) Ω ρ n ≃ₐ[Padic p] Level (Ei i) Ω ρ n) := by
  have hidentity := hβone
  sorry
example (h : H) (i : I) (n : ℕ) :
    semilocalCoefficientTransport Ω ρ Ei hc hr hu hO hinc β h i n (root (Ei i) Ω ρ n) =
      root (Ei (h•i)) Ω ρ n := by sorry
example (h : H) (i : I) (n : ℕ) (a : Ei i) (b : Ei (h•i))
    (ha : β h i a ≠ b) :
    semilocalCoefficientTransport Ω ρ Ei hc hr hu hO hinc β h i n
      (algebraMap (Ei i) (Level (Ei i) Ω ρ n) a) ≠
      algebraMap (Ei (h•i)) (Level (Ei (h•i)) Ω ρ n) b := by sorry

def semilocalPermutationAction (n : ℕ) : H →* RingEquiv (semilocalLevel Ω ρ Ei n) (semilocalLevel Ω ρ Ei n) := by
  have htransport := semilocalCoefficientTransport Ω ρ Ei hc hr hu hO hinc β
  have hidentity := hβone; have hcocycle := hβmul
  sorry
lemma semilocalPermutationAction_coordinate (h : H) (n : ℕ) (u : semilocalLevel Ω ρ Ei n) (i : I) :
    ((semilocalPermutationAction Ω ρ Ei hc hr hu hO hinc β hβone hβmul n h u (h•i) :
      𝒪[Level (Ei (h•i)) Ω ρ n]) : Level (Ei (h•i)) Ω ρ n) =
    semilocalCoefficientTransport Ω ρ Ei hc hr hu hO hinc β h i n (u i) := by sorry
lemma semilocalPermutationAction_idempotent (h : H) (n : ℕ) (i : I) :
    semilocalPermutationAction Ω ρ Ei hc hr hu hO hinc β hβone hβmul n h
      (Pi.single i 1) = Pi.single (h•i) 1 := by sorry
lemma semilocalPermutationAction_norm (h : H) (n : ℕ) (u : (semilocalLevel Ω ρ Ei (n+1))ˣ) :
    semilocalNorm Ω ρ Ei hc hr hu hO hinc n
      (Units.map (semilocalPermutationAction Ω ρ Ei hc hr hu hO hinc β hβone hβmul (n+1) h).toMonoidHom u) =
    Units.map (semilocalPermutationAction Ω ρ Ei hc hr hu hO hinc β hβone hβmul n h).toMonoidHom
      (semilocalNorm Ω ρ Ei hc hr hu hO hinc n u) := by sorry
example (n : ℕ) (u : semilocalLevel Ω ρ Ei n) :
    semilocalPermutationAction Ω ρ Ei hc hr hu hO hinc β hβone hβmul n 1 u=u := by sorry
example (h : H) (n : ℕ) (i j : I) (hij : h•i=j) :
    semilocalPermutationAction Ω ρ Ei hc hr hu hO hinc β hβone hβmul n h
      (Pi.single i 1)=Pi.single j 1 := by sorry
example (h : H) (n : ℕ) (i : I) (hi : h•i≠i) :
    semilocalPermutationAction Ω ρ Ei hc hr hu hO hinc β hβone hβmul n h
      (Pi.single i 1)≠Pi.single i 1 := by sorry
end PermutationActions

/-- Product of the twisted local sections, transferred to the actual semilocal carrier. -/
def semilocalUnitSplit : semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc ≃ₜ*
    ((∀ i, 𝓀[Ei i]ˣ) × semilocalPrincipalLimit Ω ρ Ei hc hr hu hO hinc) := by sorry
lemma semilocalUnitSplit_residue (u : semilocalUnitLimit Ω ρ Ei hc hr hu hO hinc) (i : I) :
    (((semilocalUnitSplit Ω ρ Ei hc hr hu hO hinc u).1 i) : 𝓀[Ei i]) =
      residueAt (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) 0 (MulEquiv.piUnits (u.1 0) i) := by sorry
lemma semilocalUnitSplit_symm (r : ∀ i, 𝓀[Ei i]ˣ)
    (v : semilocalPrincipalLimit Ω ρ Ei hc hr hu hO hinc) (i : I) :
    semilocalShuffle Ω ρ Ei hc hr hu hO hinc ((semilocalUnitSplit Ω ρ Ei hc hr hu hO hinc).symm (r,v)) i =
      coefficientTeichSection (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) (r i) *
        semilocalShuffle Ω ρ Ei hc hr hu hO hinc v.1 i := by sorry
lemma semilocalUnitSplit_principal (v : semilocalPrincipalLimit Ω ρ Ei hc hr hu hO hinc) :
    semilocalUnitSplit Ω ρ Ei hc hr hu hO hinc v.1 = (1,v) := by sorry
example (r : ∀ i, 𝓀[Ei i]ˣ) :
    (semilocalUnitSplit Ω ρ Ei hc hr hu hO hinc
      ((semilocalShuffle Ω ρ Ei hc hr hu hO hinc).symm
        (fun i => coefficientTeichSection (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) (r i)))).2=1 := by sorry
example (v : semilocalPrincipalLimit Ω ρ Ei hc hr hu hO hinc) :
    (semilocalUnitSplit Ω ρ Ei hc hr hu hO hinc v.1).1=1 := by sorry
example (r : ∀ i, 𝓀[Ei i]ˣ) (i : I) (h : r i ≠ 1) :
    (semilocalShuffle Ω ρ Ei hc hr hu hO hinc).symm
      (fun i => coefficientTeichSection (Ei i) Ω ρ hc hr (hu i) (hO i) (hinc i) (r i)) ∉
      semilocalPrincipalLimit Ω ρ Ei hc hr hu hO hinc := by sorry

/-- Underlying native additive/continuous statement of the product Tate comparison.
Its scalar and completed-action refinements require the current-only module receiver. -/
lemma semilocalTate_eq :
    ∃ ι : (∀ i : I, PadicInt p) →ₜ+ Additive (semilocalPrincipalLimit Ω ρ Ei hc hr hu hO hinc),
      Function.Injective ι ∧ ∀ a n i,
        MulEquiv.piUnits ((ι a).toMul.1.1 n) i =
          signedTateRoot (Ei i) Ω ρ hr n ^ (PadicInt.toZModPow (n+1) (a i)).val := by sorry
end Semilocal

end ColemanUnramified
