/-
This file is not the roadmap and is not exhaustive. The roadmap document
`research/blueprint/readmes/HabiroCyclotomicCompletions.md` is definitive. These statements
suggest Lean forms so that contributors and reviewers can converge on names and
signatures. They claim no implementation.

BP-HabiroCyclotomicCompletions, revised by the independent review
REV-HabiroCyclotomicCompletions: partial prototype, implementationStatus = unchecked.
Mathlib 082e2d37e8b0463410cdb532e111cd43d5a66174;
Tau Ceti f790474821cf4256814db967cb154e7af3d0c369.
Synced with the reviewed packet (48 nodes) and elaborated with the Lean toolchain of
Mathlib 082e2d3 against its prebuilt library: `sorry` is the only warning. The file
imports only Mathlib; the Tau Ceti declarations the packet cites (complete separated
rings, `CoeffList` synthetic division) are named in comments, and completeness is stated
through Mathlib's uniformity of a topological additive group.

Conventions fixed here.
* `S : Set ℕ`. Mathlib's `cyclotomic 0 R = 1`, so `0 ∈ S` changes nothing; a statement
  about one order `n ∈ S` also assumes `0 < n`.
* `CycloCompletion R S` is the `R[X]`-subalgebra of compatible families in
  `∀ f : cycloIndex R S, R[X] ⧸ span {f}`; the index is a set of POLYNOMIALS (over
  `ZMod 2`, `Φ₂ = Φ₁`), not of exponent vectors. `MonicCompletion R T` is the same
  construction for any submonoid `T` of monic polynomials (Habiro §3).
* `factorialPoly R N = ∏_{i=1}^N (1 - X^i)` is NOT monic for odd `N`: its leading
  coefficient is `(-1)^N`. The normalised digits are remainders modulo the monic
  `X^(n+1) - 1`, never `%ₘ factorialPoly`.
* For finite `S` the completion IS an adic completion (`adicEquivOfFinite`), e.g.
  `R[q]^{1} = R⟦q - 1⟧`; the full completion is neither `q`-adic nor `(q-1)`-adic.
* `q` is a unit of `CycloCompletion R S` for EVERY `S` (Habiro §7.1).
* `Adjacent R m n` is Habiro's `m ⇔_R n`, separatedness for `c_{m,n}`; it is REFLEXIVE
  (`c_{n,n} = 0`), so over `ℚ` it is equality, not the empty relation.
* The p-adic re-expansion is built from `PowerSeries.eval₂Hom` (topological nilpotence),
  never `PowerSeries.subst`, whose hypothesis is nilpotence of the constant coefficient.
* The completion of a polynomial module is EXACT (`cycloModuleCompletion.map_exact`);
  derived completion of modules with torsion is HabiroRings HR.2's.

Objects that another roadmap owns are not re-planned: the derived Habiro completion is
HabiroRings HR.2's and the Habiro ring of a number field HabiroNumberFields HB.6's.
Nothing below encodes a missing theorem as an assumed structure field or as a placeholder
`Prop`, and no statement is `True`. `sorry` occurs only as the body of a declaration or as
a proof obligation inside one.

Unit tests are `example`s whose docstring begins "Test `<name>`" with the name the packet
gives, or comments `-- Test <name>: not stated; needs …`. An API item or node that cannot
be stated honestly yet is a comment `-- <name>: not stated; needs <missing object>`.
-/
import Mathlib.RingTheory.Polynomial.Cyclotomic.Basic
import Mathlib.RingTheory.Polynomial.Cyclotomic.Eval
import Mathlib.RingTheory.Polynomial.Cyclotomic.Expand
import Mathlib.RingTheory.Polynomial.Cyclotomic.Roots
import Mathlib.RingTheory.Polynomial.Resultant.Basic
import Mathlib.RingTheory.AdicCompletion.Algebra
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.Algebra.Polynomial.Div
import Mathlib.Algebra.Polynomial.Laurent
import Mathlib.Algebra.Polynomial.Taylor
import Mathlib.Algebra.Polynomial.HasseDeriv
import Mathlib.Algebra.Polynomial.Module.Basic
import Mathlib.Algebra.Exact.Basic
import Mathlib.Algebra.Module.FinitePresentation
import Mathlib.Algebra.CharP.Lemmas
import Mathlib.RingTheory.PowerSeries.Evaluation
import Mathlib.RingTheory.PowerSeries.PiTopology
import Mathlib.RingTheory.PowerSeries.Substitution
import Mathlib.Topology.Algebra.LinearTopology
import Mathlib.Topology.Algebra.Nonarchimedean.AdicTopology
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.NumberTheory.Padics.PadicIntegers
import Mathlib.NumberTheory.Padics.PadicVal.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.LinearAlgebra.TensorProduct.Basic

noncomputable section

namespace TauCeti.Habiro

open Polynomial

/-! ## HC.1 — the index monoid -/

section Index

variable (R : Type*) [CommRing R] (S : Set ℕ)

/-- HC.1/the-cyclotomic-index-monoid: `Φ*_S`, the submonoid of `R[X]` generated by the
`Φ_n`, `n ∈ S`. -/
def cycloIndex : Submonoid R[X] :=
  Submonoid.closure ((fun n => cyclotomic n R) '' S)

namespace cycloIndex

theorem cyclotomic_mem {n : ℕ} (hn : n ∈ S) : cyclotomic n R ∈ cycloIndex R S := sorry

theorem monic_of_mem {f : R[X]} (hf : f ∈ cycloIndex R S) : f.Monic := sorry

theorem mono {S' : Set ℕ} (h : S' ⊆ S) : cycloIndex R S' ≤ cycloIndex R S := sorry

theorem map_mem {R' : Type*} [CommRing R'] (φ : R →+* R') {f : R[X]}
    (hf : f ∈ cycloIndex R S) : f.map φ ∈ cycloIndex R' S := sorry

/-- A cofinal divisibility chain, e.g. `g N = ∏_{n ∈ S, n ≤ N} Φ_n ^ N`. -/
theorem exists_cofinal_chain :
    ∃ g : ℕ → cycloIndex R S, (∀ n, (g n : R[X]) ∣ (g (n + 1) : R[X])) ∧
      ∀ f : cycloIndex R S, ∃ n, (f : R[X]) ∣ (g n : R[X]) := sorry

/-- Habiro p. 1131: for finite `S` the powers of `∏_{n∈S} Φ_n` are cofinal. -/
theorem dvd_pow_prod_of_finite (hS : S.Finite) (f : cycloIndex R S) :
    ∃ j : ℕ, (f : R[X]) ∣ (∏ n ∈ hS.toFinset, cyclotomic n R) ^ j := sorry

end cycloIndex

@[simp] theorem cycloIndex_empty : cycloIndex R ∅ = ⊥ := sorry

end Index

/-- Test `cycloIndex_empty` (degenerate): `Φ*_∅ = {1}`. -/
example : cycloIndex ℤ ∅ = ⊥ := cycloIndex_empty ℤ

/-- Test `cycloIndex_zmod_two` (non-example): an index of exponent vectors would be wrong,
since `Φ₂ = X + 1 = X - 1 = Φ₁` over `ZMod 2`. -/
example : cycloIndex (ZMod 2) {1} = cycloIndex (ZMod 2) {2} := sorry

/-- Test `cycloIndex_map` (compatibility). -/
example {f : ℤ[X]} (hf : f ∈ cycloIndex ℤ {1, 6}) :
    f.map (Int.castRingHom ℚ) ∈ cycloIndex ℚ {1, 6} :=
  cycloIndex.map_mem ℤ {1, 6} (Int.castRingHom ℚ) hf

/-- Test `monic_of_mem_cycloIndex` (characterisation). -/
example : cyclotomic 1 ℤ ^ 2 * cyclotomic 6 ℤ ∈ cycloIndex ℤ {1, 6} ∧
    (cyclotomic 1 ℤ ^ 2 * cyclotomic 6 ℤ).Monic ∧ -(cyclotomic 1 ℤ) ∉ cycloIndex ℤ {1, 6} := sorry

/-! ## HC.1 — monic completions and the cyclotomic completion -/

section Completion

variable (R : Type*) [CommRing R]

/-- Habiro §3.1: the compatible families over a submonoid `T` of `R[X]` directed by
divisibility, as an `R[X]`-subalgebra of the product of the finite quotients. -/
def compatSubalgebra (T : Submonoid R[X]) :
    Subalgebra R[X] (∀ f : T, R[X] ⧸ Ideal.span {(f : R[X])}) where
  carrier := {x | ∀ (f g : T) (h : (f : R[X]) ∣ (g : R[X])),
    Ideal.Quotient.factor (Ideal.span_singleton_le_span_singleton.mpr h) (x g) = x f}
  mul_mem' := sorry
  add_mem' := sorry
  algebraMap_mem' := sorry

/-- Habiro's monic completion `R[q]^M = lim_{f ∈ M*} R[q]/(f)` (§3.1, (3.1)). -/
abbrev MonicCompletion (T : Submonoid R[X]) : Type _ := ↥(compatSubalgebra R T)

/-- The map `R[q]^M → R[q]^{M'}` induced by the identity of `R[q]` when every element of
`M'*` divides one of `M*` (Habiro's `ρ_{M,M'}`; for `M' ⊆ M` this is restriction). -/
def MonicCompletion.transition {T T' : Submonoid R[X]}
    (h : ∀ f : T', ∃ g : T, (f : R[X]) ∣ (g : R[X])) :
    MonicCompletion R T →+* MonicCompletion R T' := sorry

variable (S : Set ℕ)

/-- HC.1/the-cyclotomic-completion: Habiro's `R[q]^S = lim_{f ∈ Φ*_S} R[q]/(f)` (1.1). It is
an `R[X]`-algebra. -/
abbrev CycloCompletion : Type _ := MonicCompletion R (cycloIndex R S)

namespace CycloCompletion

/-- The map `ι : R[q] → R[q]^S`. -/
abbrev fromPoly : R[X] →+* CycloCompletion R S := algebraMap R[X] (CycloCompletion R S)

/-- The projection `π_f : R[q]^S → R[q]/(f)`. -/
def proj (f : cycloIndex R S) : CycloCompletion R S →+* R[X] ⧸ Ideal.span {(f : R[X])} :=
  (Pi.evalRingHom (fun g : cycloIndex R S => R[X] ⧸ Ideal.span {(g : R[X])}) f).comp
    (compatSubalgebra R (cycloIndex R S)).val.toRingHom

@[simp] theorem proj_fromPoly (f : cycloIndex R S) (p : R[X]) :
    proj R S f (fromPoly R S p) = Ideal.Quotient.mk _ p := sorry

theorem proj_surjective (f : cycloIndex R S) : Function.Surjective (proj R S f) := sorry

theorem ext {x y : CycloCompletion R S} (h : ∀ f, proj R S f x = proj R S f y) : x = y := sorry

theorem fromPoly_injective_iff :
    Function.Injective (fromPoly R S) ↔ (∃ n ∈ S, 0 < n) ∨ Subsingleton R := sorry

theorem subsingleton_empty : Subsingleton (CycloCompletion R ∅) := sorry

theorem not_isUnit_fromPoly_cyclotomic [Nontrivial R] {n : ℕ} (hn : n ∈ S) (h0 : 0 < n) :
    ¬ IsUnit (fromPoly R S (cyclotomic n R)) := sorry

/-! ### HC.1/the-quotients-of-the-completion -/

/-- HC.1/the-quotients-of-the-completion: `ker π_f = f · R[q]^S`. -/
theorem ker_proj (f : cycloIndex R S) :
    RingHom.ker (proj R S f) = Ideal.span {fromPoly R S (f : R[X])} := sorry

/-- Multiplication by `f ∈ Φ*_S` is injective on `R[q]^S`. -/
theorem mul_left_injective_fromPoly (f : cycloIndex R S) :
    Function.Injective (fun x : CycloCompletion R S => fromPoly R S (f : R[X]) * x) := sorry

/-- Habiro (6.1): every `x` is `ι(b) + f · c`. -/
theorem exists_eq_fromPoly_add_mul (f : cycloIndex R S) (x : CycloCompletion R S) :
    ∃ (b : R[X]) (c : CycloCompletion R S), x = fromPoly R S b + fromPoly R S (f : R[X]) * c :=
  sorry

/-! ### HC.1/topology-completeness-and-universal-property -/

/-- The inverse-limit topology: induced from the product of the DISCRETE quotients. -/
instance instTopologicalSpace : TopologicalSpace (CycloCompletion R S) :=
  TopologicalSpace.induced
    (fun x : CycloCompletion R S => (x : ∀ f : cycloIndex R S, R[X] ⧸ Ideal.span {(f : R[X])}))
    (@Pi.topologicalSpace _ _ fun _ => ⊥)

instance instIsTopologicalRing : IsTopologicalRing (CycloCompletion R S) := sorry

/-- A consequence of `instIsTopologicalRing` (`IsTopologicalRing.isTopologicalAddGroup`), stated
separately because instance search through the subalgebra structure times out. -/
instance instIsTopologicalAddGroup : IsTopologicalAddGroup (CycloCompletion R S) := sorry

instance instIsLinearTopology : IsLinearTopology (CycloCompletion R S) (CycloCompletion R S) :=
  sorry

theorem isOpen_ker_proj (f : cycloIndex R S) :
    IsOpen ((RingHom.ker (proj R S f) : Ideal (CycloCompletion R S)) : Set (CycloCompletion R S)) :=
  sorry

/-- Complete and separated for the uniformity of its additive group. Tau Ceti's
`TauCeti.TopCommRingCat.IsCompleteSeparated` (TauCeti/Topology/Category/TopCommRingCat/
CompleteSeparated/Basic.lean:80), proved by `IsCompleteSeparated.pi` and
`.of_isClosedEmbedding`, is the intended form; this Mathlib-only file states it thus. -/
theorem isCompleteSeparated :
    letI : UniformSpace (CycloCompletion R S) := IsTopologicalAddGroup.rightUniformSpace _
    CompleteSpace (CycloCompletion R S) ∧ T2Space (CycloCompletion R S) := sorry

theorem denseRange_fromPoly : DenseRange (fromPoly R S) := sorry

/-- Universal property: continuity of `φ` is for the `Φ*_S`-linear topology on `R[X]`
(existence: Mathlib's `UniformSpace.Completion.extensionHom`; uniqueness: Tau Ceti's
`UniformSpace.Completion.ringHom_ext_of_continuous`). -/
theorem exists_unique_lift {T : Type*} [CommRing T] [UniformSpace T] [IsUniformAddGroup T]
    [IsTopologicalRing T] [CompleteSpace T] [T2Space T] (φ : R[X] →+* T)
    (hφ : ∀ U ∈ nhds (0 : T), ∃ f ∈ cycloIndex R S, ∀ p ∈ Ideal.span {f}, φ p ∈ U) :
    ∃! ψ : CycloCompletion R S →+* T, Continuous ψ ∧ ψ.comp (fromPoly R S) = φ := sorry

/-! ### HC.1/completion-along-a-cofinal-family -/

/-- HC.1/completion-along-a-cofinal-family: a cofinal family of indices detects equality. -/
theorem ext_of_cofinal {ι : Type*} (g : ι → cycloIndex R S)
    (hg : ∀ f : cycloIndex R S, ∃ i, (f : R[X]) ∣ (g i : R[X])) {x y : CycloCompletion R S}
    (h : ∀ i, proj R S (g i) x = proj R S (g i) y) : x = y := sorry

theorem exists_eq_of_chain (g : ℕ → cycloIndex R S)
    (hmono : ∀ n, (g n : R[X]) ∣ (g (n + 1) : R[X]))
    (hg : ∀ f : cycloIndex R S, ∃ n, (f : R[X]) ∣ (g n : R[X]))
    (y : ∀ n, R[X] ⧸ Ideal.span {(g n : R[X])})
    (hy : ∀ n, Ideal.Quotient.factor (Ideal.span_singleton_le_span_singleton.mpr (hmono n))
      (y (n + 1)) = y n) :
    ∃ x : CycloCompletion R S, ∀ n, proj R S (g n) x = y n := sorry

/-- Habiro pp. 1127, 1131: for finite `S`, the `(∏_{n∈S} Φ_n)`-adic completion. -/
def adicEquivOfFinite (hS : S.Finite) :
    CycloCompletion R S ≃+*
      AdicCompletion (Ideal.span {∏ n ∈ hS.toFinset, cyclotomic n R}) R[X] := sorry

theorem adicEquivOfFinite_fromPoly (hS : S.Finite) (p : R[X]) :
    adicEquivOfFinite R S hS (fromPoly R S p) = algebraMap R[X] _ p := sorry

/-- `R[q]^{1} ≅ R⟦T⟧` with `q ↦ 1 + T`. -/
def equivPowerSeriesOne : CycloCompletion R {1} ≃+* PowerSeries R := sorry

theorem equivPowerSeriesOne_fromPoly_X :
    equivPowerSeriesOne R (fromPoly R {1} X) = 1 + PowerSeries.X := sorry

/-- Habiro (3.2): `R[q]^S` is the limit of the `R[q]^{S'}`, `S'` finite. -/
theorem ext_of_finite_restrict {x y : CycloCompletion R S}
    (h : ∀ f : cycloIndex R S, ∃ S' : Finset ℕ, (↑S' : Set ℕ) ⊆ S ∧
      (f : R[X]) ∈ cycloIndex R S' ∧ proj R S f x = proj R S f y) : x = y := sorry

/-! ### HC.1/functoriality-in-the-ring-and-in-the-order-set -/

/-- HC.1/functoriality-in-the-ring-and-in-the-order-set: coefficient change `h^S`. -/
def mapRing {R' : Type*} [CommRing R'] (φ : R →+* R') :
    CycloCompletion R S →+* CycloCompletion R' S := sorry

@[simp] theorem mapRing_fromPoly {R' : Type*} [CommRing R'] (φ : R →+* R') (p : R[X]) :
    mapRing R S φ (fromPoly R S p) = fromPoly R' S (p.map φ) := sorry

theorem mapRing_id : mapRing R S (RingHom.id R) = RingHom.id _ := sorry

theorem mapRing_comp {R' R'' : Type*} [CommRing R'] [CommRing R''] (φ : R →+* R')
    (ψ : R' →+* R'') : mapRing R S (ψ.comp φ) = (mapRing R' S ψ).comp (mapRing R S φ) := sorry

theorem continuous_mapRing {R' : Type*} [CommRing R'] (φ : R →+* R') :
    Continuous (mapRing R S φ) := sorry

/-- Restriction `ρ_{S,S'}` for `S' ⊆ S`. -/
def restrict {S' : Set ℕ} (h : S' ⊆ S) : CycloCompletion R S →+* CycloCompletion R S' :=
  MonicCompletion.transition R (fun f => ⟨⟨f, cycloIndex.mono R S h f.2⟩, dvd_rfl⟩)

@[simp] theorem restrict_fromPoly {S' : Set ℕ} (h : S' ⊆ S) (p : R[X]) :
    restrict R S h (fromPoly R S p) = fromPoly R S' p := sorry

theorem restrict_refl : restrict R S (subset_refl S) = RingHom.id _ := sorry

theorem restrict_restrict {S' S'' : Set ℕ} (h : S' ⊆ S) (h' : S'' ⊆ S') :
    (restrict R S' h').comp (restrict R S h) = restrict R S (h'.trans h) := sorry

theorem mapRing_comp_restrict {R' : Type*} [CommRing R'] (φ : R →+* R') {S' : Set ℕ}
    (h : S' ⊆ S) :
    (mapRing R S' φ).comp (restrict R S h) = (restrict R' S h).comp (mapRing R S φ) := sorry

/-! ### HC.1/coefficient-change-injective-and-surjective (Habiro, Lemma 3.1) -/

/-- HC.1/coefficient-change-injective-and-surjective: injective coefficient changes. -/
theorem mapRing_injective {R' : Type*} [CommRing R'] {φ : R →+* R'}
    (hφ : Function.Injective φ) : Function.Injective (mapRing R S φ) := sorry

/-- Habiro, Lemma 3.1 (`Φ_S` is countable). -/
theorem mapRing_surjective {R' : Type*} [CommRing R'] {φ : R →+* R'}
    (hφ : Function.Surjective φ) : Function.Surjective (mapRing R S φ) := sorry

end CycloCompletion

end Completion

open CycloCompletion

/-- Test `subsingleton_empty` (degenerate). -/
example (R : Type*) [CommRing R] : Subsingleton (CycloCompletion R ∅) := subsingleton_empty R

/-- Test `fromPoly_injective_iff` (characterisation). -/
example : Function.Injective (fromPoly ℤ {1}) ∧ ¬ Function.Injective (fromPoly ℤ ∅) := sorry

/-- Test `ext_by_quotients` (characterisation). -/
example (R : Type*) [CommRing R] (S : Set ℕ) (x y : CycloCompletion R S) :
    x = y ↔ ∀ f, proj R S f x = proj R S f y :=
  ⟨fun h _ => h ▸ rfl, ext R S⟩

/-- Test `proj_one_sub_q` (computation): `1 - q` vanishes at `q = 1`, is `2` at `q = -1`. -/
example :
    proj ℤ {1, 2} ⟨cyclotomic 1 ℤ, cycloIndex.cyclotomic_mem ℤ {1, 2} (by simp)⟩
        (fromPoly ℤ {1, 2} (1 - X)) = 0 ∧
    proj ℤ {1, 2} ⟨cyclotomic 2 ℤ, cycloIndex.cyclotomic_mem ℤ {1, 2} (by simp)⟩
        (fromPoly ℤ {1, 2} (1 - X)) = Ideal.Quotient.mk _ 2 := sorry

/-- Test `not_isUnit_cyclotomic` (non-example): no formal division by `Φ_n`, `n ∈ S`, although
`Φ₆` is a unit of the `(q - 1)`-adic completion. -/
example : ¬ IsUnit (fromPoly ℤ Set.univ (cyclotomic 6 ℤ)) :=
  not_isUnit_fromPoly_cyclotomic ℤ Set.univ (Set.mem_univ 6) (by norm_num)

/-- Test `isCompleteSeparated_cycloCompletion` (compatibility). -/
example (R : Type*) [CommRing R] (S : Set ℕ) :
    letI : UniformSpace (CycloCompletion R S) := IsTopologicalAddGroup.rightUniformSpace _
    CompleteSpace (CycloCompletion R S) ∧ T2Space (CycloCompletion R S) :=
  isCompleteSeparated R S

/-- Test `equivPowerSeriesOne` (characterisation): `R[q]^{1} ≅ R⟦T⟧`, `ι(q) ↦ 1 + T`. -/
example (R : Type*) [CommRing R] :
    ∃ e : CycloCompletion R {1} ≃+* PowerSeries R, e (fromPoly R {1} X) = 1 + PowerSeries.X :=
  ⟨equivPowerSeriesOne R, equivPowerSeriesOne_fromPoly_X R⟩

/-- Test `lift_at_two_nonexample` (non-example): no ring map `ℤ[q]^{1} → ℤ` extends `q ↦ 2`
(`q - 2 = (q - 1) - 1` is a unit of `ℤ⟦q - 1⟧`). -/
example : ¬ ∃ ψ : CycloCompletion ℤ {1} →+* ℤ,
    ψ.comp (fromPoly ℤ {1}) = Polynomial.evalRingHom 2 := sorry

/-- Test `kernel_is_open_ideal` (characterisation). -/
example (R : Type*) [CommRing R] (S : Set ℕ) (f : cycloIndex R S) :
    IsOpen ((Ideal.span {fromPoly R S (f : R[X])} : Ideal (CycloCompletion R S)) :
      Set (CycloCompletion R S)) ∧
    IsClosed ((Ideal.span {fromPoly R S (f : R[X])} : Ideal (CycloCompletion R S)) :
      Set (CycloCompletion R S)) := sorry

/-- Test `restrict_refl` (degenerate). -/
example (R : Type*) [CommRing R] (S : Set ℕ) : restrict R S (subset_refl S) = RingHom.id _ :=
  restrict_refl R S

/-- Test `restrict_restrict` (characterisation). -/
example (R : Type*) [CommRing R] {S S' S'' : Set ℕ} (h : S' ⊆ S) (h' : S'' ⊆ S') :
    (restrict R S' h').comp (restrict R S h) = restrict R S (h'.trans h) :=
  restrict_restrict R S h h'

/-- Test `mapRing_restrict_comm` (compatibility). -/
example {R R' : Type*} [CommRing R] [CommRing R'] (φ : R →+* R') {S S' : Set ℕ} (h : S' ⊆ S) :
    (mapRing R S' φ).comp (restrict R S h) = (restrict R' S h).comp (mapRing R S φ) :=
  mapRing_comp_restrict R S φ h

/-- Test `no_interchange` (non-example): `ℚ ⊗ ℤ[q]^{1} → ℚ[q]^{1}` is not surjective although
`ℚ` is flat over `ℤ`; `y` can be taken to be `exp (q - 1)`. -/
example : ∃ y : CycloCompletion ℚ {1}, ∀ m : ℕ, 0 < m → ∀ x : CycloCompletion ℤ {1},
    (m : CycloCompletion ℚ {1}) * y ≠ mapRing ℤ {1} (Int.castRingHom ℚ) x := sorry

/-- HC.1/coefficient-change-injective-and-surjective: `ℤ[q]^S ↪ ℚ[q]^S` and
`ℤ[q]^S ↠ 𝔽_p[q]^S`. -/
example (S : Set ℕ) (p : ℕ) [Fact p.Prime] :
    Function.Injective (mapRing ℤ S (Int.castRingHom ℚ)) ∧
    Function.Surjective (mapRing ℤ S (Int.castRingHom (ZMod p))) :=
  ⟨mapRing_injective ℤ S (Int.cast_injective), mapRing_surjective ℤ S (ZMod.intCast_surjective)⟩

/-! ## HC.1 — the factorial polynomials and cofinality -/

section Factorial

variable (R : Type*) [CommRing R]

/-- HC.1/the-factorial-polynomials: `P_N = (q; q)_N = ∏_{i=1}^N (1 - q^i)`. -/
def factorialPoly (N : ℕ) : R[X] := ∏ i ∈ Finset.Icc 1 N, (1 - X ^ i)

@[simp] theorem factorialPoly_zero : factorialPoly R 0 = 1 := sorry

theorem factorialPoly_succ (N : ℕ) :
    factorialPoly R (N + 1) = factorialPoly R N * (1 - X ^ (N + 1)) := sorry

@[simp] theorem coeff_zero_factorialPoly (N : ℕ) : (factorialPoly R N).coeff 0 = 1 := sorry

theorem monic_neg_one_pow_mul_factorialPoly (N : ℕ) : ((-1) ^ N * factorialPoly R N).Monic := sorry

theorem natDegree_factorialPoly [Nontrivial R] (N : ℕ) :
    (factorialPoly R N).natDegree = N * (N + 1) / 2 := sorry

/-- The multiplicity count: `Φ_d` occurs `⌊N/d⌋` times in `(-1)^N P_N`. -/
theorem neg_one_pow_mul_factorialPoly_eq (N : ℕ) :
    (-1) ^ N * factorialPoly R N = ∏ d ∈ Finset.Icc 1 N, cyclotomic d R ^ (N / d) := sorry

theorem neg_one_pow_mul_factorialPoly_mem (N : ℕ) :
    (-1) ^ N * factorialPoly R N ∈ cycloIndex R Set.univ := sorry

theorem map_factorialPoly {R' : Type*} [CommRing R'] (φ : R →+* R') (N : ℕ) :
    (factorialPoly R N).map φ = factorialPoly R' N := sorry

theorem factorialPoly_dvd_factorialPoly {M N : ℕ} (h : M ≤ N) :
    factorialPoly R M ∣ factorialPoly R N := sorry

/-- HC.1/cofinality-of-the-factorial-products: every `f ∈ Φ*` divides some `P_N`. -/
theorem dvd_factorialPoly_of_mem {f : R[X]} (hf : f ∈ cycloIndex R Set.univ) :
    ∃ N, f ∣ factorialPoly R N := sorry

/-- Over `ℤ` the multiplicity count is sharp: `Φ_d ^ e ∣ P_N ↔ d * e ≤ N`. -/
theorem cyclotomic_pow_dvd_factorialPoly_iff {d e N : ℕ} (hd : 0 < d) :
    cyclotomic d ℤ ^ e ∣ factorialPoly ℤ N ↔ d * e ≤ N := sorry

theorem X_pow_sub_one_pow_dvd_factorialPoly (m k : ℕ) :
    (X ^ m - 1 : R[X]) ^ k ∣ factorialPoly R (m * k) := sorry

end Factorial

/-- Test `factorialPoly_three` (computation). -/
example : factorialPoly ℤ 3 = 1 - X - X ^ 2 + X ^ 4 + X ^ 5 - X ^ 6 ∧
    factorialPoly ℤ 3 = -(cyclotomic 1 ℤ ^ 3 * cyclotomic 2 ℤ * cyclotomic 3 ℤ) := sorry

/-- Test `factorialPoly_zero` (degenerate). -/
example (R : Type*) [CommRing R] : factorialPoly R 0 = 1 := factorialPoly_zero R

/-- Test `factorialPoly_one_not_monic` (non-example): `%ₘ` by `P_N` is wrong for odd `N`. -/
example : ¬ (factorialPoly ℤ 1).Monic ∧ ((-1) ^ 1 * factorialPoly ℤ 1).Monic := sorry

/-- Test `natDegree_factorialPoly` (characterisation). -/
example (R : Type*) [CommRing R] [Nontrivial R] (N : ℕ) :
    (factorialPoly R N).natDegree = N * (N + 1) / 2 ∧ (factorialPoly R N).coeff 0 = 1 :=
  ⟨natDegree_factorialPoly R N, coeff_zero_factorialPoly R N⟩

/-- The full completion `ℤ[q]^ℕ`-style ring (`S = univ`; `0 ∈ univ` contributes `Φ₀ = 1`). -/
abbrev HabiroRing (R : Type*) [CommRing R] : Type _ := CycloCompletion R Set.univ

namespace HabiroRing

variable (R : Type*) [CommRing R]

/-- The projection to `R[X] ⧸ (P_N)`. -/
def projFactorial (N : ℕ) : HabiroRing R →+* R[X] ⧸ Ideal.span {factorialPoly R N} :=
  (Ideal.Quotient.factor (Ideal.span_singleton_le_span_singleton.mpr
      (Dvd.intro_left ((-1) ^ N) rfl : factorialPoly R N ∣ (-1) ^ N * factorialPoly R N))).comp
    (proj R Set.univ ⟨(-1) ^ N * factorialPoly R N, neg_one_pow_mul_factorialPoly_mem R N⟩)

/-- HC.1/cofinality-of-the-factorial-products: `R[q]^ℕ ≅ lim_N R[q]/(P_N)` (injectivity). -/
theorem ext_factorial {x y : HabiroRing R}
    (h : ∀ N, projFactorial R N x = projFactorial R N y) : x = y := sorry

/-- `R[q]^ℕ ≅ lim_N R[q]/(P_N)` (surjectivity). -/
theorem exists_of_factorial_family (y : ∀ N, R[X] ⧸ Ideal.span {factorialPoly R N})
    (hy : ∀ N, Ideal.Quotient.factor (Ideal.span_singleton_le_span_singleton.mpr
      (factorialPoly_dvd_factorialPoly R (Nat.le_succ N))) (y (N + 1)) = y N) :
    ∃ x : HabiroRing R, ∀ N, projFactorial R N x = y N := sorry

/-- The comparison with the `(q^m - 1)`-adic completions, `m` ordered by divisibility. -/
def toAdicXPowSubOne (m : ℕ) :
    HabiroRing R →+* AdicCompletion (Ideal.span {(X ^ m - 1 : R[X])}) R[X] := sorry

theorem ext_adicXPowSubOne {x y : HabiroRing R}
    (h : ∀ m, 0 < m → toAdicXPowSubOne R m x = toAdicXPowSubOne R m y) : x = y := sorry

/-- HC.1/not-an-ideal-adic-completion: not the `(q - 1)`-adic completion. -/
theorem not_ringEquiv_adicCompletion_X_sub_one [Nontrivial R] :
    ¬ ∃ e : HabiroRing R ≃+* AdicCompletion (Ideal.span {(X - 1 : R[X])}) R[X],
      ∀ p : R[X], e (fromPoly R Set.univ p) = algebraMap R[X] _ p := sorry

/-- Not the `q`-adic completion. -/
theorem not_ringEquiv_adicCompletion_X [Nontrivial R] :
    ¬ ∃ e : HabiroRing R ≃+* AdicCompletion (Ideal.span {(X : R[X])}) R[X],
      ∀ p : R[X], e (fromPoly R Set.univ p) = algebraMap R[X] _ p := sorry

/-- `Φ₆` is a unit of the `(q - 1)`-adic completion (`Φ₆(1) = 1`). -/
theorem isUnit_algebraMap_cyclotomic_six :
    IsUnit (algebraMap R[X] (AdicCompletion (Ideal.span {(X - 1 : R[X])}) R[X])
      (cyclotomic 6 R)) := sorry

end HabiroRing

/-- Habiro, Proposition 6.1 (`R ⊆ ℚ̄`, `S` infinite): no ideal-adic completion. -/
theorem not_isAdic_of_infinite (A : Subring (AlgebraicClosure ℚ)) {S : Set ℕ} (hS : S.Infinite) :
    ¬ ∃ (I : Ideal A[X]) (e : CycloCompletion A S ≃+* AdicCompletion I A[X]),
      ∀ p : A[X], e (fromPoly A S p) = algebraMap A[X] _ p := sorry

/-! ## HC.2 — factorial series, normalised expansions, algorithms, `q⁻¹` -/

section Digits

variable (R : Type*) [CommRing R]

/-- Remainders of the digit recursion: `r₀ = p`, `r_{n+1} = (r_n - a_n) / (1 - X^(n+1))`. -/
def factorialDigitRem (p : R[X]) : ℕ → R[X]
  | 0 => p
  | n + 1 => -(factorialDigitRem p n /ₘ (X ^ (n + 1) - 1))

/-- HC.2/factorial-expansions: the `n`-th normalised digit, the remainder modulo the MONIC
`X^(n+1) - 1`. -/
def factorialDigit (p : R[X]) (n : ℕ) : R[X] :=
  factorialDigitRem R p n %ₘ (X ^ (n + 1) - 1)

theorem degree_factorialDigit_le (p : R[X]) (n : ℕ) : (factorialDigit R p n).degree ≤ n := sorry

theorem eq_sum_factorialDigit_add (p : R[X]) (N : ℕ) :
    p = ∑ n ∈ Finset.range N, factorialDigit R p n * factorialPoly R n +
      factorialPoly R N * factorialDigitRem R p N := sorry

theorem factorialDigit_eq_of_dvd_sub {p p' : R[X]} {N : ℕ} (h : factorialPoly R N ∣ p - p')
    {n : ℕ} (hn : n < N) : factorialDigit R p n = factorialDigit R p' n := sorry

theorem factorialDigit_sum {a : ℕ → R[X]} (ha : ∀ n, (a n).degree ≤ n) (N : ℕ) {n : ℕ}
    (hn : n < N) :
    factorialDigit R (∑ i ∈ Finset.range N, a i * factorialPoly R i) n = a n := sorry

theorem map_factorialDigit {R' : Type*} [CommRing R'] (φ : R →+* R') (p : R[X]) (n : ℕ) :
    (factorialDigit R p n).map φ = factorialDigit R' (p.map φ) n := sorry

/-- API `unrestricted_not_unique`: `(1 - q)·P₀ - 1·P₁ = 0`. -/
theorem unrestricted_not_unique :
    (1 - X) * factorialPoly R 0 - 1 * factorialPoly R 1 = 0 := sorry

end Digits

/-- Test `digits_of_q` (computation): `q = 1 - (1 - q)`. -/
example : factorialDigit ℤ X 0 = 1 ∧ factorialDigit ℤ X 1 = -1 ∧ factorialDigit ℤ X 2 = 0 := sorry

namespace HabiroRing

variable (R : Type*) [CommRing R]

/-- HC.2/factorial-series: `Σ a_n P_n` for ARBITRARY `a_n` (not unique). -/
def factorialSeries (a : ℕ → R[X]) : HabiroRing R :=
  (exists_of_factorial_family R
    (fun N => Ideal.Quotient.mk _ (∑ n ∈ Finset.range N, a n * factorialPoly R n)) sorry).choose

theorem projFactorial_factorialSeries (a : ℕ → R[X]) (N : ℕ) :
    projFactorial R N (factorialSeries R a) =
      Ideal.Quotient.mk _ (∑ n ∈ Finset.range N, a n * factorialPoly R n) := sorry

theorem hasSum_factorialSeries (a : ℕ → R[X]) :
    HasSum (fun n => fromPoly R Set.univ (a n * factorialPoly R n)) (factorialSeries R a) := sorry

/-- The convergence criterion requested by QSeriesPartitionsAndMockModularForms QM.5. -/
theorem summable_of_mem_span_factorialPoly (b : ℕ → R[X]) (m : ℕ → ℕ)
    (hm : Filter.Tendsto m Filter.atTop Filter.atTop)
    (hb : ∀ n, b n ∈ Ideal.span {factorialPoly R (m n)}) :
    Summable (fun n => fromPoly R Set.univ (b n)) := sorry

theorem factorialSeries_add (a b : ℕ → R[X]) :
    factorialSeries R (a + b) = factorialSeries R a + factorialSeries R b := sorry

/-- Kontsevich's series `F = Σ (q;q)_n`. -/
def kontsevichSeries : HabiroRing R := factorialSeries R 1

/-- HC.2/factorial-expansions: the normalised digits of an element. -/
def factorialCoeff (x : HabiroRing R) (n : ℕ) : R[X] :=
  factorialDigit R (Ideal.Quotient.mk_surjective (projFactorial R (n + 1) x)).choose n

theorem degree_factorialCoeff_le (x : HabiroRing R) (n : ℕ) :
    (factorialCoeff R x n).degree ≤ n := sorry

theorem factorialSeries_factorialCoeff (x : HabiroRing R) :
    factorialSeries R (factorialCoeff R x) = x := sorry

/-- Uniqueness of the normalised expansion. -/
theorem factorialCoeff_factorialSeries {a : ℕ → R[X]} (ha : ∀ n, (a n).degree ≤ n) :
    factorialCoeff R (factorialSeries R a) = a := sorry

theorem factorialCoeff_eq_of_projFactorial_eq {x y : HabiroRing R} {N : ℕ}
    (h : projFactorial R N x = projFactorial R N y) {n : ℕ} (hn : n < N) :
    factorialCoeff R x n = factorialCoeff R y n := sorry

theorem map_factorialCoeff {R' : Type*} [CommRing R'] (φ : R →+* R') (x : HabiroRing R) (n : ℕ) :
    (factorialCoeff R x n).map φ = factorialCoeff R' (mapRing R Set.univ φ x) n := sorry

/-! ### HC.2/algorithms-on-expansions -/

/-- HC.2/algorithms-on-expansions: digit `n` of a product, with renormalisation (carries go
upwards only). -/
def expansionMul (a b : ℕ → R[X]) (n : ℕ) : R[X] :=
  factorialDigit R ((∑ i ∈ Finset.range (n + 1), a i * factorialPoly R i) *
    (∑ j ∈ Finset.range (n + 1), b j * factorialPoly R j)) n

theorem factorialCoeff_add (x y : HabiroRing R) :
    factorialCoeff R (x + y) = factorialCoeff R x + factorialCoeff R y := sorry

theorem factorialCoeff_mul (x y : HabiroRing R) (n : ℕ) :
    factorialCoeff R (x * y) n = expansionMul R (factorialCoeff R x) (factorialCoeff R y) n := sorry

theorem expansionMul_congr {a a' b b' : ℕ → R[X]} {n : ℕ} (ha : ∀ i ≤ n, a i = a' i)
    (hb : ∀ i ≤ n, b i = b' i) : expansionMul R a b n = expansionMul R a' b' n := sorry

-- factorialDigitList: not stated; needs Tau Ceti's executable synthetic division
-- `TauCeti.Polynomial.divModByMonicList` (TauCeti/Algebra/Polynomial/CoeffList.lean:330),
-- which this Mathlib-only file does not import: the digit recursion on descending integer
-- coefficient lists, dividing by the tail `0, …, 0, -1` of `X^(n+1) - 1`.
-- ofCoeffList_factorialDigitList: not stated; needs the same `CoeffList` API
-- (`ofCoeffList_divByMonicList`, `ofCoeffList_modByMonicList`, lines 395 and 407):
-- `ofCoeffList (factorialDigitList l n) = factorialDigit ℤ (ofCoeffList l) n`.

/-! ### HC.2/invertibility-of-q -/

theorem X_mul_sum_eq (N : ℕ) :
    X * ∑ n ∈ Finset.range N, X ^ n * factorialPoly R n = 1 - factorialPoly R N := sorry

/-- HC.2/invertibility-of-q: Habiro, Proposition 7.1, `q⁻¹ = Σ q^n (q)_n`. -/
theorem fromPoly_X_mul_factorialSeries :
    fromPoly R Set.univ X * factorialSeries R (fun n => X ^ n) = 1 := sorry

end HabiroRing

section Units

variable (R : Type*) [CommRing R] (S : Set ℕ)

/-- Habiro §7.1: `q` is a unit for EVERY `S` (constant terms of the `Φ_n` are `±1`). -/
theorem isUnit_fromPoly_X : IsUnit (fromPoly R S X) := sorry

/-- The extension of `ι` to Laurent polynomials (`IsLocalization.Away.lift` at `X`). -/
def fromLaurent : LaurentPolynomial R →+* CycloCompletion R S := sorry

theorem fromLaurent_toLaurent (p : R[X]) :
    fromLaurent R S (Polynomial.toLaurent p) = fromPoly R S p := sorry

/-- Each finite level: `R[q]/(f) ≅ R[q, q⁻¹]/(f)`, so `R[q]^S ≅ lim R[q, q⁻¹]/(f)`. -/
def laurentQuotientEquiv (f : cycloIndex R S) :
    R[X] ⧸ Ideal.span {(f : R[X])} ≃+*
      LaurentPolynomial R ⧸ Ideal.span {Polynomial.toLaurent (f : R[X])} := sorry

theorem fromLaurent_injective (h : ∃ n ∈ S, 0 < n) : Function.Injective (fromLaurent R S) := sorry

end Units

open HabiroRing

/-- Test `kontsevich_mod_P2` (computation): `F ≡ 2 - q (mod P₂)`. -/
example : projFactorial ℤ 2 (kontsevichSeries ℤ) = Ideal.Quotient.mk _ (2 - X) := sorry

/-- Test `factorialSeries_relation` (non-example): unrestricted coefficients are not unique. -/
example : factorialSeries ℤ (fun n => if n = 0 then 1 - X else if n = 1 then -1 else 0) = 0 :=
  sorry

/-- Test `factorialSeries_X_pow` (characterisation): Habiro, Proposition 7.1. -/
example (R : Type*) [CommRing R] :
    fromPoly R Set.univ X * factorialSeries R (fun n => X ^ n) = 1 :=
  fromPoly_X_mul_factorialSeries R

/-- Test `factorialSeries_single` (degenerate). -/
example (R : Type*) [CommRing R] (p : R[X]) :
    factorialSeries R (fun n => if n = 0 then p else 0) = fromPoly R Set.univ p := sorry

/-- Test `kontsevich_digits` (computation): all normalised digits of `F` are `1`. -/
example : factorialCoeff ℤ (kontsevichSeries ℤ) = 1 := sorry

/-- Test `q_inv_digits` (computation). -/
example : factorialCoeff ℤ (factorialSeries ℤ (fun n => X ^ n)) = fun n => X ^ n := sorry

/-- Test `unrestricted_not_unique` (non-example): `(1 - q, -1, 0, …)` sums to `0`, whose
normalised digits are all `0`. -/
example : factorialSeries ℤ (fun n => if n = 0 then 1 - X else if n = 1 then -1 else 0) = 0 ∧
    factorialCoeff ℤ 0 = 0 := sorry

/-- Test `digits_map_zmod` (compatibility). -/
example (p : ℕ) (x : HabiroRing ℤ) (n : ℕ) :
    (factorialCoeff ℤ x n).map (Int.castRingHom (ZMod p)) =
      factorialCoeff (ZMod p) (mapRing ℤ Set.univ (Int.castRingHom (ZMod p)) x) n :=
  map_factorialCoeff ℤ _ x n

/-- Test `expansionAdd_digitwise` (characterisation): addition has no carries. -/
example (R : Type*) [CommRing R] (x y : HabiroRing R) :
    factorialCoeff R (x + y) = factorialCoeff R x + factorialCoeff R y :=
  factorialCoeff_add R x y

/-- Test `kontsevich_sq_precision_three` (computation):
`F² ≡ 1 + (3 - q)P₁ + (6 - 3q - q²)P₂ (mod P₃)`. -/
example : expansionMul ℤ 1 1 0 = 1 ∧ expansionMul ℤ 1 1 1 = 3 - X ∧
    expansionMul ℤ 1 1 2 = 6 - 3 * X - X ^ 2 := sorry

/-- Test `mul_needs_carry` (non-example): the unrenormalised coefficient has degree 3. -/
example : (2 + 2 * factorialPoly ℤ 1 + factorialPoly ℤ 2 : ℤ[X]) = X ^ 3 - X ^ 2 - 3 * X + 5 ∧
    (X ^ 3 - X ^ 2 - 3 * X + 5 : ℤ[X]) - (6 - 3 * X - X ^ 2) = X ^ 3 - 1 := sorry

/-- Test `expansionMul_congr` (characterisation). -/
example (R : Type*) [CommRing R] {a a' b b' : ℕ → R[X]} {n : ℕ} (ha : ∀ i ≤ n, a i = a' i)
    (hb : ∀ i ≤ n, b i = b' i) : expansionMul R a b n = expansionMul R a' b' n :=
  expansionMul_congr R ha hb

-- Test factorialDigitList_correct: not stated; needs Tau Ceti's `CoeffList` (see above).

/-- HC.2/invertibility-of-q: `q` is a unit of `ℤ[q]^{2} = ℤ⟦q + 1⟧`, so `1 ∈ S` is not needed. -/
example : IsUnit (fromPoly ℤ {2} X) := isUnit_fromPoly_X ℤ {2}

/-- HC.2/invertibility-of-q: `q⁻¹ ≡ 1 + q - q³ - q⁴ + q⁵ (mod P₃)`. -/
example : projFactorial ℤ 3 (factorialSeries ℤ (fun n => X ^ n)) =
    Ideal.Quotient.mk _ (1 + X - X ^ 3 - X ^ 4 + X ^ 5) := sorry

/-! ## HC.3 — evaluation, Taylor maps, naturality, p-adic re-expansion -/

section Evaluation

variable (R : Type*) [CommRing R] (S : Set ℕ) {A : Type*} [CommRing A] [Algebra R A]

/-- HC.3/evaluation-at-a-root-of-unity: evaluation at a root `ζ` of `Φ_n`, `n ∈ S`: the
projection to `R[X] ⧸ (Φ_n) = AdjoinRoot Φ_n` followed by `X ↦ ζ`. -/
def evalAt {n : ℕ} (hn : n ∈ S) (ζ : A) (hζ : aeval ζ (cyclotomic n R) = 0) :
    CycloCompletion R S →+* A :=
  (Ideal.Quotient.lift _ (aeval ζ).toRingHom sorry).comp
    (proj R S ⟨cyclotomic n R, cycloIndex.cyclotomic_mem R S hn⟩)

@[simp] theorem evalAt_fromPoly {n : ℕ} (hn : n ∈ S) (ζ : A)
    (hζ : aeval ζ (cyclotomic n R) = 0) (g : R[X]) :
    evalAt R S hn ζ hζ (fromPoly R S g) = aeval ζ g := sorry

/-- Independence of the truncation. -/
theorem evalAt_eq_of_proj {n : ℕ} (hn : n ∈ S) (ζ : A) (hζ : aeval ζ (cyclotomic n R) = 0)
    (f : cycloIndex R S) (hdvd : cyclotomic n R ∣ (f : R[X])) (x : CycloCompletion R S)
    (g : R[X]) (hg : proj R S f x = Ideal.Quotient.mk _ g) :
    evalAt R S hn ζ hζ x = aeval ζ g := sorry

theorem evalAt_eq_liftAlgHom_comp_proj {n : ℕ} (hn : n ∈ S) (ζ : A)
    (hζ : aeval ζ (cyclotomic n R) = 0) (x : CycloCompletion R S) :
    evalAt R S hn ζ hζ x =
      AdjoinRoot.liftAlgHom (cyclotomic n R) (Algebra.ofId R A) ζ
        (by rwa [aeval_def] at hζ) (proj R S ⟨cyclotomic n R, cycloIndex.cyclotomic_mem R S hn⟩ x) :=
  sorry

/-- Evaluation of a factorial series at a primitive root of order `m` in a domain: only the
terms with `k < m` survive (the formula QM.5 requests). -/
theorem evalAt_factorialSeries [IsDomain A] {m : ℕ} (ζ : A) (hζ : IsPrimitiveRoot ζ m)
    (hζ' : aeval ζ (cyclotomic m R) = 0) (a : ℕ → R[X]) :
    evalAt R Set.univ (Set.mem_univ m) ζ hζ' (factorialSeries R a) =
      ∑ k ∈ Finset.range m, aeval ζ (a k) * aeval ζ (factorialPoly R k) := sorry

/-- Continuous homomorphisms to a discrete domain are evaluations at roots of some `Φ_m`,
`m ∈ S`. -/
theorem exists_cyclotomic_root_of_continuous {D : Type*} [CommRing D] [IsDomain D]
    [TopologicalSpace D] [DiscreteTopology D] (φ : CycloCompletion R S →+* D)
    (hφ : Continuous φ) :
    ∃ m ∈ S, 0 < m ∧
      (cyclotomic m R).eval₂ ((φ.comp (fromPoly R S)).comp C) (φ (fromPoly R S X)) = 0 := sorry

/-- Habiro's `ε : ℤ[q]^ℕ → Map(Z_ℕ, ℤ[Z_ℕ])`: the family of values at all roots of unity. -/
def evalFamily (x : HabiroRing ℤ) : {ζ : ℂ // ∃ n, 0 < n ∧ IsPrimitiveRoot ζ n} → ℂ := sorry

end Evaluation

/-- The root of `Φ_n` in `AdjoinRoot Φ_n`. -/
theorem aeval_root_cyclotomic (R : Type*) [CommRing R] (n : ℕ) :
    aeval (AdjoinRoot.root (cyclotomic n R)) (cyclotomic n R) = 0 := by
  rw [AdjoinRoot.aeval_eq, AdjoinRoot.mk_self]

/-- Test `evalAt_kontsevich` (computation): `F(1) = 1`, `F(-1) = 3`, `F(ζ₃) = 5 - ζ₃`,
`F(i) = 8 - 3i`. -/
example : evalAt ℤ Set.univ (Set.mem_univ 1) (1 : ℤ) (by simp) (kontsevichSeries ℤ) = 1 ∧
    evalAt ℤ Set.univ (Set.mem_univ 2) (-1 : ℤ) sorry (kontsevichSeries ℤ) = 3 ∧
    evalAt ℤ Set.univ (Set.mem_univ 3) (AdjoinRoot.root (cyclotomic 3 ℤ))
      (aeval_root_cyclotomic ℤ 3) (kontsevichSeries ℤ) = 5 - AdjoinRoot.root (cyclotomic 3 ℤ) ∧
    evalAt ℤ Set.univ (Set.mem_univ 4) (AdjoinRoot.root (cyclotomic 4 ℤ))
      (aeval_root_cyclotomic ℤ 4) (kontsevichSeries ℤ) =
        8 - 3 * AdjoinRoot.root (cyclotomic 4 ℤ) := sorry

/-- Test `evalAt_one_sub_q` (computation). -/
example {A : Type*} [CommRing A] {n : ℕ} (ζ : A) (hζ : aeval ζ (cyclotomic n ℤ) = 0) :
    evalAt ℤ Set.univ (Set.mem_univ n) ζ hζ (fromPoly ℤ Set.univ (1 - X)) = 1 - ζ := by
  simp

/-- Test `evalAt_indep` (characterisation): any representative modulo `P_N`, `N ≥ ord ζ`. -/
example {A : Type*} [CommRing A] {n N : ℕ} (hnN : n ≤ N) (ζ : A)
    (hζ : aeval ζ (cyclotomic n ℤ) = 0) (x : HabiroRing ℤ) (g : ℤ[X])
    (hg : projFactorial ℤ N x = Ideal.Quotient.mk _ g) :
    evalAt ℤ Set.univ (Set.mem_univ n) ζ hζ x = aeval ζ g := sorry

/-- Test `evalAt_eq_liftAlgHom_comp_proj` (compatibility). -/
example {A : Type*} [CommRing A] {n : ℕ} (ζ : A) (hζ : aeval ζ (cyclotomic n ℤ) = 0)
    (x : HabiroRing ℤ) :
    evalAt ℤ Set.univ (Set.mem_univ n) ζ hζ x =
      AdjoinRoot.liftAlgHom (cyclotomic n ℤ) (Algebra.ofId ℤ A) ζ (by rwa [aeval_def] at hζ)
        (proj ℤ Set.univ ⟨cyclotomic n ℤ, cycloIndex.cyclotomic_mem ℤ _ (Set.mem_univ n)⟩ x) :=
  evalAt_eq_liftAlgHom_comp_proj ℤ Set.univ (Set.mem_univ n) ζ hζ x

/-- Test `no_eval_neg_one_on_Zq1` (non-example): `2 - q` is a unit of `ℤ⟦q - 1⟧`. -/
example : ¬ ∃ φ : CycloCompletion ℤ {1} →+* ℤ, φ (fromPoly ℤ {1} X) = -1 := sorry

/-- Test `evalAt_empty` (degenerate): the zero ring has no evaluation into a nonzero ring. -/
example {A : Type*} [CommRing A] [Nontrivial A] : IsEmpty (CycloCompletion ℤ ∅ →+* A) := sorry

section Taylor

variable (R : Type*) [CommRing R] (S : Set ℕ) {A : Type*} [CommRing A] [Algebra R A]

/-- HC.3/the-taylor-map: Habiro's expansion homomorphism `σ_ζ`, with `X` standing for
`q - ζ`. -/
def taylorAt {n : ℕ} (hn : n ∈ S) (ζ : A) (hζ : aeval ζ (cyclotomic n R) = 0) :
    CycloCompletion R S →+* PowerSeries A := sorry

@[simp] theorem constantCoeff_taylorAt {n : ℕ} (hn : n ∈ S) (ζ : A)
    (hζ : aeval ζ (cyclotomic n R) = 0) (x : CycloCompletion R S) :
    PowerSeries.constantCoeff (taylorAt R S hn ζ hζ x) = evalAt R S hn ζ hζ x := sorry

@[simp] theorem taylorAt_fromPoly {n : ℕ} (hn : n ∈ S) (ζ : A)
    (hζ : aeval ζ (cyclotomic n R) = 0) (g : R[X]) :
    taylorAt R S hn ζ hζ (fromPoly R S g) =
      ((taylor ζ (g.map (algebraMap R A)) : A[X]) : PowerSeries A) := sorry

/-- The `k`-th coefficient is the `k`-th HASSE derivative of any representative modulo an
index divisible by `Φ_n^(k+1)`. -/
theorem coeff_taylorAt {n : ℕ} (hn : n ∈ S) (ζ : A) (hζ : aeval ζ (cyclotomic n R) = 0)
    (k : ℕ) (f : cycloIndex R S) (hdvd : cyclotomic n R ^ (k + 1) ∣ (f : R[X]))
    (x : CycloCompletion R S) (g : R[X]) (hg : proj R S f x = Ideal.Quotient.mk _ g) :
    PowerSeries.coeff k (taylorAt R S hn ζ hζ x) =
      (hasseDeriv k (g.map (algebraMap R A))).eval ζ := sorry

/-- The factorials are kept: `k! · coeff_k = (d/dq)^k g (ζ)`. -/
theorem factorial_mul_coeff_taylorAt {n : ℕ} (hn : n ∈ S) (ζ : A)
    (hζ : aeval ζ (cyclotomic n R) = 0) (k : ℕ) (f : cycloIndex R S)
    (hdvd : cyclotomic n R ^ (k + 1) ∣ (f : R[X])) (x : CycloCompletion R S) (g : R[X])
    (hg : proj R S f x = Ideal.Quotient.mk _ g) :
    (k.factorial : A) * PowerSeries.coeff k (taylorAt R S hn ζ hζ x) =
      (derivative^[k] (g.map (algebraMap R A))).eval ζ := sorry

/-- API `taylorAt_expCoord`: for a `ℚ`-algebra `A`, the expansion in the coordinate
`q = ζ e^{-t}` requested by QM.5, `σ_ζ` followed by substitution of `ζ(e^{-t} - 1)` (constant
coefficient `0`, so `PowerSeries.subst` applies). -/
def taylorAtExpCoord [Algebra ℚ A] {n : ℕ} (hn : n ∈ S) (ζ : A)
    (hζ : aeval ζ (cyclotomic n R) = 0) : CycloCompletion R S →+* PowerSeries A := sorry

end Taylor

/-- Test `constantCoeff_taylorAt` (characterisation). -/
example {A : Type*} [CommRing A] {n : ℕ} (ζ : A) (hζ : aeval ζ (cyclotomic n ℤ) = 0)
    (x : HabiroRing ℤ) :
    PowerSeries.constantCoeff (taylorAt ℤ Set.univ (Set.mem_univ n) ζ hζ x) =
      evalAt ℤ Set.univ (Set.mem_univ n) ζ hζ x :=
  constantCoeff_taylorAt ℤ Set.univ (Set.mem_univ n) ζ hζ x

/-- Test `taylorAt_fromPoly` (compatibility with Mathlib's `Polynomial.taylor`). -/
example {A : Type*} [CommRing A] {n : ℕ} (ζ : A) (hζ : aeval ζ (cyclotomic n ℤ) = 0) (g : ℤ[X]) :
    taylorAt ℤ Set.univ (Set.mem_univ n) ζ hζ (fromPoly ℤ Set.univ g) =
      ((taylor ζ (g.map (algebraMap ℤ A)) : A[X]) : PowerSeries A) :=
  taylorAt_fromPoly ℤ Set.univ (Set.mem_univ n) ζ hζ g

/-- Test `taylorAt_one_kontsevich` (computation): `σ₁(F) = 1 - X + 2X² - 5X³ + 15X⁴ - 53X⁵ +
217X⁶ - 1014X⁷ + O(X⁸)` (signed Fishburn numbers). -/
example : (List.range 8).map (fun k => PowerSeries.coeff k
    (taylorAt ℤ Set.univ (Set.mem_univ 1) (1 : ℤ) (by simp) (kontsevichSeries ℤ))) =
      [1, -1, 2, -5, 15, -53, 217, -1014] := sorry

/-- Test `taylorAt_neg_one_kontsevich` (computation): `σ₋₁(F) = 3 + 11X + 72X² + 635X³ +
7085X⁴ + O(X⁵)`. -/
example (h : aeval (-1 : ℤ) (cyclotomic 2 ℤ) = 0) : (List.range 5).map (fun k => PowerSeries.coeff k
    (taylorAt ℤ Set.univ (Set.mem_univ 2) (-1 : ℤ) h (kontsevichSeries ℤ))) =
      [3, 11, 72, 635, 7085] := sorry

/-- Test `hasse_not_deriv_over_F2` (non-example): over `𝔽₂` the second Taylor coefficient of
`q²` at `1` is `1`, while the second derivative vanishes. -/
example (h : aeval (1 : ZMod 2) (cyclotomic 1 (ZMod 2)) = 0) :
    PowerSeries.coeff 2 (taylorAt (ZMod 2) {1} (Set.mem_singleton 1) (1 : ZMod 2) h
      (fromPoly (ZMod 2) {1} (X ^ 2))) = 1 ∧
    (derivative^[2] (X ^ 2 : (ZMod 2)[X])).eval 1 = 0 := sorry

/-- Test `factorial_mul_coeff_over_Z` (compatibility): `2 · coeff₂ σ₁(q³) = (q³)''(1) = 6`. -/
example (h : aeval (1 : ℤ) (cyclotomic 1 ℤ) = 0) :
    PowerSeries.coeff 2 (taylorAt ℤ {1} (Set.mem_singleton 1) (1 : ℤ) h
      (fromPoly ℤ {1} (X ^ 3))) = 3 := sorry

section Naturality

variable (R : Type*) [CommRing R] (S : Set ℕ) {A : Type*} [CommRing A] [Algebra R A]

/-- HC.3/naturality-and-re-expansion: naturality in the order set. -/
theorem evalAt_restrict {T : Set ℕ} (hTS : T ⊆ S) {n : ℕ} (hn : n ∈ T) (ζ : A)
    (hζ : aeval ζ (cyclotomic n R) = 0) :
    evalAt R S (hTS hn) ζ hζ = (evalAt R T hn ζ hζ).comp (restrict R S hTS) := sorry

theorem taylorAt_restrict {T : Set ℕ} (hTS : T ⊆ S) {n : ℕ} (hn : n ∈ T) (ζ : A)
    (hζ : aeval ζ (cyclotomic n R) = 0) :
    taylorAt R S (hTS hn) ζ hζ = (taylorAt R T hn ζ hζ).comp (restrict R S hTS) := sorry

/-- Naturality in the root: Galois equivariance. -/
theorem taylorAt_algEquiv (τ : A ≃ₐ[R] A) {n : ℕ} (hn : n ∈ S) (ζ : A)
    (hζ : aeval ζ (cyclotomic n R) = 0) (hτζ : aeval (τ ζ) (cyclotomic n R) = 0)
    (x : CycloCompletion R S) :
    taylorAt R S hn (τ ζ) hτζ x = PowerSeries.map (τ : A →+* A) (taylorAt R S hn ζ hζ x) := sorry

/-- `q ↦ q^a`, continuous when `m / gcd m a ∈ S` for every `m ∈ T`. -/
def powSubst {T : Set ℕ} (a : ℕ) (ha : 0 < a) (h : ∀ m ∈ T, m / Nat.gcd m a ∈ S) :
    CycloCompletion R S →+* CycloCompletion R T := sorry

theorem powSubst_fromPoly {T : Set ℕ} (a : ℕ) (ha : 0 < a) (h : ∀ m ∈ T, m / Nat.gcd m a ∈ S)
    (g : R[X]) : powSubst R S a ha h (fromPoly R S g) = fromPoly R T (g.comp (X ^ a)) := sorry

end Naturality

/-- HC.3/naturality-and-re-expansion: `ψ₂ : ℤ⟦q - 1⟧ → ℤ⟦q + 1⟧` exists, but `q ↦ q²` does not
extend to `ℤ⟦q - 1⟧ → ℤ[q]^{3}` (`2 - q²` at `ζ₃` has norm `7`). -/
example : ¬ ∃ ψ : CycloCompletion ℤ {1} →+* CycloCompletion ℤ {3},
    ∀ g : ℤ[X], ψ (fromPoly ℤ {1} g) = fromPoly ℤ {3} (g.comp (X ^ 2)) := sorry

section ReExpansion

/-- HC.3/p-adic-closeness-of-roots (a): `(ω - 1)^{p^e} ∈ pB` when `ω^{p^e} = 1`. -/
theorem sub_one_pow_prime_pow_mem_span {B : Type*} [CommRing B] (p e : ℕ) [Fact p.Prime]
    {ω : B} (hω : ω ^ p ^ e = 1) : (ω - 1) ^ p ^ e ∈ Ideal.span {(p : B)} := sorry

/-- HC.3/p-adic-closeness-of-roots (b): `1 - ω` is a unit when `ω` is a root of `Φ_m`, `m > 1`
not a prime power. -/
theorem isUnit_one_sub_of_not_isPrimePow {B : Type*} [CommRing B] {m : ℕ}
    (hm : ¬ IsPrimePow m) (hm1 : 1 < m) {ω : B} (hω : aeval ω (cyclotomic m ℤ) = 0) :
    IsUnit (1 - ω) := sorry

/-- HC.3/p-adic-closeness-of-roots: `e^{2πi/6} - e^{2πi/3} = 1`, although the orders differ by
the prime `2`. -/
example : Complex.exp (2 * Real.pi * Complex.I / 6) - Complex.exp (2 * Real.pi * Complex.I / 3)
    = 1 := sorry

variable (B : Type*) [CommRing B] (p : ℕ) [Fact p.Prime] [IsAdicComplete (Ideal.span {(p : B)}) B]

/-- HC.3/p-adic-re-expansion: `f(X) ↦ f(X + c)` for `c` topologically nilpotent in the
`p`-adically complete ring `B`, built from `PowerSeries.eval₂Hom` (NOT `PowerSeries.subst`,
whose hypothesis is nilpotence of the constant coefficient). -/
def reExpand (c : B) (hc : ∃ N, c ^ N ∈ Ideal.span {(p : B)}) :
    PowerSeries B →+* PowerSeries B := sorry

/-- The coefficients are `p`-adically convergent sums. -/
theorem coeff_reExpand (c : B) (hc : ∃ N, c ^ N ∈ Ideal.span {(p : B)}) (f : PowerSeries B)
    (j : ℕ) :
    letI := (Ideal.span {(p : B)}).adicTopology
    HasSum (fun k => ((k + j).choose j : B) * c ^ k * PowerSeries.coeff (k + j) f)
      (PowerSeries.coeff j (reExpand B p c hc f)) := sorry

@[simp] theorem reExpand_coe (c : B) (hc : ∃ N, c ^ N ∈ Ideal.span {(p : B)}) (g : B[X]) :
    reExpand B p c hc (g : PowerSeries B) = ((taylor c g : B[X]) : PowerSeries B) := sorry

@[simp] theorem reExpand_zero (h : ∃ N, (0 : B) ^ N ∈ Ideal.span {(p : B)}) :
    reExpand B p 0 h = RingHom.id _ := sorry

/-- The cocycle law. -/
theorem reExpand_comp (c c' : B) (hc : ∃ N, c ^ N ∈ Ideal.span {(p : B)})
    (hc' : ∃ N, c' ^ N ∈ Ideal.span {(p : B)}) (hcc : ∃ N, (c + c') ^ N ∈ Ideal.span {(p : B)}) :
    (reExpand B p c' hc').comp (reExpand B p c hc) = reExpand B p (c + c') hcc := sorry

open PowerSeries.WithPiTopology in
theorem continuous_reExpand (c : B) (hc : ∃ N, c ^ N ∈ Ideal.span {(p : B)}) :
    letI := (Ideal.span {(p : B)}).adicTopology
    Continuous (reExpand B p c hc) := sorry

theorem reExpand_map {B' : Type*} [CommRing B'] [IsAdicComplete (Ideal.span {(p : B')}) B']
    (φ : B →+* B') (c : B) (hc : ∃ N, c ^ N ∈ Ideal.span {(p : B)})
    (hc' : ∃ N, φ c ^ N ∈ Ideal.span {(p : B')}) :
    (PowerSeries.map φ).comp (reExpand B p c hc) =
      (reExpand B' p (φ c) hc').comp (PowerSeries.map φ) := sorry

/-- HC.3/re-expansion-of-taylor-expansions: `rex_{ζ' - ζ} ∘ σ_ζ = σ_{ζ'}` when `ζ⁻¹ζ'` has
`p`-power order. -/
theorem reExpand_taylorAt {R : Type*} [CommRing R] [Algebra R B] {S : Set ℕ}
    {n n' : ℕ} (hn : n ∈ S) (hn' : n' ∈ S) (ζ ζ' : B)
    (hζ : aeval ζ (cyclotomic n R) = 0) (hζ' : aeval ζ' (cyclotomic n' R) = 0)
    (e : ℕ) (ω : B) (hω : ω ^ p ^ e = 1) (hζζ' : ζ' = ζ * ω)
    (hc : ∃ N, (ζ' - ζ) ^ N ∈ Ideal.span {(p : B)}) (x : CycloCompletion R S) :
    reExpand B p (ζ' - ζ) hc (taylorAt R S hn ζ hζ x) = taylorAt R S hn' ζ' hζ' x := sorry

end ReExpansion

/-- Test `reExpand_coe` (compatibility with `Polynomial.taylor`). -/
example (B : Type*) [CommRing B] (p : ℕ) [Fact p.Prime] [IsAdicComplete (Ideal.span {(p : B)}) B]
    (c : B) (hc : ∃ N, c ^ N ∈ Ideal.span {(p : B)}) (g : B[X]) :
    reExpand B p c hc (g : PowerSeries B) = ((taylor c g : B[X]) : PowerSeries B) :=
  reExpand_coe B p c hc g

/-- Test `reExpand_zero` (degenerate). -/
example (B : Type*) [CommRing B] (p : ℕ) [Fact p.Prime] [IsAdicComplete (Ideal.span {(p : B)}) B]
    (h : ∃ N, (0 : B) ^ N ∈ Ideal.span {(p : B)}) : reExpand B p 0 h = RingHom.id _ :=
  reExpand_zero B p h

/-- Test `reExpand_comp` (characterisation): the cocycle law. -/
example (B : Type*) [CommRing B] (p : ℕ) [Fact p.Prime] [IsAdicComplete (Ideal.span {(p : B)}) B]
    (c c' : B) (hc : ∃ N, c ^ N ∈ Ideal.span {(p : B)}) (hc' : ∃ N, c' ^ N ∈ Ideal.span {(p : B)})
    (hcc : ∃ N, (c + c') ^ N ∈ Ideal.span {(p : B)}) :
    (reExpand B p c' hc').comp (reExpand B p c hc) = reExpand B p (c + c') hcc :=
  reExpand_comp B p c c' hc hc' hcc

/-- Test `reExpand_geometric_Z2` (computation): in `ℤ₂⟦X⟧` the constant coefficient of
`rex_{-2}(Σ X^k)` is `1/3`. -/
example [IsAdicComplete (Ideal.span {((2 : ℕ) : ℤ_[2])}) ℤ_[2]]
    (h : ∃ N, (-2 : ℤ_[2]) ^ N ∈ Ideal.span {((2 : ℕ) : ℤ_[2])}) :
    3 * PowerSeries.constantCoeff (reExpand ℤ_[2] 2 (-2) h (PowerSeries.mk 1)) = 1 := sorry

open PowerSeries.WithPiTopology in
/-- Test `no_reExpand_across_unit` (non-example): `X + 1` is not topologically nilpotent in
`B⟦X⟧` for a nonzero Hausdorff `B`; `e^{2πi/6} - e^{2πi/3} = 1`. -/
example (B : Type*) [CommRing B] [Nontrivial B] [TopologicalSpace B] [T2Space B] :
    ¬ IsTopologicallyNilpotent (PowerSeries.X + PowerSeries.C 1 : PowerSeries B) := sorry

/-! ## HC.4 — adjacency, the cyclotomic lemmas, rigidity, non-surjectivity -/

section Adjacency

/-- HC.4/adjacency-of-orders: Habiro's `c_{m,n}` (p. 1134): `0` if `m = n`, `p` if
`n/m = p^j` with `j ≠ 0`, `1` otherwise. -/
def adjacencyIndex (m n : ℕ) : ℕ := by
  classical
  exact if m = n then 0 else
    if h : ∃ p k : ℕ, p.Prime ∧ 0 < k ∧ (n = p ^ k * m ∨ m = p ^ k * n)
    then Classical.choose h else 1

/-- `m ⇔_R n`: `R` is `c_{m,n}`-adically separated. Reflexive for every `R`. -/
def Adjacent (R : Type*) [CommRing R] (m n : ℕ) : Prop :=
  IsHausdorff (Ideal.span {(adjacencyIndex m n : R)}) R

/-- Connectedness over `R`: non-empty, any two elements joined by a chain inside `S`. -/
def IsAdjConnected (R : Type*) [CommRing R] (S : Set ℕ) : Prop :=
  S.Nonempty ∧ ∀ m ∈ S, ∀ n ∈ S,
    Relation.ReflTransGen (fun a b => a ∈ S ∧ b ∈ S ∧ Adjacent R a b) m n

theorem adjacent_refl (R : Type*) [CommRing R] (n : ℕ) : Adjacent R n n := sorry

theorem Adjacent.symm {R : Type*} [CommRing R] {m n : ℕ} (h : Adjacent R m n) :
    Adjacent R n m := sorry

theorem adjacent_iff_of_ne {R : Type*} [CommRing R] [Nontrivial R] {m n : ℕ} (hmn : m ≠ n) :
    Adjacent R m n ↔ ∃ p k : ℕ, p.Prime ∧ 0 < k ∧
      (n = p ^ k * m ∨ m = p ^ k * n) ∧ IsHausdorff (Ideal.span {(p : R)}) R := sorry

theorem adjacent_rat_iff {m n : ℕ} : Adjacent ℚ m n ↔ m = n := sorry

theorem adjacent_int_iff {m n : ℕ} :
    Adjacent ℤ m n ↔ m = n ∨ ∃ p k : ℕ, p.Prime ∧ 0 < k ∧ (n = p ^ k * m ∨ m = p ^ k * n) :=
  sorry

theorem isAdjConnected_divisors_iff (R : Type*) [CommRing R] {n : ℕ} (hn : 0 < n) :
    IsAdjConnected R {d | d ∣ n} ↔
      ∀ p : ℕ, p.Prime → p ∣ n → IsHausdorff (Ideal.span {(p : R)}) R := sorry

end Adjacency

/-- Test `adjacent_self_rat` (degenerate): the `m = n` clause. -/
example : Adjacent ℚ 3 3 := adjacent_refl ℚ 3

/-- Test `not_adjacent_rat` (non-example). -/
example : ¬ Adjacent ℚ 1 2 := sorry

/-- Test `adjacent_int` (computation). -/
example : Adjacent ℤ 3 12 ∧ Adjacent ℤ 12 3 ∧ ¬ Adjacent ℤ 4 6 := sorry

/-- Test `not_transitive` (non-example). -/
example : Adjacent ℤ 1 2 ∧ Adjacent ℤ 2 6 ∧ ¬ Adjacent ℤ 1 6 := sorry

/-- Test `divisors_12` (characterisation). -/
example : IsAdjConnected ℤ {d | d ∣ 12} ∧ ¬ IsAdjConnected (Localization.Away (3 : ℤ)) {d | d ∣ 12} :=
  sorry

section CyclotomicLemmas

/-- HC.4/cyclotomic-congruence-and-prime-ideal: Habiro (4.1). -/
theorem cyclotomic_prime_pow_mul_zmod (p e n : ℕ) [Fact p.Prime] (he : 0 < e) (hn : 0 < n) :
    cyclotomic (p ^ e * n) (ZMod p) =
      cyclotomic n (ZMod p) ^ (if p ∣ n then p ^ e else (p - 1) * p ^ (e - 1)) := sorry

/-- Habiro (4.2). -/
theorem prime_mem_span_cyclotomic (p e n : ℕ) (hp : p.Prime) (he : 0 < e) (hn : 0 < n) :
    (p : ℤ[X]) ∈ Ideal.span {cyclotomic n ℤ, cyclotomic (p ^ e * n) ℤ} := sorry

/-- Wagner v5 Lemma 2.1 for `α ≠ 0`. -/
def cyclotomicPairQuotientEquiv (p e n : ℕ) [Fact p.Prime] (he : 0 < e) (hn : 0 < n) :
    (ℤ[X] ⧸ Ideal.span {cyclotomic n ℤ, cyclotomic (p ^ e * n) ℤ}) ≃+*
      ((ZMod p)[X] ⧸ Ideal.span {cyclotomic n (ZMod p)}) := sorry

/-- HC.4/cyclotomic-comaximality-and-resultant: Habiro Lemma 4.1(2). -/
theorem isCoprime_cyclotomic {m n : ℕ} (hm : 0 < m) (hn : 0 < n) (hmn : m ≠ n)
    (h : ¬ ∃ p k : ℕ, p.Prime ∧ 0 < k ∧ (n = p ^ k * m ∨ m = p ^ k * n)) :
    IsCoprime (cyclotomic m ℤ) (cyclotomic n ℤ) := sorry

open Classical in
/-- Apostol, Theorems 1, 3, 4. -/
theorem natAbs_resultant_cyclotomic {m n : ℕ} (hn : 0 < n) (hnm : n < m) :
    ((cyclotomic m ℤ).resultant (cyclotomic n ℤ)).natAbs =
      if h : ∃ p k : ℕ, p.Prime ∧ 0 < k ∧ m = p ^ k * n
      then Classical.choose h ^ n.totient else 1 := sorry

end CyclotomicLemmas

/-- HC.4/cyclotomic-comaximality-and-resultant: the resultant is a proper multiple of the
generator `2` of `(Φ₃, Φ₁₂) ∩ ℤ`. -/
example : ((cyclotomic 12 ℤ).resultant (cyclotomic 3 ℤ)).natAbs = 4 ∧
    (2 : ℤ[X]) ∈ Ideal.span {cyclotomic 3 ℤ, cyclotomic 12 ℤ} := sorry

section MonicCompletions

variable {R : Type*} [CommRing R]

/-- HC.4/radical-relation-on-monic-polynomials: Habiro §3.2, `f ⇒_R g`. -/
def MonicImplies (f g : R[X]) : Prop :=
  ∃ I : Ideal R, IsHausdorff I R ∧ f ∈ (Ideal.span {g} ⊔ I.map C).radical

theorem monicImplies_of_dvd {f g : R[X]} (h : g ∣ f) : MonicImplies f g := sorry

theorem MonicImplies.mono {f g f' g' : R[X]} (h : MonicImplies f g) (hf : f ∣ f') (hg : g' ∣ g) :
    MonicImplies f' g' := sorry

theorem monicImplies_iff_fg (f g : R[X]) :
    MonicImplies f g ↔ ∃ I : Ideal R, I.FG ∧ IsHausdorff I R ∧
      f ∈ (Ideal.span {g} ⊔ I.map C).radical := sorry

/-- `M₀ ≺ M`: every element of `M` is reached from `M₀` by a chain of `⇒` inside `M`. -/
def MonicPrecedes (M₀ M : Set R[X]) : Prop :=
  M₀ ⊆ M ∧ ∀ g ∈ M, ∃ f ∈ M₀,
    Relation.ReflTransGen (fun a b => a ∈ M ∧ b ∈ M ∧ MonicImplies a b) f g

/-- HC.4/one-step-injectivity: Habiro Proposition 3.1, `ρ_{(fg),(f)}` is injective. -/
theorem transition_injective_of_monicImplies {f g : R[X]} (hf : f.Monic) (hg : g.Monic)
    (h : MonicImplies f g) :
    Function.Injective (MonicCompletion.transition R
      (T := Submonoid.closure {f * g}) (T' := Submonoid.closure {f}) sorry) := sorry

/-- HC.4/chain-injectivity-for-monic-completions: Habiro Theorem 3.1. -/
theorem transition_injective_of_monicPrecedes {M₀ M : Set R[X]} (hM : ∀ f ∈ M, f.Monic)
    (h : MonicPrecedes M₀ M) :
    Function.Injective (MonicCompletion.transition R
      (T := Submonoid.closure M) (T' := Submonoid.closure M₀) sorry) := sorry

/-- HC.4/adjacency-is-the-radical-relation: Habiro Lemma 4.2(1). -/
theorem cyclotomic_mem_radical_adjacencyIndex (m n : ℕ) :
    cyclotomic m R ∈ (Ideal.span {cyclotomic n R, C (adjacencyIndex m n : R)}).radical := sorry

/-- Habiro Lemma 4.2(2). -/
theorem adjacent_iff_monicImplies [Nontrivial R] (m n : ℕ) :
    Adjacent R m n ↔ MonicImplies (cyclotomic m R) (cyclotomic n R) := sorry

end MonicCompletions

/-- Test `monicImplies_self` (degenerate). -/
example (R : Type*) [CommRing R] (f : R[X]) : MonicImplies f f := monicImplies_of_dvd dvd_rfl

/-- Test `phi2_implies_phi1_int` (computation): `Φ₂ = Φ₁ + 2`, with `I = (2)`. -/
example : MonicImplies (cyclotomic 2 ℤ) (cyclotomic 1 ℤ) := sorry

/-- Test `phi2_not_implies_phi1_rat` (non-example). -/
example : ¬ MonicImplies (cyclotomic 2 ℚ) (cyclotomic 1 ℚ) := sorry

/-- Test `monicImplies_of_dvd` (characterisation). -/
example : MonicImplies ((X - 1) * (X + 1) : ℤ[X]) (X - 1) :=
  monicImplies_of_dvd (dvd_mul_right _ _)

section Rigidity

variable (R : Type*) [CommRing R]

/-- HC.4/injectivity-of-restriction: Habiro Theorem 4.1, full chain hypothesis. -/
theorem restrict_injective_of_chain {S T : Set ℕ} (hTS : T ⊆ S)
    (h : ∀ n ∈ S, ∃ m ∈ T,
      Relation.ReflTransGen (fun a b => a ∈ S ∧ b ∈ S ∧ Adjacent R a b) m n) :
    Function.Injective (restrict R S hTS) := sorry

/-- Corollary: a connected `S` and any non-empty `T ⊆ S`. -/
theorem restrict_injective_of_isAdjConnected {S T : Set ℕ} (hS : IsAdjConnected R S)
    (hTS : T ⊆ S) (hT : T.Nonempty) : Function.Injective (restrict R S hTS) := sorry

/-- HC.4/connectedness-of-primitive-roots: Habiro Lemma 5.1, adjacency of roots. -/
def RootAdjacent [IsDomain R] (ζ ζ' : R) : Prop :=
  ζ = ζ' ∨ ∃ (ω : R) (p k : ℕ), p.Prime ∧ 0 < k ∧ ζ' = ζ * ω ∧ orderOf ω = p ^ k ∧
    IsHausdorff (Ideal.span {(p : R)}) R

/-- Habiro Theorem 5.1: completions at linear factors `q - ζ`, `ζ ∈ Z`, for a connected `Z`. -/
theorem transition_injective_of_rootConnected [IsDomain R] [CharZero R] {Z Z' : Set R}
    (hZ' : Z' ⊆ Z) (hne : Z'.Nonempty)
    (hZ : ∀ ζ ∈ Z, ∀ ζ' ∈ Z, Relation.ReflTransGen (fun a b => a ∈ Z ∧ b ∈ Z ∧ RootAdjacent R a b) ζ ζ') :
    Function.Injective (MonicCompletion.transition R
      (T := Submonoid.closure ((fun ζ => X - C ζ) '' Z))
      (T' := Submonoid.closure ((fun ζ => X - C ζ) '' Z')) sorry) := sorry

/-- The primitive `n`-th roots are connected under the separation hypotheses of Theorem 5.2. -/
theorem primitiveRoots_rootConnected [IsDomain R] [CharZero R] {n : ℕ} (hn : 0 < n)
    (hodd : ∀ p : ℕ, p.Prime → p ≠ 2 → p ∣ n → IsHausdorff (Ideal.span {(p : R)}) R)
    (h4 : 4 ∣ n → IsHausdorff (Ideal.span {(2 : R)}) R) :
    ∀ ζ ∈ primitiveRoots n R, ∀ ζ' ∈ primitiveRoots n R,
      Relation.ReflTransGen (fun a b => a ∈ primitiveRoots n R ∧ b ∈ primitiveRoots n R ∧
        RootAdjacent R a b) ζ ζ' := sorry

/-- HC.4/rootwise-taylor-injectivity: Habiro Theorem 5.2. -/
theorem taylorAt_injective [IsDomain R] [CharZero R] {S : Set ℕ}
    (hS : IsAdjConnected R S) {n : ℕ} (hn : n ∈ S)
    (hodd : ∀ p : ℕ, p.Prime → p ≠ 2 → p ∣ n → IsHausdorff (Ideal.span {(p : R)}) R)
    (h4 : 4 ∣ n → IsHausdorff (Ideal.span {(2 : R)}) R)
    {K : Type*} [Field K] [IsAlgClosed K] [Algebra R K] [FaithfulSMul R K]
    (ζ : K) (hζ' : aeval ζ (cyclotomic n R) = 0) :
    Function.Injective (taylorAt R S hn ζ hζ') := sorry

/-- HC.4/the-completion-is-a-domain: Habiro Corollary 5.1 (with connectedness, which the
printed 'in particular' drops). -/
theorem isDomain_of_isAdjConnected [IsDomain R] [CharZero R] {S : Set ℕ}
    (hS : IsAdjConnected R S) (n : ℕ) (hn : n ∈ S) (hn0 : 0 < n)
    (hodd : ∀ p : ℕ, p.Prime → p ≠ 2 → p ∣ n → IsHausdorff (Ideal.span {(p : R)}) R)
    (h4 : 4 ∣ n → IsHausdorff (Ideal.span {(2 : R)}) R) :
    IsDomain (CycloCompletion R S) := sorry

/-- HC.4/evaluation-uniqueness-and-its-exact-hypothesis: Habiro Theorem 6.1 (orders;
`P_T(R) = ∏_{n ∈ T} R[X]/(Φ_n)`). -/
theorem evalCyclotomic_injective (A : Subring (AlgebraicClosure ℚ)) {S T : Set ℕ}
    (hS : IsAdjConnected A S) (hTS : T ⊆ S) (hT0 : ∀ n ∈ T, 0 < n)
    (h : ∃ n ∈ S, {m | m ∈ T ∧ Adjacent A m n}.Infinite) :
    Function.Injective (fun x : CycloCompletion A S => fun n : T =>
      proj A S ⟨cyclotomic (n : ℕ) A, cycloIndex.cyclotomic_mem A S (hTS n.2)⟩ x) := sorry

-- Conjecture 6.1 (Habiro, open and not used): for every infinite set `Z` of roots of unity the
-- evaluation `ℤ[q]^ℕ → ∏_{ζ ∈ Z} ℤ[ζ]` is injective. It is recorded here as open, never as a
-- hypothesis or a theorem.

/-- HC.4/evaluation-at-individual-roots: Habiro Theorem 6.2 over `ℤ`, vanishing at
infinitely many roots of prime-power order. -/
theorem eq_zero_of_evalAt_primePow (x : HabiroRing ℤ) (Z : Set ℂ) (hZ : Z.Infinite)
    (hZ' : ∀ ζ ∈ Z, ∃ n : ℕ, IsPrimePow n ∧ IsPrimitiveRoot ζ n ∧
      ∀ h : aeval ζ (cyclotomic n ℤ) = 0, evalAt ℤ Set.univ (Set.mem_univ n) ζ h x = 0) :
    x = 0 := sorry

/-- HC.4/non-surjectivity: Habiro Proposition 7.4(1). -/
theorem restrict_pair_not_surjective {m n : ℕ} (hm : 0 < m) (hmn : m ≠ n) (h : Adjacent ℤ m n) :
    ¬ Function.Surjective (restrict ℤ ({m, n} : Set ℕ) (show ({m} : Set ℕ) ⊆ {m, n} by simp)) :=
  sorry

/-- Habiro Proposition 7.4(2). -/
theorem restrict_divisors_not_surjective {m n : ℕ} (hm : 0 < m) (hmn : m ∣ n) (hne : m ≠ n) :
    ¬ Function.Surjective (restrict ℤ {d | d ∣ n}
      (show {d | d ∣ m} ⊆ {d | d ∣ n} from fun _ hd => dvd_trans hd hmn)) := sorry

/-- Habiro Proposition 7.4(3). -/
theorem restrict_univ_not_surjective {S : Set ℕ} (hS : S.Finite) (hne : S.Nonempty)
    (h0 : ∀ n ∈ S, 0 < n) : ¬ Function.Surjective (restrict ℤ Set.univ (Set.subset_univ S)) :=
  sorry

/-- HC.4/taylor-maps-are-not-surjective. -/
theorem taylorAt_not_surjective {n : ℕ} (ζ : ℂ) (hζ : IsPrimitiveRoot ζ n)
    (hζ' : aeval ζ (cyclotomic n ℤ) = 0) :
    ¬ Function.Surjective (taylorAt ℤ Set.univ (Set.mem_univ n) ζ hζ') := sorry

end Rigidity

/-- HC.4/injectivity-of-restriction: the chain must lie in `S` (`Φ₆ - qΦ₁ = 1`). -/
example : ¬ Function.Injective (restrict ℤ ({1, 6} : Set ℕ) (show ({1} : Set ℕ) ⊆ {1, 6} by simp)) :=
  sorry

/-- HC.4/the-completion-is-a-domain: `ℤ[q]^{1,6}` is not a domain. -/
example : ¬ IsDomain (CycloCompletion ℤ {1, 6}) := sorry

/-! ## HC.5 — modules, components, inverted primes, localisation -/

section Modules

variable (R : Type*) [CommRing R] (S : Set ℕ) (M : Type*) [AddCommGroup M] [Module R M]

/-- `M[q] / f M[q]`. -/
abbrev polyModQuot (f : R[X]) : Type _ :=
  PolynomialModule R M ⧸ (Ideal.span {f} • ⊤ : Submodule R[X] (PolynomialModule R M))

/-- The compatible families in `∏_f M[q] / f M[q]`. -/
def cycloModuleSubmodule : Submodule R[X] (∀ f : cycloIndex R S, polyModQuot R M (f : R[X])) where
  carrier := {x | ∀ (f g : cycloIndex R S) (h : (f : R[X]) ∣ (g : R[X])),
    Submodule.mapQ _ _ LinearMap.id sorry (x g) = x f}
  add_mem' := sorry
  zero_mem' := sorry
  smul_mem' := sorry

/-- HC.5/the-completed-module: `M[q]^S = lim_{f ∈ Φ*_S} M[q] / f M[q]` (Habiro §7.3). -/
abbrev cycloModuleCompletion : Type _ := ↥(cycloModuleSubmodule R S M)

namespace cycloModuleCompletion

/-- The `R[q]^S`-module structure. -/
instance instModule : Module (CycloCompletion R S) (cycloModuleCompletion R S M) := sorry

/-- The canonical map `M[q] → M[q]^S`. -/
def of : PolynomialModule R M →ₗ[R[X]] cycloModuleCompletion R S M := sorry

/-- The projection `M[q]^S → M[q] / f M[q]`. -/
def proj (f : cycloIndex R S) : cycloModuleCompletion R S M →ₗ[R[X]] polyModQuot R M (f : R[X]) :=
  (LinearMap.proj f).comp (cycloModuleSubmodule R S M).subtype

theorem ext {x y : cycloModuleCompletion R S M} (h : ∀ f, proj R S M f x = proj R S M f y) :
    x = y := sorry

/-- The kernel of a projection is `f • M[q]^S`. -/
theorem proj_eq_zero_iff (f : cycloIndex R S) (x : cycloModuleCompletion R S M) :
    proj R S M f x = 0 ↔ ∃ y, x = (f : R[X]) • y := sorry

/-- For `M = R` the module completion is the ring completion. -/
def selfEquiv : cycloModuleCompletion R S R ≃ₗ[R[X]] CycloCompletion R S := sorry

variable {M} {N P : Type*} [AddCommGroup N] [Module R N] [AddCommGroup P] [Module R P]

def map (φ : M →ₗ[R] N) : cycloModuleCompletion R S M →ₗ[R[X]] cycloModuleCompletion R S N :=
  sorry

/-- Exactness, with no hypothesis on `R`, `S` or the modules. -/
theorem map_exact {φ : M →ₗ[R] N} {ψ : N →ₗ[R] P} (h : Function.Exact φ ψ) :
    Function.Exact (map R S φ) (map R S ψ) := sorry

/-- Order change `ρ^M_{S,S'}`. -/
def restrict {S' : Set ℕ} (h : S' ⊆ S) :
    cycloModuleCompletion R S M →ₗ[R[X]] cycloModuleCompletion R S' M := sorry

/-- Products, hence finite direct sums. -/
def piEquiv {ι : Type*} (M : ι → Type*) [∀ i, AddCommGroup (M i)] [∀ i, Module R (M i)] :
    cycloModuleCompletion R S (∀ i, M i) ≃ₗ[R[X]] ∀ i, cycloModuleCompletion R S (M i) := sorry

/-- The comparison `M ⊗_R R[q]^S → M[q]^S`, bijective for finitely presented `M`. -/
def ofTensor : TensorProduct R M (CycloCompletion R S) →ₗ[R] cycloModuleCompletion R S M := sorry

theorem ofTensor_bijective [Module.FinitePresentation R M] :
    Function.Bijective (ofTensor R S (M := M)) := sorry

/-- Along a cofinal chain `1 = g₀ ∣ g₁ ∣ ⋯`, `M[q]^S ≅ ∏_j M^(deg g_{j+1} - deg g_j)`,
naturally in `M`. -/
def equivPiOfChain (g : ℕ → cycloIndex R S) (hmono : ∀ n, (g n : R[X]) ∣ (g (n + 1) : R[X]))
    (hg : ∀ f : cycloIndex R S, ∃ n, (f : R[X]) ∣ (g n : R[X])) :
    cycloModuleCompletion R S M ≃ₗ[R]
      ∀ j : ℕ, Fin ((g (j + 1) : R[X]).natDegree - (g j : R[X]).natDegree) → M := sorry

end cycloModuleCompletion

end Modules

/-- Test `cycloModuleCompletion.selfEquiv_test` (compatibility). -/
example (R : Type*) [CommRing R] (S : Set ℕ) :
    Nonempty (cycloModuleCompletion R S R ≃ₗ[R[X]] CycloCompletion R S) :=
  ⟨cycloModuleCompletion.selfEquiv R S⟩

/-- Test `cycloModuleCompletion.subsingleton` (degenerate). -/
example (R : Type*) [CommRing R] (S : Set ℕ) (M : Type*) [AddCommGroup M] [Module R M]
    [Subsingleton M] : Subsingleton (cycloModuleCompletion R S M) ∧
    Subsingleton (cycloModuleCompletion R ∅ R) := sorry

/-- Test `cycloModuleCompletion.reduction_mod_two` (computation): `ℤ[q]^ℕ → 𝔽₂[q]^ℕ` is
surjective with kernel `2 ℤ[q]^ℕ`, and `𝔽₂[q]^ℕ` is not a domain (`q⁵ + q + 1` is idempotent
modulo `(2, P₃)`). -/
example : Function.Surjective (mapRing ℤ Set.univ (Int.castRingHom (ZMod 2))) ∧
    RingHom.ker (mapRing ℤ Set.univ (Int.castRingHom (ZMod 2))) = Ideal.span {2} ∧
    ¬ IsDomain (HabiroRing (ZMod 2)) := sorry

/-- Test `cycloModuleCompletion.not_tensor` (non-example): `Σ P_N / N!` is not in the image. -/
example : ¬ Function.Surjective (cycloModuleCompletion.ofTensor ℤ Set.univ (M := ℚ)) := sorry

/-- Test `cycloModuleCompletion.not_directSum` (non-example): for `M = ⊕_ℕ ℤ`, the element
`Σ_j e_j P_j` is not in the image of `M ⊗ ℤ[q]^ℕ = ⊕_j ℤ[q]^ℕ`. -/
example : ¬ Function.Surjective (cycloModuleCompletion.ofTensor ℤ Set.univ (M := ℕ →₀ ℤ)) := sorry

/-- Test `cycloModuleCompletion.proj_eq_zero_iff_test` (characterisation): for `M = ℤ`,
`f = P₂`, `q⁻¹ - 1 - q(1 - q) = Σ_{n ≥ 2} q^n (q;q)_n` is a multiple of `P₂`. -/
example : ∃ y : HabiroRing ℤ,
    factorialSeries ℤ (fun n => if n < 2 then 0 else X ^ n) = fromPoly ℤ Set.univ (factorialPoly ℤ 2) * y :=
  sorry

/-- HC.5/module-injectivity-theorem: `m ⇔_M n` (Habiro §7.3, with `m = n` allowed). -/
def AdjacentModule (M : Type*) [AddCommGroup M] (m n : ℕ) : Prop :=
  Subsingleton M ∨ m = n ∨
    ∃ p k : ℕ, p.Prime ∧ 0 < k ∧ (n = p ^ k * m ∨ m = p ^ k * n) ∧
      IsHausdorff (Ideal.span {(p : ℤ)}) M

/-- Habiro Theorem 7.1. -/
theorem cycloModuleCompletion.restrict_injective_of_chain (M : Type*) [AddCommGroup M]
    {S T : Set ℕ} (h : T ⊆ S)
    (hchain : ∀ n ∈ S, ∃ n' ∈ T,
      Relation.ReflTransGen (fun a b => a ∈ S ∧ b ∈ S ∧ AdjacentModule M a b) n' n) :
    Function.Injective (cycloModuleCompletion.restrict ℤ S (M := M) h) := sorry

/-- HC.5/module-injectivity-theorem: the chain hypothesis fails for `ℤ[1/2]` and `{1} ⊆ {1, 2}`,
and so does injectivity. -/
example : ¬ Function.Injective (cycloModuleCompletion.restrict ℤ ({1, 2} : Set ℕ)
    (M := Localization.Away (2 : ℤ)) (show ({1} : Set ℕ) ⊆ {1, 2} by simp)) := sorry

section Components

variable (R : Type*) [CommRing R]

/-- HC.5/chinese-remainder-for-disconnected-collections: the comaximality criterion. -/
theorem isCoprime_cyclotomic_iff [Nontrivial R] {m n : ℕ} (hm : 0 < m) (hn : 0 < n) (hmn : m ≠ n) :
    IsCoprime (cyclotomic m R) (cyclotomic n R) ↔
      ∀ p k : ℕ, p.Prime → 0 < k → (n = p ^ k * m ∨ m = p ^ k * n) → IsUnit (p : R) := sorry

/-- The Chinese remainder decomposition under comaximality. -/
def unionEquivProd {S₁ S₂ : Set ℕ}
    (h : ∀ m ∈ S₁, ∀ n ∈ S₂, IsCoprime (cyclotomic m R) (cyclotomic n R)) :
    CycloCompletion R (S₁ ∪ S₂) ≃+* CycloCompletion R S₁ × CycloCompletion R S₂ := sorry

theorem not_isDomain_of_isCoprime [Nontrivial R] {S₁ S₂ : Set ℕ}
    (h₁ : ∃ n ∈ S₁, 0 < n) (h₂ : ∃ n ∈ S₂, 0 < n)
    (h : ∀ m ∈ S₁, ∀ n ∈ S₂, IsCoprime (cyclotomic m R) (cyclotomic n R)) :
    ¬ IsDomain (CycloCompletion R (S₁ ∪ S₂)) := sorry

/-- HC.5/the-rational-case: `R[q]^S ≅ ∏_{n ∈ S} R[q]^{n}` when every `n ∈ S` is a unit of `R`
(Habiro §7.5). -/
def equivPiOfIsUnit {S : Set ℕ} (hS : ∀ n ∈ S, IsUnit (n : R)) :
    CycloCompletion R S ≃+* ∀ n : S, CycloCompletion R {(n : ℕ)} := sorry

theorem restrict_rat_surjective {S S' : Set ℕ} (h : S' ⊆ S) :
    Function.Surjective (restrict ℚ S h) := sorry

theorem restrict_rat_not_injective {S S' : Set ℕ} (h : S' ⊂ S) (h0 : ∀ n ∈ S, 0 < n) :
    ¬ Function.Injective (restrict ℚ S h.subset) := sorry

theorem evalAt_rat_not_injective :
    ∃ x : HabiroRing ℚ, x ≠ 0 ∧ ∀ n : ℕ, 0 < n →
      evalAt ℚ Set.univ (Set.mem_univ n) (AdjoinRoot.root (cyclotomic n ℚ))
        (aeval_root_cyclotomic ℚ n) x = 0 := sorry

theorem taylorAt_rat_not_injective {n : ℕ} (hn : 0 < n) :
    ¬ Function.Injective (taylorAt ℚ Set.univ (Set.mem_univ n) (AdjoinRoot.root (cyclotomic n ℚ))
      (aeval_root_cyclotomic ℚ n)) := sorry

/-- HC.5/inverting-a-prime-and-the-rational-case: over `ℤ[1/p]` the completion is not a
domain, restriction to `{1}` is not injective, and evaluation at all roots is injective. -/
theorem not_isDomain_away (p : ℕ) [Fact p.Prime] :
    ¬ IsDomain (HabiroRing (Localization.Away (p : ℤ))) := sorry

theorem restrict_away_not_injective (p : ℕ) [Fact p.Prime] :
    ¬ Function.Injective (restrict (Localization.Away (p : ℤ)) Set.univ
      (Set.subset_univ ({1} : Set ℕ))) := sorry

theorem evalAt_away_injective (p : ℕ) [Fact p.Prime] (x : HabiroRing (Localization.Away (p : ℤ)))
    (hx : ∀ n : ℕ, 0 < n → evalAt _ Set.univ (Set.mem_univ n)
      (AdjoinRoot.root (cyclotomic n (Localization.Away (p : ℤ))))
      (aeval_root_cyclotomic _ n) x = 0) : x = 0 := sorry

/-- HC.5/components-over-a-localised-integer-ring-are-domains: each class
`S_a = {n : v_p(n) = a}` over `ℤ[1/p]` gives a domain. -/
theorem isDomain_away_class (p : ℕ) [Fact p.Prime] (a : ℕ) :
    IsDomain (CycloCompletion (Localization.Away (p : ℤ)) {n | 0 < n ∧ padicValNat p n = a}) :=
  sorry

/-- HC.5/restricted-root-orders-versus-localisation: `1 + q ↦ 2 + (q - 1)` is not a unit of
`ℤ⟦q - 1⟧`, so inverting `Φ₂` admits no map to `ℤ[q]^{1}`. -/
theorem not_isUnit_fromPoly_cyclotomic_two : ¬ IsUnit (fromPoly ℤ {1} (cyclotomic 2 ℤ)) := sorry

/-- Over `ℚ`, restriction to `S'` is the localisation at an idempotent. -/
theorem restrict_rat_eq_idempotent {S S' : Set ℕ} (h : S' ⊆ S) :
    ∃ e : CycloCompletion ℚ S, IsIdempotentElem e ∧
      RingHom.ker (restrict ℚ S h) = Ideal.span {1 - e} := sorry

/-- HC.5/habiro-localisation-proposition-7-2: the key step `ℤ[q]^ℕ = f ℤ[q]^ℕ + ℤ[q]`. -/
theorem exists_poly_add_mul (f : cycloIndex ℤ Set.univ) (x : HabiroRing ℤ) :
    ∃ (g : ℤ[X]) (y : HabiroRing ℤ),
      x = fromPoly ℤ Set.univ g + fromPoly ℤ Set.univ (f : ℤ[X]) * y := sorry

/-- HC.5/habiro-localisation-proposition-7-3: an element of `ℤ[q]^ℕ` that is a Laurent
polynomial divided by a product of cyclotomic polynomials is a Laurent polynomial. -/
theorem mem_range_fromLaurent_of_mul (x : HabiroRing ℤ) (g : LaurentPolynomial ℤ)
    (h : cycloIndex ℤ Set.univ)
    (hx : x * fromPoly ℤ Set.univ (h : ℤ[X]) = fromLaurent ℤ Set.univ g) :
    ∃ g' : LaurentPolynomial ℤ, x = fromLaurent ℤ Set.univ g' := sorry

end Components

/-- HC.5/chinese-remainder-for-disconnected-collections: `Φ₁, Φ₆` are comaximal. -/
example : IsCoprime (cyclotomic 1 ℤ) (cyclotomic 6 ℤ) := sorry

/-- HC.5/chinese-remainder-for-disconnected-collections: non-adjacency is not comaximality,
`ℤ × ℚ` is not `2`-adically separated. -/
example : ¬ Adjacent (ℤ × ℚ) 1 2 ∧ ¬ IsCoprime (cyclotomic 1 (ℤ × ℚ)) (cyclotomic 2 (ℤ × ℚ)) :=
  sorry

-- HC.5/ordinary-versus-derived-completion: not stated; needs HabiroRings HR.2's derived Habiro
-- completion (`HabiroRings:HR.2/habiro-complete-modules`), which is not at the pins: for an
-- `R`-module `M`, the derived Habiro completion of `M[q, q⁻¹]` is static and equal to
-- `cycloModuleCompletion R Set.univ M`.

/-! ## HC.6 — the exported interface and the acceptance examples -/

-- HC.6/the-exported-interface: a bookkeeping node (exports by node id, consumers, and needs not
-- supplied here); it has no Lean form.

/-- HC.6/the-acceptance-examples: `1 - q` is not a unit of `ℤ[q]^ℕ` nor of `ℤ[q]^{2}`, but is
one of `ℤ[q]^{6}` and of `ℤ[1/2][q]^{2}`. -/
example : ¬ IsUnit (fromPoly ℤ Set.univ (1 - X)) ∧ ¬ IsUnit (fromPoly ℤ {2} (1 - X)) ∧
    IsUnit (fromPoly ℤ {6} (1 - X)) ∧
    IsUnit (fromPoly (Localization.Away (2 : ℤ)) {2} (1 - X)) := sorry

/-- HC.6/the-acceptance-examples: `(3 - 2q)⁻¹ ∈ ℤ⟦q - 1⟧` is not in the image of `ℤ[q]^{1,2}`. -/
example : ¬ ∃ x : CycloCompletion ℤ {1, 2},
    restrict ℤ ({1, 2} : Set ℕ) (show ({1} : Set ℕ) ⊆ {1, 2} by simp) x *
      fromPoly ℤ {1} (3 - 2 * X) = 1 := sorry

/-- HC.6/the-acceptance-examples: the geometric series `Σ q^n` is not an element (its partial
sums are `N` at `q = 1`). -/
example : ¬ HasSum (fun n => fromPoly ℤ Set.univ (X ^ n : ℤ[X])) (1 : HabiroRing ℤ) ∧
    ¬ Summable (fun n => fromPoly ℤ Set.univ (X ^ n : ℤ[X])) := sorry

/-- HC.6/inverted-prime-and-rational-examples: the idempotent `e₀` of the odd orders over
`ℤ[1/2]`, and `t = (q - 1)e₁` over `ℚ`, at precision `P₃`. -/
example : factorialPoly ℚ 3 ∣
      ((7 + 2 * X - X ^ 2 + X ^ 3 - 2 * X ^ 4 + X ^ 5) / 8) ^ 2 -
        (7 + 2 * X - X ^ 2 + X ^ 3 - 2 * X ^ 4 + X ^ 5) / 8 ∧
    cyclotomic 2 ℚ * cyclotomic 3 ℚ ∣ (-5 - 2 * X + 3 * X ^ 2 + 5 * X ^ 3 + 2 * X ^ 4 - 3 * X ^ 5) / 12 :=
  sorry

/-- HC.6/inverted-prime-and-rational-examples: modulo `2`, `q⁵ + q + 1` separates the orders
`2^k` from the orders `3·2^k`. -/
example : ((X ^ 5 + X + 1 : (ZMod 2)[X]) %ₘ (X + 1) ^ 4) = 1 ∧
    ((X ^ 5 + X + 1 : (ZMod 2)[X]) %ₘ (X ^ 2 + X + 1)) = 0 := sorry

end TauCeti.Habiro
