/-
This file is not the roadmap and is not exhaustive. The roadmap document
`research/blueprint/readmes/HabiroCyclotomicCompletions.md` is definitive. These
statements suggest Lean forms so that contributors and reviewers can converge on
names and signatures. They claim no implementation.

BP-HabiroCyclotomicCompletions: partial prototype, implementationStatus = unchecked.
Mathlib 082e2d37e8b0463410cdb532e111cd43d5a66174;
Tau Ceti f790474821cf4256814db967cb154e7af3d0c369. Not compiled.

Conventions fixed here.

* `cycloCompletion R S` is the limit over the monoid generated by `Φ_n`, `n ∈ S`.
  It is NOT `AdicCompletion` at `(q)` or at `(q - 1)`: `cycloCompletion_ne_adic`
  records that, because the two are easy to confuse and every theorem below is
  false for them.
* `Adjacent R m n` carries the coefficient ring: it is separatedness of `R` at the
  prime whose power is `n/m`. Over `ℚ` it is empty. The module version takes
  adjacency over the MODULE (`AdjacentModule`), not the ring.
* Expansions: `factorialExpansion` is the NORMALISED one, unique by division with
  remainder. Unrestricted expansions are not unique, and `expansion_not_unique`
  says so.
* `taylorAt` coefficients are `hasseDeriv`, not `deriv / n!`. Mathlib proves this
  at polynomial level (`Polynomial.taylor_coeff`); over `ℤ` the factorial version
  is false.
* No completion functor is assumed exact. `cycloModuleCompletion_exact_of_ML` is
  the only exactness statement, and `derivedLimit_obstruction` is the general one.
-/
import Mathlib.RingTheory.Polynomial.Cyclotomic.Basic
import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.AdicCompletion.Basic
import Mathlib.RingTheory.PowerSeries.Substitution
import Mathlib.Algebra.Polynomial.Taylor
import Mathlib.Algebra.Polynomial.HasseDeriv
import Mathlib.Algebra.Polynomial.Div
import Mathlib.Algebra.Polynomial.Laurent

noncomputable section

namespace TauCeti.Habiro

open Polynomial

variable (R : Type*) [CommRing R] (S : Set ℕ+)

/-! ## HC.1 — the completion -/

/-- The directed monoid of products of `Φ_n`, `n ∈ S`, under divisibility. -/
def cycloIndex : Type _ := by sorry

/-- HC.1/the-cyclotomic-completion. -/
def cycloCompletion : Type _ := by sorry

instance : CommRing (cycloCompletion R S) := by sorry

def cycloCompletion.proj : True := by sorry
def cycloCompletion.fromPoly : R[X] → cycloCompletion R S := by sorry

theorem cycloCompletion.ext : True := by sorry
theorem cycloCompletion.complete : True := by sorry
theorem cycloCompletion.universal : True := by sorry

/-- NO injectivity of `fromPoly` is claimed for arbitrary `R` and `S`. -/
theorem fromPoly_not_injective_in_general : True := by sorry

/-- The empty product is `1` and its quotient is the zero ring. -/
@[simp] theorem cycloCompletion_empty : True := by sorry

/-- HC.1/cofinality: `P_N = ∏_{i ≤ N} (1 - qⁱ)` is cofinal for `S = ℕ_{>0}`. -/
def factorialProduct (N : ℕ) : R[X] := by sorry

theorem factorialProduct_cofinal : True := by sorry
theorem cycloCompletion_eq_limit_factorial : True := by sorry
theorem cycloCompletion_eq_limit_qpow_sub_one : True := by sorry

/-- THE trap: this is neither the q-adic nor the (q-1)-adic completion. -/
theorem cycloCompletion_ne_adic : True := by sorry

/-- HC.1/functoriality. -/
def cycloCompletion.mapRing : True := by sorry
def cycloCompletion.restrict : True := by sorry
theorem cycloCompletion.restrict_comp : True := by sorry
theorem cycloCompletion.cofinal_iso : True := by sorry

/-- Completed base change is not uncompleted base change; flatness does not
license the interchange. -/
theorem baseChange_ne_completion : True := by sorry

/-! ## HC.2 — expansions and algorithms -/

/-- The NORMALISED expansion, by `modByMonic` against the monic `P_N`. -/
def factorialExpansion : True := by sorry

theorem factorialExpansion_unique : True := by sorry
theorem factorialExpansion_sum : True := by sorry
theorem expansion_not_unique : True := by sorry

/-- The Kontsevich series: all normalised coefficients `1`. -/
def kontsevichSeries : cycloCompletion R S := by sorry
theorem kontsevichSeries_expansion : True := by sorry

def expansionAdd : True := by sorry
def expansionMul : True := by sorry
def expansionCoeff : True := by sorry

theorem expansionAdd_correct : True := by sorry
theorem expansionMul_correct : True := by sorry
theorem expansion_finite_dependence : True := by sorry

/-- `q` is a unit in the full completion. -/
theorem isUnit_q : True := by sorry
theorem laurent_comparison : True := by sorry

/-- A cyclotomic polynomial of an order in `S` is NOT a unit; no formal division
by it. -/
theorem cyclotomic_not_unit : True := by sorry

/-! ## HC.3 — evaluation and Taylor maps -/

/-- HC.3/evaluation-at-a-root-of-unity, through ONE finite quotient. -/
def evalAt : True := by sorry
theorem evalAt_indep_of_truncation : True := by sorry
theorem evalAt_ringHom : True := by sorry
def evalMap : True := by sorry

/-- There is no evaluation at an order outside `S`. -/
theorem no_evalAt_outside : True := by sorry

/-- HC.3/the-taylor-map. -/
def taylorAt : True := by sorry
@[simp] theorem taylorAt_constantCoeff : True := by sorry

/-- The higher coefficients are HASSE derivatives. -/
theorem taylorAt_coeff_eq_hasseDeriv : True := by sorry

/-- Over `ℤ` the identification with `deriv / n!` FAILS in degree two. -/
theorem taylorAt_ne_deriv_div_factorial : True := by sorry

theorem taylorAt_natural_coeffChange : True := by sorry
theorem taylorAt_natural_conjugation : True := by sorry
theorem taylorAt_natural_restrict : True := by sorry
theorem taylorAt_natural_pow_subst : True := by sorry

/-- Re-expansion is defined ONLY under topological nilpotence in a complete ring —
exactly `PowerSeries.subst`'s hypothesis. -/
def reExpansion : True := by sorry
theorem reExpansion_cocycle : True := by sorry
theorem no_subst_without_nilpotence : True := by sorry

/-! ## HC.4 — connectedness and rigidity -/

/-- `m ⇔_R n`: `n/m` is a power of a prime at which `R` is separated. -/
def Adjacent (m n : ℕ+) : Prop := by sorry
def IsConnectedSet : Prop := by sorry

theorem cyclotomic_congr_mod_p : True := by sorry
theorem prime_mem_ideal_cyclotomic : True := by sorry
theorem cyclotomic_comaximal_of_not_prime_pow : True := by sorry

@[simp] theorem adjacent_over_Z : True := by sorry
@[simp] theorem adjacent_over_Q_empty : True := by sorry

/-- Habiro Theorem 4.1, with the FULL chain hypothesis. -/
theorem restrict_injective_of_chain : True := by sorry
theorem restrict_injective_of_connected : True := by sorry
theorem restrict_injective_over_Z : True := by sorry

/-- Habiro Theorem 5.2: domain, char 0, separation at odd `p`, and at 2 if
`4 ∣ n`. -/
theorem taylorAt_injective : True := by sorry
theorem taylorAt_injective_over_Z : True := by sorry

/-- Habiro Theorem 6.1: infinitely many `m ∈ T` ADJACENT to one `n`. -/
theorem eval_injective_of_infinitely_many_adjacent : True := by sorry
theorem eval_injective_prime_powers : True := by sorry

/-- A finite set of values never suffices, and infinitude alone is not the
hypothesis. -/
theorem finite_values_insufficient : True := by sorry
theorem infinitude_alone_insufficient : True := by sorry

/-- §7.4: none of the injective maps is an isomorphism. -/
theorem restrict_not_surjective_adjacent : True := by sorry
theorem restrict_not_surjective_divisors : True := by sorry
theorem restrict_not_surjective_finite : True := by sorry
theorem taylorAt_not_surjective : True := by sorry

/-! ## HC.5 — modules, components, inversion -/

/-- Adjacency over the MODULE, not the ring. -/
def AdjacentModule : True := by sorry

def cycloModuleCompletion : True := by sorry
theorem cycloModuleCompletion_prod : True := by sorry
theorem cycloModuleCompletion_injective_of_chain : True := by sorry

/-- The ONLY exactness statement, and the general obstruction. -/
theorem cycloModuleCompletion_exact_of_ML : True := by sorry
theorem derivedLimit_obstruction : True := by sorry

/-- Chinese remainder, under comaximality. -/
theorem cycloCompletion_prod_of_disconnected : True := by sorry
theorem not_domain_of_disconnected : True := by sorry

/-- Inverting a prime destroys adjacency across it. -/
theorem adjacency_lost_of_inverted : True := by sorry
theorem eval_not_injective_over_Q : True := by sorry
theorem taylorAt_not_injective_over_Q : True := by sorry
theorem Z_to_Q_completion_injective : True := by sorry

/-- Restricted root orders are NOT a localisation. -/
theorem restrict_ne_localisation : True := by sorry

/-! ## HC.6 — interface and examples -/

theorem exported_interface : True := by sorry
theorem no_exactness_assumed : True := by sorry

/-- An element is a COMPATIBLE FAMILY, not a divergent formal expression. -/
theorem element_is_compatible_family : True := by sorry

theorem example_at_one : True := by sorry
theorem example_at_neg_one : True := by sorry
theorem example_third_root : True := by sorry
theorem example_one_sub_q : True := by sorry
theorem example_kontsevich : True := by sorry
theorem example_q_inverse : True := by sorry
theorem example_inverted_prime : True := by sorry

/-- The comparison with the rational-number-field case: injective, NOT
surjective. -/
theorem comparison_to_number_field_case : True := by sorry

end TauCeti.Habiro
