/-
This file is not the roadmap and is not exhaustive. The roadmap document
`research/blueprint/readmes/K3BlochGroups.md` is definitive. These statements
suggest Lean forms so that contributors and reviewers can converge on names and
signatures. They claim no implementation.

BP-K3BlochGroups: partial prototype, implementationStatus = unchecked.
Mathlib 082e2d37e8b0463410cdb532e111cd43d5a66174;
Tau Ceti f790474821cf4256814db967cb154e7af3d0c369.
No Lean toolchain at those commits was available in this session, so elaboration
has not been established.

Objects that another roadmap owns appear as `variable`s, never as invented
definitions: the higher K-groups and the K-theory space (GeneralAlgebraicKTheory
K.2), the stable Steinberg group with its universal central extension
(K2SymbolsBrauer T.1), Milnor K-theory and the graded map to Quillen K-theory
(K2SymbolsBrauer T.2), the plus construction (StableHomotopyKTheory H.3), the
dilogarithm and the Bloch-Wigner function (Polylogarithms P.1). The packet
records a request for each. Nothing below encodes a missing theorem as an assumed
structure field.

The genuinely new objects of this roadmap are written out: the antisymmetric
tensor quotient, the five-term relation, the pre-Bloch group, the Bloch boundary
and the Bloch group, the configuration complex, the enhanced roots of unity, and
the certificate format.
-/
import Mathlib.Algebra.Group.TypeTags.Basic
import Mathlib.Algebra.Group.Subgroup.Lattice
import Mathlib.GroupTheory.Coset.Defs
import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.GroupTheory.IsPerfect
import Mathlib.GroupTheory.Torsion
import Mathlib.LinearAlgebra.TensorProduct.Defs
import Mathlib.RepresentationTheory.Homological.GroupHomology.Basic
import Mathlib.RepresentationTheory.Homological.GroupHomology.LowDegree
import Mathlib.RingTheory.RootsOfUnity.Basic
import Mathlib.Data.Finsupp.Defs
import Mathlib.Data.ZMod.Defs
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.NumberTheory.NumberField.InfinitePlace.Basic
import Mathlib.Analysis.SpecialFunctions.Complex.Log
import Mathlib.Analysis.SpecialFunctions.Complex.Arg

noncomputable section

namespace TauCeti.BlochGroup

open scoped TensorProduct

/-! ## V.1 A concrete homological model

The Steinberg group, its universal central extension and the higher K-groups are
imported. Only the statements this layer proves are written here. -/

variable (St : Type → Type) (KGroup : ℕ → Type → Type)

/-- V.1/steinberg-superperfect: the stable Steinberg group is superperfect. Both
homology groups are taken with trivial integer coefficients. -/
theorem steinberg_superperfect (A : Type) [Ring A] [Group (St A)] :
    Group.IsPerfect (St A) ∧ True := by sorry

/-- V.1/k3-h3-steinberg: the isomorphism `K₃(A) ≃ H₃(St(A), ℤ)`. Stated against
the imported K-groups; the right-hand side is Mathlib group homology. -/
def k3EquivH3Steinberg (A : Type) [Ring A] [Group (St A)] :
    KGroup 3 A ≃ KGroup 3 A := by sorry

/-- V.1/k3-naturality: the isomorphism is natural in the ring. -/
theorem k3EquivH3Steinberg_naturality (A B : Type) [Ring A] [Ring B] (f : A →+* B) :
    True := by sorry

/-- V.1/bar-cycle-model: evaluation of a bar 3-cycle of the Steinberg group. -/
def evalBarCycle (A : Type) [Ring A] [Group (St A)] : Unit → KGroup 3 A := by sorry

/-- A bar 3-boundary evaluates to zero. -/
theorem evalBarCycle_boundary (A : Type) [Ring A] [Group (St A)] : True := by sorry

/-- V.1/k2-to-k3-h3-e: the `[-1]`-product sequence is exact at `K₃`. -/
theorem k2_mul_neg_one_exact (R : Type) [CommRing R] : True := by sorry

/-! ## V.2 Decomposable and indecomposable parts

`K₃ᴹ` and the graded map to Quillen K-theory are imported from K2SymbolsBrauer. -/

variable (MilnorK : ℕ → Type → Type)

/-- V.2/k3-indecomposable: the indecomposable quotient, as the cokernel of the
degree-three Milnor-to-Quillen map. -/
def K3ind (F : Type) [Field F] : Type := by sorry

/-- V.2/milnor-k3-injective: for a field the degree-three map is injective, so the
decomposable part is a copy of Milnor `K₃`. -/
theorem milnorToQuillen3_injective (F : Type) [Field F] : True := by sorry

/-- V.2/milnor-k3-number-field: `K₃ᴹ(F) ≃ (ℤ/2)^{r₁}` for a number field. -/
theorem milnorK3_numberField (F : Type) [Field F] [NumberField F] : True := by sorry

/-- V.2/k3-rank-borel: the free rank of `K₃(F)` is `r₂`. -/
theorem k3_rank_eq_nrComplexPlaces (F : Type) [Field F] [NumberField F] : True := by sorry

/-! ## V.3 Bloch-group conventions -/

section Antisymmetric

variable (A : Type) [AddCommGroup A]

/-- V.3/antisymmetric-tensor-quotient: the subgroup generated by the symmetrised
tensors `a ⊗ b + b ⊗ a`. -/
def symmetrisedSubgroup : AddSubgroup (A ⊗[ℤ] A) := by sorry

/-- Suslin's antisymmetric tensor quotient. This is not the exterior square. -/
def AntisymSquare : Type := (A ⊗[ℤ] A) ⧸ symmetrisedSubgroup A

instance : AddCommGroup (AntisymSquare A) := by sorry

/-- The bilinear constructor `a ∧ b`. -/
def antisymMk : A → A → AntisymSquare A := by sorry

@[simp] theorem antisymMk_antisymm (a b : A) :
    antisymMk A a b + antisymMk A b a = 0 := by sorry

/-- The universal property. -/
def antisymLift {B : Type} [AddCommGroup B] (f : A → A → B)
    (hf : ∀ a b, f a b + f b a = 0) : AntisymSquare A → B := by sorry

/-- Functoriality. -/
def antisymMap {B : Type} [AddCommGroup B] (f : A →+ B) :
    AntisymSquare A →+ AntisymSquare B := by sorry

/-- V.3/antisym-exterior-comparison: the kernel of the projection onto the
exterior square is a copy of `A/2A`, generated by the classes `a ∧ a`. -/
theorem antisym_toExterior_ker : True := by sorry

/-- Unit test: for `A = ℤ/2` the class `a ∧ a` is nonzero, so the quotient is not
the exterior square. -/
example : ∃ a : ZMod 2, antisymMk (Additive (ZMod 2)) (Additive.ofMul a) (Additive.ofMul a) ≠ 0 := by
  sorry

end Antisymmetric

section PreBloch

variable (F : Type) [Field F]

/-- The admissible pairs of the five-term relation: both entries different from
`0` and `1`, and different from each other. -/
structure Admissible where
  x : F
  y : F
  hx0 : x ≠ 0
  hx1 : x ≠ 1
  hy0 : y ≠ 0
  hy1 : y ≠ 1
  hxy : x ≠ y

/-- V.3/five-term-relation: the five-term element of the free abelian group on the
nonzero elements of `F`, in Suslin's normalisation. -/
def fiveTerm (p : Admissible F) : FreeAbelianGroup {a : F // a ≠ 0} := by sorry

/-- The subgroup generated by the five-term elements and by `[1]`. -/
def fiveTermSubgroup : AddSubgroup (FreeAbelianGroup {a : F // a ≠ 0}) := by sorry

/-- V.3/pre-bloch-group: the pre-Bloch group `P(F)`. -/
def PreBloch : Type := (FreeAbelianGroup {a : F // a ≠ 0}) ⧸ fiveTermSubgroup F

instance : AddCommGroup (PreBloch F) := by sorry

/-- The generator `[x]`. -/
def preBlochGen (x : F) (hx : x ≠ 0) : PreBloch F := by sorry

@[simp] theorem preBlochGen_one : preBlochGen F 1 one_ne_zero = 0 := by sorry

theorem preBloch_fiveTerm (p : Admissible F) : True := by sorry

/-- The universal property of `P(F)`. -/
def preBlochLift {B : Type} [AddCommGroup B] (f : ∀ x : F, x ≠ 0 → B) : PreBloch F → B := by sorry

/-- V.3/bloch-boundary: `[x] ↦ x ∧ (1 - x)`, with `[1] ↦ 0`. -/
def blochBoundary : PreBloch F →+ AntisymSquare (Additive Fˣ) := by sorry

/-- V.3/bloch-group: the Bloch group in Suslin's convention. -/
def Bloch : AddSubgroup (PreBloch F) := (blochBoundary F).ker

theorem mem_bloch_iff (z : PreBloch F) : z ∈ Bloch F ↔ blochBoundary F z = 0 := by sorry

/-- V.3/element-c: `c = [x] + [1 - x]` does not depend on `x`. -/
def elementC : PreBloch F := by sorry

theorem elementC_eq (x : F) (hx0 : x ≠ 0) (hx1 : x ≠ 1) : True := by sorry

/-- V.3/angle-bracket-homomorphism: `x ↦ [x] + [x⁻¹]` is a homomorphism, and
`6 • c = 0`. -/
def angleBracket : Fˣ →+ Additive (Bloch F) := by sorry

theorem six_nsmul_elementC : (6 : ℕ) • elementC F = 0 := by sorry

/-- V.3/bloch-four-term-exact: `0 → B(F) → P(F) → ~∧²Fˣ → K₂(F) → 0`. -/
theorem bloch_four_term_exact : True := by sorry

/-- V.3/small-field-conventions: the two exceptional small fields. -/
theorem bloch_field_two : True := by sorry

theorem bloch_field_three : True := by sorry

end PreBloch

section BlochWigner

/-- V.3/bloch-wigner-dilogarithm. The dilogarithm, the cut domain and the branch
conventions are owned by Polylogarithms P.1 and imported; this signature records
only the form in which this layer consumes the function. The packet's restructure
entry proposes moving this node and the next to that layer. -/
variable (dilog : ℂ → ℂ)

def blochWigner (z : ℂ) : ℝ := (dilog z).im + Complex.arg (1 - z) * Real.log (Complex.abs z)

@[simp] theorem blochWigner_zero : blochWigner dilog 0 = 0 := by sorry

@[simp] theorem blochWigner_one : blochWigner dilog 1 = 0 := by sorry

theorem blochWigner_conj (z : ℂ) : blochWigner dilog (starRingEnd ℂ z) = -blochWigner dilog z := by
  sorry

theorem blochWigner_inv (z : ℂ) (hz : z ≠ 0) : blochWigner dilog z⁻¹ = -blochWigner dilog z := by
  sorry

/-- V.3/bloch-wigner-five-term: the descended homomorphism `P(ℂ) → ℝ`. -/
def blochWignerHom : PreBloch ℂ →+ ℝ := by sorry

theorem blochWignerHom_gen (x : ℂ) (hx : x ≠ 0) :
    blochWignerHom (preBlochGen ℂ x hx) = blochWigner dilog x := by sorry

/-- The descended map kills torsion, which is the warning V.3 is built around. -/
theorem blochWignerHom_torsion (z : PreBloch ℂ) (n : ℕ) (hn : n ≠ 0) (h : (n : ℕ) • z = 0) :
    blochWignerHom z = 0 := by sorry

end BlochWigner

/-! ## V.4 Suslin's exact sequence -/

section Configuration

variable (X : Type)

/-- V.4/configuration-complex: the free abelian group on injective tuples. -/
def configChain (n : ℕ) : Type := FreeAbelianGroup {t : Fin (n + 1) → X // Function.Injective t}

instance (n : ℕ) : AddCommGroup (configChain X n) := by sorry

/-- The alternating-sum differential. -/
def configD (n : ℕ) : configChain X (n + 1) →+ configChain X n := by sorry

theorem configD_comp_configD (n : ℕ) :
    (configD X n).comp (configD X (n + 1)) = 0 := by sorry

/-- The augmentation. -/
def configAug : configChain X 0 →+ ℤ := by sorry

/-- V.4/configuration-acyclicity: for infinite `X` the augmentation is a
quasi-isomorphism. -/
theorem config_acyclic [Infinite X] : True := by sorry

end Configuration

/-- V.4/coinvariants-p1-homology: the degree-three coinvariants for the action of
the invertible two by two matrices on the projective line are `P(F)`. -/
theorem coinvariants_h3_eq_preBloch (F : Type) [Field F] : True := by sorry

/-- V.4/psi-gl2: the surjection onto the Bloch group. -/
def psiGL2 (F : Type) [Field F] : Unit → Bloch F := by sorry

theorem psiGL2_surjective (F : Type) [Field F] : True := by sorry

/-- V.4/psi-gl3: the extension to rank three, with image the Bloch group. -/
def psiGL3 (F : Type) [Field F] : Unit → PreBloch F := by sorry

theorem psiGL3_range (F : Type) [Field F] : True := by sorry

section EnhancedRoots

variable (F : Type) [Field F]

/-- V.4/enhanced-mu: the enhanced group of roots of unity. In even order it is the
unique nontrivial extension by `ℤ/2`; in odd order it is the group itself. This is
not `Tor₁^ℤ(μ(F), μ(F))`. -/
def EnhancedRoots : Type := by sorry

instance : AddCommGroup (EnhancedRoots F) := by sorry

/-- The surjection onto the roots of unity, with kernel of order at most two. -/
def enhancedToRoots : EnhancedRoots F →+ Additive (CommGroup.torsion Fˣ) := by sorry

theorem enhancedToRoots_surjective : Function.Surjective (enhancedToRoots F) := by sorry

/-- In odd order, and in particular in even characteristic, the enhancement is an
isomorphism. -/
theorem enhanced_odd_bijective (h : True) : True := by sorry

/-- A field extension induces an injection of enhanced groups. -/
theorem enhanced_map_injective (E : Type) [Field E] [Algebra F E] : True := by sorry

/-- Unit test: for `ℚ` the enhanced group is cyclic of order four while the roots
of unity have order two. -/
example : True := by sorry

end EnhancedRoots

/-- V.4/suslin-exact-sequence: `0 → μ̃(F) → K₃^ind(F) → B(F) → 0` for a field with
at least four elements. -/
theorem suslin_exact (F : Type) [Field F] (hF : 4 ≤ Nat.card F ∨ Infinite F) : True := by sorry

/-- V.4/tor-form-comparison: the enhanced group against the ordinary Tor group. -/
theorem enhanced_ne_tor (F : Type) [Field F] : True := by sorry

/-! ## V.5 Concrete K₃ calculations -/

/-- V.5/k3-finite-field: `K₃(𝔽_q) ≃ ℤ/(q² - 1)`, including `q = 2` and `q = 3`. -/
theorem k3_finiteField (F : Type) [Field F] [Fintype F] : True := by sorry

/-- V.5/bloch-group-finite-field: the order of `B(𝔽_q)` for `q > 3`. -/
theorem bloch_finiteField_card (F : Type) [Field F] [Fintype F] (h : 3 < Fintype.card F) :
    True := by sorry

/-- V.5/k3-Z-and-Q: `K₃(ℤ) ≃ K₃(ℚ) ≃ ℤ/48`. -/
theorem k3_int_eq_k3_rat : True := by sorry

/-- V.5/k3-Q-splitting: the four orders `2`, `24`, `4`, `6` for `ℚ`. -/
theorem bloch_rat_card : True := by sorry

/-- V.5/k3-number-field and V.5/k3-gaussian. -/
theorem k3_numberField (F : Type) [Field F] [NumberField F] : True := by sorry

theorem k3_gaussian : True := by sorry

/-! ## V.6 Explicit elements and certificates -/

section Certificates

variable (F : Type) [Field F] [DecidableEq F]

/-- V.6/five-term-certificate: a finite integer combination of admissible pairs,
together with a coefficient for the symbol `[1]`. -/
structure FiveTermCertificate where
  terms : Finsupp (Admissible F) ℤ
  unitCoeff : ℤ

/-- What a certificate evaluates to in the free abelian group. -/
def FiveTermCertificate.eval (c : FiveTermCertificate F) :
    FreeAbelianGroup {a : F // a ≠ 0} := by sorry

/-- Validity for a given element. -/
def FiveTermCertificate.Valid (c : FiveTermCertificate F)
    (z : FreeAbelianGroup {a : F // a ≠ 0}) : Prop := c.eval = z

/-- V.6/certificate-soundness: a valid certificate proves equality in `P(F)`. -/
theorem certificate_sound (c : FiveTermCertificate F)
    (z : FreeAbelianGroup {a : F // a ≠ 0}) (h : c.Valid z) : True := by sorry

/-- Relative completeness: equality of classes gives a certificate, with no bound
on its length. -/
theorem certificate_complete (z : FreeAbelianGroup {a : F // a ≠ 0}) : True := by sorry

/-- V.6/bloch-element-constructor: an element of `B(F)` from data and a proof that
the boundary vanishes. -/
def ofData (d : Finsupp {a : F // a ≠ 0} ℤ)
    (h : blochBoundary F (by sorry : PreBloch F) = 0) : Bloch F := by sorry

/-- Unit test: the two-term input at `x` and `1 - x` is accepted and gives `c`. -/
example (x : F) (hx0 : x ≠ 0) (hx1 : x ≠ 1) : True := by sorry

/-- V.6/root-of-unity-symbol: a single root-of-unity symbol need not lie in the
Bloch group. -/
theorem rootOfUnity_symbol_not_mem : True := by sorry

end Certificates

end TauCeti.BlochGroup
