import Mathlib.Topology.Compactification.OnePoint.ProjectiveLine
import Mathlib.NumberTheory.ModularForms.CongruenceSubgroups
import Mathlib.RepresentationTheory.Basic
import Mathlib.LinearAlgebra.Finsupp.LinearCombination
import Mathlib.RingTheory.MvPolynomial.Homogeneous
import Mathlib.Algebra.MonoidAlgebra.Basic
import Mathlib.LinearAlgebra.Matrix.SpecialLinearGroup
import Mathlib.RepresentationTheory.Homological.GroupCohomology.LongExactSequence
import Mathlib.RepresentationTheory.Homological.GroupCohomology.Functoriality
import Mathlib.NumberTheory.ModularForms.Basic
import Mathlib.Analysis.SpecialFunctions.Complex.Circle
import Mathlib.NumberTheory.Padics.PadicIntegers
import Mathlib.NumberTheory.Zsqrtd.GaussianInt
import Mathlib.Tactic.Linarith
import Mathlib.LinearAlgebra.Projection
import Mathlib.LinearAlgebra.Charpoly.Basic
import Mathlib.Algebra.Algebra.Subalgebra.Lattice

/-!
# Suggested Lean forms: modular symbols (ModularSymbolsPadicLFunctions, L0–L4)

**Standard note.** This file is not the roadmap and it is not exhaustive. The roadmap document
(`ModularSymbolsPadicLFunctions`) is definitive. The statements below suggest Lean forms, so that
contributors and reviewers converge on names and signatures. Every proof of a new declaration is
`sorry`; nothing here claims to be formalised.

Pinned baseline: Mathlib `082e2d3`, Tau Ceti `f790474`.

## Conventions

* `P¹(ℚ)` is `OnePoint ℚ` with Mathlib's `GL₂(ℚ)`-action; `Δ₀` is the kernel of the degree map
  on `P¹(ℚ) →₀ ℤ`.
* Pollack–Stevens' right `Γ`-action `v | γ` is encoded as the left representation
  `ρ(γ) v = v | γ⁻¹`, so a modular symbol satisfies `φ(γ D) = ρ(γ) φ(D)`.
* Manin's relations are stated over `SL₂(ℤ)`, with `1 - (-1)` added because `-1` acts trivially
  on `P¹(ℚ)`; modulo it they are Manin's relations over `PSL₂(ℤ)`.
* `V_k` is the space of degree-`k` homogeneous polynomials in `X, Y` with the adjugate action
  `(P | γ)(X, Y) = P(dX - cY, -bX + aY)`.
* **Imported objects.** `Δ₀`, the unimodular map and Manin's theorem are planned by Tau Ceti's
  ModularForms roadmap, Layer 8 (this packet requests them; see the roadmap document). The
  declarations for them below are prototype stand-ins so that the Hom-side API can be stated;
  they are not planned here and should be replaced by Layer 8's declarations.
* Diamond operators use the lower-right entry, as Tau Ceti's `diamondOp` does on forms.
-/

open Matrix OnePoint
open scoped MatrixGroups

noncomputable section

namespace TauCeti.ModularSymbol

/-- `P¹(ℚ)`, with the action of `GL₂(ℚ)` by linear fractional transformations. -/
abbrev P1Q := OnePoint ℚ

/-- **Stand-in for ModularForms Layer 8's `Div⁰`** (requested). `Δ₀ = Div⁰(P¹(ℚ))`: finitely supported `ℤ`-valued functions on
`P¹(ℚ)` of total degree `0`. -/
def Delta0 : Submodule ℤ (P1Q →₀ ℤ) :=
  LinearMap.ker (Finsupp.linearCombination ℤ fun _ : P1Q ↦ (1 : ℤ))

/-- The permutation representation of `GL₂(ℚ)` on divisors of `P¹(ℚ)`: `g · {x} = {g x}`. -/
def divisorRep : Representation ℤ (GL (Fin 2) ℚ) (P1Q →₀ ℤ) := sorry

theorem divisorRep_single (g : GL (Fin 2) ℚ) (x : P1Q) (n : ℤ) :
    divisorRep g (Finsupp.single x n) = Finsupp.single (g • x) n := sorry

/-- API: `Δ₀` is stable under `GL₂(ℚ)`. -/
theorem divisorRep_mem_Delta0 (g : GL (Fin 2) ℚ) {D : P1Q →₀ ℤ} (hD : D ∈ Delta0) :
    divisorRep g D ∈ Delta0 := sorry

/-- The `GL₂(ℚ)`-representation on `Δ₀`. -/
def steinbergRep : Representation ℤ (GL (Fin 2) ℚ) Delta0 := sorry

/-- The divisor `{b} - {a}`. -/
def divisorOf (a b : P1Q) : Delta0 := ⟨Finsupp.single b 1 - Finsupp.single a 1, sorry⟩

/-- API: `Δ₀` is generated by the divisors `{b} - {a}`. -/
theorem span_divisorOf : Submodule.span ℤ (Set.range fun p : P1Q × P1Q ↦ divisorOf p.1 p.2) = ⊤ :=
  sorry

/-- `SL₂(ℤ)` inside `GL₂(ℚ)`. -/
def toGLQ : SL(2, ℤ) →* GL (Fin 2) ℚ :=
  (Matrix.SpecialLinearGroup.toGL).comp (Matrix.SpecialLinearGroup.map (Int.castRingHom ℚ))

section Symbols

variable (Γ : Subgroup SL(2, ℤ)) {R V : Type*} [CommRing R] [AddCommGroup V] [Module R V]

/-- **`L0/modular-symbols`** (Pollack–Stevens §2.1). For a representation `ρ` of `Γ` on `V` (the
left action `ρ(γ) v = v|γ⁻¹` of Pollack–Stevens' right action), the `V`-valued modular symbols are
the additive maps `φ : Δ₀ → V` with `φ(γ D) = ρ(γ) φ(D)`. -/
def symbols (ρ : Representation R Γ V) : AddSubgroup (Delta0 →ₗ[ℤ] V) where
  carrier := {φ | ∀ (γ : Γ) (D : Delta0), φ (steinbergRep (toGLQ γ) D) = ρ γ (φ D)}
  add_mem' := sorry
  zero_mem' := sorry
  neg_mem' := sorry

/-- API: a modular symbol is determined by its values on the unimodular divisors
`{γ 0} - {γ ∞}` (Manin). -/
theorem symbols_ext (ρ : Representation R Γ V) {φ ψ : Delta0 →ₗ[ℤ] V}
    (h : ∀ γ : SL(2, ℤ), φ (divisorOf (toGLQ γ • (∞ : P1Q)) (toGLQ γ • ((0 : ℚ) : P1Q))) =
      ψ (divisorOf (toGLQ γ • (∞ : P1Q)) (toGLQ γ • ((0 : ℚ) : P1Q)))) : φ = ψ := sorry

end Symbols

section Unimodular

/-- The two-torsion element `σ = !![0, -1; 1, 0]`. -/
def σ : SL(2, ℤ) := ⟨!![0, -1; 1, 0], by decide⟩

/-- The three-torsion element `τ = !![0, -1; 1, -1]`. -/
def τ : SL(2, ℤ) := ⟨!![0, -1; 1, -1], by decide⟩

/-- **Stand-in for Layer 8's unimodular map** (requested). `d : ℤ[SL₂(ℤ)] → Δ₀`, `γ ↦ {γ 0} - {γ ∞}` (the boundary of the
unimodular path `[γ]` from `a/c` to `b/d`). -/
def unimodularMap : MonoidAlgebra ℤ SL(2, ℤ) →ₗ[ℤ] Delta0 := sorry

theorem unimodularMap_of (γ : SL(2, ℤ)) :
    unimodularMap (MonoidAlgebra.of ℤ _ γ) =
      divisorOf (toGLQ γ • (∞ : P1Q)) (toGLQ γ • ((0 : ℚ) : P1Q)) := sorry

/-- API: `d` is `SL₂(ℤ)`-equivariant. -/
theorem unimodularMap_of_mul (g γ : SL(2, ℤ)) :
    unimodularMap (MonoidAlgebra.of ℤ _ (g * γ)) =
      steinbergRep (toGLQ g) (unimodularMap (MonoidAlgebra.of ℤ _ γ)) := sorry

/-- **Imported from Layer 8** (requested): Manin's surjectivity (continued fractions). -/
theorem unimodularMap_surjective : Function.Surjective unimodularMap := sorry

/-- **Imported from Layer 8** (requested): Manin's relations (Pollack–Stevens §2.2). Over `SL₂(ℤ)` the kernel of `d` is the
left ideal generated by `1 + σ`, `1 + τ + τ²` and `1 - (-1)`, the last because `-1` acts trivially
on `P¹(ℚ)`; modulo it, this is Manin's `ℤ[PSL₂(ℤ)](1 + τ + τ²) + ℤ[PSL₂(ℤ)](1 + σ)`. -/
theorem ker_unimodularMap :
    LinearMap.ker unimodularMap =
      (Submodule.span (MonoidAlgebra ℤ SL(2, ℤ))
        {MonoidAlgebra.of ℤ _ 1 + MonoidAlgebra.of ℤ _ σ,
         MonoidAlgebra.of ℤ _ 1 + MonoidAlgebra.of ℤ _ τ + MonoidAlgebra.of ℤ _ (τ ^ 2),
         MonoidAlgebra.of ℤ _ 1 - MonoidAlgebra.of ℤ _ (-1)}).restrictScalars ℤ := sorry

/-- **`L0/coset-basis`**. `ℤ[SL₂(ℤ)]` is a free left `ℤ[Γ]`-module (a basis is a set of right
coset representatives of `Γ \ SL₂(ℤ)`). -/
theorem free_monoidAlgebra (Γ : Subgroup SL(2, ℤ)) :
    letI : Module (MonoidAlgebra ℤ Γ) (MonoidAlgebra ℤ SL(2, ℤ)) :=
      (MonoidAlgebra.mapDomainRingHom ℤ Γ.subtype).toModule
    Module.Free (MonoidAlgebra ℤ Γ) (MonoidAlgebra ℤ SL(2, ℤ)) := sorry

end Unimodular

section Coefficients

variable (R : Type*) [CommRing R] (k : ℕ)

/-- **`L0/polynomial-coefficients`** (Pollack–Stevens §3.4). `V_k(R) = Sym^k(R²)`, the
homogeneous polynomials of degree `k` in `X, Y`. -/
abbrev Vk : Submodule R (MvPolynomial (Fin 2) R) := MvPolynomial.homogeneousSubmodule (Fin 2) R k

/-- The right action `(P | γ)(X, Y) = P(d X - c Y, -b X + a Y)` of an integral matrix `γ`
(through its adjugate), a right action of the monoid `M₂(ℤ)`. -/
def slashVk (γ : Matrix (Fin 2) (Fin 2) ℤ) : Vk R k →ₗ[R] Vk R k := sorry

theorem slashVk_apply (γ : Matrix (Fin 2) (Fin 2) ℤ) (P : Vk R k) :
    ((slashVk R k γ P : Vk R k) : MvPolynomial (Fin 2) R) =
      MvPolynomial.aeval ![(γ 1 1 : R) • MvPolynomial.X 0 - (γ 1 0 : R) • MvPolynomial.X 1,
        -(γ 0 1 : R) • MvPolynomial.X 0 + (γ 0 0 : R) • MvPolynomial.X 1] (P : MvPolynomial (Fin 2) R) :=
  sorry

/-- API: `P | (γ δ) = (P | γ) | δ` (right action). -/
theorem slashVk_mul (γ δ : Matrix (Fin 2) (Fin 2) ℤ) (P : Vk R k) :
    slashVk R k (γ * δ) P = slashVk R k δ (slashVk R k γ P) := sorry

theorem slashVk_one (P : Vk R k) : slashVk R k 1 P = P := sorry

/-- The left representation of `Γ` on `V_k(R)`: `γ ↦ (P ↦ P | γ⁻¹)`. -/
def vkRep (Γ : Subgroup SL(2, ℤ)) : Representation R Γ (Vk R k) := sorry

end Coefficients

section Hecke

variable (N : ℕ) {R V : Type*} [CommRing R] [AddCommGroup V] [Module R V]

/-- **`L0/hecke-monoid`**. `Σ₀(N)`: integral matrices `!![a, b; c, d]` with `det ≠ 0`, `N ∣ c`
and `(a, N) = 1`. -/
def Sigma0 : Submonoid (Matrix (Fin 2) (Fin 2) ℤ) where
  carrier := {γ | γ.det ≠ 0 ∧ (N : ℤ) ∣ γ 1 0 ∧ IsCoprime (γ 0 0) (N : ℤ)}
  mul_mem' := sorry
  one_mem' := sorry

/-- The image in `GL₂(ℚ)` of an integral matrix of nonzero determinant. -/
def toGLQ' (γ : Matrix (Fin 2) (Fin 2) ℤ) (h : γ.det ≠ 0) : GL (Fin 2) ℚ := sorry

/-- API: `Γ₀(N)` lies in `Σ₀(N)`. -/
theorem Gamma0_le_Sigma0 (γ : SL(2, ℤ)) (hγ : γ ∈ CongruenceSubgroup.Gamma0 N) :
    (γ : Matrix (Fin 2) (Fin 2) ℤ) ∈ Sigma0 N := sorry

/-- The slash action `(φ | δ)(D) = φ(δ D) | δ` on maps `Δ₀ → V`, for `V` with a right action of
`Σ₀(N)` given by `act`. -/
def slash (act : (Sigma0 N)ᵐᵒᵖ →* Module.End R V) (δ : Sigma0 N)
    (φ : Delta0 →ₗ[ℤ] V) : Delta0 →ₗ[ℤ] V :=
  sorry

/-- **`L0/hecke-operators`** (Pollack–Stevens §2.1). For `ℓ ∤ N`,
`φ | T_ℓ = φ | !![ℓ, 0; 0, 1] + ∑_{a < ℓ} φ | !![1, a; 0, ℓ]`; for `q ∣ N`,
`φ | U_q = ∑_{a < q} φ | !![1, a; 0, q]`. They preserve `Γ₀(N)`-modular symbols. -/
def heckeT (act : (Sigma0 N)ᵐᵒᵖ →* Module.End R V) (ℓ : ℕ)
    (φ : Delta0 →ₗ[ℤ] V) : Delta0 →ₗ[ℤ] V := sorry

def heckeU (act : (Sigma0 N)ᵐᵒᵖ →* Module.End R V) (q : ℕ)
    (φ : Delta0 →ₗ[ℤ] V) : Delta0 →ₗ[ℤ] V := sorry

/-- API: the Hecke operators preserve `Γ₀(N)`-modular symbols, for a right `Σ₀(N)`-action `act`
restricting on `Γ₀(N)` to the representation `ρ` (via `ρ(γ) = act(γ⁻¹)`). -/
theorem heckeT_mem_symbols (act : (Sigma0 N)ᵐᵒᵖ →* Module.End R V)
    (ρ : Representation R (CongruenceSubgroup.Gamma0 N) V)
    (hact : ∀ (γ : CongruenceSubgroup.Gamma0 N) (v : V),
      act (MulOpposite.op ⟨(γ.val : Matrix (Fin 2) (Fin 2) ℤ),
        Gamma0_le_Sigma0 N γ.val γ.property⟩) v = ρ γ⁻¹ v)
    (ℓ : ℕ) (hℓ : ℓ.Prime) (hℓN : ¬ ℓ ∣ N) {φ : Delta0 →ₗ[ℤ] V}
    (hφ : φ ∈ symbols (CongruenceSubgroup.Gamma0 N) ρ) :
    heckeT N act ℓ φ ∈ symbols (CongruenceSubgroup.Gamma0 N) ρ := sorry

/-- API: good-prime Hecke operators commute on equivariant symbols. The coefficient
action is a genuine right monoid action, with the stated restriction to `ρ`. -/
theorem heckeT_comm (act : (Sigma0 N)ᵐᵒᵖ →* Module.End R V)
    (ρ : Representation R (CongruenceSubgroup.Gamma0 N) V)
    (hact : ∀ (γ : CongruenceSubgroup.Gamma0 N) (v : V),
      act (MulOpposite.op ⟨(γ.val : Matrix (Fin 2) (Fin 2) ℤ),
        Gamma0_le_Sigma0 N γ.val γ.property⟩) v = ρ γ⁻¹ v)
    (ℓ m : ℕ) (hℓ : ℓ.Prime) (hm : m.Prime) (hℓN : ¬ ℓ ∣ N) (hmN : ¬ m ∣ N)
    (φ : Delta0 →ₗ[ℤ] V) (hφ : φ ∈ symbols (CongruenceSubgroup.Gamma0 N) ρ) :
    heckeT N act ℓ (heckeT N act m φ) = heckeT N act m (heckeT N act ℓ φ) := sorry

end Hecke

section Involution

/-- **`L0/involution-at-infinity`**. `ι = !![-1, 0; 0, 1]` acts on modular symbols when it
normalises `Γ`; when `2` is invertible they split into `±1`-eigenspaces. -/
def iota : GL (Fin 2) ℚ := sorry

theorem iota_mul_self : iota * iota = 1 := sorry

/-- API: `ι` normalises `Γ₀(N)`. -/
theorem iota_normalizes_Gamma0 (N : ℕ) (γ : SL(2, ℤ)) (hγ : γ ∈ CongruenceSubgroup.Gamma0 N) :
    ∃ γ' ∈ CongruenceSubgroup.Gamma0 N, toGLQ γ' = iota * toGLQ γ * iota⁻¹ := sorry

/-- API: `ι` acts on `P¹(ℚ)` by `x ↦ -x`. -/
theorem iota_smul (x : ℚ) : iota • ((x : ℚ) : P1Q) = ((-x : ℚ) : P1Q) := sorry

end Involution

section Boundary

variable (Γ : Subgroup SL(2, ℤ)) {R V : Type} [CommRing R] [AddCommGroup V] [Module R V]

/-- **`L0/boundary-symbols`**. `BSymb_Γ(V) = Hom_Γ(ℤ[P¹(ℚ)], V)`: additive maps on all divisors,
equivariant for `ρ`. -/
def bsymbols (ρ : Representation R Γ V) : AddSubgroup ((P1Q →₀ ℤ) →ₗ[ℤ] V) where
  carrier := {ψ | ∀ (γ : Γ) (D : P1Q →₀ ℤ), ψ (divisorRep (toGLQ γ) D) = ρ γ (ψ D)}
  add_mem' := sorry
  zero_mem' := sorry
  neg_mem' := sorry

/-- Restriction along `Δ₀ ⊆ ℤ[P¹(ℚ)]`. -/
def res : ((P1Q →₀ ℤ) →ₗ[ℤ] V) →+ (Delta0 →ₗ[ℤ] V) where
  toFun ψ := ψ.comp Delta0.subtype
  map_zero' := sorry
  map_add' := sorry

/-- API: restriction sends boundary symbols to modular symbols. -/
theorem res_mem_symbols (ρ : Representation R Γ V) {ψ : (P1Q →₀ ℤ) →ₗ[ℤ] V}
    (hψ : ψ ∈ bsymbols Γ ρ) : res ψ ∈ symbols Γ ρ := sorry

/-- `Eis_Γ(V)`, the image of the boundary symbols. -/
def eisSymbols (ρ : Representation R Γ V) : AddSubgroup (Delta0 →ₗ[ℤ] V) :=
  (bsymbols Γ ρ).map res

theorem eisSymbols_le (ρ : Representation R Γ V) : eisSymbols Γ ρ ≤ symbols Γ ρ := sorry

end Boundary

section Cohomology

variable (Γ : Subgroup SL(2, ℤ)) {R V : Type} [CommRing R] [AddCommGroup V] [Module R V]

/-- **`L0/symbols-to-cohomology`**. `δ : Symb_Γ(V) → H¹(Γ, V)`, represented by the cocycle
`γ ↦ φ({γ x} - {x})` for any base cusp `x`. -/
def toH1 (ρ : Representation R Γ V) : symbols Γ ρ →+ groupCohomology (Rep.of ρ) 1 := sorry

/-- API: `δ` kills the Eisenstein symbols (exactness at `Symb_Γ(V)`, one inclusion). -/
theorem toH1_eis (ρ : Representation R Γ V) (φ : symbols Γ ρ)
    (hφ : (φ : Delta0 →ₗ[ℤ] V) ∈ eisSymbols Γ ρ) : toH1 Γ ρ φ = 0 := sorry

/-- **`L0/parabolic-cohomology`**. `H¹_par(Γ, V)`: classes restricting to zero on every cusp
stabiliser. -/
def H1par (ρ : Representation R Γ V) : Submodule R (groupCohomology (Rep.of ρ) 1) := sorry

/-- **`L0/symbols-cohomology-sequence`** and **`L0/symbols-mod-eisenstein`**: the kernel of `δ` is
the Eisenstein symbols and its image is `H¹_par`, integrally. -/
theorem ker_toH1 (ρ : Representation R Γ V) :
    (toH1 Γ ρ).ker = (eisSymbols Γ ρ).addSubgroupOf (symbols Γ ρ) := sorry

theorem range_toH1 (ρ : Representation R Γ V) :
    Set.range (toH1 Γ ρ) = (H1par Γ ρ : Set (groupCohomology (Rep.of ρ) 1)) := sorry

/-- **`L0/symbols-level-descent`** (first half, integral): a `Γ`-symbol is a `Γ'`-symbol for any
`Γ' ≤ Γ`, and for `Γ'` normal the `Γ`-symbols are exactly the `Γ/Γ'`-invariant ones. -/
theorem symbols_le_of_le {Γ' : Subgroup SL(2, ℤ)} (h : Γ' ≤ Γ) (ρ : Representation R Γ V) :
    symbols Γ ρ ≤ symbols Γ' (ρ.comp (Subgroup.inclusion h)) := sorry

end Cohomology

section Diamond

variable (N : ℕ) {R V : Type} [CommRing R] [AddCommGroup V] [Module R V]

/-- The restriction of a representation of `Γ₀(N)` to `Γ₁(N)`. -/
abbrev restrictGamma1 (ρ : Representation R (CongruenceSubgroup.Gamma0 N) V) :
    Representation R (CongruenceSubgroup.Gamma1 N) V :=
  ρ.comp (Subgroup.inclusion (CongruenceSubgroup.Gamma1_in_Gamma0 N))

/-- **`L0/diamond-operators`**. `⟨d⟩ φ = φ | σ_d` for `σ_d ∈ Γ₀(N)` with lower-right entry `d`. -/
def diamond (ρ : Representation R (CongruenceSubgroup.Gamma0 N) V) (d : (ZMod N)ˣ) :
    (Delta0 →ₗ[ℤ] V) →+ (Delta0 →ₗ[ℤ] V) := sorry

theorem diamond_mem_symbols (ρ : Representation R (CongruenceSubgroup.Gamma0 N) V) (d : (ZMod N)ˣ)
    {φ : Delta0 →ₗ[ℤ] V} (hφ : φ ∈ symbols (CongruenceSubgroup.Gamma1 N) (restrictGamma1 N ρ)) :
    diamond N ρ d φ ∈ symbols (CongruenceSubgroup.Gamma1 N) (restrictGamma1 N ρ) := sorry

theorem diamond_one (ρ : Representation R (CongruenceSubgroup.Gamma0 N) V) (φ : Delta0 →ₗ[ℤ] V)
    (hφ : φ ∈ symbols (CongruenceSubgroup.Gamma1 N) (restrictGamma1 N ρ)) :
    diamond N ρ 1 φ = φ := sorry

theorem diamond_mul (ρ : Representation R (CongruenceSubgroup.Gamma0 N) V) (d e : (ZMod N)ˣ)
    (φ : Delta0 →ₗ[ℤ] V) (hφ : φ ∈ symbols (CongruenceSubgroup.Gamma1 N) (restrictGamma1 N ρ)) :
    diamond N ρ (d * e) φ = diamond N ρ d (diamond N ρ e φ) := sorry

/-- The diamond-fixed `Γ₁(N)`-symbols are the `Γ₀(N)`-symbols. -/
theorem mem_symbols_Gamma0_iff (ρ : Representation R (CongruenceSubgroup.Gamma0 N) V)
    (φ : Delta0 →ₗ[ℤ] V) :
    φ ∈ symbols (CongruenceSubgroup.Gamma0 N) ρ ↔
      φ ∈ symbols (CongruenceSubgroup.Gamma1 N) (restrictGamma1 N ρ) ∧
        ∀ d : (ZMod N)ˣ, diamond N ρ d φ = φ := sorry

/-- **`L0/nebentypus-symbols`**. Symbols with character `ε`: the `ε`-eigenspace of the diamond
operators. -/
def symbolsChar (ρ : Representation R (CongruenceSubgroup.Gamma0 N) V) (ε : (ZMod N)ˣ →* Rˣ) :
    AddSubgroup (Delta0 →ₗ[ℤ] V) where
  carrier := {φ | φ ∈ symbols (CongruenceSubgroup.Gamma1 N) (restrictGamma1 N ρ) ∧
    ∀ (d : (ZMod N)ˣ) (D : Delta0), diamond N ρ d φ D = ((ε d : Rˣ) : R) • φ D}
  add_mem' := sorry
  zero_mem' := sorry
  neg_mem' := sorry

/-- The trivial character recovers the `Γ₀(N)`-symbols. -/
theorem symbolsChar_one (ρ : Representation R (CongruenceSubgroup.Gamma0 N) V) :
    symbolsChar N ρ 1 = symbols (CongruenceSubgroup.Gamma0 N) ρ := sorry

end Diamond

section Pairing

variable (R : Type) [CommRing R] (k : ℕ)

/-- **`L0/polynomial-duality`**. The invariant pairing `⟨(uX + vY)^k, (sX + tY)^k⟩ = (ut - vs)^k`,
defined when `k!` is invertible. -/
def vkPairing (hk : IsUnit ((k.factorial : ℕ) : R)) : Vk R k →ₗ[R] Vk R k →ₗ[R] R := sorry

theorem vkPairing_linearForm_pow (hk : IsUnit ((k.factorial : ℕ) : R)) (u v s t : R) :
    vkPairing R k hk
        ⟨(MvPolynomial.C u * MvPolynomial.X 0 + MvPolynomial.C v * MvPolynomial.X 1) ^ k, sorry⟩
        ⟨(MvPolynomial.C s * MvPolynomial.X 0 + MvPolynomial.C t * MvPolynomial.X 1) ^ k, sorry⟩ =
      (u * t - v * s) ^ k := sorry

/-- The pairing is perfect. -/
theorem vkPairing_bijective (hk : IsUnit ((k.factorial : ℕ) : R)) :
    Function.Bijective (vkPairing R k hk) := sorry

end Pairing

section Periods

open Matrix.SpecialLinearGroup in
/-- **`L0/period-symbol`**. `ψ_f({s} - {r}) = 2πi ∫_r^s f(z) (zX + Y)^k dz` for a cusp form `f` of
weight `k + 2` on `Γ`. -/
def periodSymbol (Γ : Subgroup SL(2, ℤ)) (k : ℕ) :
    CuspForm (Γ.map (mapGL ℝ)) ((k : ℤ) + 2) →ₗ[ℂ] (Delta0 →ₗ[ℤ] Vk ℂ k) := sorry

open Matrix.SpecialLinearGroup in
theorem periodSymbol_mem (Γ : Subgroup SL(2, ℤ)) (k : ℕ)
    (f : CuspForm (Γ.map (mapGL ℝ)) ((k : ℤ) + 2)) :
    periodSymbol Γ k f ∈ symbols Γ (vkRep ℂ k Γ) := sorry

open Matrix.SpecialLinearGroup in
/-- **`L0/eichler-shimura-isomorphism`** (injectivity on cusp forms, Wiese Theorem 6.15): the
Eichler–Shimura class of `f` determines `f`. -/
theorem periodSymbol_toH1_injective (N k : ℕ) (hN : 4 ≤ N) :
    Function.Injective fun f : CuspForm ((CongruenceSubgroup.Gamma1 N).map (mapGL ℝ)) ((k : ℤ) + 2) ↦
      toH1 (CongruenceSubgroup.Gamma1 N) (vkRep ℂ k _) ⟨periodSymbol _ k f, periodSymbol_mem _ k f⟩ :=
  sorry

open Matrix.SpecialLinearGroup in
/-- **`L0/eichler-shimura-isomorphism`** (dimension): `dim H¹_par = 2 dim S_{k+2}` for `Γ₁(N)`,
`N ≥ 4`. -/
theorem finrank_H1par_eq_two_mul (N k : ℕ) (hN : 4 ≤ N) :
    Module.finrank ℂ (H1par (CongruenceSubgroup.Gamma1 N) (vkRep ℂ k _)) =
      2 * Module.finrank ℂ (CuspForm ((CongruenceSubgroup.Gamma1 N).map (mapGL ℝ)) ((k : ℤ) + 2)) :=
  sorry

end Periods

section CriticalValues

/-!
### L1: periods and critical values (signatures; comment only)

```
-- L1/period-lines (K_f from Tau Ceti ModularForms Layer 8)
def periodLine (f : Newform N (k + 2) ε) (s : Sign) : Submodule K_f (Symb (Gamma1 N) (vkRep K_f k))
theorem periodLine_finrank : Module.finrank K_f (periodLine f s) = 1
def period (φ : periodLine f s) (hφ : φ ≠ 0) : ℂˣ         -- ψ_f^s = period φ • φ
theorem period_smul (c : K_fˣ) : period (c • φ) _ = c⁻¹ • period φ _
-- L1/twisted-mellin-formula (L-functions from Tau Ceti ModularForms Layer 7)
theorem twisted_mellin (χ : DirichletCharacter ℂ m) (hχ : χ.IsPrimitive) (j : ℕ) (hj : j ≤ k) :
    ∑ a : ZMod m, χ a * twistedPeriod f j a = gaussSum χ (ZMod.stdAddChar) * (j ! / (-2 * π * I) ^ j) *
      LSeries (fun n ↦ (χ n)⁻¹ * coeff f n) (j + 1)
-- L1/critical-value-algebraicity
theorem critical_value_mem (hs : s = (-1) ^ (k - j) * χ (-1)) : … ∈ K_f⟮χ⟯
```
-/

end CriticalValues

section SmallSlope

/-!
### L2: refinements and small slope

`Σ₀(p)` over `ℤ_p` is stated here as `Sigma0p` (the integral `Sigma0 N` above is L0's Hecke
monoid). The distribution spaces `A[r]`, `D[r]`, `D(ℤ_p)` are requested from
LocallyAnalyticDistributions L0, and h-admissibility from its L2, so the remaining signatures
are comments.

```
-- L2/p-stabilisation (Tau Ceti `CuspForm.levelRaise` is V_p)
def pStabilisation (f : Newform N (k + 2)) (α β : ℂ) : CuspForm (Gamma1 (N * p)) (k + 2) :=
  f - β • CuspForm.levelRaise p _ f
theorem pStabilisation_Up (hαβ : α + β = a_p f) (hαβ' : α * β = ε p * p ^ (k + 1)) :
    heckeUCuspNat (k + 2) p _ _ (pStabilisation f α β) = α • pStabilisation f α β
-- L2/refinement
structure Refinement (N k p) where
  f : Newform N (k + 2)
  α : ℚ̄_p
  isRoot : if p ∣ N then α = a_p f ∧ α ≠ 0 else α ^ 2 - a_p f * α + ε p * p ^ (k + 1) = 0
def Refinement.slope (r : Refinement N k p) : ℚ := padicValuation r.α
-- L2/refined-eigenline
theorem refinedLine_finrank (r : Refinement N k p) (s : Sign) : finrank K (refinedLine r s) = 1
-- L2/weight-k-distributions, L2/specialisation-map (D[r] from LocallyAnalyticDistributions L0)
def distWeight (k : ℕ) (r : ℝ≥0) (hr : r < p) : Representation ℚ_[p] (Sigma0p p)ᵐᵒᵖ (Dist r)
def specialise (k : ℕ) : Dist 1 →ₗ[ℚ_[p]] Vk ℚ_[p] k    -- μ ↦ ∫ (Y - z X)^k dμ
theorem specialise_smul (γ : Sigma0p p) (μ) :
    specialise k (μ ∣ γ) = slashVk _ k γ (specialise k μ)
-- L2/control-theorem
theorem control (h : slope < k + 1) :
    Function.Bijective
      (specialiseSymb k : SymbSlopeLT (k + 1) (DistAn p) → SymbSlopeLT (k + 1) (Vk _ k))
-- L2/p-adic-l-function, L2/interpolation-and-uniqueness
def padicLFunction (r : Refinement N k p) (hr : r.slope < k + 1) (φ : Sign → refinedLine r _) :
    DistAn (ℤ_[p]ˣ)
theorem padicLFunction_interpolation (χ) (hχ : conductor χ = p ^ n) (j ≤ k) :
    padicLFunction r hr φ (z ^ j * χ) =
      e n j * α⁻¹ ^ n * p ^ (n * j) * gaussSum χ * j ! / (2πi) ^ j *
        L (f_α) χ⁻¹ (j + 1) / Ω (sign ((-1) ^ j * χ (-1)))
```
-/

variable (p : ℕ) [Fact p.Prime]

/-- **`L2/weight-k-distributions`**: `Σ₀(p) = {(a b; c d) ∈ M₂(ℤ_p) : p ∤ a, p ∣ c, det ≠ 0}`. -/
def Sigma0p : Submonoid (Matrix (Fin 2) (Fin 2) ℤ_[p]) where
  carrier := {γ | IsUnit (γ 0 0) ∧ γ 1 0 ∈ IsLocalRing.maximalIdeal ℤ_[p] ∧ γ.det ≠ 0}
  mul_mem' := sorry
  one_mem' := sorry

end SmallSlope

section CriticalSlope

/-!
### L3: critical slope, and L4: examples (signatures; comment only)

Criticality, θ-criticality and Bellaïche's critical and secondary p-adic L-functions are planned
by PadicFamilies L3 (RS-08); this packet specialises them to a single refinement.

```
-- L3/non-theta-critical-lift (IsThetaCritical from PadicFamilies L3/refinement-criticality)
def criticalSlopePadicL (r : Refinement N k p) (hs : r.slope = k + 1) (hθ : ¬ r.IsThetaCritical)
    (φ : Sign → refinedLine r _) : DistAn (ℤ_[p]ˣ)
theorem criticalSlopePadicL_lift_unique (Φ : Sign → SymbEigen r (DistAn p))
    (hΦ : ∀ s, specialiseSymb k (Φ s) = φ s) : Φ = criticalLift r hs hθ φ
theorem criticalSlopePadicL_admissible : IsAdmissible (k + 1) (criticalSlopePadicL r hs hθ φ)
-- L3/critical-slope-interpolation: the formula of padicLFunction_interpolation
-- L3/critical-slope-non-uniqueness
theorem exists_admissible_vanishing (k : ℕ) :
    ∃ μ : DistAn (ℤ_[p]ˣ), μ ≠ 0 ∧ IsAdmissible (k + 1) μ ∧
      ∀ j ≤ k, ∀ χ : DirichletCharacter ℂ_[p] (p ^ n), μ (z ^ j * χ) = 0
-- L4/euler-factor-comparison (αβ = ε(p)p^{k+1})
theorem eulerFactor_eq (χ) (hχ : conductor χ = 1) (j ≤ k) :
    e r χ j = (1 - χ p * p ^ j / α) * (1 - (χ p)⁻¹ * ε p * p ^ (k - j) / α)
```
-/

end CriticalSlope

end TauCeti.ModularSymbol

namespace TauCeti.ModularSymbol.SuggestedTest

open TauCeti.ModularSymbol

/-- A single point is not a degree-zero divisor. -/
example : Finsupp.single (∞ : P1Q) (1 : ℤ) ∉ Delta0 := sorry

/-- `{b} - {a} + {c} - {b} = {c} - {a}`. -/
example (a b c : P1Q) : divisorOf a b + divisorOf b c = divisorOf a c := sorry

/-- `{a} - {a} = 0`. -/
example (a : P1Q) : divisorOf a a = 0 := sorry

/-- `d(1 + σ) = 0` and `d(1 + τ + τ²) = 0`. -/
example : unimodularMap (MonoidAlgebra.of ℤ _ 1 + MonoidAlgebra.of ℤ _ σ) = 0 := sorry

example : unimodularMap (MonoidAlgebra.of ℤ _ 1 + MonoidAlgebra.of ℤ _ τ +
    MonoidAlgebra.of ℤ _ (τ ^ 2)) = 0 := sorry

/-- There are no nonzero `ℤ`-valued modular symbols for `SL₂(ℤ)` (the Manin relations force
`2v = 3v = 0`). -/
example : symbols (⊤ : Subgroup SL(2, ℤ)) (Representation.trivial ℤ (⊤ : Subgroup SL(2, ℤ)) ℤ) = ⊥ :=
  sorry

/-- `Symb_{Γ₀(11)}(ℤ)` has rank `3 = 2g + (c - 1)` with `g = 1`, `c = 2`. -/
example : Module.finrank ℤ (symbols (CongruenceSubgroup.Gamma0 11)
    (Representation.trivial ℤ (CongruenceSubgroup.Gamma0 11) ℤ)) = 3 := sorry

/-- `V_k(R)` has rank `k + 1`. -/
example (R : Type*) [CommRing R] [Nontrivial R] (k : ℕ) : Module.finrank R (Vk R k) = k + 1 := sorry

/-- A scalar matrix `λ • 1` acts on `V_k` by `λ ^ k`. -/
example (R : Type*) [CommRing R] (k : ℕ) (c : ℤ) (P : Vk R k) :
    slashVk R k (c • (1 : Matrix (Fin 2) (Fin 2) ℤ)) P = ((c : R) ^ k) • P := sorry

/-- For `SL₂(ℤ)` and `V = ℤ` every boundary symbol restricts to zero (one cusp). -/
example : eisSymbols (⊤ : Subgroup SL(2, ℤ)) (Representation.trivial ℤ (⊤ : Subgroup SL(2, ℤ)) ℤ) = ⊥ :=
  sorry

/-- `k = 1`: the pairing is the determinant pairing `⟨X, Y⟩ = 1`. -/
example (R : Type) [CommRing R] :
    vkPairing R 1 (by simp) ⟨MvPolynomial.X 0, sorry⟩ ⟨MvPolynomial.X 1, sorry⟩ = 1 := sorry

/-- `k = 2`: the pairing is not integral, `⟨XY, XY⟩ = -1/2`. -/
example : vkPairing ℚ 2 (by norm_num [Nat.factorial]) ⟨MvPolynomial.X 0 * MvPolynomial.X 1, sorry⟩
    ⟨MvPolynomial.X 0 * MvPolynomial.X 1, sorry⟩ = -1 / 2 := sorry

/-- `dim H¹_par(Γ₁(11), ℂ) = 2`, twice the genus of `X₁(11)`. -/
example : Module.finrank ℂ (H1par (CongruenceSubgroup.Gamma1 11) (vkRep ℂ 0 _)) = 2 := sorry

/-- `L1/period-lines`: rescaling the basis of a period line by `λ` rescales the period by `λ⁻¹`
(`ψ = Ω • φ` gives `ψ = (λ⁻¹ * Ω) • (λ • φ)`). -/
example {V : Type*} [AddCommGroup V] [Module ℂ V] (Ω c : ℂ) (hc : c ≠ 0) (φ ψ : V)
    (h : ψ = Ω • φ) : ψ = (c⁻¹ * Ω) • (c • φ) := by
  rw [h, smul_smul, mul_assoc, mul_comm Ω c, ← mul_assoc, inv_mul_cancel₀ hc, one_mul]

/-- `L1/twisted-mellin-formula`, the Mellin constant: `-2πi · i^{j+1}/(2π)^{j+1} = 1/(-2πi)^j`
reduces to `-i^{j+2} = i^j`. -/
example (j : ℕ) : -(Complex.I ^ (j + 2)) = Complex.I ^ j := by
  rw [pow_add, Complex.I_sq]; ring

/-- `L1/rjw-b1-comparison`, the conversion constant: `-(-c)^j / c^{j+1} = (-1)^{j+1} / c` for
`c = 2πi`. -/
example (c : ℂ) (hc : c ≠ 0) (j : ℕ) : -((-c) ^ j / c ^ (j + 1)) = (-1) ^ (j + 1) / c := by
  rw [neg_pow, pow_succ, pow_succ]
  field_simp

/-- `L2/p-stabilisation`: with `α + β = a_p` and `αβ = ε(p)p^{k+1}`, the good-prime recurrence
`a_{pm} = a_p a_m - ε(p)p^{k+1} a_{m/p}` gives `a_{pm}(f_α) = α a_m(f_α)`. -/
example {R : Type*} [CommRing R] (α β x y : R) :
    ((α + β) * x - α * β * y) - β * x = α * (x - β * y) := by ring

/-- `L2/specialisation-map`: `ρ_k` is `Σ₀(p)`-equivariant, since
`(a + cz)^k (Y - γz X)^k = ((aY - bX) - z(dX - cY))^k`. -/
example (a b c d z X Y : ℚ) (k : ℕ) (h : a + c * z ≠ 0) :
    (a + c * z) ^ k * (Y - (b + d * z) / (a + c * z) * X) ^ k =
      ((a * Y - b * X) - z * (d * X - c * Y)) ^ k := by
  rw [← mul_pow]
  congr 1
  field_simp
  ring

/-- `L2/overconvergent-lift` (Lemma 5.3): the moments of `μ | β(a, p)` are
`Σ_r C(j, r) a^{j-r} p^r μ(z^r)`. -/
example (a p z : ℚ) (j : ℕ) :
    (p * z + a) ^ j = ∑ r ∈ Finset.range (j + 1), (p * z) ^ r * a ^ (j - r) * (j.choose r) :=
  add_pow _ _ _

/-- `L2/interpolation-and-uniqueness`, `n = 0`: removing `pℤ_p` multiplies by `1 - p^j/α`. -/
example (Φ α q : ℂ) : Φ - α⁻¹ * q * Φ = (1 - q / α) * Φ := by ring

/-- Source issue `E4`: Pollack–Stevens (1) over (2) is `χ(-1) S / ((-1)^j S) = (-1)^j χ(-1)`. -/
example (u e S : ℂ) (hu : u ^ 2 = 1) (hS : S ≠ 0) : (e * S) / (u * S) = u * e := by
  have hu0 : u ≠ 0 := by
    rintro rfl
    norm_num at hu
  rw [mul_div_mul_right _ _ hS, div_eq_iff hu0]
  linear_combination -e * hu

/-- Source issue `E8`: `z/(1 + pz)` has a pole at `z = -1/p`, of absolute value `p`. -/
example (p : ℚ) (hp : p ≠ 0) : 1 + p * (-1 / p) = 0 := by
  rw [mul_div, mul_neg_one, neg_div, div_self hp]
  ring

/-- `L3/critical-slope-non-uniqueness`: the polynomial model `∏_{i ≤ k} (s - γ^i)` of
`log^{[k]}` vanishes at every `s = γ^j` with `j ≤ k`. -/
example (γ : ℚ) (k j : ℕ) (hj : j ≤ k) : ∏ i ∈ Finset.range (k + 1), (γ ^ j - γ ^ i) = 0 :=
  Finset.prod_eq_zero (Finset.mem_range.2 (Nat.lt_succ_of_le hj)) (sub_self _)

/-- `L4/euler-factor-comparison`: with `αβ = ε(p)p^{k+1}` and `i + j = k`,
`ε(p)p^{k-j}/α = β/p^{j+1}`, so the second factor is the p-stabilisation factor at `s = j + 1`. -/
example (α β e q : ℂ) (i j : ℕ) (hα : α ≠ 0) (hq : q ≠ 0) (h : α * β = e * q ^ (i + j + 1)) :
    e * q ^ i / α = β / q ^ (j + 1) := by
  rw [div_eq_div_iff hα (pow_ne_zero _ hq), mul_comm β α, h]
  ring

/-- `L4/level-eleven-examples`: the first Greenberg lift `(97, 59, 61)` of `(1/5, -3/2, 1/2)`
agrees with it modulo `11²`. -/
example : (97 : ℚ) - 1 / 5 = 11 ^ 2 * (4 / 5) ∧ (59 : ℚ) - (-3 / 2) = 11 ^ 2 * (1 / 2) ∧
    (61 : ℚ) - 1 / 2 = 11 ^ 2 * (1 / 2) := by
  norm_num

/-- `L4/level-eleven-examples`: the linear coefficient of `L₁₁(f, T)` is an `11`-adic unit, so
`λ = 1`. -/
example : ¬ (11 ∣ 1490719231) := by norm_num

end TauCeti.ModularSymbol.SuggestedTest

namespace TauCeti.ModularSymbol.SupersingularTest

/-- `L4/supersingular-refinements` (Pollack, Corollary 3.6): at a good supersingular prime `p ≥ 5` of an elliptic
curve, `p ∣ a_p` and the Hasse bound `a_p² < 4p` force `a_p = 0`. -/
example (p : ℕ) (hp : 5 ≤ p) (a : ℤ) (hdvd : (p : ℤ) ∣ a) (hH : a ^ 2 < 4 * p) : a = 0 := by
  obtain ⟨c, rfl⟩ := hdvd
  by_contra h
  have hc : c ≠ 0 := by rintro rfl; simp at h
  have hc2 : 1 ≤ c ^ 2 := by
    have := pow_pos (abs_pos.mpr hc) 2
    rw [sq_abs] at this
    omega
  have hp' : (5 : ℤ) ≤ p := by exact_mod_cast hp
  have h1 : (p : ℤ) ^ 2 ≤ (p : ℤ) ^ 2 * c ^ 2 := le_mul_of_one_le_right (sq_nonneg _) hc2
  have h2 : (p : ℤ) ^ 2 * c ^ 2 < 4 * p := by rw [← mul_pow]; exact hH
  have h3 : 5 * (p : ℤ) ≤ (p : ℤ) ^ 2 := by nlinarith
  linarith

/-- `L4/supersingular-examples`, `X₀(11)` at `p = 2`: `α = −1 + i` is a root of `X² + 2X + 2` (so `a₂ = −2`), of norm
`2` (slope `1/2`), and the other root is `−1 − i = α · i`, so `α₁/α₂` is a primitive fourth root of unity. -/
example : ((-1 + ⟨0, 1⟩ : GaussianInt)) ^ 2 + 2 * (-1 + ⟨0, 1⟩) + 2 = 0 := by decide
example : Zsqrtd.norm (-1 + ⟨0, 1⟩ : GaussianInt) = 2 := by decide
example : (-1 + ⟨0, 1⟩ : GaussianInt) * ⟨0, 1⟩ = -1 - ⟨0, 1⟩ := by decide

/-- `L4/half-logarithms`, Lemma 4.7 bookkeeping: at a primitive `pⁿ`-th root of unity, `log⁺` has `(n − 1)/2` head
factors for odd `n` and `log⁻` has `n/2` for even `n`; with the leading `1/p` the exponents are `(n + 1)/2` and
`n/2 + 1`. -/
example (n : ℕ) (h : n % 2 = 1) : 1 + (n - 1) / 2 = (n + 1) / 2 := by omega
example (n : ℕ) : 1 + n / 2 = n / 2 + 1 := by omega

end TauCeti.ModularSymbol.SupersingularTest

namespace TauCeti.ModularSymbol

/-!
## Rational Drinfeld–Manin splitting (L0)

Nakamura, Invent. Math. 234 (2023), §3.2, p. 220. His weight is `k + 2` here.
The connected Betti model uses `Γ(N)`, `N ≥ 3`. The full arithmetic curve has several
geometric components. Its local systems and Betti–étale comparison are requested from
ModularCurvesPartII R14.3; their Galois signatures cannot yet be stated here.

The following Hecke maps are prototypes of the actions already planned by L0. They
use the usual double-coset normalization on cohomology, transferred to `vkRep` through
the coefficient-system dictionary. That dictionary is an explicit gap in the packet.
The generic projection and characteristic-polynomial theory are imported from Mathlib.
-/

abbrev RationalH1 (N k : ℕ) :=
  groupCohomology (Rep.of (vkRep ℚ k (CongruenceSubgroup.Gamma N))) 1

abbrev RationalH1par (N k : ℕ) :=
  H1par (CongruenceSubgroup.Gamma N) (vkRep ℚ k (CongruenceSubgroup.Gamma N))

/-- Good primes indexing Nakamura's `T_ℓ` and scalar `S_ℓ`. -/
abbrev GoodPrime (N : ℕ) := {ℓ : ℕ // ℓ.Prime ∧ Nat.Coprime ℓ N}

/-- Prototype of L0's usual cohomological `T_ℓ` action at full level. -/
def h1Hecke (N k : ℕ) (ℓ : GoodPrime N) : Module.End ℚ (RationalH1 N k) := sorry

/-- Prototype of L0's scalar double-coset `S_ℓ` action at full level. -/
def h1ScalarHecke (N k : ℕ) (ℓ : GoodPrime N) : Module.End ℚ (RationalH1 N k) := sorry

theorem h1Hecke_commute (N k : ℕ) (ℓ m : GoodPrime N) :
    Commute (h1Hecke N k ℓ) (h1Hecke N k m) := sorry

theorem h1ScalarHecke_commute (N k : ℕ) (ℓ m : GoodPrime N) :
    Commute (h1ScalarHecke N k ℓ) (h1ScalarHecke N k m) := sorry

theorem h1Hecke_scalarHecke_commute (N k : ℕ) (ℓ m : GoodPrime N) :
    Commute (h1Hecke N k ℓ) (h1ScalarHecke N k m) := sorry

/-- The good Hecke algebra is the native subalgebra generated by these operators. -/
def h1HeckeAlgebra (N k : ℕ) : Subalgebra ℚ (Module.End ℚ (RationalH1 N k)) :=
  Algebra.adjoin ℚ (Set.range (h1Hecke N k) ∪ Set.range (h1ScalarHecke N k))

/-- **`L0/rational-hecke-separation`**. A good Hecke-algebra element has coprime
annihilators on the parabolic subspace and the boundary quotient. The range condition
is the precise assertion that `Q(A)` annihilates the quotient. The higher-weight
source proof is recorded as a gap; this is a proposed theorem, not an assumption
silently bundled into a representation. -/
theorem rational_hecke_separation (N k : ℕ) (hN : 3 ≤ N) :
    ∃ (A : h1HeckeAlgebra N k) (P Q : Polynomial ℚ), IsCoprime P Q ∧
      (∀ x : RationalH1par N k,
        (Polynomial.aeval (A.val : Module.End ℚ (RationalH1 N k)) P) x.val = 0) ∧
      LinearMap.range (Polynomial.aeval (A.val : Module.End ℚ (RationalH1 N k)) Q) ≤
        RationalH1par N k := sorry

/-- **`L0/drinfeld-manin-splitting`**. The unique rational good-Hecke-equivariant
retraction onto parabolic cohomology. Existence is obtained from the separating
annihilators by a Bézout polynomial projection, using Mathlib's `projectionOnto`. -/
def drinfeldManin (N k : ℕ) (hN : 3 ≤ N) :
    RationalH1 N k →ₗ[ℚ] RationalH1par N k := sorry

theorem drinfeldManin_subtype (N k : ℕ) (hN : 3 ≤ N) (x : RationalH1par N k) :
    drinfeldManin N k hN x.val = x := sorry

theorem drinfeldManin_hecke (N k : ℕ) (hN : 3 ≤ N) (ℓ : GoodPrime N)
    (x : RationalH1 N k) :
    (drinfeldManin N k hN (h1Hecke N k ℓ x)).val =
      h1Hecke N k ℓ (drinfeldManin N k hN x).val := sorry

theorem drinfeldManin_scalarHecke (N k : ℕ) (hN : 3 ≤ N) (ℓ : GoodPrime N)
    (x : RationalH1 N k) :
    (drinfeldManin N k hN (h1ScalarHecke N k ℓ x)).val =
      h1ScalarHecke N k ℓ (drinfeldManin N k hN x).val := sorry

theorem drinfeldManin_unique (N k : ℕ) (hN : 3 ≤ N)
    (s : RationalH1 N k →ₗ[ℚ] RationalH1par N k)
    (hs : ∀ x : RationalH1par N k, s x.val = x)
    (hT : ∀ (ℓ : GoodPrime N) (x : RationalH1 N k),
      (s (h1Hecke N k ℓ x)).val = h1Hecke N k ℓ (s x).val)
    (hS : ∀ (ℓ : GoodPrime N) (x : RationalH1 N k),
      (s (h1ScalarHecke N k ℓ x)).val = h1ScalarHecke N k ℓ (s x).val) :
    s = drinfeldManin N k hN := sorry

theorem drinfeldManin_idempotent (N k : ℕ) (hN : 3 ≤ N) (x : RationalH1 N k) :
    drinfeldManin N k hN (drinfeldManin N k hN x).val = drinfeldManin N k hN x := sorry

/-- Involutions and realization actions commute with the splitting after their
commutation with the usual Hecke operators and preservation of the parabolic
subspace have been proved. This statement retains both concrete hypotheses. -/
theorem drinfeldManin_natural (N k : ℕ) (hN : 3 ≤ N)
    (F : Module.End ℚ (RationalH1 N k))
    (hF : ∀ x : RationalH1par N k, F x.val ∈ RationalH1par N k)
    (hT : ∀ ℓ : GoodPrime N, Commute F (h1Hecke N k ℓ))
    (hS : ∀ ℓ : GoodPrime N, Commute F (h1ScalarHecke N k ℓ))
    (x : RationalH1 N k) :
    (drinfeldManin N k hN (F x)).val = F (drinfeldManin N k hN x).val := sorry

namespace DrinfeldManinTest

/-- X(3) has genus zero. Its weight-two parabolic cohomology is zero, so the
splitting is zero; the ordinary H¹ still has three boundary dimensions. -/
theorem genus_zero : drinfeldManin 3 0 (by decide) = 0 := sorry
example : drinfeldManin 3 0 (by decide) = 0 := sorry

/-- X(6) has genus one. This excludes the zero map as a proposed splitting. -/
theorem identity_parabolic :
    Module.finrank ℚ (RationalH1par 6 0) = 2 ∧
      ∀ x : RationalH1par 6 0, drinfeldManin 6 0 (by decide) x.val = x := sorry
example : Module.finrank ℚ (RationalH1par 6 0) = 2 ∧
    ∀ x : RationalH1par 6 0, drinfeldManin 6 0 (by decide) x.val = x := sorry

/-- A small instance of the Bézout projection used in the construction:
T(x,y) = (y,2y), parabolic subspace y = 0, projector 1 - T/2.
The first coordinate is x - y/2, not x. -/
theorem rational_model :
    let T : Module.End ℚ (ℚ × ℚ) :=
      (LinearMap.snd ℚ ℚ ℚ).prod ((2 : ℚ) • LinearMap.snd ℚ ℚ ℚ)
    let e : Module.End ℚ (ℚ × ℚ) := LinearMap.id - (1 / 2 : ℚ) • T
    e (0, 1) = (-1 / 2, 0) ∧ e (1, 0) = (1, 0) ∧
      (∀ v, e (T v) = 0) ∧ Commute e T ∧ e * e = e := sorry
example :
    let T : Module.End ℚ (ℚ × ℚ) :=
      (LinearMap.snd ℚ ℚ ℚ).prod ((2 : ℚ) • LinearMap.snd ℚ ℚ ℚ)
    let e : Module.End ℚ (ℚ × ℚ) := LinearMap.id - (1 / 2 : ℚ) • T
    e (0, 1) = (-1 / 2, 0) ∧ e (1, 0) = (1, 0) ∧
      (∀ v, e (T v) = 0) ∧ Commute e T ∧ e * e = e := sorry

/-- The same spectral separation does not give an integral Hecke-equivariant
retraction. Such a retraction would give 1 + 2s(0,1) = 0 in ℤ. -/
theorem integral_obstruction (s : (ℤ × ℤ) →ₗ[ℤ] ℤ) (hs : s (1, 0) = 1) :
    ¬ ∀ v : ℤ × ℤ, s (v.2, 2 * v.2) = 0 := sorry
example (s : (ℤ × ℤ) →ₗ[ℤ] ℤ) (hs : s (1, 0) = 1) :
    ¬ ∀ v : ℤ × ℤ, s (v.2, 2 * v.2) = 0 := sorry

end DrinfeldManinTest
end TauCeti.ModularSymbol
