import Mathlib.Topology.Compactification.OnePoint.ProjectiveLine
import Mathlib.NumberTheory.ModularForms.CongruenceSubgroups
import Mathlib.RepresentationTheory.Basic
import Mathlib.LinearAlgebra.Finsupp.LinearCombination
import Mathlib.RingTheory.MvPolynomial.Homogeneous
import Mathlib.Algebra.MonoidAlgebra.Basic
import Mathlib.LinearAlgebra.Matrix.SpecialLinearGroup

/-!
# Suggested Lean forms: modular symbols (ModularSymbolsPadicLFunctions, L0)

**Standard note.** This file is not the roadmap and it is not exhaustive. The roadmap document
(`ModularSymbolsPadicLFunctions`) is definitive. The statements below suggest Lean forms, so that
contributors and reviewers converge on names and signatures. Every proof of a new declaration is
`sorry`; nothing here claims to be formalised.

Pinned baseline: Mathlib `082e2d3`, Tau Ceti `f790474`.

## Conventions

* `P¹(ℚ)` is `OnePoint ℚ` with Mathlib's `GL₂(ℚ)`-action; `Δ₀` is the kernel of the degree map
  on `P¹(ℚ) →₀ ℤ`.
* Pollack–Stevens' right `Γ`-action `v | γ` is encoded as the left representation
  `ρ(γ) v = v | γ⁻¹`, so a modular symbol satisfies `φ(γ D) = ρ(γ) φ(D)`.
* Manin's relations are stated over `SL₂(ℤ)`, with `1 - (-1)` added because `-1` acts trivially
  on `P¹(ℚ)`; modulo it they are Manin's relations over `PSL₂(ℤ)`.
* `V_k` is the space of degree-`k` homogeneous polynomials in `X, Y` with the adjugate action
  `(P | γ)(X, Y) = P(dX - cY, -bX + aY)`.
-/

open Matrix OnePoint
open scoped MatrixGroups

noncomputable section

namespace TauCeti.ModularSymbol

/-- `P¹(ℚ)`, with the action of `GL₂(ℚ)` by linear fractional transformations. -/
abbrev P1Q := OnePoint ℚ

/-- **`L0/steinberg-module`**. `Δ₀ = Div⁰(P¹(ℚ))`: finitely supported `ℤ`-valued functions on
`P¹(ℚ)` of total degree `0`. -/
def Delta0 : Submodule ℤ (P1Q →₀ ℤ) :=
  LinearMap.ker (Finsupp.linearCombination ℤ fun _ : P1Q ↦ (1 : ℤ))

/-- The permutation representation of `GL₂(ℚ)` on divisors of `P¹(ℚ)`: `g · {x} = {g x}`. -/
def divisorRep : Representation ℤ (GL (Fin 2) ℚ) (P1Q →₀ ℤ) := sorry

theorem divisorRep_single (g : GL (Fin 2) ℚ) (x : P1Q) (n : ℤ) :
    divisorRep g (Finsupp.single x n) = Finsupp.single (g • x) n := sorry

/-- API: `Δ₀` is stable under `GL₂(ℚ)`. -/
theorem divisorRep_mem_Delta0 (g : GL (Fin 2) ℚ) {D : P1Q →₀ ℤ} (hD : D ∈ Delta0) :
    divisorRep g D ∈ Delta0 := sorry

/-- The `GL₂(ℚ)`-representation on `Δ₀`. -/
def steinbergRep : Representation ℤ (GL (Fin 2) ℚ) Delta0 := sorry

/-- The divisor `{b} - {a}`. -/
def divisorOf (a b : P1Q) : Delta0 := ⟨Finsupp.single b 1 - Finsupp.single a 1, sorry⟩

/-- API: `Δ₀` is generated by the divisors `{b} - {a}`. -/
theorem span_divisorOf : Submodule.span ℤ (Set.range fun p : P1Q × P1Q ↦ divisorOf p.1 p.2) = ⊤ :=
  sorry

/-- `SL₂(ℤ)` inside `GL₂(ℚ)`. -/
def toGLQ : SL(2, ℤ) →* GL (Fin 2) ℚ :=
  (Matrix.SpecialLinearGroup.toGL).comp (Matrix.SpecialLinearGroup.map (Int.castRingHom ℚ))

section Symbols

variable (Γ : Subgroup SL(2, ℤ)) {R V : Type*} [CommRing R] [AddCommGroup V] [Module R V]

/-- **`L0/modular-symbols`** (Pollack–Stevens §2.1). For a representation `ρ` of `Γ` on `V` (the
left action `ρ(γ) v = v|γ⁻¹` of Pollack–Stevens' right action), the `V`-valued modular symbols are
the additive maps `φ : Δ₀ → V` with `φ(γ D) = ρ(γ) φ(D)`. -/
def symbols (ρ : Representation R Γ V) : AddSubgroup (Delta0 →ₗ[ℤ] V) where
  carrier := {φ | ∀ (γ : Γ) (D : Delta0), φ (steinbergRep (toGLQ γ) D) = ρ γ (φ D)}
  add_mem' := sorry
  zero_mem' := sorry
  neg_mem' := sorry

/-- API: a modular symbol is determined by its values on the unimodular divisors
`{γ 0} - {γ ∞}` (Manin). -/
theorem symbols_ext (ρ : Representation R Γ V) {φ ψ : Delta0 →ₗ[ℤ] V}
    (h : ∀ γ : SL(2, ℤ), φ (divisorOf (toGLQ γ • (∞ : P1Q)) (toGLQ γ • ((0 : ℚ) : P1Q))) =
      ψ (divisorOf (toGLQ γ • (∞ : P1Q)) (toGLQ γ • ((0 : ℚ) : P1Q)))) : φ = ψ := sorry

end Symbols

section Unimodular

/-- The two-torsion element `σ = !![0, -1; 1, 0]`. -/
def σ : SL(2, ℤ) := ⟨!![0, -1; 1, 0], by decide⟩

/-- The three-torsion element `τ = !![0, -1; 1, -1]`. -/
def τ : SL(2, ℤ) := ⟨!![0, -1; 1, -1], by decide⟩

/-- **`L0/unimodular-map`**. `d : ℤ[SL₂(ℤ)] → Δ₀`, `γ ↦ {γ 0} - {γ ∞}` (the boundary of the
unimodular path `[γ]` from `a/c` to `b/d`). -/
def unimodularMap : MonoidAlgebra ℤ SL(2, ℤ) →ₗ[ℤ] Delta0 := sorry

theorem unimodularMap_of (γ : SL(2, ℤ)) :
    unimodularMap (MonoidAlgebra.of ℤ _ γ) =
      divisorOf (toGLQ γ • (∞ : P1Q)) (toGLQ γ • ((0 : ℚ) : P1Q)) := sorry

/-- API: `d` is `SL₂(ℤ)`-equivariant. -/
theorem unimodularMap_of_mul (g γ : SL(2, ℤ)) :
    unimodularMap (MonoidAlgebra.of ℤ _ (g * γ)) =
      steinbergRep (toGLQ g) (unimodularMap (MonoidAlgebra.of ℤ _ γ)) := sorry

/-- **`L0/manin-surjectivity`** (Manin; continued fractions). -/
theorem unimodularMap_surjective : Function.Surjective unimodularMap := sorry

/-- **`L0/manin-relations`** (Manin; Pollack–Stevens §2.2). Over `SL₂(ℤ)` the kernel of `d` is the
left ideal generated by `1 + σ`, `1 + τ + τ²` and `1 - (-1)`, the last because `-1` acts trivially
on `P¹(ℚ)`; modulo it, this is Manin's `ℤ[PSL₂(ℤ)](1 + τ + τ²) + ℤ[PSL₂(ℤ)](1 + σ)`. -/
theorem ker_unimodularMap :
    LinearMap.ker unimodularMap =
      (Submodule.span (MonoidAlgebra ℤ SL(2, ℤ))
        {MonoidAlgebra.of ℤ _ 1 + MonoidAlgebra.of ℤ _ σ,
         MonoidAlgebra.of ℤ _ 1 + MonoidAlgebra.of ℤ _ τ + MonoidAlgebra.of ℤ _ (τ ^ 2),
         MonoidAlgebra.of ℤ _ 1 - MonoidAlgebra.of ℤ _ (-1)}).restrictScalars ℤ := sorry

/-- **`L0/coset-basis`**. `ℤ[SL₂(ℤ)]` is a free left `ℤ[Γ]`-module (a basis is a set of right
coset representatives of `Γ \ SL₂(ℤ)`). -/
theorem free_monoidAlgebra (Γ : Subgroup SL(2, ℤ)) :
    letI : Module (MonoidAlgebra ℤ Γ) (MonoidAlgebra ℤ SL(2, ℤ)) :=
      (MonoidAlgebra.mapDomainRingHom ℤ Γ.subtype).toModule
    Module.Free (MonoidAlgebra ℤ Γ) (MonoidAlgebra ℤ SL(2, ℤ)) := sorry

end Unimodular

section Coefficients

variable (R : Type*) [CommRing R] (k : ℕ)

/-- **`L0/polynomial-coefficients`** (Pollack–Stevens §3.4). `V_k(R) = Sym^k(R²)`, the
homogeneous polynomials of degree `k` in `X, Y`. -/
abbrev Vk : Submodule R (MvPolynomial (Fin 2) R) := MvPolynomial.homogeneousSubmodule (Fin 2) R k

/-- The right action `(P | γ)(X, Y) = P(d X - c Y, -b X + a Y)` of an integral matrix `γ`
(through its adjugate), a right action of the monoid `M₂(ℤ)`. -/
def slashVk (γ : Matrix (Fin 2) (Fin 2) ℤ) : Vk R k →ₗ[R] Vk R k := sorry

theorem slashVk_apply (γ : Matrix (Fin 2) (Fin 2) ℤ) (P : Vk R k) :
    ((slashVk R k γ P : Vk R k) : MvPolynomial (Fin 2) R) =
      MvPolynomial.aeval ![(γ 1 1 : R) • MvPolynomial.X 0 - (γ 1 0 : R) • MvPolynomial.X 1,
        -(γ 0 1 : R) • MvPolynomial.X 0 + (γ 0 0 : R) • MvPolynomial.X 1] (P : MvPolynomial (Fin 2) R) :=
  sorry

/-- API: `P | (γ δ) = (P | γ) | δ` (right action). -/
theorem slashVk_mul (γ δ : Matrix (Fin 2) (Fin 2) ℤ) (P : Vk R k) :
    slashVk R k (γ * δ) P = slashVk R k δ (slashVk R k γ P) := sorry

theorem slashVk_one (P : Vk R k) : slashVk R k 1 P = P := sorry

/-- The left representation of `Γ` on `V_k(R)`: `γ ↦ (P ↦ P | γ⁻¹)`. -/
def vkRep (Γ : Subgroup SL(2, ℤ)) : Representation R Γ (Vk R k) := sorry

end Coefficients

section Hecke

variable (N : ℕ) {R V : Type*} [CommRing R] [AddCommGroup V] [Module R V]

/-- **`L0/hecke-monoid`**. `Σ₀(N)`: integral matrices `!![a, b; c, d]` with `det ≠ 0`, `N ∣ c`
and `(a, N) = 1`. -/
def Sigma0 : Submonoid (Matrix (Fin 2) (Fin 2) ℤ) where
  carrier := {γ | γ.det ≠ 0 ∧ (N : ℤ) ∣ γ 1 0 ∧ IsCoprime (γ 0 0) (N : ℤ)}
  mul_mem' := sorry
  one_mem' := sorry

/-- The image in `GL₂(ℚ)` of an integral matrix of nonzero determinant. -/
def toGLQ' (γ : Matrix (Fin 2) (Fin 2) ℤ) (h : γ.det ≠ 0) : GL (Fin 2) ℚ := sorry

/-- API: `Γ₀(N)` lies in `Σ₀(N)`. -/
theorem Gamma0_le_Sigma0 (γ : SL(2, ℤ)) (hγ : γ ∈ CongruenceSubgroup.Gamma0 N) :
    (γ : Matrix (Fin 2) (Fin 2) ℤ) ∈ Sigma0 N := sorry

/-- The slash action `(φ | δ)(D) = φ(δ D) | δ` on maps `Δ₀ → V`, for `V` with a right action of
`Σ₀(N)` given by `act`. -/
def slash (act : Sigma0 N → V →ₗ[R] V) (δ : Sigma0 N) (φ : Delta0 →ₗ[ℤ] V) : Delta0 →ₗ[ℤ] V :=
  sorry

/-- **`L0/hecke-operators`** (Pollack–Stevens §2.1). For `ℓ ∤ N`,
`φ | T_ℓ = φ | !![ℓ, 0; 0, 1] + ∑_{a < ℓ} φ | !![1, a; 0, ℓ]`; for `q ∣ N`,
`φ | U_q = ∑_{a < q} φ | !![1, a; 0, q]`. They preserve `Γ₀(N)`-modular symbols. -/
def heckeT (act : Sigma0 N → V →ₗ[R] V) (ℓ : ℕ) (φ : Delta0 →ₗ[ℤ] V) : Delta0 →ₗ[ℤ] V := sorry

def heckeU (act : Sigma0 N → V →ₗ[R] V) (q : ℕ) (φ : Delta0 →ₗ[ℤ] V) : Delta0 →ₗ[ℤ] V := sorry

/-- API: the Hecke operators preserve `Γ₀(N)`-modular symbols, for a right `Σ₀(N)`-action `act`
restricting on `Γ₀(N)` to the representation `ρ` (via `ρ(γ) = act(γ⁻¹)`). -/
theorem heckeT_mem_symbols (act : Sigma0 N → V →ₗ[R] V) (ρ : Representation R (CongruenceSubgroup.Gamma0 N) V)
    (ℓ : ℕ) (hℓ : ℓ.Prime) (hℓN : ¬ ℓ ∣ N) {φ : Delta0 →ₗ[ℤ] V}
    (hφ : φ ∈ symbols (CongruenceSubgroup.Gamma0 N) ρ) :
    heckeT N act ℓ φ ∈ symbols (CongruenceSubgroup.Gamma0 N) ρ := sorry

/-- API: `T_ℓ` and `T_m` commute. -/
theorem heckeT_comm (act : Sigma0 N → V →ₗ[R] V) (ℓ m : ℕ) (φ : Delta0 →ₗ[ℤ] V) :
    heckeT N act ℓ (heckeT N act m φ) = heckeT N act m (heckeT N act ℓ φ) := sorry

end Hecke

section Involution

/-- **`L0/involution-at-infinity`**. `ι = !![-1, 0; 0, 1]` acts on modular symbols when it
normalises `Γ`; when `2` is invertible they split into `±1`-eigenspaces. -/
def iota : GL (Fin 2) ℚ := sorry

theorem iota_mul_self : iota * iota = 1 := sorry

/-- API: `ι` normalises `Γ₀(N)`. -/
theorem iota_normalizes_Gamma0 (N : ℕ) (γ : SL(2, ℤ)) (hγ : γ ∈ CongruenceSubgroup.Gamma0 N) :
    ∃ γ' ∈ CongruenceSubgroup.Gamma0 N, toGLQ γ' = iota * toGLQ γ * iota⁻¹ := sorry

/-- API: `ι` acts on `P¹(ℚ)` by `x ↦ -x`. -/
theorem iota_smul (x : ℚ) : iota • ((x : ℚ) : P1Q) = ((-x : ℚ) : P1Q) := sorry

end Involution

end TauCeti.ModularSymbol

namespace TauCeti.ModularSymbol.SuggestedTest

open TauCeti.ModularSymbol

/-- A single point is not a degree-zero divisor. -/
example : Finsupp.single (∞ : P1Q) (1 : ℤ) ∉ Delta0 := sorry

/-- `{b} - {a} + {c} - {b} = {c} - {a}`. -/
example (a b c : P1Q) : divisorOf a b + divisorOf b c = divisorOf a c := sorry

/-- `{a} - {a} = 0`. -/
example (a : P1Q) : divisorOf a a = 0 := sorry

/-- `d(1 + σ) = 0` and `d(1 + τ + τ²) = 0`. -/
example : unimodularMap (MonoidAlgebra.of ℤ _ 1 + MonoidAlgebra.of ℤ _ σ) = 0 := sorry

example : unimodularMap (MonoidAlgebra.of ℤ _ 1 + MonoidAlgebra.of ℤ _ τ +
    MonoidAlgebra.of ℤ _ (τ ^ 2)) = 0 := sorry

/-- There are no nonzero `ℤ`-valued modular symbols for `SL₂(ℤ)` (the Manin relations force
`2v = 3v = 0`). -/
example : symbols (⊤ : Subgroup SL(2, ℤ)) (Representation.trivial ℤ (⊤ : Subgroup SL(2, ℤ)) ℤ) = ⊥ :=
  sorry

/-- `Symb_{Γ₀(11)}(ℤ)` has rank `3 = 2g + (c - 1)` with `g = 1`, `c = 2`. -/
example : Module.finrank ℤ (symbols (CongruenceSubgroup.Gamma0 11)
    (Representation.trivial ℤ (CongruenceSubgroup.Gamma0 11) ℤ)) = 3 := sorry

/-- `V_k(R)` has rank `k + 1`. -/
example (R : Type*) [CommRing R] [Nontrivial R] (k : ℕ) : Module.finrank R (Vk R k) = k + 1 := sorry

/-- A scalar matrix `λ • 1` acts on `V_k` by `λ ^ k`. -/
example (R : Type*) [CommRing R] (k : ℕ) (c : ℤ) (P : Vk R k) :
    slashVk R k (c • (1 : Matrix (Fin 2) (Fin 2) ℤ)) P = ((c : R) ^ k) • P := sorry

end TauCeti.ModularSymbol.SuggestedTest
