#!/usr/bin/env python3
"""Turn accepted library audits into data/library-coverage.json.

Reads research/blueprint/audit/AUDIT-NN.result.json. Only results whose review
object says "accepted" are used. For each audited layer it records the verdict,
the declarations that show what the libraries already contain, and the other
roadmaps' layers that state the same targets. The builder treats a layer the
accepted audit finds fully built as complete (with that evidence), and a
partly built one as in progress; layers that are process or duplicates are
listed for the atlas owner to decide on, not changed automatically.

    python3 scripts/merge_library_audit.py
"""
from __future__ import annotations

import datetime
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AUDIT = ROOT / "research" / "blueprint" / "audit"
PRIVATE = re.compile(r"/(?:Users|home)/[^/\s]+/")
VERDICTS = {"built", "partly built", "not built", "process"}


def main() -> None:
    atlas = json.loads((ROOT / "data" / "atlas.json").read_text(encoding="utf-8"))
    stage_ids = {stage["id"] for stage in atlas["stages"]}
    layers, reviews, skipped = {}, {}, []
    for path in sorted(AUDIT.glob("AUDIT-[0-9][0-9].result.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        job = path.name.split(".")[0]
        review = data.get("review") or {}
        if review.get("status") != "accepted":
            skipped.append(job)
            continue
        reviews[job] = {"reviewer": review.get("reviewer"), "date": review.get("date"), "checked": review.get("checked"),
                        "corrections": len(review.get("corrections") or [])}
        for rid, roadmap in (data.get("roadmaps") or {}).items():
            for lid, layer in (roadmap.get("layers") or {}).items():
                if lid not in stage_ids or layer.get("verdict") not in VERDICTS:
                    continue
                evidence = []
                for target in layer.get("targets") or []:
                    for decl in target.get("declarations") or []:
                        if decl.get("fit") in ("exact", "more general") and target.get("library") in ("mathlib", "tauceti", "both"):
                            evidence.append({"target": target.get("target", ""), "name": decl.get("name"), "library": decl.get("library"),
                                             "file": decl.get("file"), "line": decl.get("line"), "fit": decl.get("fit")})
                text = json.dumps(layer)
                if PRIVATE.search(text):
                    raise SystemExit(f"{job} {lid}: a private path in the audit")
                layers[lid] = {"verdict": layer["verdict"], "job": job,
                               "targets": [{"target": t.get("target", ""), "library": t.get("library"), "note": t.get("note", "")}
                                           for t in layer.get("targets") or []],
                               "evidence": evidence[:12],
                               "duplicates": [d for d in layer.get("duplicates") or [] if d.get("layer") in stage_ids]}
    document = {
        "version": 1,
        "purpose": "What the pinned Mathlib and Tau Ceti already contain, layer by layer, from reviewed library audits (research/blueprint/audit). Generated by scripts/merge_library_audit.py; do not edit by hand.",
        "generated": datetime.date.today().isoformat(),
        "reviews": reviews,
        "pendingReview": skipped,
        "layers": layers,
    }
    (ROOT / "data" / "library-coverage.json").write_text(json.dumps(document, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    counts = {}
    for layer in layers.values():
        counts[layer["verdict"]] = counts.get(layer["verdict"], 0) + 1
    print(f"{len(reviews)} accepted audits, {len(skipped)} awaiting review; layers: {counts}")


if __name__ == "__main__":
    main()
