import Mathlib

/-!
# DerivedDeRhamCohomology: representative target signatures

README.md is the definitive roadmap. This file records definitions and theorem
signatures statable against the pinned APIs and is not exhaustive. Ordinary
forms use the existing Kähler and exterior-power carriers, strict alternation
also in characteristic 2, and an A-linear differential. Derived signatures
record ordinary views of the specified enhanced constructions; mapping spaces,
coherent filtrations and their multiplicative laws remain part of the README.
Cohomological shifts place a module M[1] in degree −1. The tensor and scalar
extension views have the EnhancedDerivedSheaves supplier as their fixed meaning.
-/

namespace TauCetiRoadmap.DerivedDeRhamCohomology

open CategoryTheory CategoryTheory.Limits CategoryTheory.Pretriangulated ExteriorAlgebra
open scoped TensorProduct ZeroObject
set_option linter.unusedVariables false
noncomputable section

/-! ## Layer 0: Cotangent complexes and integral derived powers -/

namespace DerivedDeRham
open scoped ZeroObject
/-- The standard derived-category instance for modules over R, local to these signatures. -/
local instance moduleDerived (R : Type) [CommRing R] :
    HasDerivedCategory.{1} (ModuleCat.{0} R) := HasDerivedCategory.standard _
/-- The ordinary derived category of R-modules. -/
abbrev D (R : Type) [CommRing R] := DerivedCategory (ModuleCat.{0} R)
/-- A discrete module placed in cohomological degree zero. -/
abbrev mod0 (R : Type) [CommRing R] (M : ModuleCat.{0} R) : D R :=
  (DerivedCategory.singleFunctor (ModuleCat R) 0).obj M
/-- Cohomology in the indicated integer cohomological degree. -/
abbrev H (R : Type) [CommRing R] (n : ℤ) (M : D R) : ModuleCat R :=
  (DerivedCategory.homologyFunctor (ModuleCat R) n).obj M
/-- The base ring as a discrete derived module. -/
abbrev unit (R : Type) [CommRing R] : D R := mod0 R (ModuleCat.of R R)
/-- A decreasing integer-indexed diagram in the ordinary derived category. -/
abbrev Filtered (R : Type) [CommRing R] := OrderDual ℤ ⥤ D R
-- A forgetful augmented diagram, not the enhanced filtered category.
/-- The ordinary augmented diagram underlying a coherent filtered module; it records no enhanced coherences. -/
structure FilteredModel (R : Type) [CommRing R] where
  underlying : D R
  filtration : Filtered R
  toward : filtration ⟶ (Functor.const (OrderDual ℤ)).obj underlying
/-- The dual-number algebra k[t]/t². -/
abbrev Dual (k : Type) [CommRing k] :=
  Polynomial k ⧸ Ideal.span {(Polynomial.X : Polynomial k)^2}
/-- The algebra k[x,y]/(x²,xy,y²), whose maximal ideal has square zero. -/
abbrev SquareZero2 (k : Type) [CommRing k] :=
  MvPolynomial (Fin 2) k ⧸ Ideal.span
    ({(MvPolynomial.X (0 : Fin 2))^2,
     MvPolynomial.X (0 : Fin 2) * MvPolynomial.X (1 : Fin 2),
     (MvPolynomial.X (1 : Fin 2))^2} : Set (MvPolynomial (Fin 2) k))
-- Forgetful views of EDS's derived tensor and extension of scalars. These are
-- fixed planned constructions, never operators supplied by an arbitrary caller.
/-- The ordinary view of EnhancedDerivedSheaves derived tensor, with the functorial enhanced structure specified by that supplier. -/
private def tensor (A : Type) [CommRing A] (M N : D A) : D A := by sorry
/-- The ordinary view of EnhancedDerivedSheaves derived extension of scalars. -/
private def extend (A B : Type) [CommRing A] [CommRing B] [Algebra A B]
    (M : D A) : D B := by sorry
/-- Derived extension of scalars to the actual ordinary quotient A/I. -/
private def reduction (A : Type) [CommRing A] (I : Ideal A) (M : D A) : D (A ⧸ I) :=
  extend A (A ⧸ I) M
/-- Tor amplitude tested against every discrete coefficient module, using derived tensor. -/
private def amplitude (A : Type) [CommRing A] (M : D A) (a b : ℤ) : Prop :=
  ∀ N : ModuleCat A, ∀ n : ℤ, n < a ∨ b < n →
    IsZero (H A n (tensor A M (mod0 A N)))
/-- A single exponent kills all p-power torsion elements. -/
private def boundedTorsion (p : ℕ) (M : Type) [AddCommGroup M] : Prop :=
  ∃ c : ℕ, ∀ x : M, (∃ n : ℕ, p^n • x = 0) → p^c • x = 0
/-- The principal ideal generated by p in A. -/
private abbrev pIdeal (A : Type) [CommRing A] (p : ℕ) := Ideal.span {(p : A)}


/-- For A→B in animated commutative rings construct the connective B-module L_(B/A). For ordinary rings and a cofibrant simplicial polynomial A-algebra resolution P•→B its underlying cochain complex is the normalized realization of Ω¹_(P•/A)⊗_(P•)B, with simplicial degree n placed in cohomological degree −n. Comparisons between free resolutions and naturality in commutative base squares are coherent. The full object retains all negative cohomology. -/
def cotangentComplex (A B : Type) [CommRing A] [CommRing B] [Algebra A B] : D B := by sorry
/-- For ordinary A→B, H⁰L_(B/A)≃KaehlerDifferential A B, preserving the universal derivation. -/
theorem cotangentH0 (A B : Type) [CommRing A] [CommRing B] [Algebra A B] :
    Nonempty (H B 0 (cotangentComplex A B) ≅ ModuleCat.of B (KaehlerDifferential A B)) := by sorry
-- L_(A/A)=0.
example (A : Type) [CommRing A] : IsZero (cotangentComplex A A) := by sorry
-- L_(A[t]/A)≃A[t]·dt in degree 0.
example (A : Type) [CommRing A] : Nonempty
    (cotangentComplex A (Polynomial A) ≅ unit (Polynomial A)) := by sorry
-- For k a field of characteristic different from 2 and B=k[ε]/ε², L_(B/k) is [B→B·dε], in degrees −1,0 with map multiplication by 2ε; H^−1 is nonzero.
example (k : Type) [Field k] (h2 : (2 : k) ≠ 0) :
    ¬ IsZero (H (Dual k) (-1) (cotangentComplex k (Dual k))) := by sorry
-- In characteristic 2 the presentation differential 2ε is zero in both degrees.
example (k : Type) [Field k] [CharP k 2] :
    Nonempty (H (Dual k) (-1) (cotangentComplex k (Dual k)) ≅
      ModuleCat.of (Dual k) (Dual k)) ∧
    Nonempty (H (Dual k) 0 (cotangentComplex k (Dual k)) ≅
      ModuleCat.of (Dual k) (Dual k)) := by sorry


/-- The degree −1 part of the naive-comparison target: H^−1 L_(B/A) agrees with Algebra.H1Cotangent for ordinary rings. The degree-zero comparison is cotangentH0; the truncation model is specified in README.md. -/
theorem cotangentNaiveComparison (A B : Type) [CommRing A] [CommRing B] [Algebra A B] :
    Nonempty (H B (-1) (cotangentComplex A B) ≅ ModuleCat.of B (Algebra.H1Cotangent A B)) := by sorry


/-- For a smooth finitely presented ordinary ring map A→B, L_(B/A)≃Ω¹_(B/A)[0], where Ω¹ is finite projective. For an étale map it vanishes. Polynomial rings on arbitrary sets have a free differential module in degree zero without a finiteness claim. -/
theorem smoothCotangent (A B : Type) [CommRing A] [CommRing B] [Algebra A B]
    [Algebra.Smooth A B] : Nonempty
    (cotangentComplex A B ≅ mod0 B (ModuleCat.of B (KaehlerDifferential A B))) := by sorry


/-- For composable ordinary ring maps the three specified cotangent objects fit into a distinguished triangle. This records the objects of the transitivity triangle; README.md separately specifies its canonical maps and enhanced naturality. -/
theorem cotangentTransitivity (A B C : Type) [CommRing A] [CommRing B] [CommRing C]
    [Algebra A B] [Algebra B C] [Algebra A C] [IsScalarTower A B C] :
    ∃ T : Triangle (D C), T.obj₁ = extend B C (cotangentComplex A B) ∧
      T.obj₂ = cotangentComplex A C ∧ T.obj₃ = cotangentComplex B C ∧
      T ∈ distTriang (D C) := by sorry


-- The ordinary pushout specialization has an explicit sufficient Tor-independence hypothesis.
/-- Ordinary base change for the cotangent complex when B is flat over A. The displayed tensor algebra is then the derived pushout. The animated version without this flatness assumption is a separate part of the README target. -/
theorem cotangentBaseChange (A B C : Type) [CommRing A] [CommRing B] [CommRing C]
    [Algebra A B] [Algebra A C] [Module.Flat A B] :
    letI : Algebra B (C ⊗[A] B) := (Algebra.TensorProduct.includeRight : B →ₐ[A] C ⊗[A] B).toRingHom.toAlgebra
    Nonempty (extend B (C ⊗[A] B) (cotangentComplex A B) ≅ cotangentComplex C (C ⊗[A] B)) := by sorry


-- The relative regular quotient computation; the conormal basis uses the chosen sequence.
/-- The relative cotangent complex of a quotient by the specified finite regular sequence is the free conormal module shifted by [1]. The absolute two-term computation over a smooth base is separately specified in README.md. -/
theorem regularQuotientCotangent (A : Type) [CommRing A] (xs : List A)
    (hx : RingTheory.Sequence.IsRegular A xs) : Nonempty
    (cotangentComplex A (A ⧸ Ideal.ofList xs) ≅
      (mod0 (A ⧸ Ideal.ofList xs)
        (ModuleCat.of (A ⧸ Ideal.ofList xs) (Fin xs.length → A ⧸ Ideal.ofList xs)))⟦(1 : ℤ)⟧) := by sorry


/-- For an ordinary map A→B, a B-module N and n≥0 define D_n(B|A,N)=H^−n(L_(B/A)⊗^L_B N). Coefficients are derived-tensored, even if the cotangent module has a two-term presentation. Transitivity gives the homological long exact sequence. -/
def andreQuillenHomology (A B : Type) [CommRing A] [CommRing B] [Algebra A B]
    (n : ℕ) (N : ModuleCat B) : ModuleCat B :=
  H B (-(n : ℤ)) (tensor B (cotangentComplex A B) (mod0 B N))
/-- D₀(B|A,N)≃Ω¹_(B/A)⊗_B N. -/
theorem andreQuillenZero (A B : Type) [CommRing A] [CommRing B] [Algebra A B]
    (N : ModuleCat B) : Nonempty
    (andreQuillenHomology A B 0 N ≅ ModuleCat.of B (KaehlerDifferential A B ⊗[B] N)) := by sorry
-- D₀(A[t]|A,N)≃N and D_n=0 for n>0.
example (A : Type) [CommRing A] (N : ModuleCat (Polynomial A)) :
    Nonempty (andreQuillenHomology A (Polynomial A) 0 N ≅ N) ∧
      ∀ n, 0 < n → IsZero (andreQuillenHomology A (Polynomial A) n N) := by sorry
-- D₁(F_p|Z,F_p)≃F_p and D_n=0 for n≠1.
example (p : ℕ) [Fact p.Prime] :
    Nonempty (andreQuillenHomology ℤ (ZMod p) 1 (ModuleCat.of (ZMod p) (ZMod p)) ≅
      ModuleCat.of (ZMod p) (ZMod p)) ∧
    ∀ n, n ≠ 1 → IsZero (andreQuillenHomology ℤ (ZMod p) n (ModuleCat.of (ZMod p) (ZMod p))) := by sorry
-- For A=k[ε]/ε² and its residue field k, D₂(k|A,k)≃k; A is not regular.
example (k : Type) [Field k] (ρ : Dual k →ₐ[k] k)
    (hρ : ρ (Ideal.Quotient.mk _ Polynomial.X) = 0) :
    letI : Algebra (Dual k) k := ρ.toRingHom.toAlgebra
    Nonempty (andreQuillenHomology (Dual k) k 2 (ModuleCat.of k k) ≅ ModuleCat.of k k) := by sorry

end DerivedDeRham

/-! ## Layer 1: Completion and filtered modules -/

namespace DerivedDeRham

/-- Let I=(f₁,…,f_r)⊂A be finitely generated. A complex M∈D(A) is derived I-complete if RHom_A(A[1/f_i],M)=0 for each i, equivalently Hom_D(A)(A[1/f_i][n],M)=0 for every integer n and i. This depends only on √I and is equivalent to each H^j(M) being a derived I-complete module. Completeness is a homotopical condition, not ordinary separatedness. -/
def derivedCompleteness (A : Type) [CommRing A] (I : Ideal A) (M : D A) : Prop :=
  ∀ f ∈ I, ∀ n : ℤ,
    Subsingleton ((mod0 A (ModuleCat.of A (Localization.Away f)))⟦n⟧ ⟶ M)
/-- The condition is RHom-vanishing for any finite generating set of I. -/
theorem isDerivedCompleteGenerators (A : Type) [CommRing A] (I : Ideal A) (M : D A)
    (s : Finset A) (hs : Ideal.span (s : Set A) = I) :
    derivedCompleteness A I M ↔ ∀ f ∈ s, ∀ n : ℤ,
      Subsingleton ((mod0 A (ModuleCat.of A (Localization.Away f)))⟦n⟧ ⟶ M) := by sorry
/-- If √I=√J for finite-generated ideals, I-complete and J-complete objects coincide. -/
theorem isDerivedCompleteRadical (A : Type) [CommRing A] (I J : Ideal A)
    (hI : I.FG) (hJ : J.FG) (h : I.radical = J.radical) (M : D A) :
    derivedCompleteness A I M ↔ derivedCompleteness A J M := by sorry
/-- M is I-complete iff every H^j(M) is derived I-complete. -/
theorem isDerivedCompleteCohomology (A : Type) [CommRing A] (I : Ideal A)
    (hI : I.FG) (M : D A) : derivedCompleteness A I M ↔
      ∀ j : ℤ, derivedCompleteness A I (mod0 A (H A j M)) := by sorry
-- For I=0, every complex is derived complete.
example (A : Type) [CommRing A] (M : D A) : derivedCompleteness A ⊥ M := by sorry
-- For I=A, only the zero object is complete.
example (A : Type) [CommRing A] (M : D A) : derivedCompleteness A ⊤ M ↔ IsZero M := by sorry
-- Z_p is derived p-complete, while Q_p is not: RHom_Zp(Q_p,Q_p) has a nonzero identity class.
example (p : ℕ) [Fact p.Prime] :
    derivedCompleteness ℤ (pIdeal ℤ p) (mod0 ℤ (ModuleCat.of ℤ (PadicInt p))) ∧
    ¬ derivedCompleteness ℤ (pIdeal ℤ p) (mod0 ℤ (ModuleCat.of ℤ (Padic p))) := by sorry


/-- For finite-generated I⊂A construct Λ_I:D(A)→D_I-comp(A) left adjoint to the inclusion, with natural unit η_M:M→Λ_I M. For I=(f_i), put C_I=⊗_i[A→A[1/f_i]] in cochain degrees 0,1 and Λ_I M=RHom_A(C_I,M). This is exact, independent of generators, idempotent and preserves colimits formed in the complete category. Derived Nakayama: if M is complete and M⊗^L_A A/I=0 then M=0. -/
def derivedCompletion (A : Type) [CommRing A] (I : Ideal A) (M : D A) : D A := by sorry
-- A chosen natural unit, rather than the vacuous existence of a zero map.
/-- η_M is the universal map from M to an I-complete object. -/
def completionUnit (A : Type) [CommRing A] (I : Ideal A) (M : D A) :
    M ⟶ derivedCompletion A I M := by sorry
/-- Map_(D_I-comp)(Λ_I M,N)≃Map_D(A)(M,N), naturally for complete N. -/
theorem completionAdjunction (A : Type) [CommRing A] (I : Ideal A) (hI : I.FG)
    (M N : D A) (hN : derivedCompleteness A I N) :
    Function.Bijective (fun f : derivedCompletion A I M ⟶ N => completionUnit A I M ≫ f) := by sorry
/-- Λ_IΛ_I M≃Λ_I M, compatibly with both units. -/
theorem completionIdempotent (A : Type) [CommRing A] (I : Ideal A) (hI : I.FG)
    (M : D A) : IsIso (completionUnit A I (derivedCompletion A I M)) := by sorry
/-- A complete M with M⊗^L_A A/I=0 vanishes. -/
theorem completeNakayama (A : Type) [CommRing A] (I : Ideal A) (hI : I.FG)
    (M : D A) (hM : derivedCompleteness A I M) (hred : IsZero (reduction A I M)) :
    IsZero M := by sorry
/-- For a finitely generated ideal I, the reflected object Λ_I M is derived I-complete. -/
theorem completionComplete (A : Type) [CommRing A] (I : Ideal A) (hI : I.FG)
    (M : D A) : derivedCompleteness A I (derivedCompletion A I M) := by sorry
-- Λ_(p)Z≃Z_p in degree 0.
example (p : ℕ) [Fact p.Prime] : Nonempty
    (derivedCompletion ℤ (pIdeal ℤ p) (unit ℤ) ≅ mod0 ℤ (ModuleCat.of ℤ (PadicInt p))) := by sorry
-- Λ_(p)Z[1/p]=0, although Z[1/p] is nonzero.
example (A : Type) [CommRing A] (p : A) : IsZero
    (derivedCompletion A (Ideal.span {p}) (mod0 A (ModuleCat.of A (Localization.Away p)))) := by sorry
-- Λ_(p)(Z/p^m)≃Z/p^m for m≥1.
example (A : Type) [CommRing A] (p : A) (m : ℕ) (hm : 0 < m) :
    IsIso (completionUnit A (Ideal.span {p})
      (mod0 A (ModuleCat.of A (A ⧸ Ideal.span {p^m})))) := by sorry


/-- For finite I⊂A, an object M∈D(A) is I-completely flat when M⊗^L_A A/I is a flat A/I-module in degree zero, equivalently M⊗^L_A N is discrete for every I-power-torsion A-module N. It is I-completely faithfully flat if that reduction is faithfully flat. The predicate itself does not require M to be complete. Define finite I-complete Tor-amplitude [a,b] using the derived reduction and all discrete A/I-modules. -/
def completeFlatness (A : Type) [CommRing A] (I : Ideal A) (M : D A) : Prop :=
  (∀ n : ℤ, n ≠ 0 → IsZero (H (A ⧸ I) n (reduction A I M))) ∧
    Module.Flat (A ⧸ I) (H (A ⧸ I) 0 (reduction A I M))
/-- Complete flatness is equivalent to flat discrete derived reduction. -/
theorem completeFlatReduction (A : Type) [CommRing A] (I : Ideal A) (M : D A) :
    completeFlatness A I M ↔ amplitude (A ⧸ I) (reduction A I M) 0 0 := by sorry
/-- The derived I-completion of a flat A-module is I-completely flat. -/
theorem completeFlatCompletion (A : Type) [CommRing A] (I : Ideal A) (hI : I.FG)
    (M : Type) [AddCommGroup M] [Module A M] [Module.Flat A M] :
    completeFlatness A I (derivedCompletion A I (mod0 A (ModuleCat.of A M))) := by sorry
/-- Amplitude [a,b] means every tensor with a discrete A/I-module has cohomology in [a,b]. -/
theorem completeTorAmplitude (A : Type) [CommRing A] (I : Ideal A) (M : D A) (a b : ℤ)
    : amplitude (A ⧸ I) (reduction A I M) a b ↔
    ∀ (N : ModuleCat (A ⧸ I)) (n : ℤ), n < a ∨ b < n →
      IsZero (H (A ⧸ I) n
        (tensor (A ⧸ I) (reduction A I M) (mod0 (A ⧸ I) N))) := by sorry
-- For a prime p, Z as a Z-module is p-completely flat but is not derived p-complete.
example (p : ℕ) [Fact p.Prime] :
    completeFlatness ℤ (pIdeal ℤ p) (unit ℤ) ∧
    ¬ derivedCompleteness ℤ (pIdeal ℤ p) (unit ℤ) := by sorry
-- Z_p is p-completely faithfully flat over Z.
example (p : ℕ) [Fact p.Prime] :
    completeFlatness ℤ (pIdeal ℤ p) (mod0 ℤ (ModuleCat.of ℤ (PadicInt p))) ∧
    Module.FaithfullyFlat (ℤ ⧸ pIdeal ℤ p)
      (H (ℤ ⧸ pIdeal ℤ p) 0
        (reduction ℤ (pIdeal ℤ p) (mod0 ℤ (ModuleCat.of ℤ (PadicInt p))))) := by sorry
-- F_p is not p-completely flat over Z: F_p⊗^L_Z F_p has a nonzero degree −1 term. The analogous Z_p calculation has the same obstruction.
example (p : ℕ) [Fact p.Prime] :
    ¬ completeFlatness ℤ (pIdeal ℤ p) (mod0 ℤ (ModuleCat.of ℤ (ZMod p))) := by sorry


-- BMS2 Lemma 4.6 gives ordinary amplitude, not bounded torsion at finite amplitude.
/-- Assume A has bounded p-power torsion. If M is derived p-complete and has p-complete Tor-amplitude [a,b], then M has ordinary cohomological amplitude [a,b]. Bounded p-power torsion in every cohomology group does not follow from this finite amplitude assumption. The bounded-torsion conclusion below is restricted to the p-completely flat case [a,b]=[0,0]. In particular derived p-complete, p-completely flat M is an ordinary p-adically complete bounded-torsion module with M/p^n flat over A/p^n and M[p^n]≃M⊗_A A[p^n]. Conversely an ordinary p-complete bounded-torsion module satisfying these flatness/torsion conditions is p-completely flat. -/
theorem boundedTorsionCriterion (p : ℕ) [Fact p.Prime] (A : Type) [CommRing A]
    (hA : boundedTorsion p A) (M : D A) (hM : derivedCompleteness A (pIdeal A p) M)
    (a b : ℤ) (hamp : amplitude (A ⧸ pIdeal A p) (reduction A (pIdeal A p) M) a b) :
    ∀ n : ℤ, n < a ∨ b < n → IsZero (H A n M) := by sorry


/-- Let A be Noetherian, π∈A, and suppose A and an A-algebra B are π-torsion-free and classically π-adically complete. If A/π→B/π is flat, then A→B is flat; if it is faithfully flat, then A→B is faithfully flat. This is the Noetherian algebra criterion of Bhatt Proposition 5.1, not a general identification of complete flatness and ordinary flatness. -/
theorem ordinaryFlatnessFromCompleteFlatness (A B : Type) [CommRing A] [CommRing B]
    [Algebra A B] [IsNoetherianRing A] (π : A)
    (hπA : IsSMulRegular A π) (hπB : IsSMulRegular B (algebraMap A B π))
    (hA : IsAdicComplete (Ideal.span {π}) A)
    (hB : IsAdicComplete (Ideal.span {π}) B)
    (hflat : completeFlatness A (Ideal.span {π}) (mod0 A (ModuleCat.of A B))) :
    Module.Flat A B := by sorry


/-- A quotient by multiplication by g of a discrete derived f-complete module remains derived f-complete. This ordinary derived-category statement does not assert separatedness; the stronger classical comparison in README.md additionally requires that f act injectively on N/gN. -/
theorem quotientCompleteness (A : Type) [CommRing A] (N : ModuleCat A) (f g : A)
    (h : derivedCompleteness A (Ideal.span {f}) (mod0 A N)) :
    derivedCompleteness A (Ideal.span {f})
      (mod0 A (ModuleCat.of A (N ⧸ LinearMap.range (g • (LinearMap.id : N →ₗ[A] N))))) := by sorry


-- Object and relative-map conditions are separate. Reduction is derived over
-- the ordinary quotient ring; amplitude is tested against every discrete coefficient.
/-- The absolute quasisyntomic object condition, separately from complete-flat relative maps. -/
private def qsynRing (A : Type) [CommRing A] (p : ℕ) : Prop :=
  IsAdicComplete (pIdeal A p) A ∧ boundedTorsion p A ∧
    amplitude (A ⧸ pIdeal A p) (reduction A (pIdeal A p) (cotangentComplex ℤ A)) (-1) 0
/-- Fix a prime p. A quasisyntomic ring A is an ordinary p-adically complete ring with bounded p-power torsion and L_(A/Z)⊗^L_A A/p of Tor-amplitude [−1,0]. A quasisyntomic map A→B between such objects is p-completely flat and L_(B/A)⊗^L_B B/p has Tor-amplitude [−1,0]; a cover is p-completely faithfully flat. The mod-p ring in this formula is the ordinary A/p while the module tensor is derived. Object and morphism conditions are distinct. -/
def quasisyntomicCondition (A B : Type) [CommRing A] [CommRing B] [Algebra A B]
    (p : ℕ) [Fact p.Prime] : Prop :=
  qsynRing A p ∧ qsynRing B p ∧ completeFlatness A (pIdeal A p) (mod0 A (ModuleCat.of A B)) ∧
    amplitude (B ⧸ pIdeal B p) (reduction B (pIdeal B p) (cotangentComplex A B)) (-1) 0
/-- Composites and p-completed base changes of quasisyntomic maps are quasisyntomic, with bounded-torsion hypotheses inherited from the objects. -/
theorem quasisyntomicComp (A B C : Type) [CommRing A] [CommRing B] [CommRing C]
    [Algebra A B] [Algebra B C] [Algebra A C] [IsScalarTower A B C] (p : ℕ) [Fact p.Prime]
    (hAB : quasisyntomicCondition A B p) (hBC : quasisyntomicCondition B C p) :
    quasisyntomicCondition A C p := by sorry
-- Z_p is quasisyntomic.
example (p : ℕ) [Fact p.Prime] : qsynRing (PadicInt p) p := by sorry
-- F_p is a quasisyntomic object, but Z→F_p fails complete flatness.
example (p : ℕ) [Fact p.Prime] : qsynRing (ZMod p) p ∧
    ¬ completeFlatness ℤ (pIdeal ℤ p) (mod0 ℤ (ModuleCat.of ℤ (ZMod p))) := by sorry
-- The canonical Z_p→F_p quotient has Tor₁=F_p, so also fails complete flatness.
example (p : ℕ) [Fact p.Prime] :
    letI : Algebra (PadicInt p) (ZMod p) :=
      (PadicInt.toZMod : PadicInt p →+* ZMod p).toAlgebra
    ¬ completeFlatness (PadicInt p) (pIdeal (PadicInt p) p)
      (mod0 (PadicInt p) (ModuleCat.of (PadicInt p) (ZMod p))) := by sorry
-- A p-completed smooth finitely presented algebra over a bounded-torsion quasisyntomic base gives a quasisyntomic map.
example (p : ℕ) [Fact p.Prime] (A B : Type) [CommRing A] [CommRing B] [Algebra A B]
    [Algebra.Smooth A B] (hA : qsynRing A p)
    (hB : IsAdicComplete (pIdeal B p) B) (ht : boundedTorsion p B) :
    quasisyntomicCondition A B p := by sorry

end DerivedDeRham

/-! ## Layer 2: Ordinary and derived de Rham cohomology -/

namespace DeRham
universe u
variable (A B : Type u) [CommRing A] [CommRing B] [Algebra A B]

-- Notation for existing carriers; these introduce no new mathematical objects.
/-- The existing exterior power of the Kähler differential module, with scalars restricted to A. -/
abbrev Forms (n : ℕ) := exteriorPower B n (KaehlerDifferential A B)
/-- The free A-module on coefficient and differential-generator tuples. -/
abbrev Symbols (n : ℕ) := (B × (Fin n → B)) →₀ A
/-- The basis symbol with the displayed coefficient and ordered tuple. -/
abbrev sym (n : ℕ) (c : B) (v : Fin n → B) : Symbols A B n :=
  Finsupp.single (c, v) 1
/-- The form c db₁∧…∧dbₙ in the existing exterior-power carrier. -/
abbrev elementary (n : ℕ) (c : B) (v : Fin n → B) : Forms A B n :=
  c • exteriorPower.ιMulti B n (fun i => KaehlerDifferential.D A B (v i))
/-- Multiplication in the existing graded exterior algebra, without factorial normalization. -/
abbrev wedge {m n : ℕ} (x : Forms A B m) (y : Forms A B n) : Forms A B (m+n) :=
  ⟨x.val * y.val, SetLike.mul_mem_graded x.property y.property⟩
/-- A coefficient viewed as a degree-zero form through the exterior-power equivalence. -/
abbrev zeroForm (b : B) : Forms A B 0 :=
  (exteriorPower.zeroEquiv B (KaehlerDifferential A B)).symm b

-- The six displayed relation families, as an explicit set in the free A-module.
-- Only additive and A-scalar closure in the coefficient is imposed.
/-- The six additive, base-scalar, Leibniz, base-constant and strict-alternation relation families. -/
def relationSet (n : ℕ) : Set (Symbols A B n) :=
  {x | (∃ c e v, x = sym A B n (c+e) v - sym A B n c v - sym A B n e v) ∨
    (∃ (a : A) (c : B) (v : Fin n → B), x = sym A B n (a • c) v - a • sym A B n c v) ∨
    (∃ c v i b e, x = sym A B n c (Function.update v i (b+e)) -
      sym A B n c (Function.update v i b) - sym A B n c (Function.update v i e)) ∨
    (∃ c v i b e, x = sym A B n c (Function.update v i (b*e)) -
      sym A B n (c*b) (Function.update v i e) -
      sym A B n (c*e) (Function.update v i b)) ∨
    (∃ (c : B) (v : Fin n → B) (i : Fin n) (a : A), x = sym A B n c (Function.update v i (algebraMap A B a))) ∨
    (∃ c v i j, i ≠ j ∧ v i = v j ∧ x = sym A B n c v)}

/-- Let Sₙ be the free A-module on pairs (c,v) with c∈B and v:{1,…,n}→B, written [c;v]. Define Rₙ⊂Sₙ as the A-span of six families: [c+e;v]−[c;v]−[e;v]; [ac;v]−a[c;v] for a∈A; slot additivity [c;v(i↦x+y)]−[c;v(i↦x)]−[c;v(i↦y)]; slot Leibniz [c;v(i↦xy)]−[cx;v(i↦y)]−[cy;v(i↦x)]; [c;v(i↦a)] for a∈A; and [c;v] when v_i=v_j with i≠j. There is no B-linearity requirement in the coefficient before applying d. -/
def symbolRelations (n : ℕ) : Submodule A (Symbols A B n) := by sorry
/-- Rₙ is exactly the A-span of the six explicitly displayed relation families. -/
theorem symbolRelations_eq_span (n : ℕ) : symbolRelations A B n = Submodule.span A (relationSet A B n) := by sorry
/-- Coefficient additivity belongs to Rₙ. -/
theorem symbolRelations_coeff_add (n : ℕ) (c e : B) (v : Fin n → B) : sym A B n (c+e) v - sym A B n c v - sym A B n e v ∈ symbolRelations A B n := by sorry
/-- The slot Leibniz relation belongs to Rₙ for every slot. -/
theorem symbolRelations_slot_mul (n : ℕ) (c x y : B) (v : Fin n → B) (i : Fin n) : sym A B n c (Function.update v i (x*y)) - sym A B n (c*x) (Function.update v i y) - sym A B n (c*y) (Function.update v i x) ∈ symbolRelations A B n := by sorry
-- The degree-zero relation [0;()] belongs to R₀, whereas the unit does not.
example  : sym A B 0 0 Fin.elim0 ∈ symbolRelations A B 0 := by sorry
example : sym ℤ ℤ 0 1 Fin.elim0 ∉ symbolRelations ℤ ℤ 0 := by sorry
-- A differential slot filled with an element from A is zero in the quotient.
example (c : B) (a : A) : sym A B 1 c (fun _ => algebraMap A B a) ∈ symbolRelations A B 1 := by sorry
-- The nonzero polynomial differential dX excludes the full relation submodule.
example : sym ℤ (Polynomial ℤ) 1 1 (fun _ => Polynomial.X) ∉
    symbolRelations ℤ (Polynomial ℤ) 1 := by sorry
-- Over F₂, the diagonal degree-two symbol is itself a relation, not merely twice that symbol.
example (x : Polynomial (ZMod 2)) : sym (ZMod 2) (Polynomial (ZMod 2)) 2 1 (fun _ => x) ∈ symbolRelations (ZMod 2) (Polynomial (ZMod 2)) 2 := by sorry

/-- Define qₙ:Sₙ→Ωⁿ as the A-linear map [c;v]↦c·Dv₁∧…∧Dvₙ. In degree zero it sends [c;()] to c under Ω⁰≃B. -/
def symbolMap (n : ℕ) : Symbols A B n →ₗ[A] Forms A B n := by sorry
/-- For a∈A, qₙ(a s)=a qₙ(s). -/
theorem symbolMap_smul (n : ℕ) (a : A) (s : Symbols A B n) : symbolMap A B n (a • s) = a • symbolMap A B n s := by sorry
/-- qₙ([c;v])=c Dv₁∧…∧Dvₙ. -/
theorem symbolMap_single (n : ℕ) (c : B) (v : Fin n → B) : symbolMap A B n (sym A B n c v) = elementary A B n c v := by sorry
/-- qₙ is additive. -/
theorem symbolMap_add (n : ℕ) (x y : Symbols A B n) : symbolMap A B n (x+y) = symbolMap A B n x + symbolMap A B n y := by sorry
-- Evaluation in weight zero agrees with the existing zeroEquiv.
example (c : B) : (exteriorPower.zeroEquiv B (KaehlerDifferential A B)) (symbolMap A B 0 (sym A B 0 c Fin.elim0)) = c := by sorry
-- Evaluation in weight one agrees with c times the universal derivation.
example (c x : B) : (exteriorPower.oneEquiv B (KaehlerDifferential A B)) (symbolMap A B 1 (sym A B 1 c (fun _ => x))) = c • KaehlerDifferential.D A B x := by sorry
-- The image of [c;x,x] is zero in every characteristic.
example (c x : B) : symbolMap A B 2 (sym A B 2 c (fun _ => x)) = 0 := by sorry

/-- The map qₙ is surjective for every n≥0; equivalently the forms c Dv₁∧…∧Dvₙ span Ωⁿ as an A-module. -/
theorem symbolMap_surjective (n : ℕ) : Function.Surjective (symbolMap A B n) := by sorry

/-- For every n, ker(qₙ)=Rₙ. Thus Sₙ/Rₙ is canonically Ωⁿ as an A-module, including n=0. -/
theorem symbolRelations_ker (n : ℕ) : LinearMap.ker (symbolMap A B n) = symbolRelations A B n := by sorry

/-- Define δₙ:Sₙ→Ωⁿ⁺¹ as the A-linear map [c;v]↦Dc∧Dv₁∧…∧Dvₙ. This uses the coefficient as the first slot, with positive sign. -/
def freeDifferential (n : ℕ) : Symbols A B n →ₗ[A] Forms A B (n+1) := by sorry
/-- The free differential is A-linear on free-module coefficients. -/
theorem freeDifferential_smul (n : ℕ) (a : A) (s : Symbols A B n) : freeDifferential A B n (a • s) = a • freeDifferential A B n s := by sorry
/-- The free differential preserves sums. -/
theorem freeDifferential_add (n : ℕ) (s t : Symbols A B n) : freeDifferential A B n (s+t) = freeDifferential A B n s + freeDifferential A B n t := by sorry
/-- δₙ([c;v])=Dc∧Dv₁∧…∧Dvₙ. -/
theorem freeDifferential_single (n : ℕ) (c : B) (v : Fin n → B) : freeDifferential A B n (sym A B n c v) = exteriorPower.ιMulti B (n+1) (Fin.cons (KaehlerDifferential.D A B c) (fun i => KaehlerDifferential.D A B (v i))) := by sorry
-- Symbols with coefficient one have zero differential.
example (n : ℕ) (v : Fin n → B) : freeDifferential A B n (sym A B n 1 v) = 0 := by sorry
-- In weight zero the free differential agrees with D after oneEquiv.
example (c : B) : (exteriorPower.oneEquiv B (KaehlerDifferential A B)) (freeDifferential A B 0 (sym A B 0 c Fin.elim0)) = KaehlerDifferential.D A B c := by sorry
-- δ₁([x;x])=Dx∧Dx=0.
example (x : B) : freeDifferential A B 1 (sym A B 1 x (fun _ => x)) = 0 := by sorry
-- The positive leading slot gives the nonzero oriented two-form dX∧dY.
example :
    let B := MvPolynomial (Fin 2) ℤ
    let x : B := MvPolynomial.X 0
    let y : B := MvPolynomial.X 1
    let dx := KaehlerDifferential.D ℤ B x
    let dy := KaehlerDifferential.D ℤ B y
    freeDifferential ℤ B 1 (sym ℤ B 1 x (fun _ => y)) =
      exteriorPower.ιMulti B 2 (Fin.cons dx (fun _ => dy)) ∧
      exteriorPower.ιMulti B 2 (Fin.cons dx (fun _ => dy)) ≠ 0 := by sorry

/-- For every n, Rₙ⊂ker(δₙ), so δₙ depends only on the represented ordinary form. -/
theorem freeDifferential_relations (n : ℕ) : symbolRelations A B n ≤ LinearMap.ker (freeDifferential A B n) := by sorry

/-- For every n≥0 define dₙ:Ωⁿ→Ωⁿ⁺¹, A-linear, as the descent of δₙ along qₙ. It is characterised by dₙ(c Dv₁∧…∧Dvₙ)=Dc∧Dv₁∧…∧Dvₙ. The scalar ring is A; in general it is not B-linear. -/
def d (n : ℕ) : Forms A B n →ₗ[A] Forms A B (n+1) := by sorry
-- In Z[X,Y], d(X dY)=dX∧dY and this two-form is nonzero. This detects a zero positive-degree differential and fixes the leading-slot sign.
example :
    let B := MvPolynomial (Fin 2) ℤ
    let x : B := MvPolynomial.X 0
    let y : B := MvPolynomial.X 1
    let dx := KaehlerDifferential.D ℤ B x
    let dy := KaehlerDifferential.D ℤ B y
    d ℤ B 1 (elementary ℤ B 1 x (fun _ => y)) =
      exteriorPower.ιMulti B 2 (Fin.cons dx (fun _ => dy)) ∧
      exteriorPower.ιMulti B 2 (Fin.cons dx (fun _ => dy)) ≠ 0 := by sorry
/-- dₙ(α+β)=dₙα+dₙβ. -/
theorem d_add (n : ℕ) (x y : Forms A B n) : d A B n (x+y) = d A B n x + d A B n y := by sorry
/-- For a∈A, dₙ(aα)=a dₙα. -/
theorem d_base_smul (n : ℕ) (a : A) (x : Forms A B n) : d A B n (a • x) = a • d A B n x := by sorry
/-- Transport d₀ along Ω⁰≃B and Ω¹≃Ω to recover the pinned universal derivation. -/
theorem d_zero_degree (b : B) : (exteriorPower.oneEquiv B (KaehlerDifferential A B)) (d A B 0 (zeroForm A B b)) = KaehlerDifferential.D A B b := by sorry
-- The differential of the image of a base-ring constant is zero.
example (a : A) : d A B 0 (zeroForm A B (algebraMap A B a)) = 0 := by sorry
-- The differential of X in Z[X] over Z is nonzero, so the zero operator fails.
example  : d ℤ (Polynomial ℤ) 0 (zeroForm ℤ (Polynomial ℤ) Polynomial.X) ≠ 0 := by sorry
-- The differential of X in F₂[X] over F₂ is still nonzero.
example  : d (ZMod 2) (Polynomial (ZMod 2)) 0 (zeroForm (ZMod 2) (Polynomial (ZMod 2)) Polynomial.X) ≠ 0 := by sorry

/-- dₙ(c Dv₁∧…∧Dvₙ)=Dc∧Dv₁∧…∧Dvₙ, for every n including zero. -/
theorem d_elementary (n : ℕ) (c : B) (v : Fin n → B) : d A B n (elementary A B n c v) = exteriorPower.ιMulti B (n+1) (Fin.cons (KaehlerDifferential.D A B c) (fun i => KaehlerDifferential.D A B (v i))) := by sorry

/-- An A-linear map Ωⁿ→Ωⁿ⁺¹ satisfying the displayed elementary-form rule equals dₙ. -/
theorem d_unique (n : ℕ) (f : Forms A B n →ₗ[A] Forms A B (n+1)) (h : ∀ c v, f (elementary A B n c v) = exteriorPower.ιMulti B (n+1) (Fin.cons (KaehlerDifferential.D A B c) (fun i => KaehlerDifferential.D A B (v i)))) : f = d A B n := by sorry

/-- For every n, dₙ₊₁∘dₙ=0 as an A-linear map Ωⁿ→Ωⁿ⁺². -/
theorem d_squared (n : ℕ) : (d A B (n+1)).comp (d A B n) = 0 := by sorry

/-- For α∈Ωᵐ and β∈Ωⁿ, d(α∧β)=dα∧β+(−1)ᵐα∧dβ. The product is the existing graded multiplication of the exterior algebra. -/
theorem d_leibniz (m n : ℕ) (x : Forms A B m) (y : Forms A B n) :
    (d A B (m+n) (wedge A B x y)).val =
      (d A B m x).val * y.val + (-1 : B)^m • (x.val * (d A B n y).val) := by sorry

/-- Define Ω•_(B/A) as the nonnegative cochain complex of A-modules with degree n object Ωⁿ and differential dₙ. Its multiplication is the existing wedge product and satisfies the graded Leibniz identity. This is the ordinary complex, not a claim of a derived smooth comparison in characteristic zero. -/
def complex : CochainComplex (ModuleCat A) ℕ :=
  CochainComplex.of (fun n => ModuleCat.of A (Forms A B n))
    (fun n => ModuleCat.ofHom (d A B n)) (by intro n; sorry)
/-- The object in degree n is the existing module Ωⁿ, restricted to A. -/
theorem complex_X (n : ℕ) : (complex A B).X n = ModuleCat.of A (Forms A B n) := by sorry
/-- The adjacent differential of Ω• is dₙ. -/
theorem complex_d_apply (n : ℕ) (x : Forms A B n) : (complex A B).d n (n+1) x = d A B n x := by sorry
/-- Every nonadjacent differential is zero. -/
theorem complex_d_nonadjacent (i j : ℕ) (h : i+1 ≠ j) : (complex A B).d i j = 0 := by sorry
-- The first arrow agrees with the universal derivation after the existing degree-one equivalence.
example (b : B) : (exteriorPower.oneEquiv B (KaehlerDifferential A B)) ((complex A B).d 0 1 (zeroForm A B b)) = KaehlerDifferential.D A B b := by sorry
-- The first two arrows compose to zero on each b.
example (b : B) : (complex A B).d 1 2 ((complex A B).d 0 1 (zeroForm A B b)) = 0 := by sorry
-- Over A→A the first differential is zero.
example  : (complex A A).d 0 1 = 0 := by sorry

variable {A B}
variable {C E : Type u} [CommRing C] [CommRing E] [Algebra A C] [Algebra A E]

/-- For an A-algebra homomorphism f:B→C, extend the pinned KaehlerDifferential.mapSemilinear to f-semilinear maps f*ₙ:Ωⁿ_(B/A)→Ωⁿ_(C/A). On elementary forms, c Dv₁∧…∧Dvₙ maps to f(c)D(fv₁)∧…∧D(fvₙ). These are A-linear as well, but in general are not B-linear for an unrelated B-action on C. -/
def pullback (f : B →ₐ[A] C) (n : ℕ) : Forms A B n →ₛₗ[f.toRingHom] Forms A C n := by sorry
/-- Pullback preserves sums of forms. -/
theorem pullback_add (f : B →ₐ[A] C) (n : ℕ) (x y : Forms A B n) : pullback f n (x+y) = pullback f n x + pullback f n y := by sorry
/-- Pullback is f-semilinear in B-scalars. -/
theorem pullback_smul (f : B →ₐ[A] C) (n : ℕ) (b : B) (x : Forms A B n) : pullback f n (b • x) = f b • pullback f n x := by sorry
/-- Pullback is linear in A-scalars. -/
theorem pullback_base_smul (f : B →ₐ[A] C) (n : ℕ) (a : A) (x : Forms A B n) : pullback f n (a • x) = a • pullback f n x := by sorry
-- Degree-zero pullback agrees with f under the existing zero equivalence.
example (f : B →ₐ[A] C) (b : B) : pullback f 0 (zeroForm A B b) = zeroForm A C (f b) := by sorry
-- Degree-one pullback agrees with the pinned Kaehler mapSemilinear.
example (f : B →ₐ[A] C) (x : Forms A B 1) :
    letI : Algebra B C := f.toRingHom.toAlgebra
    letI : IsScalarTower A B C := IsScalarTower.of_algebraMap_eq' f.comp_algebraMap.symm
    (exteriorPower.oneEquiv C (KaehlerDifferential A C)) (pullback f 1 x) =
      KaehlerDifferential.map A A B C
        ((exteriorPower.oneEquiv B (KaehlerDifferential A B)) x) := by sorry
-- The identity fixes an arbitrary degree-two form.
example (x : Forms A B 2) : pullback (AlgHom.id A B) 2 x = x := by sorry

/-- For every A-algebra map f:B→C and n, f*ₙ₊₁(dₙω)=dₙ(f*ₙω). -/
theorem pullback_d (f : B →ₐ[A] C) (n : ℕ) (x : Forms A B n) : pullback f (n+1) (d A B n x) = d A C n (pullback f n x) := by sorry

/-- For every A-algebra homomorphism f, f*(α∧β)=f*α∧f*β, with the existing exterior products. -/
theorem pullback_wedge (f : B →ₐ[A] C) (m n : ℕ) (x : Forms A B m) (y : Forms A B n) : pullback f (m+n) (wedge A B x y) = wedge A C (pullback f m x) (pullback f n y) := by sorry

/-- For every n, pullback along id_B is the identity on Ωⁿ. -/
theorem pullback_id (n : ℕ) (x : Forms A B n) : pullback (AlgHom.id A B) n x = x := by sorry

/-- For f:B→C and g:C→E of A-algebras, pullback along g∘f equals g*∘f* in every degree. -/
theorem pullback_comp (f : B →ₐ[A] C) (g : C →ₐ[A] E) (n : ℕ) (x : Forms A B n) : pullback (g.comp f) n x = pullback g n (pullback f n x) := by sorry

/-- An A-algebra homomorphism f:B→C induces a morphism Ω•_(B/A)→Ω•_(C/A) in CochainComplex(ModuleCat A), whose degree-n map is f*ₙ. These maps preserve identities, composition and wedge multiplication. -/
def complexMap (f : B →ₐ[A] C) : complex A B ⟶ complex A C := by sorry
/-- The degree-n component is pullback f n. -/
theorem complexMap_apply (f : B →ₐ[A] C) (n : ℕ) (x : Forms A B n) : (complexMap f).f n x = pullback f n x := by sorry
/-- The complex map of id is the identity. -/
theorem complexMap_id : complexMap (AlgHom.id A B) = 𝟙 (complex A B) := by sorry
/-- The complex map of g∘f is the categorical composite of the two complex maps. -/
theorem complexMap_comp (f : B →ₐ[A] C) (g : C →ₐ[A] E) : complexMap (g.comp f) = complexMap f ≫ complexMap g := by sorry
-- In degree zero, the complex map takes b to f(b).
example (f : B →ₐ[A] C) (b : B) : (complexMap f).f 0 (zeroForm A B b) = zeroForm A C (f b) := by sorry
-- The identity map of B induces the identity in degree one.
example (x : Forms A B 1) : (complexMap (AlgHom.id A B)).f 1 x = x := by sorry
-- The degree-one image of db is d(fb).
example (f : B →ₐ[A] C) (b : B) : (complexMap f).f 1 (d A B 0 (zeroForm A B b)) = d A C 0 (zeroForm A C (f b)) := by sorry

/-- Pullback sends c Dv₁∧…∧Dvₙ to f(c) D(fv₁)∧…∧D(fvₙ). -/
theorem pullback_elementary (f : B →ₐ[A] C) (n : ℕ) (c : B) (v : Fin n → B) : pullback f n (elementary A B n c v) = elementary A C n (f c) (fun i => f (v i)) := by sorry

end DeRham

namespace DerivedDeRham

-- Forget the coherent algebra but retain its canonical augmented filtration.
/-- For a map of animated commutative rings A→B, define dR_(B/A) by the sifted-colimit extension of the polynomial ordinary de Rham functor: for a free resolution P•→B use |Ω•_(P•/A)| with direct sums along antidiagonals. This is a coherent E∞ A-algebra with a decreasing multiplicative Hodge filtration, natural in the base square and independent of a free resolution. No derived Hodge completeness is imposed; its completion is a separate reflection. The construction is not the ordinary smooth de Rham complex over every base. -/
def ofPolynomialResolution (A B : Type) [CommRing A] [CommRing B] [Algebra A B] :
    FilteredModel A := by sorry
/-- A morphism of A-algebras induces a map of the coherent Hodge-filtered derived de Rham objects, with identity and composition coherences. -/
def map (A B C : Type) [CommRing A] [CommRing B] [CommRing C]
    [Algebra A B] [Algebra A C] (f : B →ₐ[A] C) :
    (ofPolynomialResolution A B).filtration ⟶ (ofPolynomialResolution A C).filtration := by sorry
-- For A→A, dR_(A/A) is A concentrated in degree zero.
example (A : Type) [CommRing A] : Nonempty
    ((ofPolynomialResolution A A).underlying ≅ unit A) := by sorry
-- For Q→Q[t,t⁻¹], uncompleted dR is Q, whereas ordinary degree-one de Rham cohomology is Q·dt/t. The unrestricted uncompleted smooth comparison fails.
example : Nonempty ((ofPolynomialResolution ℚ (LaurentPolynomial ℚ)).underlying ≅ unit ℚ) := by sorry



-- The target is the actual tensor-product algebra, rather than an unrelated B′.
/-- The degree-n module part of ordinary base change: C⊗_A Ωⁿ_(B/A) agrees with Ωⁿ_(C⊗_A B/C). README.md additionally specifies differential compatibility and the polynomial Künneth equivalence; this signature only records the degreewise linear equivalence. -/
theorem ordinaryBaseChangeKunneth (A B C : Type) [CommRing A] [CommRing B] [CommRing C]
    [Algebra A B] [Algebra A C] (n : ℕ) : Nonempty
    ((C ⊗[A] DeRham.Forms A B n) ≃ₗ[C]
      DeRham.Forms C (C ⊗[A] B) n) := by sorry


-- Forgetful uniqueness only; graded-algebra existence is explicitly omitted.
/-- Two maps of the ordinary de Rham complex that agree on every elementary form agree. This is the uniqueness part of the graded differential-algebra universal property in README.md; this signature forgets the graded multiplication and does not assert existence of its map. -/
theorem ordinaryDeRhamUniversalProperty (A B : Type) [CommRing A] [CommRing B] [Algebra A B]
    (G : CochainComplex (ModuleCat A) ℕ) (f g : DeRham.complex A B ⟶ G)
    (h : ∀ n (c : B) (v : Fin n → B),
      f.f n (DeRham.elementary A B n c v) =
      g.f n (DeRham.elementary A B n c v)) : f = g := by sorry


/-- Define dR^hc_(B/A)=Rlim_i(dR_(B/A)/Fil_H^i), with its complete decreasing filtration as the Layer 1 reflection of the Hodge-filtered object. The natural dR→dR^hc map is universal among maps to complete Hodge-filtered objects and leaves every graded piece L∧^i L_(B/A)[−i] unchanged. Hodge completion and p-completion are different operations. -/
def hodgeCompletedDerham (A B : Type) [CommRing A] [CommRing B] [Algebra A B] :
    FilteredModel A := by sorry
/-- The underlying ordinary derived-category map of the Hodge completion unit. The enhanced filtered-algebra unit is specified in README.md. -/
def hodgeCompletionMap (A B : Type) [CommRing A] [CommRing B] [Algebra A B] :
    (ofPolynomialResolution A B).underlying ⟶ (hodgeCompletedDerham A B).underlying := by sorry
-- dR^hc_(A/A)=A.
example (A : Type) [CommRing A] : Nonempty
    ((hodgeCompletedDerham A A).underlying ≅ unit A) := by sorry
-- For Q[t,t⁻¹]/Q, the completed complex is ordinary de Rham, with H¹=Q·dt/t, whereas uncompleted dR=Q.
example : Nonempty (H ℚ 1 (hodgeCompletedDerham ℚ (LaurentPolynomial ℚ)).underlying ≅
    ModuleCat.of ℚ ℚ) := by sorry
-- For F₂[t]/t² the completed closed sum of divided powers is absent from direct-sum realization.
example : ¬ Function.Surjective
    ((@DerivedCategory.homologyFunctor (ModuleCat.{0} (ZMod 2)) _ _
      (moduleDerived (ZMod 2)) 0).map
      (hodgeCompletionMap (ZMod 2) (Dual (ZMod 2)))) := by sorry


/-- For A→B define dR̂_(B/A)=Λ_(p)dR_(B/A)=Rlim_n(dR_(B/A)⊗^L_Z Z/p^n). Apply p-completion to every specified filtration term, and use completed tensor for its multiplication. A p-completed increasing conjugate diagram is not automatically exhaustive before a bounded-connectivity argument. For maps of p-completely flat bounded-torsion algebras the mod-p computation uses the ordinary reductions; general reductions are animated. -/
def pCompletedDerham (A B : Type) [CommRing A] [CommRing B] [Algebra A B] (p : ℕ) :
    FilteredModel A := by sorry
-- For A=A, dR̂_(A/A) is Λ_p A.
example (A : Type) [CommRing A] (p : ℕ) : Nonempty
    ((pCompletedDerham A A p).underlying ≅ derivedCompletion A (pIdeal A p) (unit A)) := by sorry
-- Inverting p annihilates p-completion but leaves the Hodge-completed identity value.
example (p : ℕ) [Fact p.Prime] :
    IsZero (pCompletedDerham (Padic p) (Padic p) p).underlying ∧
    Nonempty ((hodgeCompletedDerham (Padic p) (Padic p)).underlying ≅ unit (Padic p)) := by sorry
-- The regular quotient Z_p→F_p has extra completed PD torsion, so its value is not the base.
example (p : ℕ) [Fact p.Prime] :
    letI : Algebra (PadicInt p) (ZMod p) :=
      (PadicInt.toZMod : PadicInt p →+* ZMod p).toAlgebra
    ¬ Nonempty ((pCompletedDerham (PadicInt p) (ZMod p) p).underlying ≅ unit (PadicInt p)) := by sorry

end DerivedDeRham

/-! ## Layer 3: Conjugate filtration and Cartier theory -/

namespace DeRham
universe u
variable {A B : Type u} [CommRing A] [CommRing B] [Algebra A B]
/-- Let p be prime and A→B a map of characteristic-p commutative rings. For every b∈B and ω∈Ωⁿ_(B/A), dₙ(bᵖω)=bᵖdₙω. Thus the ordinary differential is linear for the B-action through Frobenius, the algebraic input to the B^(1)-action. -/
theorem d_frobenius_smul (p : ℕ) [Fact p.Prime] [CharP A p] [CharP B p]
        (n : ℕ) (b : B) (x : Forms A B n) :
        d A B n (b^p • x) = b^p • d A B n x := by sorry

end DeRham

namespace DerivedDeRham

/-- For k=F_p and B=k[x,y]/(x²,xy,y²), L_(B/k) is unbounded in negative cohomological degrees. The polynomial-presentation complex [I/I²→B dx⊕B dy] computes only τ≥−1L; it cannot replace the full complex. The quotient has a flat Z/p² lift with the same equations and a compatible p-power Frobenius lift; derived Cartier then makes dR_(B/k) unbounded on the left. Classical crystalline cohomology, computed as sheaf cohomology in nonnegative degrees, cannot be equivalent to this object. -/
theorem nonregularQuotientHomology (p : ℕ) [Fact p.Prime] :
    ∀ d : ℤ, ∃ n : ℤ, n < d ∧
      ¬ IsZero (H (SquareZero2 (ZMod p)) n
        (cotangentComplex (ZMod p) (SquareZero2 (ZMod p)))) := by sorry


/-- For ordinary Q-algebras, the underlying direct-sum derived de Rham object is the base ring. This differs from Hodge completion; Bhatt, Corollary 2.5, p.5. -/
theorem rationalCollapse (A B : Type) [CommRing A] [CommRing B] [Algebra A B]
    [Algebra ℚ A] [Algebra ℚ B] [IsScalarTower ℚ A B] :
    Nonempty ((ofPolynomialResolution A B).underlying ≅ unit A) := by sorry

end DerivedDeRham

/-! ## Layer 4: Crystalline comparison maps and Witt animation -/

namespace DerivedDeRham
-- CR.2 supplies this particular crystalline value, with the canonical base PD structure.
-- This is its forgetful view, not a second construction of the crystalline site.
/-- The ordinary filtered view of the CrystallineCohomology value for the canonical PD base Z/pⁿ. -/
private def crystallineValue (p n : ℕ) (A B : Type) [CommRing A] [CommRing B]
    [Algebra A B] [Algebra (ZMod (p^n)) A] [Algebra (ZMod (p^n)) B]
    [IsScalarTower (ZMod (p^n)) A B] : FilteredModel A := by sorry


/-- For an ordinary map A→B of Z/p^n-algebras, n≥1, construct Comp_(B/A):dR_(B/A)→RΓ((B/A)_crys,O_crys) as a natural map of Hodge-filtered E∞ A-algebras. The crystalline site has nilpotent PD thickenings compatible with the canonical divided powers on p. On a surjective free resolution P•→B, map Ω•_(P•/A) into Ω•_(P•/A)⊗_(P•)D_(P•)(ker(P•→B)) and use the PD Poincaré comparison. The target is classical crystalline cohomology of B (of π₀B for the separately specified animated extension). -/
def crystallineComparisonMap (p n : ℕ) [Fact p.Prime] (hn : 0 < n)
    (A B : Type) [CommRing A] [CommRing B] [Algebra A B]
    [Algebra (ZMod (p^n)) A] [Algebra (ZMod (p^n)) B]
    [IsScalarTower (ZMod (p^n)) A B] :
    (ofPolynomialResolution A B).filtration ⟶ (crystallineValue p n A B).filtration := by sorry
/-- For a smooth map in the nilpotent-p range this is the PD Poincaré equivalence. -/
theorem crystallineComparisonSmooth (p n : ℕ) [Fact p.Prime] (hn : 0 < n)
    (A B : Type) [CommRing A] [CommRing B] [Algebra A B]
    [Algebra (ZMod (p^n)) A] [Algebra (ZMod (p^n)) B]
    [IsScalarTower (ZMod (p^n)) A B]
    [Module.Flat (ZMod (p^n)) A] [Module.Flat (ZMod (p^n)) B] [Algebra.Smooth A B] :
    IsIso (crystallineComparisonMap p n hn A B) := by sorry
-- For A→A over Z/p^n, Comp is the identity on A.
example (p : ℕ) [Fact p.Prime] :
    IsIso (crystallineComparisonMap p 1 (by omega) (ZMod (p^1)) (ZMod (p^1))) := by sorry
-- A smooth polynomial algebra over F_p gives the positive-dimensional comparison.
example (p : ℕ) [Fact p.Prime] :
    IsIso (crystallineComparisonMap p 1 (by omega)
      (ZMod (p^1)) (Polynomial (ZMod (p^1)))) := by sorry
-- For F_p→F_p[x,y]/(x,y)², the map exists but cannot be an equivalence: source cohomology is unbounded negatively and the classical target is coconnective.
example (p : ℕ) [Fact p.Prime] :
    ¬ IsIso (crystallineComparisonMap p 1 (by omega)
      (ZMod (p^1)) (SquareZero2 (ZMod (p^1)))) := by sorry

end DerivedDeRham

/-! ## Layer 5: Quasisyntomic descent, crystalline applications and geometric control -/

/- Enhanced site, cover and descent interfaces are specified in README.md. -/

/-! ## Layer 6: Logarithmic cotangent and de Rham theory -/

/- Animated prelog and coherent log-period interfaces are specified in README.md. -/

/-
The following enhanced constructions have no representative signature at the
imported APIs; their definitions, named laws and checks are in README.md:
conjugateFiltration, baseChangeKunneth, frobeniusTwist, polynomialCartier, conjugateGradedCartier, derivedDerivations, derivationsCotangentComparison, cotangentLocalizationColimits, derivedExteriorPowers, derivedSymmetricPowers, derivedDividedPowers, powerTriangleFiltration, lciAmplitude, absoluteCompleteIntersection, andreRegularity, fFiniteCotangent, pBasesDifferentials, squareZeroDeformations, koszulCompletionTower, ordinaryQuotientCompletion, animatedRingCompletion, completeFlatDescent, completelySmoothAlgebraization, filteredModules, filteredCompletion, reesDescription, completedFilteredTensor, beilinsonTStructure, beilinsonHeart, complexHeartExt, weakPostnikovTowers, completionExchanges, hodgeGradedPieces, formalOrdinaryDerham, smoothDeRhamComparison, deRhamTransitivity, deRhamSheaves, smoothCartier, conjugateSpectralSequence, regularQuotientDividedPowers, cartierExtensionObstruction, frobeniusLiftSplitting, singularHypersurfaceHodge, regularPdComparison, lciCrystallineComparison, pAdicCrystallineComparison, deRhamFrobenius, acrisDerivedDescription, fpOverZpTorsion, rationalHodgePeriodComparison, pdConjugateFiltration, qrspPdDerham, derivedDeRhamWitt, qrspWittControl, acrysStructure, regularFpCrystallineCech, quasisyntomicSite, quasiregularSemiperfectoidRings, elementarySemiperfectoidCovers, qrspRefinement, qrspUnfolding, completedCotangentDescent, filteredDeRhamDescent, uncompletedPDeRhamDescent, relativeTorAmplitude, properSmoothCohomologicalControl, completedBaseChangeCupProducts, projQuasisyntomicSite, formalEtaleRealization, freePrelogResolutions, logDerivedDerivations, gabberLogCotangent, logCotangentFunctoriality, homologicalLogFlatness, logDerivedDeRham, logDeRhamBaseChange, logCartier, logificationBoundaries, logSmoothCartierComparison, logCrystallineComparisonMap, correctedLogLciCondition, logLciCrystallineComparison, logQuasisyntomicSites, logPowerDeRhamDescent, logPointExample, semistableChartExample, logPeriodDlog, logQuasiregularSemiperfectoid, logCompatibleRootCovers.
-/

end
end TauCetiRoadmap.DerivedDeRhamCohomology
