(function () {
'use strict';
const offlineDocument='<!doctype html>\n'+document.documentElement.outerHTML;
const DATA=JSON.parse(document.getElementById('atlas-data').textContent);
const $=id=>document.getElementById(id);
const maps=new Map(DATA.roadmaps.map(r=>[r.id,r]));
const stages=new Map(DATA.stages.map(s=>[s.id,s]));
const groups=new Map(DATA.groups.map(g=>[g.id,g]));
const external=new Map((DATA.external||[]).map(x=>[x.id,x]));
const documents=new Map((DATA.documents||[]).map(d=>[d.id,d]));
const progress=new TauProgress(DATA,DATA.progress||{});
const routeDefaults={view:'all',id:null,selected:null,tab:'overview',outside:false,origin:'all',activity:'all'};
const PIN_KEY='tauceti-atlas-pins-v1';
let pins=new Set();
try { const saved=JSON.parse(localStorage.getItem(PIN_KEY)||'[]');if(Array.isArray(saved))pins=new Set(saved.filter(id=>maps.has(id))); } catch {}
let state={...routeDefaults},currentDoc=null,graphModel={nodes:[],edges:[]},toastTimer;
const stageChildren=new Map(),childRoadmaps=new Map();
for(const s of DATA.stages)if(s.parentStageId){if(!stageChildren.has(s.parentStageId))stageChildren.set(s.parentStageId,[]);stageChildren.get(s.parentStageId).push(s.id);}
for(const r of DATA.roadmaps)if(r.parentRoadmapId){if(!childRoadmaps.has(r.parentRoadmapId))childRoadmaps.set(r.parentRoadmapId,[]);childRoadmaps.get(r.parentRoadmapId).push(r.id);}
const mapSearch=new Map(DATA.roadmaps.map(r=>[r.id,(r.title+' '+r.id+' '+r.summary+' '+r.readme).toLowerCase()]));
const stageSearch=new Map(DATA.stages.map(s=>[s.id,(s.title+' '+s.key+' '+s.id+' '+s.description).toLowerCase()]));
const labels={planned:'Not started',in_progress:'In progress',complete:'Complete',unknown:'Not assessed'};
function el(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n;}
function btn(text,action,className=''){const n=el('button',className,text);n.type='button';n.addEventListener('click',action);return n;}
function clear(n){n.replaceChildren();return n;}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000);}
function shortTitle(s){return String(s||'').replace(/^Roadmap:\s*/i,'');}
function groupOf(r){return groups.get(r.group)||{label:r.group,color:'#8698a5'};}
function inCollection(r){return r&&(state.origin==='all'||(r.origin||'campaign')===state.origin);}
function permitted(r){if(!inCollection(r))return false;if(state.activity==='all')return true;if(state.activity==='pinned')return pins.has(r.id);const p=progress.roadmap(r.id);return (p[state.activity]||0)>0;}
function summarize(rs){return progress.aggregate(rs.flatMap(r=>progress.roadmapLeaves(r.id)));}
function revealRoadmap(id){const r=maps.get(id);navigate({view:'group',id:r.group,selected:id,tab:'overview',activity:'all',origin:inCollection(r)?state.origin:'all'});graph.focus(id);}
function togglePin(id){if(pins.has(id))pins.delete(id);else pins.add(id);try{localStorage.setItem(PIN_KEY,JSON.stringify([...pins]));}catch{toast('Pins are kept for this session; browser storage is unavailable');}renderPins();renderInspector();if(state.activity==='pinned')buildGraph();}
function renderPins(){const box=clear($('pinned-list'));if(!pins.size)return;box.append(el('div','pinned-heading','Pinned for your next visit'));for(const id of pins){const r=maps.get(id);const b=btn('☆ '+shortTitle(r.title),()=>revealRoadmap(id),'pin-item');b.title=r.title;box.append(b);}}
const statusMetrics=[['complete','Complete','Recorded or locally marked'],['active','In progress','Work under way'],['planned','Planned','Explicitly not started'],['unknown','Unassessed','No recorded layer status']];
function collectionName(){return state.origin==='tauceti'?'Tau Ceti repository':state.origin==='campaign'?'Number theory campaign':'Combined collections';}
function renderStats(){let rs=DATA.roadmaps.filter(inCollection),scope=collectionName();if(state.view==='group'){rs=rs.filter(r=>r.group===state.id);scope=groups.get(state.id).label;}else if(['roadmap','collection'].includes(state.view)){rs=state.view==='roadmap'?[maps.get(state.id)]:(childRoadmaps.get(state.id)||[]).map(id=>maps.get(id));scope=shortTitle(maps.get(state.id).title);}else if(state.view==='neighbors'){const r=maps.get(state.id),ids=new Set([r.id,...r.prerequisites,...r.consumers]);rs=DATA.roadmaps.filter(r=>ids.has(r.id));scope='Connections of '+shortTitle(r.title);}const p=summarize(rs);clear($('landscape-stats'));for(const [key,label,note]of statusMetrics){const b=btn('',()=>$('stats-dialog').showModal());b.dataset.status=key;b.title=`${scope}: ${note.toLowerCase()}. Open the progress breakdown`;b.append(el('strong','',p[key].toLocaleString()),el('span','',label+' layers'));$('landscape-stats').append(b);}
 $('stats-scope').textContent=`${scope} · ${rs.length} roadmaps · ${p.total.toLocaleString()} tracked leaf layers`;
 clear($('stats-summary'));for(const [key,label,note]of statusMetrics){const cell=el('div','metric '+key);cell.dataset.status=key;cell.append(el('strong','',p[key].toLocaleString()),el('span','',label),el('small','',note));$('stats-summary').append(cell);}
 const tc=rs.filter(r=>r.origin==='tauceti').length,campaign=rs.length-tc;$('stats-sources').textContent=`${tc} Tau Ceti roadmaps · ${campaign} campaign roadmaps · ${Object.keys(progress.export().stages).length} local layer updates`;
 const areas=clear($('area-progress'));for(const g of DATA.groups){const members=rs.filter(r=>r.group===g.id);if(!members.length)continue;const a=summarize(members),button=btn('',()=>{$('stats-dialog').close();navigate({view:'group',id:g.id,selected:null,activity:'all'});},'area-stat');button.dataset.group=g.id;const label=el('div','area-stat-label');label.append(el('span','area-name',g.label),el('span','area-count',`${a.complete} / ${a.total} complete`));const bar=el('div','area-bar');for(const [key]of statusMetrics){const segment=el('span',key);segment.style.width=(a.total?a[key]/a.total*100:0)+'%';bar.append(segment);}button.append(label,bar,el('span','area-stat-detail',`${members.length} roadmaps · ${a.active} active · ${a.planned} planned · ${a.unknown} unassessed`));areas.append(button);}
}
function color(value){return TauGraph.progressColor(value)||'#899ba4';}
function statString(p){return `${p.complete||0} / ${p.total||0} layers complete`;}
function routeHash(s){const q=new URLSearchParams();q.set('view',s.view);if(s.id)q.set('id',s.id);if(s.selected)q.set('selected',s.selected);if(s.tab!=='overview')q.set('tab',s.tab);if(s.outside)q.set('outside','1');if(s.origin!=='all')q.set('origin',s.origin);if(s.activity!=='all')q.set('activity',s.activity);return '#'+q.toString();}
function readRoute(){const q=new URLSearchParams(location.hash.slice(1));const next={...routeDefaults,view:q.get('view')||'all',id:q.get('id'),selected:q.get('selected'),tab:q.get('tab')||'overview',outside:q.get('outside')==='1',origin:q.get('origin')||'all',activity:q.get('activity')||'all'};if(!['subjects','all','group','roadmap','collection','neighbors'].includes(next.view))next.view='subjects';if(!['all','tauceti','campaign'].includes(next.origin))next.origin='all';if(!['all','active','complete','planned','unknown','pinned'].includes(next.activity))next.activity='all';if(next.id&&!maps.has(next.id)&&!groups.has(next.id))next.id=null;if(!next.id&&!['subjects','all'].includes(next.view))next.view='subjects';if(next.selected&&!maps.has(next.selected)&&!groups.has(next.selected)&&!stages.has(next.selected)&&!external.has(next.selected))next.selected=null;return next;}
function navigate(change,replace=false){document.body.classList.remove('catalogue-open');$('catalogue-button').setAttribute('aria-expanded','false');state={...state,...change};const hash=routeHash(state);if(location.hash!==hash){try{history[replace?'replaceState':'pushState'](null,'',hash);}catch{location.hash=hash;}}render();}
function select(id){state.selected=id;state.tab='overview';try{history.replaceState(null,'',routeHash(state));}catch{}renderInspector();graph.select(id);renderCatalogue();}
function openItem(id){if(groups.has(id)){navigate({view:'group',id,selected:null,tab:'overview'});return;}if(maps.has(id)){const r=maps.get(id);navigate({view:r.stages.length?'roadmap':'collection',id,selected:id,tab:'stages'});return;}if(stages.has(id))openStage(id);}
function openStage(id){const s=stages.get(id);if(!s){select(id);return;}navigate({view:'roadmap',id:s.owner,selected:id,tab:'overview'});graph.focus(id);}
const graph=new TauGraph($('graph'),{onSelect:n=>select(n.id),onOpen:n=>openItem(n.id),onGroupSelect:label=>{const g=DATA.groups.find(g=>g.label===label);if(g)navigate({view:'group',id:g.id,selected:null});}});
function roadmapNode(r){const p=progress.roadmap(r.id);return {id:r.id,label:shortTitle(r.title),type:'roadmap',group:groupOf(r).label,color:groupOf(r).color,subtitle:`${r.stages.length} stages · ${(r.origin||'campaign')==='tauceti'?'Tau Ceti':'Campaign'}`,progress:p.percent||0,progressLabel:p.total?Math.round(p.percent||0)+'% layers':'Not assessed'};}
function stageNode(s,type='stage'){const p=progress.stage(s.id);return {id:s.id,label:s.title||s.key,type,group:maps.has(s.owner)?groupOf(maps.get(s.owner)).label:'Dependencies',subtitle:s.key,progress:p.percent||0,progressLabel:labels[p.status]||'Not assessed',color:'#b67859'};}
function boundaryNode(id){if(stages.has(id)){const n=stageNode(stages.get(id),'external');n.subtitle=shortTitle(maps.get(stages.get(id).owner)?.title||stages.get(id).owner)+' · '+stages.get(id).key;return n;}const x=external.get(id);return{id,label:x?.title||id.replace(/^UPSTREAM:/,''),type:'external',group:'External suppliers',subtitle:'External prerequisite',progress:0,progressLabel:'Not assessed'};}
function buildGraph(){let nodes=[],edges=[];const roadmaps=DATA.roadmaps.filter(permitted);const title=$('view-title'),description=$('view-description'),eyebrow=$('view-eyebrow');clear($('view-actions'));
 if(state.view==='subjects'){
  for(const g of DATA.groups){const rs=roadmaps.filter(r=>r.group===g.id);if(!rs.length)continue;const p=summarize(rs);nodes.push({id:g.id,label:g.label,type:'group',group:g.label,color:g.color,subtitle:`${rs.length} roadmaps · click to explore`,progress:p.percent||0,progressLabel:Math.round(p.percent||0)+'% layers complete'});}
  title.textContent='Explore by subject';eyebrow.textContent='THE MATHEMATICAL LANDSCAPE';description.textContent='Click a subject for its scope. Open it to explore the roadmaps and their layers.';
 }else if(['all','group','collection','neighbors'].includes(state.view)){
  let rs=roadmaps;
  if(state.view==='group')rs=rs.filter(r=>r.group===state.id);
  if(state.view==='collection')rs=(childRoadmaps.get(state.id)||[]).map(id=>maps.get(id)).filter(Boolean);
  if(state.view==='neighbors'){const r=maps.get(state.id),ids=new Set([r.id,...r.prerequisites,...r.consumers]);rs=DATA.roadmaps.filter(x=>ids.has(x.id));}
  const core=new Set(rs.map(r=>r.id));if(state.outside&&state.view==='group'){for(const e of DATA.edges)if(core.has(e.source)||core.has(e.target)){const id=core.has(e.source)?e.target:e.source;if(!rs.some(r=>r.id===id)&&maps.has(id))rs.push(maps.get(id));}}
  nodes=rs.map(roadmapNode);const ids=new Set(nodes.map(n=>n.id));edges=DATA.edges.filter(e=>ids.has(e.source)&&ids.has(e.target));
  title.textContent=state.view==='all'?'An atlas of mathematics':state.view==='group'?groups.get(state.id).label:state.view==='collection'?shortTitle(maps.get(state.id).title):'Connections: '+shortTitle(maps.get(state.id).title);
  eyebrow.textContent=state.view==='all'?'THE COMPLETE MAP':state.view==='neighbors'?'PREREQUISITES AND CONSUMERS':'ROADMAPS';description.textContent=state.view==='all'?'Follow the branches into each area. Select a roadmap to see its scope and mathematical connections.':'Click a roadmap to read its scope. Open its stage layers to explore the mathematics inside.';
  if(state.view==='group')outsideControl('Show connected roadmaps');
 }else if(state.view==='roadmap'){
  const r=maps.get(state.id),ids=new Set(r.stages);nodes=r.stages.map(id=>stages.get(id)).filter(Boolean).map(s=>stageNode(s));
  edges=DATA.stageEdges.filter(e=>ids.has(e.source)&&ids.has(e.target));
  if(state.outside){const additions=new Set();for(const e of DATA.stageEdges)if(ids.has(e.source)!==ids.has(e.target)){edges.push(e);additions.add(ids.has(e.source)?e.target:e.source);}for(const id of additions)nodes.push(boundaryNode(id));}
  title.textContent=shortTitle(r.title);eyebrow.textContent='STAGE LAYERS';description.textContent='Click a stage to read its construction target, follow dependencies and update progress.';outsideControl('Show outside dependencies');
  $('view-actions').append(btn('Full roadmap',()=>openReader(r.id),'secondary'));
 }
 $('graph-empty').hidden=nodes.length>0;$('edge-legend').textContent=state.view==='all'?'Gold branches: subject groupings · Select a node for dependency arrows':'Arrows: prerequisite → consumer · Dashes: declared dependency';
 graphModel={nodes,edges};graph.setData(graphModel,{layout:state.view==='subjects'?'groups':state.view==='roadmap'?'layers':state.view==='all'?'vessels':'clusters',selectedId:state.selected});
 $('graph-counts').textContent=`${nodes.length.toLocaleString()} ${state.view==='subjects'?'subjects':state.view==='roadmap'?'stage nodes':'roadmaps'} · ${edges.length.toLocaleString()} links`;
 $('graph-hint').textContent=state.view==='subjects'?'Click to inspect · double-click to open a subject':'Scroll to zoom · drag to pan · click a node to highlight its links';
}
function outsideControl(label){const n=el('label','toggle'),input=document.createElement('input');input.type='checkbox';input.checked=state.outside;input.addEventListener('change',()=>navigate({outside:input.checked}));n.append(input,document.createTextNode(label));$('view-actions').append(n);}
function renderBreadcrumbs(){const box=clear($('breadcrumbs'));box.append(btn('All mathematics',()=>navigate({view:'all',id:null,selected:null})));if(state.id){box.append(el('span','','›'));if(maps.has(state.id)){const r=maps.get(state.id),g=groupOf(r);box.append(btn(g.label,()=>navigate({view:'group',id:r.group,selected:null})),el('span','','›'),btn(shortTitle(r.title),()=>openItem(r.id),'current'));}else if(groups.has(state.id))box.append(btn(groups.get(state.id).label,()=>{},'current'));}else if(state.view==='all')box.append(el('span','','›'),el('span','current','All roadmaps'));}
function renderCatalogue(){const box=clear($('catalogue'));const query=$('search').value.trim().toLowerCase();const rs=DATA.roadmaps.filter(permitted);if(query){const mapHits=rs.filter(r=>mapSearch.get(r.id).includes(query));const stageHits=DATA.stages.filter(s=>permitted(maps.get(s.owner))&&stageSearch.get(s.id).includes(query));box.append(el('div','catalogue-heading',`${mapHits.length} roadmaps · ${stageHits.length} stages`));for(const r of mapHits.slice(0,35)){const b=btn('',()=>{navigate({view:'group',id:r.group,selected:r.id,tab:'overview'});graph.focus(r.id);},'search-hit');b.append(el('strong','',shortTitle(r.title)),el('small','',groupOf(r).label));box.append(b);}for(const s of stageHits.slice(0,60)){const b=btn('',()=>openStage(s.id),'search-hit');b.append(el('strong','',s.title),el('small','',s.key+' · '+shortTitle(maps.get(s.owner).title)));box.append(b);}if(!mapHits.length&&!stageHits.length)box.append(el('p','search-empty','No matching roadmap or stage. Try a broader mathematical term.'));return;}
 box.append(el('div','catalogue-heading','Browse the collection'));for(const g of DATA.groups){const members=rs.filter(r=>r.group===g.id);if(!members.length)continue;const d=document.createElement('details');d.open=state.view==='group'&&state.id===g.id||!!state.selected&&maps.has(state.selected)&&maps.get(state.selected).group===g.id;const summary=document.createElement('summary'),dot=el('span','dot');dot.style.background=g.color;summary.append(dot,el('span','label',g.label),el('small','',members.length));d.append(summary);for(const r of members){const b=btn(shortTitle(r.title),()=>navigate({view:'group',id:r.group,selected:r.id,tab:'overview'}),'catalogue-item'+(state.selected===r.id?' active':''));b.title=r.title;d.append(b);}box.append(d);}}
function detailHeader(box,title,subtitle,accent){const strip=el('div','detail-color');strip.style.background=accent;box.append(strip,el('h2','detail-title',shortTitle(title)));if(subtitle)box.append(el('p','detail-subtitle',subtitle));}
function stats(box,items){const row=el('div','detail-stats');for(const [value,label]of items){const cell=el('div');cell.append(el('strong','',String(value)),el('span','',label));row.append(cell);}box.append(row);}
function section(box,title){box.append(el('h3','section-label',title));}
function item(box,id,action){const s=stages.get(id),r=maps.get(id),x=external.get(id);const title=s?s.title:r?shortTitle(r.title):x?.title||id;const b=btn('',action||(()=>s?openStage(id):r?navigate({view:'group',id:r.group,selected:id,tab:'overview'}):select(id)),'item-link');b.dataset.itemId=id;const label=el('span');if(s)label.append(el('span','item-key',s.key));label.append(document.createTextNode(title));b.append(label,el('span','arrow','↗'));box.append(b);return b;}
function tabs(box){const nav=el('div','detail-tabs');for(const [id,title]of [['overview','Overview'],['stages','Layers'],['links','Links']])nav.append(btn(title,()=>{state.tab=id;renderInspector();},state.tab===id?'active':''));box.append(nav);}
function progressSummary(box,r){const p=progress.roadmap(r.id),wrap=el('div','progress-summary');const top=el('div','progress-caption');top.append(el('strong','',`${Math.round(p.percent||0)}%`),el('span','',statString(p)));const bar=el('div','progress-track'),fill=el('div');fill.style.width=(p.percent||0)+'%';fill.style.background=color(p.percent||0);bar.append(fill);wrap.append(top,bar,el('p','detail-note',`${p.active||0} in progress · ${p.unknown||0} not assessed. Progress counts tracked leaf layers.`));box.append(wrap);if(r.lifecycle==='completed')box.append(el('span','status-chip','Archived as complete by Tau Ceti maintainers'));}
function stageTree(box,r){const roots=r.stages.filter(id=>!stages.get(id)?.parentStageId||!r.stages.includes(stages.get(id).parentStageId));function walk(id,parent,depth){const s=stages.get(id);if(!s||depth>12)return;const p=progress.stage(id);const b=item(parent,id);const mark=el('span','stage-state-dot');mark.style.background=color(p.percent||0);mark.title=labels[p.status];b.prepend(mark);const children=stageChildren.get(id)||[];if(children.length){const d=el('details'),summary=el('summary','',`${children.length} sub-layers`),content=el('div','substage');d.append(summary,content);children.forEach(c=>walk(c,content,depth+1));parent.append(d);}}const tree=el('div','stage-tree');roots.forEach(id=>walk(id,tree,0));box.append(tree);if(!r.stages.length){for(const id of childRoadmaps.get(r.id)||[])item(box,id,()=>openItem(id));}}
function renderInspector(){const id=state.selected,box=clear($('inspector-content'));$('inspector').hidden=!id;document.body.classList.toggle('has-selection',!!id);if(!id)return;
 if(groups.has(id)){const g=groups.get(id),members=DATA.roadmaps.filter(r=>r.group===id&&permitted(r));$('selection-kind').textContent='SUBJECT';detailHeader(box,g.label,`${members.length} roadmaps`,g.color);box.append(el('p','detail-summary',`Explore ${g.label.toLowerCase()} through the roadmaps below. Each roadmap contains its own construction stages, dependencies and full mathematical specification.`));box.append(btn('Open roadmaps →',()=>openItem(id),'primary'));section(box,'In this subject');members.forEach(r=>item(box,r.id,()=>navigate({view:'group',id:g.id,selected:r.id,tab:'overview'})));return;}
 if(maps.has(id)){const r=maps.get(id),p=progress.roadmap(id);$('selection-kind').textContent=(r.origin||'campaign')==='tauceti'?'TAU CETI ROADMAP':'CAMPAIGN ROADMAP';detailHeader(box,r.title,groupOf(r).label,color(p.percent||0));const pin=btn(pins.has(id)?'★ Pinned':'☆ Pin roadmap',()=>togglePin(id),'pin-button');pin.setAttribute('aria-pressed',String(pins.has(id)));box.append(pin);progressSummary(box,r);const row=el('div','button-row');row.append(btn(r.stages.length?'Open stage layers →':'Open sub-roadmaps →',()=>openItem(id),'primary'),btn('Read full roadmap',()=>openReader(id),'secondary'));box.append(row);tabs(box);
 if(state.tab==='overview'){box.append(el('p','detail-summary',r.summary));stats(box,[[r.stages.length,'stages'],[r.prerequisites.length,'prerequisites'],[r.consumers.length,'consumers']]);if(r.parentRoadmapId)item(box,r.parentRoadmapId,()=>openItem(r.parentRoadmapId));if(r.statusMarkdown){section(box,'Recorded project status');box.append(el('p','detail-note','Imported from the local Tau Ceti roadmap checkout. Reports are snapshots; local changes are kept separately.'+(p.snapshotDate?' Reported '+p.snapshotDate+'.':'')),btn('Read status report',()=>openReader(id,'status'),'secondary'));}if(r.progressMarkdown)box.append(btn('Read progress log',()=>openReader(id,'progress'),'quiet'));section(box,'First layers');r.stages.slice(0,4).forEach(s=>item(box,s));if((childRoadmaps.get(id)||[]).length){section(box,'Sub-roadmaps');childRoadmaps.get(id).forEach(child=>item(box,child,()=>openItem(child)));}}
 if(state.tab==='stages'){box.append(el('p','detail-note','Open a layer to read its target and update its local progress. Sub-layers can be expanded independently.'));stageTree(box,r);}
 if(state.tab==='links'){box.append(btn('Show connection map',()=>navigate({view:'neighbors',id,selected:id,tab:'links'}),'secondary'));section(box,'Prerequisite roadmaps');if(!r.prerequisites.length)box.append(el('p','detail-note','No internal roadmap prerequisites are encoded.'));r.prerequisites.filter(x=>maps.has(x)).forEach(x=>item(box,x));section(box,'Roadmaps using this');r.consumers.filter(x=>maps.has(x)).forEach(x=>item(box,x));if(r.relatedRoadmaps?.length){section(box,'Related plans');r.relatedRoadmaps.forEach(x=>item(box,typeof x==='string'?x:x.id));}}
 return;}
 if(stages.has(id)){const s=stages.get(id),r=maps.get(s.owner),p=progress.stage(id);$('selection-kind').textContent='STAGE · '+s.key;detailHeader(box,s.title,'',color(p.percent||0));box.append(btn(shortTitle(r.title),()=>openItem(r.id),'inline-owner'));box.append(el('p','status-chip',`${p.manual?'Your local status':p.basis&&p.basis!=='unknown'?'Recorded status':'Progress'}: ${labels[p.status]||p.status}`));renderProgressControls(box,s,p);const md=el('div','md-content stage-description');md.append(TauMarkdown.render(s.description,{basePath:s.sourcePath}));box.append(md);const children=stageChildren.get(id)||[];if(children.length){section(box,'Sub-layers');children.forEach(x=>item(box,x));}section(box,`Prerequisites (${s.requires.length})`);if(!s.requires.length)box.append(el('p','detail-note','No encoded stage prerequisites.'));s.requires.forEach(x=>item(box,x));section(box,`Consumers (${s.consumers.length})`);s.consumers.forEach(x=>item(box,x));box.append(btn('Read full roadmap',()=>openReader(r.id),'secondary'));return;}
 const x=external.get(id);$('selection-kind').textContent='EXTERNAL PREREQUISITE';detailHeader(box,x?.title||id,'Integration contract','#89959d');box.append(el('p','detail-summary',x?.action||'This prerequisite is outside the currently embedded roadmaps. Its exact statement and implementation must be checked in the supplying library.'));if(x?.integration_owner&&stages.has(x.integration_owner))item(box,x.integration_owner);if(x?.consumers?.length){section(box,'Consumers');x.consumers.forEach(c=>item(box,c));}}
function renderProgressControls(box,s,p){const card=el('div','progress-controls');card.append(el('h3','section-label','Track this layer'));const selectEl=el('select');selectEl.setAttribute('aria-label','Layer status');for(const [value,title]of Object.entries(labels)){const o=el('option','',title);o.value=value;selectEl.append(o);}selectEl.value=p.status||'unknown';const note=el('textarea');note.rows=2;note.maxLength=4000;note.placeholder='Evidence, PR link or a note (optional)';note.setAttribute('aria-label','Progress note');note.value=p.note||'';const count=descendants(s.id).length;if(count)card.append(el('p','detail-note',`Updating this layer also updates its ${count} sub-layers.`));card.append(selectEl,note);const row=el('div','button-row');row.append(btn('Save status',()=>{progress.setStage(s.id,selectEl.value,note.value);toast('Progress saved locally');},'primary'));if(p.manual)row.append(btn('Use recorded status',()=>{progress.resetStage(s.id);toast('Restored recorded status');},'quiet'));card.append(row);if(p.basis)card.append(el('p','detail-note','Source: '+String(p.basis).replace(/_/g,' ')+(p.snapshotDate?' · '+p.snapshotDate:'')));if(p.evidence?.length){const d=el('details','progress-evidence');d.append(el('summary','','Recorded evidence'));for(const evidence of p.evidence){d.append(el('p','detail-note',typeof evidence==='string'?evidence:evidence.quote||evidence.path||JSON.stringify(evidence)));}card.append(d);}box.append(card);}
function descendants(id){const result=[];const visit=n=>{for(const c of stageChildren.get(n)||[]){if(result.includes(c))continue;result.push(c);visit(c);}};visit(id);return result;}
function render(){document.querySelectorAll('[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===state.view));$('source-filter').value=state.origin;$('activity-filter').value=state.activity;renderBreadcrumbs();renderInspector();renderCatalogue();renderPins();renderStats();buildGraph();}
function showDocument(doc){currentDoc=doc;$('reader-title').textContent=shortTitle(doc.title);const body=clear($('reader-body'));body.append(TauMarkdown.render(doc.text,{basePath:doc.path}));$('open-source').href=fileURL(doc.path);clear($('reader-toc'));body.querySelectorAll('h2,h3').forEach(h=>{$('reader-toc').append(btn(h.dataset.tocLabel||h.textContent,()=>h.scrollIntoView({behavior:'smooth',block:'start'})));});if(!$('reader').open)$('reader').showModal();body.scrollTop=0;}
function openReader(id,kind='readme'){const r=maps.get(id);if(!r){const doc=documents.get(id);if(doc)showDocument({...doc,path:doc.sourcePath});return;}let text=r.readme,title=r.title,path=r.sourcePath;if(kind==='status'){text=r.statusMarkdown;title=r.title+' — status';path=r.sourcePath.replace(/README\.md$/,'STATUS.md');}if(kind==='progress'){text=r.progressMarkdown;title=r.title+' — progress log';path=r.sourcePath.replace(/README\.md$/,'PROGRESS.md');}if(text)showDocument({id,kind,text,title,path});}

function fileURL(path){if(!path)return'#';try{if(/^(https?:|file:)/.test(path))return new URL(path).href;if(path.startsWith('/'))return new URL(path,'file:///').href;return new URL(path,location.href).href;}catch{return'#';}}
function download(name,text,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function handleDocLink(event){const a=event.target.closest('[data-doc-link]');if(!a)return;event.preventDefault();const raw=a.dataset.docLink,base=a.dataset.basePath||currentDoc?.path||'';if(raw.startsWith('#')){const id=decodeURIComponent(raw.slice(1));const target=$('reader-body').querySelector('#'+CSS.escape(id))||$('inspector-content').querySelector('#'+CSS.escape(id));if(target)target.scrollIntoView({behavior:'smooth'});return;}let url;try{url=new URL(raw,fileURL(base));}catch{return;}const path=decodeURIComponent(url.pathname),r=DATA.roadmaps.find(x=>fileURL(x.sourcePath)===url.href.split('#')[0]||fileURL(x.sourcePath.replace(/README\.md$/,'STATUS.md'))===url.href.split('#')[0]||fileURL(x.sourcePath.replace(/README\.md$/,'PROGRESS.md'))===url.href.split('#')[0]);const doc=[...documents.values()].find(d=>fileURL(d.sourcePath)===url.href.split('#')[0]);if(r||doc){if(r)openReader(r.id,path.endsWith('STATUS.md')?'status':path.endsWith('PROGRESS.md')?'progress':'readme');else openReader(doc.id);if(url.hash)setTimeout(()=>{const target=$('reader-body').querySelector('#'+CSS.escape(decodeURIComponent(url.hash.slice(1))));target?.scrollIntoView();},50);return;}if(['file:','http:','https:'].includes(url.protocol))window.open(url.href,'_blank','noopener');}
document.addEventListener('click',handleDocLink);
$('search').addEventListener('input',renderCatalogue);
document.querySelectorAll('[data-view]').forEach(n=>n.addEventListener('click',()=>navigate({view:n.dataset.view,id:null,selected:null,tab:'overview'})));
$('source-filter').addEventListener('change',e=>navigate({origin:e.target.value,view:'all',id:null,selected:null,activity:'all'}));
$('activity-filter').addEventListener('change',e=>navigate({activity:e.target.value,view:'all',id:null,selected:null}));
$('catalogue-button').addEventListener('click',()=>{const open=document.body.classList.toggle('catalogue-open');$('catalogue-button').setAttribute('aria-expanded',String(open));if(open)$('search').focus();});
$('stats-button').addEventListener('click',()=>{renderStats();$('stats-dialog').showModal();});$('close-stats').addEventListener('click',()=>$('stats-dialog').close());
$('download-offline').addEventListener('click',()=>download('TauCeti_Atlas.html',offlineDocument,'text/html'));
$('close-inspector').addEventListener('click',()=>{state.selected=null;try{history.replaceState(null,'',routeHash(state));}catch{}renderInspector();graph.select(null);});
$('zoom-in').addEventListener('click',()=>graph.zoomIn());$('zoom-out').addEventListener('click',()=>graph.zoomOut());$('fit-graph').addEventListener('click',()=>graph.fit());
$('export-graph').addEventListener('click',()=>download('TauCeti-'+state.view+'.svg',graph.exportSVG(),'image/svg+xml'));
$('copy-link').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);toast('View link copied');}catch{toast('Bookmark this page to save the current view');}});
$('help-button').addEventListener('click',()=>$('help').showModal());$('close-help').addEventListener('click',()=>$('help').close());$('start-exploring').addEventListener('click',()=>$('help').close());$('close-reader').addEventListener('click',()=>$('reader').close());
$('download-readme').addEventListener('click',()=>{if(currentDoc)download(currentDoc.id.replace(/[^a-z0-9_-]/gi,'_')+'.md',currentDoc.text,'text/markdown');});
$('progress-button').addEventListener('click',()=>{$('storage-status').textContent=progress.persistent?'Changes save in this browser. Export a backup before moving or replacing the HTML file.':'Browser storage is unavailable. Export your progress before closing this page.';$('progress-dialog').showModal();});
$('close-progress').addEventListener('click',()=>$('progress-dialog').close());
$('export-progress').addEventListener('click',()=>download('TauCeti-progress-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(progress.export(),null,2)));
$('import-progress').addEventListener('click',()=>$('progress-file').click());
$('progress-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5000000)throw new Error('Progress file is too large.');const count=progress.import(JSON.parse(await file.text()));toast('Imported progress'+(typeof count==='number'?` for ${count} layers`:''));$('progress-dialog').close();}catch(error){toast('Could not import: '+error.message);}e.target.value='';});
window.addEventListener('popstate',()=>{state=readRoute();render();});window.addEventListener('hashchange',()=>{state=readRoute();render();});
document.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();if(matchMedia('(max-width:600px)').matches){document.body.classList.add('catalogue-open');$('catalogue-button').setAttribute('aria-expanded','true');}$('search').focus();}if(event.key==='Escape'&&!document.querySelector('dialog[open]')&&state.selected){state.selected=null;renderInspector();graph.select(null);}});
progress.subscribe(()=>{renderInspector();renderCatalogue();renderStats();if(state.activity!=='all')buildGraph();const update={};for(const n of graphModel.nodes){if(stages.has(n.id)){const p=progress.stage(n.id);update[n.id]={progress:p.percent||0,progressLabel:labels[p.status]||'Not assessed'};}else if(maps.has(n.id)){const p=progress.roadmap(n.id);update[n.id]={progress:p.percent||0,progressLabel:p.total?Math.round(p.percent||0)+'% layers':'Not assessed'};}else if(groups.has(n.id)){const p=progress.group(n.id);update[n.id]={progress:p.percent||0,progressLabel:Math.round(p.percent||0)+'% layers complete'};}}graph.setProgress(update);});
$('roadmap-total').textContent=DATA.roadmaps.length.toLocaleString();$('stage-total').textContent=DATA.stages.length.toLocaleString();document.querySelector('[data-view="subjects"] small').textContent=DATA.groups.length;document.querySelector('[data-view="all"] small').textContent=DATA.roadmaps.length;
state=readRoute();render();window.TauExplorer={data:DATA,graph,progress,navigate,openItem,openStage,openReader,getState:()=>({...state}),getGraph:()=>graphModel,version:'2026-09-15'};
})();
